### ISSUE TITLE
Support for h2o.ai models

### ISSUE THREAD

**Issue by Talador12** [bentoml/BentoML#1000]
**Is your feature request related to a problem? Please describe.**
Add support and examples for h2o.ai models

**Describe the solution you'd like**
Similar to other model type integrations, there is definitely a use case for using Bento for h2o models once it is integrated. There is also a need for docs/examples similar to other model types that have been added.

**Describe alternatives you've considered**
Not really alternatives here, other than when priority over other models types, such as:

```
scikit-learn
XGBoost
Torch
Spark MLlib
h2o
Keras
Tensorflow
TensorRT
ONNX
mxnet
LightGBM
```

**Additional context**

> http://h2o.ai

**Comment by parano** [comment]
Hi @Talador12, is [this](https://docs.bentoml.org/en/latest/frameworks.html#h2o) what you are looking for?

**Comment by yubozhao** [comment]
@Talador12  Have you had the chance to check out the H2o Artifact? Let us know if we can help you out.

Here is the link to the example notebooks that use H2o Artifact: https://github.com/bentoml/gallery/tree/master/h2o
