### ISSUE TITLE
autogenerated requirements.txt is missing version numbers of select dependencies

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1005]
**Describe the bug**
I use the auto_pip_dependencies on the env_decorator for my Service
@bentoml.env(auto_pip_dependencies=True)

After I save the Service - as expected the BentoML autogenerates a requirements.txt with the correct list of dependent packages.

However I notice that the version number of scikit-learn is left unspecified. Why is this the case ?
The versions of the other two libraries match that of the training environment.
Shouldn't I expect the same of scikit-learn as well ?

** Contents of autogenerated requirements.txt**
```
scikit-learn
bentoml==0.8.4
numpy==1.19.1
```

**Environment:**
```
 - OS: Windows 10
 - Python 3.8.3
 - bentoml, version 0.8.4

```

**Comment by parano** [comment]
This is fixed in #1086, will be available in next release 0.9.0
