### ISSUE TITLE
Add Statsmodel to framework page

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1011]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Include Statsmodel to the framework page on the documentation site

- [ ] Add sample code using PickleArtifact
- [ ] Add example notebook in the bentoml/gallery repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
Is this done? @yubozhao

**Comment by yubozhao** [comment]
Yep. We can close this.
