### ISSUE TITLE
Accept orient='table' in DataframeInput

### ISSUE THREAD

**Issue by thoo** [bentoml/BentoML#1014]
**Is your feature request related to a problem? Please describe.**
It would be great if `bentoml.adapters.DataframeInput` can accept `orient='table'`. Since `orient='table'` is the only format which can transfer datatype like `category`. 

```python
import pandas as pd
df=pd.DataFrame({'sex':pd.Categorical(['F','F','M'],categories=['F','M'])})
df.info()
```
Right now, `df.dtypes` is `category`. If we convert `DataFrame` to `JSON` and reconvert to `DataFrame` without `orient='table'` , we end up with `object` type instead `category` type.  
```python
df.equals(pd.read_json(df.to_json())) # This return False since one is category and another is object.
df.equals(pd.read_json(df.to_json(orient='table'),orient='table')) # This return True. 
```
**Describe the solution you'd like**
`bentoml.adapters.DataframeInput(orient='table')`

**Describe alternatives you've considered**
Currently I use `JsonInput()`  along with the preprocessing function instead of `DataframeInput`.

**Comment by yubozhao** [comment]
@thoo Thanks for the suggestion

I remember @bojiang created #815, which added support for other orients except `table`.  Deferring to him on this topic.

**Comment by bojiang** [comment]
@thoo Hi. 
For developers who wrote the API function, they already knew what dtype they want.
Therefore, for this demand, I prefer declaring in the parameter than supporting table orientation:

```python
@api(
    input=DataFrameInput(
        columns=["sex"],
        dtypes={"sex": pd.CategoricalDtype(categories=['F','M'])},
    ))
def predict(self, df):
    pass
```

This is consistent with `pandas.read_csv()` `pandas.read_json()`. 
(but you know, because of pandas' defects, `pandas.read_json(dtype=)` does not support specifying categorical dtype now. I'm refactoring DataFrameInput and would try to workaround this issue)

**Comment by thoo** [comment]
@bojiang That will do. Right now, I just pass `JSON` object with `orient='table'` and preprocess  ` pd.read_json(data.text,orient='table')` before making prediction.

**Comment by bojiang** [comment]
Rather than supporting the `table` orientation, I chose to support the `dtype` of `categories`.

```python
@api(
    input=DataFrameInput(
        columns=["sex"],
        dtypes={"sex": pd.CategoricalDtype(categories=['F','M'])},
    ))
def predict(self, df):
    pass
```

BentoML is mainly designed for serving. Specifying the `dtype` of the data when defining the API is more explicit and easier to implement.
