### ISSUE TITLE
bento flask service not accessible from outside the docker container

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1031]
**Describe the bug**
On my RHEL docker container:
If I use plain-flask - the Model API is NOT accessible outside of the container:
`bentoml serve /<some_dir>`
However, if I ssh into the container and try invoking the Model API - it works.

If I use gunicorn - the Model API is accessible from outside the container.
`bentoml serve-gunicorn --workers=2 /<some_dir>`

There is some difference in the way  gunicorn and plain-flask are configured that is causing flask to NOT be accessible. I don't know enough of either to tell.

However, one thing i note is the following in /bentoml/server/api_server.py:
```
def start(self):
	"""
	Start an REST server at the specific port on the instance or parameter.
	"""
	# Bentoml api service is not thread safe.
	# Flask dev server enabled threaded by default, disable it.
	self.app.run(
		port=self.port, threaded=False, debug=get_debug_mode(), use_reloader=False,
	)
```
Should the call to app.run() include the host for it to be accessible outside the container ?
`app.run(host='0.0.0.0')`

**To Reproduce**
1. Run on Docker
`bentoml serve /<some_dir>`

**Environment:**
 - OS: RHEL Docker
 - Python 3.8, BentoML-0.8.4]

**Comment by yubozhao** [comment]
@jiyer2016 Yep. I can reproduce it. We should include the host there.  

Just curious, what's the reason/use-case that you want to run flask via `bentoml serve` instead of using gunicorn with `bentoml serve-gunicorn`?

We were thinking that if users are containerizing, they are probably using it for production; hence gunicorn is a better choice. I would love to learn about your use-cases more, so we can have a better design in future versions.

**Comment by jiyer2016** [comment]
Yes, gunicorn is good for me. 
Just that I took the (default) route of running flask to prove this works on my environment.

**Comment by parano** [comment]
@jiyer2016 do you mind sharing a bit more context about the environment you're working with and the requirements there? That'd help us understand a bit more about what's the best way to support those requirements.

**Comment by jiyer2016** [comment]
@parano - Let me get back to you on this in a few days.

**Comment by yubozhao** [comment]
@jiyer2016 feel free to reach us directly on slack or email us at bo@bentoml.ai or chaoyu@bentoml.ai, if sharing in public is a concern.

**Comment by bojiang** [comment]
The server launched by `bentoml serve` is for debug only, and bound to `127.0.0.1`, which means we can only access it from inside of the container. Since it is not suitable for production (many unexcepted issues), I think this default behaviour is okay.

**Comment by bojiang** [comment]
Plus there would be some security issues when expose debug service to public (bind to `0.0.0.0`).

**Comment by jiyer2016** [comment]
@bojiang - Thanks, Fine with this behavior. Not high priority - but does it make sense to add a warning during startup to make users aware that the service would not be accessible outside the host. OR perhaps add it to documentation OR even in the output of `bentoml serve --help`.  

Closing this issue.
