### ISSUE TITLE
YataiService Web UI not responding on Docker

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1034]
**Describe the bug**
I started up the YataiService on Docker (RHEL Base Image)

```
bentoml yatai-service-start --debug --verbose

[2020-08-27 07:40:38,709] DEBUG - Enabling gRPC server reflection for debugging
* Starting BentoML YataiService gRPC Server
* Debug mode: on
* Web UI: running on http://127.0.0.1:3000
* Running on 127.0.0.1:50051 (Press CTRL+C to quit)
* Usage:
*  Set config: `bentoml config set yatai_service.url=127.0.0.1:50051`
*  Set env var: `export BENTOML__YATAI_SERVICE__URL=127.0.0.1:50051`
* Help and instructions: https://docs.bentoml.org/en/latest/guides/yatai_service.html
* Web server log can be found here: /home/<some_user>/bentoml/logs/yatai_web_server.log
```

I have the local port 3000 on docker exposed to the outside world. 
I proceed with accessing the Web UI URL from a browser - that does NOT work (not acccessible) 
I then ssh into my docker container and use curl to access the Web UI URL - that doesn't work either.

```
curl http://127.0.0.1:3000
curl: (7) Failed connect to 127.0.0.1:3000; Connection refused
```

I look at the logs directory - surprisingly it is missing the yatai_web_server.log
I would have expected a zero byte log file for yatai_web_server.log - as was the case on my local environment.

```
ls -l ~/bentoml/logs
-rw-r--r--. 1 <some_user> <some_group> 258 Aug 27 07:40 active.log
-rw-r--r--. 1 <some_user> <some_group>   0 Aug 27 07:40 feedback.log
-rw-r--r--. 1 <some_user> <some_group>   0 Aug 27 07:40 prediction.log

```

I need inputs on what else I should be looking at to debug the problem.
I don't see any errors in a log file.

**Environment:**
 - Python 3.8.0
 - bentoml, version 0.8.4
 - node v8.12.0
 - npm 6.4.1
 - Docker - RHEL Base Image (I use my own Docker file - and NOT the ones autogenerated by bentoml)

**Comment by parano** [comment]
@jiyer2016 did you use the officially released docker image for YataiService from the docker hub? https://hub.docker.com/repository/docker/bentoml/yatai-service  Or did you try building the docker image yourself?

**Comment by parano** [comment]
If you are building your own docker image for YataiService, take a look at our release script here:  https://github.com/bentoml/BentoML/blob/master/dev/release_pypi.sh

You will need to build the javascript/typescript project before packaging them into a bentoml distribution.

**Comment by jiyer2016** [comment]
@parano - I am not building the Docker image from source. 
So I assume, I do not need to build the javascript / typescript project.

Here is how my custom Dockerfile for yatai-service looks:

```
FROM <company provided base image containing Python 3.8> 
RUN pip3.8 install bentoml==0.8.4 grpcio-reflection==1.27.2
RUN yum -y install nodejs npm
```

And then I start it up using the command:
`bentoml yatai-service-start --no-ui --debug --verbose`

I also have a configuration that exposes local ports 3000 and 50051 to outside the world.

**Comment by parano** [comment]
I see, `—no-ui` might be the reason then, it means running only the gRPC server without the web ui server.

**Comment by jiyer2016** [comment]
Sorry, I meant I use:
yatai-service-start --debug --verbose

I had temporarily added the --no-ui flag to turn OFF the Web UI since it wasn't working for me.
I can confirm that this is still an issue for me.

**Comment by parano** [comment]
@jiyer2016 could you try `docker exec` into the container where you ran `bentoml yatai-service-start --debug --verbose`, and try running the following command to see what's the output?

```bash
node yatai/web/dist/bundle.js localhost:50051 3000 ~/bentoml/logs/yatai_web_server.log
```

**Comment by jiyer2016** [comment]
Thanks, that was helpful - Here is the error I get:

```
node yatai/web/dist/bundle.js localhost:50051 3000 ~/bentoml/logs/yatai_web_server.log
Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.module.exports.e.exports (/usr/local/lib/python3.8/site-packages/bentoml/yatai/web/dist/bundle.js:38:13139)
```

I am currently running a lower version of node - Let me upgrade and see if that helps. 
```
$ node --version
v8.12.0
$ npm --version
6.4.1

```
In the meanwhile do you recommend any specific version for node and npm ?

**Comment by yubozhao** [comment]
@jiyer2016 I think node version `12.13.0` and npm version `6.12.0` is a good one.  

The latest version 12 for node `12.18.3` breaks the UI client bundler `parcel`. Please steer away from that.

**Comment by jiyer2016** [comment]
Upgrading node fixed this issue.
