### ISSUE TITLE
Allow access to artifacts in the service __init__(self) during pack process

### ISSUE THREAD

**Issue by shihgianlee** [bentoml/BentoML#1037]
**Is your feature request related to a problem? Please describe.**
In BentoML service class, we don't have access to artifacts during `pack` process, e.g. `self.artifacts.my_artifact`, in the `__init__(self)` method. The reason to have access to the artifacts in the init is so that I can pass the artifact to my class initialization, e.g. `self._provider = Provider(self.artifacts.my_artifact)`. Later in the service `predict` method, I can access my class this way, e.g. `self._provider.fetch_predicted_value`, where the predicted value is computed value from the prediction produced by `my_artifact`.

**Describe the solution you'd like**
In [slack discussion message thread](https://bentoml.slack.com/archives/CKRANBHPH/p1598399213067800), a `service_init` callback is proposed to allow the above service initialization.

**Describe alternatives you've considered**
In [slack discussion message thread](https://bentoml.slack.com/archives/CKRANBHPH/p1598399213067800), a couple solutions were proposed. I ended up using `@property` decorator for my use case. It is a bit more code but it achieved the end result described above and made my code simpler.

```python
@property
def provider(self):
    if not self._provider:
          self._provider = Foo(self.artifacts.my_csv, self.artifacts.my_json) 
    return self._provider
```

**Comment by shihgianlee** [comment]
We encountered the same problem again where we need to load a json config file within the same package but couldn't. We had to use the same workaround for our config, which is awkward. I see `help wanted` label in this issue. Is there anything I can do to help with this issue?

**Comment by parano** [comment]
This is now possible in BentoML 1.0, where models are first saved in local model store before the Bento build process. User can also create a custom Runner class, and define how/when a model is loaded. e.g.:

```
import bentoml

class CustomRunner(bentoml.Runner):

    def _setup(self):
        # load model from model store
        model_info = bentoml.model.get('...')
        self.model = load_model(model_info.path)

   def _run_batch(self, df: pd.DataFrame):
        # run inference on a batch input
        ...

runner = CustomRunner('my_runner')
svc = bentoml.Service('my_service', runners=[runner])

...
```
