### ISSUE TITLE
Prediction log shows encoded payload when enable micro-batching

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1040]
**Describe the bug**

Run BentoML API server with `--enable-microbatch`, the prediction log currently shows the entire batched request payload instead of individual inference task's input and output. 

![Screen Shot 2020-08-27 at 10 34 22 PM](https://user-images.githubusercontent.com/489344/91525526-92a1f180-e8b6-11ea-8858-3453ae93c19a.png)

![image](https://user-images.githubusercontent.com/489344/91525549-9cc3f000-e8b6-11ea-84f5-301f46cf270b.png)

This issue will be addressed by the ongoing input adapters refactoring: https://github.com/bentoml/BentoML/issues/1002

**Expected behavior**
Show 1 prediction log item for each prediction request sent from client

**Comment by bojiang** [comment]
resolved
