### ISSUE TITLE
Error in retrieving BENTO if yatai-service uses local disk storage repository for model artifacts (default)

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1042]
**Describe the bug**
This issue happens only if yatai-service uses the default local disk storage repository.
It doesn't happen if configured to use S3 / Minio for storing Model Artifacts.

The call to **bentoml retrieve** fails from a Remote Node with the following error:

```
  File "/home/<some_user>/.local/lib/python3.6/site-packages/bentoml/cli/bento_management.py", line 242, in retrieve
    safe_retrieve(bento_service_bundle_path, target_dir)
  File "/home/<some_user>/.local/lib/python3.6/site-packages/bentoml/saved_bundle/loader.py", line 178, in safe_retrieve
    shutil.copytree(bundle_path, target_dir)
  File "/usr/local/lib/python3.6/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/<some_user>/bentoml/repository/<some_service>/20200828200111_90BFD8'
```

It turns out that the path **/home/<some_user>/bentoml/repository/<some_service>/20200828200111_90BFD8** is valid on the node that runs the yatai-service. 

It seems like **bentoml retrieve** is looking for that same path on the Remote Node - which wouldn't exist anyway. Why would this happen ? Does it assume than nodes running the yata-service and the remote bento client share the same disk ?

Reproduce**
1. Node 1 - bentoml yatai-service-start --no-ui --debug --verbose
2. Node 1 - Save a Model Service using the API (to local disk storage repository)
2. Node 2 -  bentoml config set yatai_service.url=<yatai-service-url-on-Node1>
3. Node 2 - bentoml retrieve <some_service>:latest --target_dir <some_dir>
4. Node 2 - The call to bentoml retrieve fails with the Error Stack above

**Environment:**
 - Python 3.8, BentoML-0.8.4]

**Comment by parano** [comment]
Hi @jiyer2016 - thanks for reporting this. This is a known limitation of YataiService and it is on our roadmap.  For now, we'd recommend using AWS S3 or your own MinIO deployment as the storage for YataiService.

**Comment by jiyer2016** [comment]
Thanks for confirming - @parano   - I will close this since it is a known issue and you may already have a separate item to track this. Yes, I shall use S3 / MinIO for the actual setup. 

Just that the local disk option would be a lot more convenient for demos showcasing the capability to so easily save and distribute a Service across nodes.

BTW - I really appreciate the work you'll have done on making BentoML available as Open Source to the Data Scientists.
