### ISSUE TITLE
Deploy model on local server on windows tablet

### ISSUE THREAD

**Issue by miyrai** [bentoml/BentoML#1061]
Hi!
I have a question regarding the deployment. Is its possible to deploy a ml model with BentoML on a local server on a windows tablet, so it can be accessed via HTTP request to the localhost? And if it is possible, how would you do that?
This will only be a tepmorary solution (but a needed one) until the model will be deployed on a real server

**Comment by parano** [comment]
hey @miyrai, hope you don't mind let's move questions like this to discussions board here: https://github.com/bentoml/BentoML/discussions
