### ISSUE TITLE
Cli get command crash if bento name is not found bento meatadata store

### ISSUE THREAD

**Issue by mayurnewase** [bentoml/BentoML#1098]
**Describe the bug**
if we run command bento get InvalidBentoName:latest,cli throws
`[2020-09-17 19:15:39,725] ERROR - RPC ERROR GetBento: 'NoneType' object has no attribute 'version'`

**Expected behavior**
should give `Error: bentoml-cli get failed: NOT_FOUND:BentoService `InvalidBentoName:latest` is not found`

**Comment by parano** [comment]
hey @mayurnewase, could you share more detail about your setup and what `get` command did you run?

**Comment by yubozhao** [comment]
Thanks for the PR @mayurnewase 
Close with this issue with the PR merged
