### ISSUE TITLE
Add a --profile flag to make it easier to work with multiple AWS accounts

### ISSUE THREAD

**Issue by HenryDashwood** [bentoml/BentoML#1134]
**Is your feature request related to a problem? Please describe.**
If a user has multiple AWS accounts such that their `.aws/credentials` file looks something like
```
[default]
aws_access_key_id = *****************
aws_secret_access_key = *****************
[another_profile]
aws_access_key_id = *****************
aws_secret_access_key = *****************
[yet_another_profile]
aws_access_key_id = *****************
aws_secret_access_key = *****************
```
and are working directly with the AWS CLI, they can specify which account to use with the `--profile` flag.

**Describe the solution you'd like**
It would be good if Bentoml followed this pattern so users could give commands like `bentoml lambda/sagemaker deploy ... --profile another_profile`

**Describe alternatives you've considered**
The current way to handle this is to do `export AWS_PORFILE=another_profile & bentoml lambda/sagemaker deploy ....`

**Additional context**

**Comment by ramanaditya** [comment]
Shall I take up this issue and start working over it?

**Comment by parano** [comment]
After some discussion with the team, we think the alternative approach proposed here is preferrable - ```export AWS_PORFILE=another_profile & bentoml lambda/sagemaker deploy```, thus closing this issue now. 

Thank you @HenryDashwood @ramanaditya.  @ramanaditya let me know if you are interested in taking other issues, happy to chat.
