### ISSUE TITLE
support multiple models deploy for one time in docker

### ISSUE THREAD

**Issue by hwen78** [bentoml/BentoML#1139]
when i use bentoml to deploy model in docker, i can only deploy one model  for one docker . whether i can deploy multiply models in docker for one time ,so models will share same resources. thank you !
such as tensorflow serving:
![model config](https://user-images.githubusercontent.com/22793440/94518192-0f304300-025c-11eb-90f5-1b86d9a7e6e3.JPG)
![docker deploy](https://user-images.githubusercontent.com/22793440/94518193-0fc8d980-025c-11eb-9a51-8ab5ae2a4d9e.JPG)

![models](https://user-images.githubusercontent.com/22793440/94518152-f889ec00-025b-11eb-8d4d-9a672032d0f5.JPG)

**Comment by parano** [comment]
Hey @hwen78, multiple models in one docker is already supported. Here are some related discussion and sample code for working with multiple models: https://github.com/bentoml/BentoML/discussions/928

I'd recommend also reading through the core concept docs here which also covered working with multiple models: https://docs.bentoml.org/en/latest/concepts.html#packaging-model-artifacts

**Comment by hwen78** [comment]
Hey@parano , thanks your answer,but #928 is not my needs. #928 use two models for one predict service, but i want multiply models for multiply predict service, they have not relationship,they just occupy one docker. i have twenty models for twenty different predict services, i want they can run in one docker,so they could take up the least resources in computer. thanks.

**Comment by parano** [comment]
@hwen78 got it,you are looking for serving two models via two different endpoints, but running from the same docker container, right? 

BentoML supports multiple endpoints in one service(one container), and you can define what model you want to use in each endpoint. Here's related docs: https://docs.bentoml.org/en/latest/concepts.html#service-with-multiple-apis

A quick example;
```
import bentoml
from bentoml.adapters import DataframeInput
from bentoml.artifact import SklearnModelArtifact, XgboostModelArtifact

@bentoml.env(infer_pip_packages=True)
@artifacts([
    SklearnModelArtifact("model_a"),
    XgboostModelArtifact("model_b")
])
class MyPredictionService(bentoml.BentoService):

    @bentoml.api(input=DataframeInput(), batch=True)
    def predict_with_a(self, df):
        return self.artifacts.model_a.predict(df)

    @bentoml.api(input=DataframeInput(), batch=True)
    def predict_with_b(self, df):
        return self.artifacts.model_b.predict(df)
```

Packaging models with it:
```
if __name__ == "__main__":
  svc = MyPredictionService()
  svc.pack('model_a', my_model_a)
  svc.pack('model_b', my_model_b)
  svc.save()
```
And now you can containerize the MyPredictionService saved `bentoml containerize MyPredictionService:{VERSION}`, and when starting the container, you will have two endpoints: "/predict_with_a" and "/predict_with_b".

**Comment by hwen78** [comment]
@parano  thanks!
