### ISSUE TITLE
ValueError when starting API server: Unable to configure formatter 'prediction'

### ISSUE THREAD

**Issue by aagq** [bentoml/BentoML#1140]
When I run script, there are some problems:
![image](https://user-images.githubusercontent.com/25698117/94508048-ae950c00-0243-11eb-9de8-708411400b64.png)
![image](https://user-images.githubusercontent.com/25698117/94508123-cff5f800-0243-11eb-94f4-645065669c36.png)

Please tell me how could I do to fix it. Thank you

**Comment by bojiang** [comment]
@aagq Hi. I can not reproduce this issue. What version of BentoML and Python are you using?

**Comment by mayurnewase** [comment]
I face similar issue when all dependencies are not installed.I suggest create new conda env,and install all requirements.

**Comment by yubozhao** [comment]
@aagq Have you try @mayurnewase 's answer?  Let me know if this issue still persists for you.

**Comment by parano** [comment]
Closing it for now, please let us know if you are still seeing similar error messages.
