### ISSUE TITLE
ImageInput doesn't exactly return numpy array

### ISSUE THREAD

**Issue by gregd33** [bentoml/BentoML#1157]
**Describe the bug**
When using the `ImageInput` adapter, the `type` of the object is `<class 'imageio.core.util.Array'>`  rather than `<class 'numpy.ndarray'>`

**To Reproduce**

1. Create a simple service that includes something like:

```  
@bentoml.api(ImageInput)       
def predict(self, image ):
    if type(image) is np.ndarray:
        return True
    return False
```

2. Run the service with any image

**Expected behavior**
You will get a `false`. 

**Environment:**
 - OS: Ubuntu 16.04
 - Python 3.7.9
 - BentoML 0.9.1, numpy 1.19.1, imageio 0.9.1

**Additional context**
This is a somewhat trivial bug and can easily be solved with an explicit cast to ` image = np.array(image)` in the service. However, it did cause me to waste much of the day to try to debug a complex bento service (I looked at a lot of other potential causes before ending up here), so I would like to spare others the same pain.

For a fix, I would either update the documentation to state precisely what it returns or cast it to a numpy array in the adapter itself.

**Comment by yubozhao** [comment]
@gregd33 Sorry about you spend the day debuging Bento Service. I know it can be very frustrating.

Like you suggested, It is now explicitly cast as numpy array in the adapters.

**Comment by yubozhao** [comment]
https://github.com/bentoml/BentoML/pull/1163

**Comment by gregd33** [comment]
Not a problem and thank you for the fix!

**Comment by yubozhao** [comment]
@gregd33 Thank you and really appricate the patients.  Closing this issue, feel free to open for any follow up questions.
