### ISSUE TITLE
Provide a general-purpose API decorator

### ISSUE THREAD

**Issue by fernandocamargoai** [bentoml/BentoML#1161]
**Is your feature request related to a problem? Please describe.**
I'm trying to use BentoML with Seldon Core and I need an endpoint that would receive a GET and return a JSON. Currently, it's not possible with BentoML because it only allows me to create inference endpoints.

**Describe the solution you'd like**
A general-purpose API decorator, which would allow me to create endpoints that are not meant to do inference.

**Describe alternatives you've considered**
Maybe allow me to use the Flask's @route directly.

**Comment by guy4261** [comment]
👍 

The infra already supports `GET` methods (if I browse to `localhost:5000`) - would be nice if we could define some get methods of our own for server metadata etc. Wouldn't even say any support for arguments (i.e. localhost:5000/info?foo=bar) is needed.

![Screen Shot 2020-10-09 at 0 27 26](https://user-images.githubusercontent.com/1596283/95515402-36a6ae80-09c6-11eb-8d5b-53861270e427.png)

**Comment by yubozhao** [comment]
Yes, this is a great idea. It would be great to provide this and give more flexibility for the users.

**Comment by bojiang** [comment]
I guess I know why it was closed  :)

**Comment by parano** [comment]
This has come up a few times before - I think BentoML should provide a more generic `add_url_route` method similar to the one in Flask, which allows users to define arbitrary custom URL routes in their BentoService code.  Those routes should also bypass BentoML's micro batching layer unlike inference APIs annotated with `@api`.

I'm inclined to separate these custom URL route away from `@api` because `@api` is meant for defining an entry point for running inference task, it can be accessed via HTTP request, but also from other places like python API, gRPC, CLI command, batch offline inference job, etc

**Comment by fernandocamargoti** [comment]
I agree with you, @parano. I think it would be better to avoid using `@api` for that and instead expose something similar to the Flask API.

**Comment by parano** [comment]
This is now supported in BentoML 1.0, where users can add any custom ASGI or WSGI app to the BentoService, giving advanced users full customization of their ML Service endpoints.  Here are two examples using Flask and FastAPI to add additional endpoints to a BentoML service:


## Mounting a Flask App to Service

Use `Service#mount_wsgi_app` to mount flask app to a Service. This works for any WSGI based python web application. 

```python
# hello.py
import bentoml
from bentoml.io import JSON
from flask import Flask

flask_app = Flask("sample_wsgi_app")

@flask_app.route("/hello")
def hello_world():
    return "<p>Hello, World!</p>"


svc = bentoml.Service("bento-server-test")
svc.mount_wsgi_app(flask_app)

@svc.api(input=JSON(), output=JSON())
def predict(input_json):
    return {'input_received': input_json, 'foo': 'bar'}

app = svc.asgi_app
```


## Mounting a FastAPI app to Service

Use `Service#mount_asgi_app` to mount FastAPI app to a Service. This works for any ASGI based python web application. 

```python
import bentoml
from bentoml.io import JSON

from fastapi import FastAPI

fastapi_app = FastAPI()

@fastapi_app.get("/hello")
def hello():
    return {"Hello": "World"}

svc = bentoml.Service("hello")
svc.mount_asgi_app(fastapi_app)

@svc.api(input=JSON(), output=JSON())
def predict(input_json):
    return {'input_received': input_json, 'foo': 'bar'}

app = svc.asgi_app
```
