### ISSUE TITLE
Add tf.RaggedTensor support for Tensor input adapter

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1165]
**Is your feature request related to a problem? Please describe.**

For NLP applications, it is common to see variable length tensors, like `[["So", "long"], ["thanks", "for", "all", "the", "fish"]]`.
Tensorflow provides `RaggedTensor` to store and process data with non-uniform shapes
```
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])
```

The current `TfTensorInput` does not support `RaggedTensor`

Current workaround is to use `JsonInput` and convert the data to tensor within the API function.

**Describe the solution you'd like**

Add support for `RaggedTensor` on TfTensorInput

Possible solution:
1. Add `ragged` option for the TfTensorInput:  `TfTensorInput(method='predict', ragged=True)`

```python
@api(input=TfTensorInput(), batch=True)
def predict(self, input: tf.Tensor):
    pass

@api(input=TfTensorInput(ragged=True), batch=True)
def predict(self, input: tf.RaggedTensor):
    pass
```

2. Create a separate InputAdapter, `TfRaggedTensorInput`

**Describe alternatives you've considered**

**Additional context**

**Comment by bojiang** [comment]
Is that `workaround` with JsonInput already a good practice?

**Comment by yubozhao** [comment]
@bojiang I think `JsonInput` is an ok alternative now.  If users want to use the same request schema as `tf-serving` REST API, they will need to do more.

**Comment by bojiang** [comment]
> @bojiang I think `JsonInput` is an ok alternative now.  If users want to use the same request schema as `tf-serving` REST API, they will need to do more.

Got it. 👍

**Comment by terrykong** [comment]
@yubozhao 
I wonder if this should be made a separate issue, but I don't think I can load a model with a `tf.RaggedTensorSpec`. For example, this is an example of a model I might want to save:
```python
class Model(tf.keras.Model):
  @tf.function(input_signature=[
        tf.RaggedTensorSpec([None, None], tf.string),
  ])
  def echo_ragged(self, inputs):
     return inputs

But I get this error when I try to call the API function:
```
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/bentoml/frameworks/tensorflow.py", line 44, in __call__
    for i, arg in enumerate(args)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/bentoml/frameworks/tensorflow.py", line 44, in <genexpr>
    for i, arg in enumerate(args)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/bentoml/frameworks/tensorflow.py", line 69, in _transform_input_by_tensorspec
    if _input.dtype != tensorspec.dtype:
AttributeError: 'RaggedTensorSpec' object has no attribute 'dtype'

```

**Comment by yubozhao** [comment]
@terrykong Let's open a separate issue for this.  Since you have the most context, could you open it and we will go from there.

**Comment by yubozhao** [comment]
@bojiang Let's add documentation and then we can close this issue.

**Comment by bojiang** [comment]
`TfSavedmodelArtifact` now supports RaggedTensor, SparseTensor as the input signatures. Users can use it like this:
```python

@bentoml.artifacts([TfSavedModelArtifact('model')])
class ImdbClassifier(bentoml.BentoService):
    @api(input=JsonInput(), batch=True)
    def predict(self, jsons):
        ragged_tensor = tf.ragged.constant(jsons, dtype=tf.float64)
        return self.artifact.model.predict(ragged_tensor)
```

**Comment by bojiang** [comment]
TfTensorInput doesn't support RaggedTensor now. It is low priority for now.
