### ISSUE TITLE
Option to disable swagger UI

### ISSUE THREAD

**Issue by shihgianlee** [bentoml/BentoML#1167]
**Is your feature request related to a problem? Please describe.**
We would like to have an option to disable Swagger UI in production for select model services.

**Describe the solution you'd like**
A configuration option to disable Swagger UI.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by liusy182** [comment]
My understanding is that, this involves adding a config to turn off swagger when the deployment mode is production.
Since the deployment options vary across platforms, e.g. aws uses bentoml cli, kubernetes uses the yaml, what should the generic solution to this problem?

**Comment by parano** [comment]
@liusy182  I think first you can make this an option in the API Server class: https://github.com/bentoml/BentoML/blob/v0.9.2/bentoml/server/api_server.py#L96

And then add it as a CLI option for `bentoml server` and `bentoml serve-gunicorn`. There's no need to worry about the other deployment platforms(AWS sagemaker, AWS Lambda, Azure Fucntions) for now.

**Comment by liusy182** [comment]
thanks! I will be taking a look of this item.

**Comment by ethagnawl** [comment]
I might be missing something very obvious, but is it possible to disable Swagger via an env var? The only option I see in the PR is `BENTOML_ENABLE_SWAGGER`. Is the expectation that you'd provide 0/1, "t"/"f" or similar as that environment variable's value?
