### ISSUE TITLE
Support Tensorflow signatures that have tf.RaggedTensorSpec inputs

### ISSUE THREAD

**Issue by terrykong** [bentoml/BentoML#1182]
**Is your feature request related to a problem? Please describe.**

Branching off of this comment: https://github.com/bentoml/BentoML/issues/1165#issuecomment-707270318

 I don't think I can load a model with a tf.RaggedTensorSpec. For example, this is an example of a model I might want to save:

```python
class Model(tf.keras.Model):
  @tf.function(input_signature=[
        tf.RaggedTensorSpec([None, None], tf.string),
  ])
  def echo_ragged(self, inputs):
     return inputs
```
But I get this error when I try to call the API function:

```
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/bentoml/frameworks/tensorflow.py", line 44, in __call__
    for i, arg in enumerate(args)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/bentoml/frameworks/tensorflow.py", line 44, in <genexpr>
    for i, arg in enumerate(args)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/bentoml/frameworks/tensorflow.py", line 69, in _transform_input_by_tensorspec
    if _input.dtype != tensorspec.dtype:
AttributeError: 'RaggedTensorSpec' object has no attribute 'dtype'
```

**Describe the solution you'd like**

I would like signatures that use tf.RaggedTensorSpec's to be supported.

**Describe alternatives you've considered**

I could just continue using tf.TensorSpecs and convert to a ragged tensor without my method, but that is inefficient for very jagged tensors

**Additional context**

**Comment by bojiang** [comment]
dup: https://github.com/bentoml/BentoML/issues/1165

**Comment by terrykong** [comment]
@bojiang @yubozhao Should any further discussion about this issue/feature (which describes an issue with methods decorated with `tf.function(input_signature=[tf.RaggedTensorSpec(...`) be continued on https://github.com/bentoml/BentoML/issues/1165 (which describes a feature request for `TfTensorInput` to support `tf.RaggedTensor`s)?

**Comment by bojiang** [comment]
@terrykong oops, my bad.

Let me reopen it.

**Comment by bojiang** [comment]
I am trying to make tensorflow artifact support RaggedTensors. I can join the discussion later.

**Comment by terrykong** [comment]
awesome! 🥳
