### ISSUE TITLE
Azure Functions deployment stale entries for failed deployments

### ISSUE THREAD

**Issue by timlod** [bentoml/BentoML#1187]
**Describe the bug**
After a failed Azure functions deployment (e.g. `bentoml azure-functions deploy iris-classifier-demo2 -b IrisClassifier:0.1.20201019122052_19597E --location uksouth`, which could fail because `az login` was not done), the deployment will still show up in `bentoml azure-functions list`.

Retrying will advice the user to use `bentoml azure-functions update` or `apply`, or deleting the deployment.
When trying to `bentoml azure-functions delete <xxxx>`, there will be an error if the Azure resource group doesn't exist (which invariably will happen if the call fails before Azure does anything).
That deployment is thus going to sit in the list, blocking the name, impossible/hard to remove/update.

**To Reproduce**
See above.

**Expected behavior**
Either make re-deployment override previous deployments, or allow for update/apply/deletion for deployments regardless of where they failed previously.

**Environment:**
 - OS: Ubuntu 18.04
 - Python Version 3.8.0
 - BentoML Version 0.9.2

**Comment by yubozhao** [comment]
@timlod Thanks for reporting.

Did you had the chance to use the `--force` option for the delete command?  It should remove the record for local BentoML. Let me know if this works or not.

I think we should do better at handling the failed create deployment attempts, should automatically handle this type of situations. Thanks for bring this up!

**Comment by timlod** [comment]
Unfortunately, the error persists, in this case by means of missing docker permissions (I don't have `sudo` rights here):
```
> bentoml azure-functions delete --force iris-classifier-demo
errors pretty printing info
[2020-10-20 09:29:14,150] ERROR - RPC ERROR DeleteDeployment: Error executing docker command: Client:
 Debug Mode: false

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by yubozhao** [comment]
Got it. I am going to look into this.

**Comment by yubozhao** [comment]
@timlod For your case, could you make sure your user has docker access/permission and try it again?

I think it is ok to assume the system must have docker access for any Azure Functions deployment actions.

**Comment by timlod** [comment]
I will try bentoML again with the next release, I can check then.

**Comment by yubozhao** [comment]
Got it.  I am going to close the issue for now. Feel free to open back up again, if this issue still happens even when the user has docker access.
