### ISSUE TITLE
Support Adding Metadata at the Bento Level

### ISSUE THREAD

**Issue by terrykong** [bentoml/BentoML#1193]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hi all,

I'm wondering if BentoML can support adding Metadata at the bento level, so that there exists some `METADATA` or `README.md` file at the top level of a service, e.g., `FooService/2019..../README.md` that I can edit/update manually or through something like:
```bash
bentoml edit-medata FooService/2019...
```
And also view either in the Swagger UI and with something like
```bash
bentoml view-metadata FooService/2019...
```

I have learned [there is a PR](https://github.com/bentoml/BentoML/pull/1179) for support for metadata at the artifact level, but I was looking for adding data at the service level, possibly much later after I've `BentoService.pack()/BentoService.save()` the service. Here are some examples of types of metadata I think are more fitting to add after I've packed/saved the service:

1. Metadata that describes usage, e.g., `Use <API> for this partner_1, partner_2, etc. But do not use it for partner_3 because blah blah blah license blah blah`
2. Perhaps I discover that a bento uses a TF version with some vulnerability, and I want to include this information, much later after I did the initial pack/save (Example:[ TF 2.1.2 where certain vulnerabilities were addressed](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.2))
3. I might also want to add some metadata related to latency which is relevant for deployment, e.g.,
```
Here are some sample latencies for <api1>  on V100:
shape=[1, 512]: 52ms
shape=[5, 512]: 100ms
shape=[32, 512]: 120ms 
....
```
4. Strengths or weaknesses of the model. For example, I may learn after the service/model is deployed out in the wild, it does not do well on uncased data, and I would want to elaborate in this bento level `METADATA` file.

Thanks!

**Describe alternatives you've considered**

**Additional context**

@jackyzha0 @yubozhao 
slack thread: https://bentoml.slack.com/archives/CKRANBHPH/p1603146338221400

**Comment by jackyzha0** [comment]
would like to take this on after finishing #1179 :)) but if anyone wants to pick it up before then, feel free

**Comment by yubozhao** [comment]
Hi @terrykong, you can use the undocumented docstring feature on the BentoService.

When you save a BentoService, the docstring on that BentoService will be saved as part of the `README.md` that is automatically generated in the BentoService bundle.

For example:
```python
def MyService(BentoService):
    """
    Additional Information I can share with my teammates

## markdown compatible
    """
    @api(...)
    def predict(...):
        pass
```

I will add documentation for this feature and we will add the readme view as part of the YataiService web UI

**Comment by terrykong** [comment]
Hi @yubozhao. That is interesting and indeed useful

> I will add documentation for this feature and we will add the readme view as part of the YataiService web UI

We aren't currently using yatai, but we may in the future.

Do you think this markdown can be viewable (in the Swagger UI) or retrievable as one of the "infra" endpoints?
![image](https://user-images.githubusercontent.com/7576060/100706538-0ba16100-335e-11eb-8f37-bdd10bb5efcb.png)

**Comment by yubozhao** [comment]
@terrykong I think that's a great suggestion. I am going to try work on that.

**Comment by yubozhao** [comment]
@terrykong This will be release in the next version. You can check out the screenshots of what it looks like in the PR #1333

Feel free to reopen this for more discussions.

**Comment by terrykong** [comment]
awesome @yubozhao ! can't wait to try it out
