### ISSUE TITLE
Add integration tests for FastAI

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1194]
Currently, FastAI artifact code is not tested: https://codecov.io/gh/bentoml/BentoML/tree/master/bentoml/frameworks

We would want to add an integration test suit to test its functionalities including save, load, and run inference from API server.  The setup should be similar to other integration tests that can be found here: https://github.com/bentoml/BentoML/tree/master/tests/integration

**Comment by xiwang129** [comment]
Hi, I would like to work on this one. thank you!

**Comment by yubozhao** [comment]
@xiwang129 Any update? Let me know if you need any help

**Comment by jjmachan** [comment]
@xiwang129 let me know if you're still working on this or can give it a go

**Comment by parano** [comment]
@jjmachan feel free to take it, I don't think @xiwang129  is still working on this.

**Comment by xiwang129** [comment]
@jjmachan can we collaborate on this this week? @parano I got distracted on other stuff but still want to work on this issue :)

**Comment by jjmachan** [comment]
@xiwang129 I missed your message, just saw it now. I've built a rough draft, still, need a lot of corrections. check it out and let me know

**Comment by yubozhao** [comment]
closed #1430
