### ISSUE TITLE
Add integration tests for LightGBM

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1197]
Currently, LightGBM artifact code is not tested: https://codecov.io/gh/bentoml/BentoML/tree/master/bentoml/frameworks

We would want to add an integration test suit to test its functionalities including save, load, and run inference from API server. The setup should be similar to other integration tests that can be found here: https://github.com/bentoml/BentoML/tree/master/tests/integration

**Comment by yubozhao** [comment]
Closing issue.  Thanks to @telescopic !
