### ISSUE TITLE
Using requests is much more difficult for an AnnotatedImageInput than I expected

### ISSUE THREAD

**Issue by pietermarsman** [bentoml/BentoML#1201]
**Is your feature request related to a problem? Please describe.**

It took me a while to use the `requests` package to send properly formatted http requests to a BentoML endpoint that uses a `AnnotatedImageInput`. 

The curl request is nicely documented and it took me a few seconds to adjust it for my usecase:

```
curl -i \
-F image=@20200902050256_2053d67e-c6d3-4352-8dc5-f58a7a120bbe.jpg \
-F polygons=@20200902050256_2053d67e-c6d3-4352-8dc5-f58a7a120bbe.json \
127.0.0.1:15006/predict_polygons
```

However, it took me much more time to reproduce this with the `requests` python package: 

```
import json
import requests

PICTURE_PATH = '20201020130510_c3528898-95f6-4479-9095-c1d9d191d7cb-small.jpg'
ANNOTATION_PATH = '20201020130510_c3528898-95f6-4479-9095-c1d9d191d7cb-small.json'


def get_picture_and_annotation_bytes():
    with open(ANNOTATION_PATH) as f_annotation:
        annotation = json.load(f_annotation)
    polygon_bytes = json.dumps(annotation['annotations']['polygons']).encode()

    with open(PICTURE_PATH, 'rb') as f_picture:
        picture_bytes = f_picture.read()

    return picture_bytes, polygon_bytes


def test_classification_polygon_endpoint(host, port):
    url = f'http://{host.strip("/")}:{port}/predict_polygons'
    image_bytes, polygon_bytes = get_picture_and_annotation_bytes()
    data = {
        'image': ('image.jpg', image_bytes),
        'polygons': polygon_bytes
    }
    return requests.post(url, files=data)


print(test_classification_polygon_endpoint('localhost', 15006).json())
```

**Describe the solution you'd like**

I think there are several fixes:

- First of all, using requests to query the endpoints is not documented. I can why that makes sense, but you could consider adding a page somewhere about this.
- Loosing requirement of filenames with proper extention or allow the content type to be specified in the requests. E.g. the following should work:

```
    url = f'http://{host.strip("/")}:{port}/predict_polygons'
    image_bytes, polygon_bytes = get_picture_and_annotation_bytes()
    data = {
        'image': image_bytes,
        'polygons': polygon_bytes
    }
    return requests.post(url, files=data)
```

or

```
    url = f'http://{host.strip("/")}:{port}/predict_polygons'
    image_bytes, polygon_bytes = get_picture_and_annotation_bytes()
    data = {
        'image': (None, image_bytes, 'image/jpeg'),
        'polygons': polygon_bytes
    }
    return requests.post(url, files=data)
```

Both currently result in response content `BentoML#AnnotatedImageInput Input image file must be in supported format list: ['.jpg', '.png', '.jpeg', '.tiff', '.webp', '.bmp']`

**Describe alternatives you've considered**

It took me toooo long to figure this out...

**Additional context**

**Comment by bojiang** [comment]
It's our flaw that we didn't provide an example using requests.

> First of all, using requests to query the endpoints is not documented. I can why that makes sense, but you could consider adding a page somewhere about this.

I'll open a pull request to fix this.

Just like MultiFileInput, AnnotatedImageInput relies on HTTP content-type `multipart`. In most cases, this kind of request is sent by HTML Form.

> Loosing requirement of filenames with proper extension or allow the content type to be specified in the requests.

We can't. `imageio` need the extension to load images.
