### ISSUE TITLE
Cannot delete bento that was created with same name:version as an older (deleted) bento

### ISSUE THREAD

**Issue by timlod** [bentoml/BentoML#1209]
**Describe the bug**
After deleting a bento, I cannot delete another bento that was created with that same name:version.

**To Reproduce**
1. Create a bento with `name:1` through `model_service.save(version='1')`.
2. In a shell, `bentoml delete name:1`
3. Create a new bento with the same name, again with  `model_service.save(version='1')`.
4. Try to `bentoml delete name:1`

The error is the following:
```
Are you sure about delete name:1? This will delete the BentoService saved bundle files permanently [y/N]: y                                                                                                                                            
[2020-10-27 15:22:33,477] ERROR - RPC ERROR DangerouslyDeleteBento: Multiple rows were found for one()                                                                                                                                                    
Error: bentoml-cli delete failed: INTERNAL:Multiple rows were found for one() 
```
**Expected behavior**
I can endlessly delete and recreate bentos with the same name/version for testing.

**Environment:**
 - OS: Ubuntu 20.04
 - Python 3.8.5
 - BentoML Version 0.9.2

**Comment by yubozhao** [comment]
Thanks @timlod 

I found the issue and will submit a PR to fix this.
