### ISSUE TITLE
Log errors and stack trace inside inference API function user code

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1210]
**Is your feature request related to a problem? Please describe.**

Currently, the BentoML API model server does not print the errors and stack trace when the exception was raised within the user's inference API function code. This makes it hard for users to debug issues in their code.

**Describe the solution you'd like**

Pieter Marsman suggested the following workaround in bentoml slack group:
```python
def log_traceback(f):
    """Log traceback before reraising error
    BentoML does not show traceback by default
    """
    @wraps(f)
    def wrapper(*args, **kwargs):
        try:
            return f(*args, **kwargs)
        except Exception as e:
            logger.exception('Something went wrong')
            raise e
    return wrapper
```

This should be the default behavior in BentoML

**Describe alternatives you've considered**

* always print the error type and error message, but only print stack trace if it’s in debug mode
* vs. always print the error message and stack trace

**Additional context**
\

Discussion in slack channel: https://bentoml.slack.com/archives/CKRANBHPH/p1603730524277500

**Comment by AyoubDali** [comment]
Hey, 
this issue got my attention, can I work on it?

**Comment by parano** [comment]
@AyoubDali sure thing!  I'm always available in slack if you have questions.

**Comment by parano** [comment]
Hi @AyoubDali, just checking in, any update on this?

**Comment by ramanaditya** [comment]
I have considered creating a decorator and using them by wrapping over all the functions.
Will it solve the problem?

**Comment by parano** [comment]
@ramanaditya a decorator API for the user? I don't think that is necessary, this should be BentoML internal and default behavior, user does not need to be aware of it or write any code to invoke it.

**Comment by ramanaditya** [comment]
@parano, not the decorator API for the user, it was meant to be internally used. Or, shall I script down the logger inside each of the function?

**Comment by parano** [comment]
@ramanaditya oh if it's internal use then definitely we can do that to make the code changes cleaner!
