### ISSUE TITLE
No default docker base image configuration in the config file

### ISSUE THREAD

**Issue by anuragvij264** [bentoml/BentoML#1225]
**No default docker base image is available in the config. It breaks the containerizing of service**
https://github.com/bentoml/BentoML/blob/c32c36da5f323e9bccc235c4385e302201c3e798/bentoml/configuration/default_bentoml.cfg#L23

**To Reproduce**
 1. Use this above the service`@bentoml.env(docker_base_image="bentoml/model-server:0.8.12-slim-py37")`

**Expected behavior**
1. Using the commands give here https://docs.bentoml.org/en/latest/concepts.html#api-server-dockerization. It's not able to dockerize the service

**Logs**
<img width="1131" alt="Screenshot 2020-11-05 at 5 14 55 PM" src="https://user-images.githubusercontent.com/41577645/98237131-70011880-1f8a-11eb-86bd-b73dad34b9b0.png">

`Error: bentoml-cli containerize failed: manifest for bentoml/model-server:0.8.12-slim-py37 not found: manifest unknown: manifest `unknown`  `                           

**Environment:**
 - OS: [e.g. MacOS 10.15.7]
 - Python Version [e.g. Python 3.7.9]
 - BentoML Version [e.g. BentoML-0.9.2]

**Comment by parano** [comment]
@anuragvij264 do you mean to use `model-server:0.9.2-slim-py37`?  BentoML does not have 0.8.12 release

The config is supposed to be empty so it uses the default value.
