### ISSUE TITLE
Automatic dockerfile generation not working properly for spacy models

### ISSUE THREAD

**Issue by anuragvij264** [bentoml/BentoML#1226]
**Dockerfile is not getting generated properly**

The Dockerfile that is generated doesn't have the spacy model download command `python -m spacy download en_web_core_sm`. 
 

**To Reproduce**
 I ran the following serving script.

```import bentoml,spacy
from bentoml.adapters import JsonInput
from bentoml.frameworks.spacy import SpacyModelArtifact
@bentoml.env(docker_base_image="bentoml/model-server:0.9.2-py37")
# @bentoml.env(infer_pip_packages=False)
@bentoml.artifacts([SpacyModelArtifact('nlp')])
class SpacyModelService(bentoml.BentoService):
    @bentoml.api(input=JsonInput(),batch = False)
    def predict(self,parsed_json):
        doc = self.artifacts.nlp(parsed_json['text'])
        result = []
        for entity in doc.ents:
            temp = dict()
            temp["name"] = entity.text
            temp["type"] = entity.label_
            temp["span"] = (entity.start_char,entity.end_char)
            result.append(temp)
        return result

nlp = spacy.load("en_core_web_sm")
ner_prediction_service = SpacyModelService()
ner_prediction_service.pack('nlp',nlp)
saved_path = ner_prediction_service.save()
```

**Expected behavior**
The Dockerfile automatically generated should have the Spacy Model download command, since it's being used in the serving script.                      

**Environment:**
 - OS: [e.g. MacOS 10.15.7]
 - Python Version [e.g. Python 3.7.9]
 - BentoML Version [e.g. BentoML-0.9.2]

**Comment by parano** [comment]
Thanks for reporting this @anuragvij264 -  I will look into this.

Is the expected behavior to run the download command during docker build time?

**Comment by anuragvij264** [comment]
@parano Yes its expected to run download command at docker run time.
When one needs to download pretrained models, it should be correctly reflected in the Dockerfile.

**Comment by parano** [comment]
The ideal solution to this problem is to design an `on docker build` hook for BentoService and/or Artifacts to inject code or commands to be executed when building and preparing the docker image. I will do some more exploration on potential solutions and share updates here.
