### ISSUE TITLE
Respect Docker env variables when creating docker API client in bentoml containerize

### ISSUE THREAD

**Issue by ecrows** [bentoml/BentoML#1232]
**Is your feature request related to a problem? Please describe.**
When building Docker images for a private Docker registry, Docker authentication is required.  However, since BentoML uses `docker.APIClient()` instead of `docker.from_env().api` to create the API client, environment variables aren't read (including ones important for authentication).  Everything works fine if you perform a docker login first, but that means that my CI build needs to install the docker CLI (or use a custom image with docker already installed), which is a minor annoyance.

**Describe the solution you'd like**
Switch out `docker.APIClient()` for `docker.from_env().api` (specifically in the bentoml containerize call)

**Describe alternatives you've considered**
`sed 's/docker.APIClient()/docker.from_env().api/g' -i [somepath]/bento_service.py` is the simple monkey patch I'm using at the moment.  Alternatively, you can install docker in the CI builder and call login.

Happy to write the PR myself if you like, though I figured that opening a new pull request and submitting it may be more work than changing the code in this case.

**Comment by jackyzha0** [comment]
Ah this was an oversight from my end when implementing `containerize`. Will make a patch PR in a few minutes! Thanks

**Comment by ecrows** [comment]
Awesome, thanks!

**Comment by yubozhao** [comment]
@jackyzha0 Thank you for the patch!
@ecrows Thank you for sporting this issue. It will be available next release!
