### ISSUE TITLE
Allow specifying BentoML config values when creating a bundle for deployment

### ISSUE THREAD

**Issue by vonsovsky** [bentoml/BentoML#1235]
When docker image is being created, it does not include config file in it. It is recreated with default parameters on the first run. I didn't find any mention if config file could be passed to dockerization step somehow.

**To Reproduce**
Steps to reproduce the issue:
1. bentoml containerize build/MyService/<build id> -t my_service:latest
2. docker ps & docker exec
3. bentoml config view
4. Prints out INFO - Creating local BentoML config file at: /root/bentoml/bentoml.cfg and default config contents

**Expected behavior**
I expect my global config file to be copied into docker and/or give us a way of copying config file of specific project

**Environment:**
 - OS: Windows 10 2004
 - Python 3.8.6
 - BentoML 0.9.1

**Comment by parano** [comment]
Hi @vonsovsky - this is currently an expected behavior because users may want to have their own development config and set production config only explicitly via environment variables.

**Comment by parano** [comment]
@vonsovsky I think you raised a good point and BentoML should provide users a way to specific bentoml config values for a BentoService after it was deployed, I will look into a proposal for making this better

**Comment by parano** [comment]
@vonsovsky could you tell me what are the config values that you'd like to change when deploying with docker?

**Comment by vonsovsky** [comment]
Logging.level=WARN as INFO is causing server to be blocked even for one minute when returning large predictions.

**Comment by parano** [comment]
@vonsovsky I see - have you tested that by changing the logging level the issue went away?  It may also has to do with BentoML writing the prediction request and result to a log file by default(which we are adding an option to allow users to turn off the behavior)

**Comment by vonsovsky** [comment]
Yes, setting up logging.level as WARN solved this issue. We also don't want INFO in production anyway. But option to turn this off completely would be great addition to BentoML.

**Comment by parano** [comment]
thanks for the feedback @vonsovsky - here's the related issue for tuning off logging when running in production and it's on our roadmap https://github.com/bentoml/BentoML/issues/1009

**Comment by vonsovsky** [comment]
@parano Thank you for your cooperation. We appreciate the hard work you put into the framework :-)

**Comment by ssheng** [comment]
@vonsovsky, we'd love to hear your feedback on https://github.com/bentoml/BentoML/pull/1365, which supposed to be addressing this issue.

**Comment by parano** [comment]
I think #1365 will solve the issue of customizing logging behavior in production, we've also revamped BentoML's config system to make it easier to interact with - all BentoML CLI commands now accept a `--config-file` option for users to specify all configuration required for running a BentoML API server or batch inference job.
