### ISSUE TITLE
Support upcoming SqlAlchemy 1.4 version

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1237]
**Describe the bug**

Users encounter `ImportError: cannot import name '_ColumnEntity` issue when using the latest sqlalchemy pre-release 1.4.0b1.

**To Reproduce**

1. install the latest sqlalchemy, `pip install -U sqlalchemy==1.4.0b1`
2. run quickstart example

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by yubozhao** [comment]
We should pin down the version for now, and look into add supporting for the upcoming 1.4 version

**Comment by Sylver11** [comment]
@yubozhao does that mean there is no fix for sqlalchemy==1.4.0b1 ?

**Comment by YunLiaw** [comment]
Hi, is there any plan to upgrade the sqlalchemy to 1.4? thanks.

**Comment by yubozhao** [comment]
@YunLiaw For the upcoming Yatai server, if we are stay with python implementation, we will make sure it supports 1.4 version.

For the local bundle management, we will remove that database dependency.

**Comment by thomasaarholt** [comment]
Has anyone looked at the necessary changes required to support SA 1.4? There are some packages (snowflake-sqlalchemy) that now have 1.4 as a hard dependency.

**Comment by thomasaarholt** [comment]
Brilliant! I see that you have a 1.0 branch going, great stuff :)

There are two main reasons for the request, one nice to have and one more awkward: 
Nice: We have a utility package for creating and serving models that most of our users rely on that depends on (amongst other things) bentoml, pyarrow, snowflake-connector-python. The current chain of dependencies has us unable to use latest pandas, as well as a few other packages (latest snowflake-connector for bugfixes). 

Awkward: New users on the M1 platform are having trouble installing a couple of packages, specifically the old/current version of snowflake-connector, and also pyarrow 3. 

Really great to see effort in reducing the number of dependencies with BentoML! That's something that is typically hard to do, and really appreciated!
