### ISSUE TITLE
New input adapter to support a new format, <image file, string>

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#1239]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I would like to share a requirement that my teammate learned while replacing an existing serving system with BentoML.
Does BentoML provide an input adapter consisting of `<image file, string>`? I didn't find a suitable input adapter at https://github.com/bentoml/BentoML/tree/master/bentoml/adapters.
I would love to hear from you, and I would like to implement this if necessary. It seems that the new input adapter will need to combine FileInput and StringInput.

**Describe alternatives you've considered**

**Additional context**

* Python: 3.6.10
* BentoML Version: 0.9.2

**Comment by parano** [comment]
Hi @withsmilo  - is the `AnnotatedImageInput` is what you are looking for?

https://docs.bentoml.org/en/latest/api/adapters.html#annotatedimageinput

https://github.com/bentoml/BentoML/blob/master/bentoml/adapters/annotated_image_input.py

Example:
```
from typing import Sequence

from bentoml import BentoService, api, artifacts
from bentoml.frameworks.tensorflow import TensorflowSavedModelArtifact
from bentoml.adapters import AnnotatedImageInput

CLASS_NAMES = ['cat', 'dog']

@artifacts([TensorflowSavedModelArtifact('classifier')])
class PetClassification(BentoService):
   @api(input=AnnotatedImageInput(), batch=True)
   def predict(
           self,
           image_list: 'Sequence[imageio.core.utils.Array]',
           annotations_list: 'Sequence[JsonSerializable]',
       ) -> Sequence[str]:
       cropped_pets = some_pet_finder(image_list, annotations_list)
       results = self.artifacts.classifer.predict(cropped_pets)
       return [CLASS_NAMES[r] for r in results]
Query with HTTP request performed by cURL:
```
```
curl -i \
  -F image=@test.jpg \
  -F annotations=@test.json \
  localhost:5000/predict
```

**Comment by withsmilo** [comment]
I had already reviewed it. But there seems to be something I misunderstood in the code. I will discuss this adapter with my teammate in more depth today. Thanks a lot, @parano !

**Comment by withsmilo** [comment]
We decided to use AnnotatedImageInput. Thanks for advice, @parano .
