### ISSUE TITLE
Running wrong BentoML service when accessing it as API 

### ISSUE THREAD

**Issue by Piyush46749** [bentoml/BentoML#1248]
**Describe the bug**
When I am creating and saving multiple bento services and trying to access it as API service, the name of the bento service present on top of the screen is wrong. Each time I change the service and runs a new one, the name is not being updated. There might be two possibilities: -
1. Either the name displayed is wrong.
2. The service running is also not updated and it's running the old service.
![7](https://user-images.githubusercontent.com/35342125/99306338-75cce880-282b-11eb-859a-ad0992114e48.PNG)

**Comment by parano** [comment]
@Piyush46749  could you provide more details for us to reproduce? I've never seen this problem before.

**Comment by Piyush46749** [comment]
@parano  This error has been demonstrated to Bo during a call.

**Comment by parano** [comment]
@Piyush46749  I can not reproduce this on my end. Closing now.  Feel free to re-open if you can provide detailed steps to reproduce.
