### ISSUE TITLE
New input format -- <pdf file , image file>

### ISSUE THREAD

**Issue by sownds7** [bentoml/BentoML#1268]
**Describe the solution you'd like**
I am working on a project that requires input to be <pdf file , image file>. With MulltiImage input adapter , I can take 2 inputs (pdf converted to image and image file). But I would like to know if you can support  my scenario where the input is <pdf file , image file>

**Describe alternatives you've considered**

**Additional context**

![Screenshot ](https://user-images.githubusercontent.com/20153522/99927947-1e2a0200-2d82-11eb-9b5f-e33d0f6a82b7.png)

**Comment by parano** [comment]
@sownds7  have you tried the `bentoml.adapters.MultiFileInput`?

**Comment by sownds7** [comment]
> @sownds7 have you tried the `bentoml.adapters.MultiFileInput`?

Sorry no. Is there a documentation for the same ? I don't seem to find bentoml.adapters.MultiFileInput in  https://docs.bentoml.org/en/latest/api/adapters.html#

**Comment by parano** [comment]
@sownds7  thanks for pointing that out, I just realized that we didn't add it to the docs list(adding it here https://github.com/bentoml/BentoML/pull/1269). For now, you can take a look a the inline docs in that class https://github.com/bentoml/BentoML/blob/master/bentoml/adapters/multi_file_input.py
