### ISSUE TITLE
error while trying to run yatai_service in docker.

### ISSUE THREAD

**Issue by dalavayi** [bentoml/BentoML#1275]
hi, 

i was getting this error, when i tried to run:
docker run -v ~/bentoml:/bentoml -p 3000:3000 -p 50051:50051 bentoml/yatai-service:0.8.6 --db-url=sqlite:///bentoml/storage.db --repo-base-url=/bentoml/repository

alembic.util.exc.CommandError: Can't locate revision identified by '719dd2aacc9a'

not sure what to do for this error, so i tried deleting the record from alembic table with this id,
 after that i am getting this error: 

File "/home/name/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: last_updated_at
[SQL: ALTER TABLE deployments ADD COLUMN last_updated_at DATETIME]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Please help me resolve this issue at the earliest.

**Comment by parano** [comment]
What is the BentoML version installed on your machine?  Can you try using the `latest` version of yatai-service and try again?

```
docker run -v ~/bentoml:/bentoml -p 3000:3000 -p 50051:50051 bentoml/yatai-service:latest --db-url=sqlite:///bentoml/storage.db --repo-base-url=/bentoml/repository
```

**Comment by dalavayi** [comment]
hi @parano , thank you for responding, i am using bentoml version 0.9.2, on GCP VM, i have tried with the revised command which you have suggested, now it is working fine, thank you very much.

**Comment by parano** [comment]
Np! This is due to a database version mismatch. That `docker run` command is only for user to quickly try out running a standalone yatai-service with their local BentoML data. In the production environment with a deployed and standalone yatai-service deployment, the versioning is guarded by gRPC calls so it's not an issue as long as the gRPCs are compatible with the client BentoML version.
