### ISSUE TITLE
Tensorflow Lite Support

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1276]
**Is your feature request related to a problem? Please describe.**

Support Tensorflow Lite in BentoML https://www.tensorflow.org/lite

**Describe the solution you'd like**

Requires further investigation.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by paullee2018** [comment]
I am keen to work on this. I have been playing around with tflite recently with facenet. Could use that as an example?

**Comment by parano** [comment]
@paullee2018 using facenet as an example sounds good, do you mind ping me in the community slack and discuss the solution you had in mind?

**Comment by harshitsinghai77** [comment]
Is this open? I am open to taking this if it is already not taken? @paullee2018 can you please confirm if you're working on the issue?

**Comment by paullee2018** [comment]
I have been busy with my work and moving house so haven't had the time to
do anything. Go ahead harshit.

**Comment by paullee2018** [comment]
Just letting you know I am trying this out  for a project I am working on.
I let you know how it goes.
