### ISSUE TITLE
Add `bentoml prune` command for deleting all saved bundles

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1309]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

```
# remove all local saved bundle
bentoml prune --local

# remove in remote yatai service
bentoml prune --yatai-url=....

# confirm deleting interactively
bentoml prune --interactive
> Remove service IrisClassifer:V1231231? enter y(yes) or n(no):
> yes
> ..

```

**Describe alternatives you've considered**

**Additional context**

**Comment by tahentx** [comment]
@parano What is the intended distinction between prune and `bento delete`?

**Comment by parano** [comment]
@tahentx `bentoml delete` currently can only delete one saved bundle at a time, this issue was meant for adding support for deleting in batches by labels, service name or DateTime range, and there's a python API for it right now called `prune`: https://docs.bentoml.org/en/latest/api/yatai_client.html#bentoml.yatai.client.bento_repository_api.BentoRepositoryAPIClient.prune

Great question, I actually think merging `delete` and `prune` into one API and one command make sense, e.g.:

```
yatai_client = get_yatai_client()

# delete single item
yatai_client.repository.delete('my_service:version')

# batch delete by labels
yatai_client.repository.delete(labels='ci=failed')
yatai_client.repository.delete(name='my_service')
yatai_client.repository.delete(prune=True) # delete all

```

cc @yubozhao

**Comment by yubozhao** [comment]
I think this is a great suggestion. We should combine the APIs together and make it easier to understand.
