### ISSUE TITLE
Add support for CatBoost

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1327]
**Is your feature request related to a problem? Please describe.**

Add support for serving CatBoost models in BentoML. CatBoost is a high-performance open source library for gradient boosting on decision trees https://catboost.ai/

**Describe the solution you'd like**

* Add a new BentoArtifact class in bentoml that support loading and saving CatBoost model
* Add documentation on how to use CatBoost with BentoML
* Add integration tests
* Add an example notebook to bentoml/gallery

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by Trollgeir** [comment]
Have you tested if this doesn't already work by using the scikit learn framework?

**Comment by j-hartshorn** [comment]
As `SklearnModelArtifact` uses `joblib` to serialise the model, I can see why this would work. Still, it might be good to have an explicit `CatBoostModelArtifact` which utilises CatBoost's binary format do you think?

**Comment by harshitsinghai77** [comment]
Is this issue still open?

**Comment by harshitsinghai77** [comment]
I'm working on this issue.

For the documentation part, notebooks are uploaded on `https://colab.research.google.com/github/bentoml/gallery/blob/master/`

How to get my notebook uploaded so that I can link it in the documentation page?

**Comment by harshitsinghai77** [comment]
https://github.com/bentoml/BentoML/pull/1539

**Comment by harshitsinghai77** [comment]
Can we close this as it's already been taken care of?
