### ISSUE TITLE
Can't reach swagger static files when deploy with ingress

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1328]
**Describe the bug**

This issue is created from discussion #1325.

Swagger static files are not able to reach (404) when the bento service is deployed as service with ingress (ingress controller is Nginx) in a Kubernetes cluster.

When porter forwarding from the deployment `kubectl por-forward bentopod 5000:5000`, everything works fine.

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by mat-berna** [comment]
Hi.
Are there any evolutions on this issue?

I have the same problem when the bento service is deployed as service with ingress (ingress controller is Nginx) in a Kubernetes cluster.

My manifests:

`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bento-deploy-123
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bento-123
  template:
    metadata:
      labels:
        run: bento-123
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      serviceAccountName: sa
      containers:
        - name: bento-{service-request-name}
          image: cr/bento-{service-request-name}:{image-id}
          ports:
            - containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: cr-auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: bento-123
  name: bento-service-123
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    run: bento-123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bento-ingress-123
  annotations:
    cert-manager.io/cluster-issuer: q3p-issuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: bento-host
      http:
        paths:
          - path: /123(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: bento-service-123
                port:
                  number: 5000
  tls:
    - hosts:
        - bento-host
      secretName: bento-tls
`

Thanks.

**Comment by parano** [comment]
In BentoML version 1.0, kubernetes deployments are managed via [Yatai](https://github.com/bentoml/yatai) which handles all the deployment endpoints creation and ingress resources out-of-the-box. Updating to 1.0 will resolve this issue.
