### ISSUE TITLE
The YataiService gRPC server doesn't support URL location prefix

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#1329]
**Describe the bug**

When I run YataiService with `--web-prefix-path` option, the YataiService gRPC server doesn't have a prefix path. I think https://github.com/bentoml/BentoML/issues/1063 missed this bug.

**To Reproduce**

**Expected behavior**

The YataiService gRPC server should be executed on `127.0.0.1:50051/test_prefix`.

**Screenshots/Logs**

```bash
BENTOML__CORE__DEBUG=true bentoml yatai-service-start --web-prefix-path test_prefix --verbose
[2020-12-16 09:57:52,224] DEBUG - Setting debug mode: ON for current session
[2020-12-16 09:57:52,367] DEBUG - Upgrading tables to the latest revision
[2020-12-16 09:57:52,374] DEBUG - Enabling gRPC server reflection for debugging
* Starting BentoML YataiService gRPC Server
* Debug mode: on
* Web UI: running on http://127.0.0.1:3000/test_prefix
* Running on 127.0.0.1:50051 (Press CTRL+C to quit)
* Usage:
*  Set config: `bentoml config set yatai_service.url=127.0.0.1:50051`
*  Set env var: `export BENTOML__YATAI_SERVICE__URL=127.0.0.1:50051`
* Help and instructions: https://docs.bentoml.org/en/latest/guides/yatai_service.html
* Web server log can be found here: /Users/user/bentoml/logs/yatai_web_server.log
```

**Environment:**
 - OS: MacOS Catalina 10.15.7
 - Python Version: 3.6.12
 - BentoML Version: 0.10.1

**Additional context**

**Comment by yubozhao** [comment]
I think that's the expected behavior for the gRPC endpoints right now.  Did you run into a use-case that you want to have the prefix for the gRPC endpoints?

**Comment by withsmilo** [comment]
@yubozhao 
Yes. I'd like to run the YataiService behind a reverse proxy server. Is it impossible?

**Comment by yubozhao** [comment]
It is definitely possible.  That PR only added the support for the prefix on web UI.  We will need to add the prefix support for the gRPC endpoints.  

Is this a blocking issue for you right now?

**Comment by withsmilo** [comment]
@yubozhao 
It is not a blocking issue for me, but I think it is a necessary function for security.

**Comment by yubozhao** [comment]
Yes, that makes sense.  I will add this to the roadmap and we will try to get this address in the next few releases

**Comment by withsmilo** [comment]
Thanks, @yubozhao !

**Comment by parano** [comment]
@withsmilo I thought the URL prefix was only meant for the browser when deploying a web server behind a proxy, could you tell me about what use cases it would need the prefix for the gRPC endpoint?

**Comment by withsmilo** [comment]
@parano 
You're right. It works without any problem, but there is a security problem that exposes gRPC server's port to users.
