### ISSUE TITLE
bentoml retrieve fails after upgrading to 0.10.1

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1336]
**Describe the bug**
I first upgraded my yatai-service from 0.9.2 to 0.10.1.
Then upgraded my traning pipeline to 0.10.1 - It worked flawlessly and stored newer versions of Model into S3 storage.
I then proceeded to build my BentoService via a custom Docker build.
Note - I use my own Dockerfile - with the command:

`RUN bentoml retrieve Service:latest --target_dir /bentoservice`

The Docker build broke with the following error:
```
|   File "/usr/local/lib/python3.8/site-packages/bentoml/cli/bento_management.py", line 256, in retrieve                                                       
|     yc.repository.download_to_directory(bento_pb, target_dir)                    |
|   File "/usr/local/lib/python3.8/site-packages/bentoml/yatai/client/bento_repository_api.py", line 255, in download_to_directory                             |
|     bento_service_bundle_path = bento_pb.bento.uri.s3_presigned_url              |
| AttributeError: bento                                                            |
| The command '/bin/sh -c bentoml retrieve Service:latest --target_dir /bentoservice' returned a non-zero code: 1                              |
```

**Environment:**
 - Python 3.7.1
 - BentoML-0.10.1
 -

**Comment by bojiang** [comment]
Ops. I guess just remove the `bento.` and it will work.

**Comment by bojiang** [comment]
@yubozhao

**Comment by jiyer2016** [comment]
@bojiang - Sorry, I didnt understand - Whhere do I remove the `bento.` ?

**Comment by bojiang** [comment]
@jiyer2016
Sorry for the unclear reply.
I believe it is indeed a bug of bentoml. The comment I just made is for developers.

**Comment by yubozhao** [comment]
Thanks for reporting this issue. I will fix it and hopefully we can release a new patch before the holiday with this fix in.
