### ISSUE TITLE
Issues with Rolling back from 0.10.1 into 0.9.2

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1337]
**Describe the bug**
I have BentoML v0.9.2 running on my infrastructure.
Today, I decided to upgrade to 0.10.1

1. I first upgraded the yatai-service and then my training pipeline.
2. Things were going smooth - and I was even able to store a new version of my Model in S3.
3. However, I faced an issue with building my Model into a Docker Image - see [1336](https://github.com/bentoml/BentoML/issues/1336)
4. I now decided to roll-back yatai and my training pipeline back to 0.9.2
5. After I rolled back - I noticed that the yata-service began malfunctioning - See error below.
6. It seems like this happened because the older version of Bento (0.9.2) could NOT handle model artifacts created by the training pipeline after m original 0.10.1 upgrade.
7. I then re-upgraded back to 0.10.1 - and used the `bentoml delete`  to get rid of the offending model 
8. Finally downgraded to 0.9.2 - and now my system is operational

```
Encounter HTTP Request Error
{"data":{"error":"Failed to parse artifacts field: Message type \"bentoml.BentoServiceMetadata.BentoArtifact\" has no field named \"metadata\".\n Available Fields(except extensions): ['name', 'artifactType']."},"status":400,"statusText":"Bad Request"
```

My questions are:

1. Did I do the right thing ?
2. Could I have managed the situation better / differently ?
3. Is there something that can be baked into the product for safer upgrades ?

**Comment by yubozhao** [comment]
You did the right thing.  It was a regression that will block your workflow.  Rolling back is the best option at that moment.

It is an unaccounted change(The new metadata field) that breaks when downgrading to an older version.

**Comment by parano** [comment]
Thanks for reporting the issue @jiyer2016 - this helped us discover a problem when changing BentoML's Protobuf definition. We have since introduced a set of backwards compatibility tests to prevent errors like this from happening in the future: https://github.com/bentoml/BentoML/pull/1370
