### ISSUE TITLE
Yatai Web UI has potentially slowed down in 0.10.x

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1339]
**Describe the bug**
Converted [discussion - 1335](https://github.com/bentoml/BentoML/discussions/1335) into bug report.
I (briefly) upgraded to 0.10.1 today - and found the yatai-web ui significantly slower than the norm. 
I timed a few page loads via "Chrome Developer Tools" - and it took ~60 seconds. 

A downgrade to 0.9.2 brought back page load times into the normal range.
I did not get a chance to explore if this was caused by a network issue on my end - but it seemed like it wasn't because the downgrade effectively fixed the "slowness" (on two counts).
I have 153 Bento's (under Repository) - None of them have "labels" attached.

**Environment:**
 - Python 3.8
 - BentoML-0.10.1
 - S3 (Minio)
 - PostGreSQL

**Comment by parano** [comment]
@jiyer2016  is this still an issue with the newer versions of BentoML?
