### ISSUE TITLE
Customize request schema in swagger

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1348]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
```python
my_schema = {
  "application/json": {
    "schema": {
      "type": "object",
      "required": ["field1", "field2"],
      "properties": {"field1": {"type": "string"}, "field2": {"type": "uuid"}},
    },
  }
}
class MyService(BentoService):
    @bentoml.api(input=JsonInput(request_schema=my_schema))
    def predict(self, input):
        ....
```

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
Does swagger/openapi has a helper function for something like "input json example to schema" convertor?

**Comment by yubozhao** [comment]
> Does swagger/openapi has a helper function for something like "input json example to schema" convertor?

I am not sure about first party.  When I was looking into this issue before, I found a few 3rd parties tools, such as https://github.com/Roger13/SwagDefGen
