### ISSUE TITLE
Bentoml incompatible with tensorflow 2.4.0 due to grpcio dependency

### ISSUE THREAD

**Issue by lminer** [bentoml/BentoML#1359]
Bentoml appears to be incompatible with the latest tensorflow

```
pip install tensorflow
pip install --pre -U bentoml
```

Yields:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.4.0 requires grpcio~=1.32.0, but you'll have grpcio 1.27.2 which is incompatible.
```
tensorflow=2.4.0
bentoml=0.10.1

**Comment by parano** [comment]
Thank you for reporting this @lminer - grpcio version has come up a few times lately and looks like we are limited to an older version now, I will look into upgrading it.

**Comment by bojiang** [comment]
I've checked the dep tree with `pipdeptree`. There are no other dependencies that required grpcio<=1.27.2. So it's safe to bump the version of `grpcio`.

**Comment by lminer** [comment]
Is this fixed?

**Comment by parano** [comment]
@lminer this is not fixed, I haven't got a chance to look into it

**Comment by Samreay** [comment]
+1 for this issue. I noticed that the grpcio version was locked due to issues with Lambda, so fingers crossed that one of the more recent grpcio releases since that issue 6 months ago has resolved it :)

**Comment by parano** [comment]
This is resolved in the latest release 0.11.0

**Comment by kosigz-lyft** [comment]
> This is resolved in the latest release 0.11.0

Hi @parano and all, what does it mean that it's resolved? 

I'm also seeing issues installing tensorflow versions 2.4.0 and 2.4.1 due to a pinned dependency in grpcio that doesn't play nice with other packages we use at Lyft.

**Comment by parano** [comment]
It should no longer be a problem if you upgrade BentoML to the latest version. Are you still experiencing the same problem with the new version?

**Comment by kosigz-lyft** [comment]
> It should no longer be a problem if you upgrade BentoML to the latest version. Are you still experiencing the same problem with the new version?

> tensorflow 2.4.0 requires grpcio~=1.32.0

Thanks! I actually experienced this problem with one of our Lyft-internal libraries (unrelated to Bento). 😅 Googled the error and wound up here thinking there's some discussion of why tensorflow 2.4.0 is constrained to use that exact grpcio version.

**Comment by parano** [comment]
@kosigz-lyft got it, glad to hear that the Lyft team is using BentoML now!
