### ISSUE TITLE
Allow cross-origin resource sharing with serve-gunicorn

### ISSUE THREAD

**Issue by jvdavim** [bentoml/BentoML#1367]
**Is your feature request related to a problem? Please describe.**
I can't post to a REST API served with `bentoml serve-gunicorn` using javascript. The browser seems to need the cross-origin resource sharing (CORS) response header to get the right response.
 
**Describe the solution you'd like**
Add `Access-Control-Allow-Origin` to the response header.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yubozhao** [comment]
Hey @jvdavim That's a good ssuggestion. We should make browser access more easier.

Would you mind share how are you using BentoML in your production and your usecases?  I'd love to use this opportunity to undertstand them better and make BentoML better suite for them.

**Comment by parano** [comment]
Hi @jvdavim -  you can already customize the HTTP response header in BentoML, here are some sample code from the documentation https://docs.bentoml.org/en/latest/concepts.html#defining-a-batch-api

```python
import bentoml
from bentoml.types import JsonSerializable, InferenceTask, InferenceError  # type annotations are optional

class MyService(bentoml.BentoService):

    @bentoml.api(input=JsonInput(), batch=False)
    def predict(self, parsed_json: JsonSerializable, task: InferenceTask) -> InferenceResult:
        if task.http_headers['Accept'] == "application/json":
            predictions = self.artifact.model.predict([parsed_json])
            return InferenceResult(
                data=predictions[0],
                http_status=200,
                http_headers={"Content-Type": "application/json"},
            )
        else:
            return InferenceError(err_msg="application/json output only", http_status=400)
```

**Comment by yubozhao** [comment]
Closing this with @parano's solution. @jvdavim  Feel free to reopen this issue with any questions.
