### ISSUE TITLE
Avoid ambiguous sources for conda-forge packages in `environment.yml`

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1371]
**Describe the bug**

The current channel priority setting causes unpredictable behavior during building model-server docker images.
This is also the reason for the eventual failures of integration tests using TensorFlow.

Take the default conda requirement `pip` as an example.
Since the first channel in `environment.yml` is "conda-forge", conda will **randomly** pick the first package named `pip` in the forge (https://anaconda.org/search?q=pip).

More specifically, on macOS, in half cases, it got `pip` of `pypy` installed. And then it will fail when running `pip install tensorflow==1.14.0` because there is no tensorflow release for pypy.

refs:
- https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html?highlight=channel_priority#strict-channel-priority
- https://github.com/bentoml/bentoml/blob/1e452e9575d455136dd441e7a1c7190bc0231cf7/bentoml/service/env.py#L57

**How to reproduce:**
- step 1: prepare an environment with `TensorFlow==1.14.0` and `bentoml[test]` installed
- step 2: run `pytest -s tests/integration/test_tensorflow_v1_savedmodel_artifact.py`
- step 3: try 1 and 2 for several times until errors occured

**Environment:**
 - OS: All
 - Python Version: All
 - BentoML Version: 0.10.1 and before

**Additional context**

**Comment by bojiang** [comment]
```
(base) root@a101ba16670b:/# conda install conda-forge::python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda-forge::python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h7b6447c_0          78 KB
    cffi-1.14.0                |   py37h2e261b9_0         224 KB
    expat-2.2.10               |       he6710b0_2         153 KB
    gdbm-1.18                  |       h941a26a_0         187 KB  conda-forge
    libffi-3.2.1               |    hf484d3e_1007          48 KB
    pypy3.7-7.3.3              |       h0effd1a_1        33.6 MB  conda-forge
    python-3.7.9               |        4_73_pypy           5 KB  conda-forge
    python_abi-3.7             |    1_pypy37_pp73           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        34.3 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  expat              pkgs/main/linux-64::expat-2.2.10-he6710b0_2
  gdbm               conda-forge/linux-64::gdbm-1.18-h941a26a_0
  pypy3.7            conda-forge/linux-64::pypy3.7-7.3.3-h0effd1a_1
  python_abi         conda-forge/linux-64::python_abi-3.7-1_pypy37_pp73

The following packages will be UPDATED:

  python                 pkgs/main::python-3.7.6-h0371630_2 --> conda-forge::python-3.7.9-4_73_pypy

The following packages will be DOWNGRADED:

  cffi                                1.14.1-py37he30daa8_0 --> 1.14.0-py37h2e261b9_0
  libffi                                     3.3-he6710b0_2 --> 3.2.1-hf484d3e_1007


Proceed ([y]/n)?
```

**Comment by bojiang** [comment]
```
(base) root@a101ba16670b:/# conda install defaults::python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

```

**Comment by withsmilo** [comment]
Hi, @bojiang @parano 
We're suffering this issue with BentoML 0.10.1 on the production environment now How can we avoid this as workaround?

**Comment by parano** [comment]
@withsmilo I just spoke to @bojiang about #1375, we are planning to remove `conda-forge` from the default conda-channels list. We are planning to release a new version next Monday which will contain this fix.

'conda-forge' was added there because we used to install the exact python version, which sometimes only available from `conda-forge`, but we've changed that behavior to only making sure the Python major and minor version matches requirement.

**Comment by withsmilo** [comment]
@parano 
I'm so glad to hear the good news! Thanks for quick patch. I'will wait for new release next Monday. 👍

**Comment by bojiang** [comment]
@withsmilo 
The workaround depends.

For a service like this
```python
@bentoml.artifacts([H2oModelArtifact('model')])
@bentoml.env(
  pip_packages=['pandas', 'tersorflow==1.14.0'],
)
class ExamplePredictionService(bentoml.BentoService):

  @bentoml.api(input=DataframeInput(), batch=True)
  def predict(self, df):
      return self.artifacts.model.predict(df)
```

Just put "pkgs/main::python=<your_python_version>" into the conda_dependencies should do the trick. It prevents conda from installing python from channel `conda-forge`.
```
@bentoml.env(
  pip_packages=['pandas'],
  conda_dependencies=['tersorflow==1.14.0', "pkgs/main::python=3.7"]
)
```

**Comment by withsmilo** [comment]
@bojiang 
Wow! Thanks for great workaround.
