### ISSUE TITLE
Failed to containerize bundle with s3 as BentoML repository

### ISSUE THREAD

**Issue by felix-zg** [bentoml/BentoML#1373]
**Describe the bug**
When I use S3 storage for the package repo creating of docker image.

**To Reproduce**
1. set `BENTOML_REPO_BASE_URL=bentoml-repo`
2. create a package, package created localy
3. run `bentoml containerize XXX:latest -t xyz` creating a new working docker image
4. set `BENTOML_REPO_BASE_URL=s3://bentoml-repo`
5. create a package, package created in s3 bucket
6.  run `bentoml containerize XXX:latest -t xyz` no image created

Environment:

MacOS 10.15.6
Python 3.6.8
BentoML 0.10.1
PostgreSQL 11.9

**Comment by yubozhao** [comment]
Thanks for creating an issue for this.  Here is the link to the additional context in Slack: https://bentoml.slack.com/archives/CKRANBHPH/p1609261908276300

**Comment by yubozhao** [comment]
@felix-zg This issue is fixed after #1316 merges into master.

**Comment by felix-zg** [comment]
@yubozhao I'm using the latest docker image

**Comment by yubozhao** [comment]
@felix-zg Yeah, the PR is still open and ongoing.  After we merged it and publish a new version, this bug will be fixed then.

**Comment by felix-zg** [comment]
@yubozhao sorry I missed the fact is still open :) 
When its plan to publish a new version?

**Comment by felix-zg** [comment]
@yubozhao thank you :)
