### ISSUE TITLE
Unable to access Yatai Web UI

### ISSUE THREAD

**Issue by dalavayi** [bentoml/BentoML#1380]
I have spin up the docker image for yatai service for model management, when i am trying to access the web UI from the url, the page shows loading symbol for a fraction of second and the page goes blank. I tried reloading it many times but the same thing is happening. 

version of bentoml : 0.10.1

command used : docker run -v ~/bentoml:/bentoml -p 3000:3000 -p 50051:50051 bentoml/yatai-service:latest --db-url=sqlite:///bentoml/storage.db --repo-base-url=/bentoml/repository

**Comment by parano** [comment]
Hi @dalavayi - I can't seem to reproduce this issue, I ran the same command and see the web UI without any problem.  This could be a frontend issue too, could you share what's the browser and OS where you tested it?

**Comment by dalavayi** [comment]
hi @parano thanks for the quick response, i am using windows 10 OS, i used google chrome Version 87.0.4280.88, i tried the same in internet explorer also, it shows a blank page only.

**Comment by dalavayi** [comment]
![image](https://user-images.githubusercontent.com/72725647/103616351-48aad580-4f52-11eb-9107-5d03b76d9587.png)
It shows this for a fraction of second and goes blank.
![image](https://user-images.githubusercontent.com/72725647/103616379-58c2b500-4f52-11eb-9608-18fcfe5a5205.png)
