### ISSUE TITLE
BentoService unexpectedly works despite feeding bad input to Tensorflow Function

### ISSUE THREAD

**Issue by jiyer2016** [bentoml/BentoML#1384]
**Describe the bug**
I was debugging some tensorflow function warnings on my BentoService deployment (more on that later) which led me to the following observation.

1. My Bento Service is backed with a Tensorflow Model
2. The Tensorflow Model accepts tf.float32 type tensors only
3. My Bento Service is purposefully programmed to fail always - i.e. feed an incompatible tensor (tf.int32 type) to the Tensorflow Model
4. The Bento Service fails (as expected) during unit tests
5. However - once deployed - the BentoService (unexpectedly) successfully invokes the Tensorflow Model - and even returns a response.

Why does this happen ??

**Test Cases To Reproduce the problem**
```
import unittest
import bentoml
import requests
import tensorflow as tf
from bentoml.adapters import JsonInput
from bentoml.frameworks.tensorflow import TensorflowSavedModelArtifact
```

1. First Define the Tensorflow Model - This model accepts only tf.float32 based on the input_signature spec
```
class Model(tf.Module):
    # This tensorflow model accepts float32 input only
    @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.float32), ])
    def double(self, a: tf.Tensor) -> tf.Tensor:
        return tf.multiply(a, 2)
```

2. Next Define the Bento Service - Set it up so that incompatible tensors (int32) is always fed into the underlying Tensorflow Model - This Service is designed to fail always
```
@bentoml.env(auto_pip_dependencies=True)
@bentoml.artifacts([TensorflowSavedModelArtifact('model')])
class Service(bentoml.BentoService):

    @bentoml.api(input=JsonInput(), )
    def predict(self, json_input: dict):
        # Purposefully feed bad input - int32 always - This model should always fail
        bad_value = tf.constant(120, dtype=tf.int32)
        r = self.artifacts.model.double(bad_value)
        return {'r': r.numpy()}
```
3. Run a series of test cases that validates that the Model and Service fail always. Surprisingly the final test case fails - i.e. the BentoService - Tensorflow Model interaction actually works when it is NOT supposed to
```
class MyTestCase(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.target_dir = '...'
        cls.service_url = 'http://127.0.0.1:5000/predict'


    def test_model_must_error_on_incompatible_input(self):
        model = Model()
        with self.assertRaises(ValueError):
            # Fails since input is int32 instead of float32
            model.double(tf.constant(120, dtype=tf.int32))

    def test_bento_service_should_fail_always(self):
        model_dir = self.target_dir
        model = Model()
        service = Service()
        service.pack('model', model)
        with self.assertRaises(ValueError):
            # Fails since BentoService feeds bad input - int32 to tensorflow model
            service.predict(dict()) # should fail always
        service.save_to_dir(model_dir)

    def test_deployed_bento_service_should_fail_always(self):
        # Make sure Bento Service is running via a - bentoml serve ...
        # Surprisingly - The BentoService - Model invocation works when deployed (tested on flask deployment)
        response = requests.post(url=self.service_url, json=dict())
        print(response.content)
        # Was expecting this to fail with something other than a HTTP 200
        self.assertNotEqual(response.status_code, 200)
```

**Environment:**
 - OS: Windows (might happen in Linux as well)
 - Python 3.8.3
 - bentoml==0.9.2
 - tensorflow==2.3.1

**Comment by jiyer2016** [comment]
Did anyone get a chance to review this ?

**Comment by bojiang** [comment]
@jiyer2016 Hi. Sorry for my late reply.
This is because of the automatic casting feature of the `TensorflowSavedModelArtifact`. It will convert the input data to meet the signatures when possible.

**Comment by parano** [comment]
@jiyer2016 closing this ticket now - let me know if this is still an issue for you
