### ISSUE TITLE
hadoop file system load and write support

### ISSUE THREAD

**Issue by ghostviper** [bentoml/BentoML#1393]
Firstly, thanks everyone who make contribution to bentoML. when i delopy ML model to production situation,I need to use hadoop file system exchange raw data on local prod env.but BentoML only support s3 and google cloud remote save bundle.Hope project can support more remote bundle saved in the future. thanks again!

**Comment by parano** [comment]
Hi @ghostviper - are you currently using a standalone Yatai server for model management?  HDFS might not be an ideal solution for Yatai but we could certainly add support for the `load` and `save` API. Do you mind tell me a bit more about your use case and requirements here?

**Comment by ghostviper** [comment]
> Hi @ghostviper - are you currently using a standalone Yatai server for model management? HDFS might not be an ideal solution for Yatai but we could certainly add support for the `load` and `save` API. Do you mind tell me a bit more about your use case and requirements here?

@parano Hello parano! I want to build a central model management env for project team share ML models on machine A.other production env machine (eg. B,C,D) can pull ML model from A through 'bentoml pull MODEL' command.I read the code related to repository api and yatai service configuration only find ‘s3’，‘google driver’ support repo_base_url. When I setting repo_base_uri='~/bentoml/repository' or http url,'FileNotFoundError: [Errno 2] No such file or directory:' occur!

**Comment by parano** [comment]
@ghostviper BentoML now supports uploading and downloading directly with Yatai server backed by local file system storage https://github.com/bentoml/BentoML/commit/d367c2e90dabdb5207e15814ed0a2f25fb49c013

This will be available in the next release 0.13.0
