### ISSUE TITLE
Refactor SQL query for listing bentos with labels

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1395]
**Describe the solution you'd like**

For listing bentos, yatai service's metadata_store is first query a list of it in labels table with matching filters, and then query the bentos with those ids.  

Desired solution is retrieve bento from sql with one query only.

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
This is no longer relevant since we have moved Yatai to a separate project here, rebuilt from scratch https://github.com/bentoml/yatai
