### ISSUE TITLE
Pipenv lock requirements.txt failes validation with InvalidRequirement

### ISSUE THREAD

**Issue by j-hartshorn** [bentoml/BentoML#1406]
**Describe the bug**
I am using `Pipenv` to manage package environments, and so I want to use it to generate a requirements file for use in the bento package. However, the file generated by `Pipenv` fails validation when calling `.save()` or `.save_to_dir()`.

```
InvalidRequirement: Parse error at "'-i https'": Expected W:(abcd...)
```

To generate a `requirements.txt` file for non-development packages with `pipenv` one can run the command `pipenv lock -r > requirements.txt`.

The top of that file looks like this
```
#
# These requirements were autogenerated by pipenv
# To regenerate from the project's Pipfile, run:
#
#    pipenv lock --requirements
#

-i https://pypi.org/simple
```

It looks like the like beginning `-i` is not expected by the validation mechanism in bentoml, even though it's a valid requirements file for pip.

**To Reproduce**
Using `pipenv` to manage a python environment,  create a `requirements.txt` using the command
```
pipenv lock -r > requirements.txt
```

Then refer to this file in the bento definition like so
```
@bentoml.env(requirements_txt_file="./requirements.txt")
```

When saving the bento, you will see the error mentioned above.

**Expected behavior**
Bentoml accepts this format of requirements.txt without any changes.

**Environment:**
 - OS: MacOS 10.15.7
 - Python 3.8.6
 - pipenv, version 2020.11.15
 - bentoml, version 0.10.1

**Additional context**
A workaround for now is to remove the offending line when creating the `requirements.txt` file with something like this:
```
pipenv lock -r > requirements.txt && sed -i -e "/^-i/d" requirements.txt && rm requirements.txt-e
```

**Comment by bojiang** [comment]
In short pip supports `requirements.txt`with customized PyPI URL like this:
```
-i https://pypi.org/simple
bentoml=0.11.0
```
, but `@bentoml.env(requirements_txt_file` throws `InvalidRequirement`.
