### ISSUE TITLE
Support multi-input custom dataframe input adaptor

### ISSUE THREAD

**Issue by ANDRYA005** [bentoml/BentoML#1413]
**Is your feature request related to a problem? Please describe.**

We are trying to create a custom Dataframe input adaptor that allows the user to pass multiple dataframes to a prediction api. An example input to the service is:

```
'{
  "df_1": {"index":[0, 1], "columns": ["A", "B"], "data": [[1.0, 0.5], [3, 4]]},
  "df_2": {"index":[0, 1], "columns": ["C", "D"], "data": [[1.0, 2], [3, 2]]}
}'
```

There is one line in `dataframe_util.py` that inhibits us from doing it efficiently. The `_dataframe_csv_from_input(.)` method contains the line

```python
table = json.loads(table)
```

The problem is that we have to parse the input data (string) to a python dictionary to be able to identify and isolate each specific data input. Then we have to parse the isolated inputs back to JSON to be able to run `_dataframe_csv_from_input(.)` for each respective input. This is computationally expensive.

**Describe the solution you'd like**

We would like `_dataframe_csv_from_input(.)` to be slighty modified. This involves changing

```python
table = json.loads(table)
```

to

```python
if isinstance(table, str): 
   table = json.loads(table)
```

This allows us to run `json.loads(input_data)` prior to calling `_dataframe_csv_from_input(.)` which suits our use case.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by yubozhao** [comment]
cc @bojiang

**Comment by bojiang** [comment]
`_dataframe_csv_from_input` is a private API and for bentoml internal use only, since it is not documented. Plus it starts with a `_`.
Because it may change without warning in the future, I recommend maintaining the dataframe_utils into your codebase.

**Comment by ANDRYA005** [comment]
Thank you @bojiang.
