### ISSUE TITLE
bentoml config default never works for https/gRPCs

### ISSUE THREAD

**Issue by jack1902** [bentoml/BentoML#1417]
**Describe the bug**

When i run `bentoml list` from the command line, `BentoML` will blow up stating i am missing a `client` Key. This is incorrect as the documentation states `Optional` for a client cert/key. This happens because of the following 

https://github.com/bentoml/BentoML/blob/c7e64242eada3e96c528c389a8dfae3437b03c96/bentoml/yatai/yatai_service.py#L48-L53

assumes that i have an `old` config file but `.get` throws an exception which in truth is not the expected behaviour of a method called `.get()` (x or y will never work if the x throws an exception. The code is written in such a way that it expects `x` to never throw an exception)

The exception being thrown comes from:

https://github.com/bentoml/BentoML/blob/c7e64242eada3e96c528c389a8dfae3437b03c96/bentoml/configuration/configparser.py#L58-L64

**To Reproduce**

Steps to reproduce the issue:
1. Download/install `bentoml`
2. Set the URL to contain `https://` or `grpcs://`
3. Run `bentoml list`

**Expected behavior**

I expected `bentoml` to just work, without me having to edit the config file anymore than just throwing in a URL which contains `https` or `grpcs`. The certificate used is publically signed so `certifi.where()` is good enough without having to specify a custom location and ensuring that my config contains an old setting name

**Screenshots/Logs**

**Environment:**
 - OS: MacOS 11.1 (Intel)
 - Python Version: `Python 3.8.5`
 - BentoML Version: `master` running locally

**Additional context**

**To Fix**

There are a few ways to fix this:

1. Update `.get()` to not throw an exception so that the `x or y or z` will work as expected
2. Wrap all `.get` calls with a `try/except` (feels ugly but ensures that anything that uses the `.get` that expects an exception to be thrown will continue to work

**Comment by yubozhao** [comment]
@jack1902 Thanks for filing this issue. We are working on a new configuration system that would improve from the current system and solve this issue.  You can check it out the PR at #1422
