### ISSUE TITLE
yatai_service image should contain docker by default

### ISSUE THREAD

**Issue by jack1902** [bentoml/BentoML#1420]
**Describe the bug**

When running `yatai` with the client/server model, any commands sent (mainly around `sagemaker` here) to the server for deployments run `docker` but this fails due to this PR being merged (it highlights the problem but doesn't fix it)

relates to: https://github.com/bentoml/BentoML/pull/1386

**To Reproduce**
Steps to reproduce the issue:
1. Run `yatai` with client/server model and configure your `bentoML` to target `yatai`
2. Run a deployment via `bentoml sagemaker deploy ...`
3. Obersve error about `docker` not being available

**Expected behavior**

I expected the `docker` container being used by the `yatai` server to contain all dependancies used within its internal packaging logic. Since `docker` is one of those such dependancies i would have assumed `docker` be available within the container that is published by this project

**Screenshots/Logs**

**Environment:**
 - OS: Public Docker Yatai service
 - BentoML Version v0.11.0

**To Fix**

1. pre-bake `docker` into the container
2. (kubernetes only) update documentation for running within `kubernetes` (`yatai` will need to run in `priviledged` mode)

**Comment by parano** [comment]
Hi @jack1902 - the docker client required by BentoML's SageMaker deployment operator is already installed in the Yatai docker image. In your Yatai server, did you mount the docker daemon socket? And is the docker daemon up and running?

**Comment by parano** [comment]
We are moving the deployment functionalities out of Yatai https://github.com/bentoml/BentoML/issues/1677
