### ISSUE TITLE
Issue while storing bundles to GCS | yatai_service

### ISSUE THREAD

**Issue by dalavayi** [bentoml/BentoML#1423]
when trying to save the bundle to GCS backend. this error is popping up. 
error: Error adding BentoService bundle to repository: INTERNAL:Not able to get pre-signed URL on GCS. Error: string index out of range.

**Comment by yubozhao** [comment]
@dalavayi Can you share with us your env (python version/bentoml version/os) and your setup?

It seems like the error could comes from when we are creating the name of the bundle for uploading to GCS.  Could you share with me the base path for GCS(if you setup one), the bento service name and version?

**Comment by dalavayi** [comment]
@yubozhao i have tried resetting the google credentials now it is resolved thanks
