### ISSUE TITLE
Can't load pickle file (Keras Model) after deployment on the azure server

### ISSUE THREAD

**Issue by HGamalElDin** [bentoml/BentoML#1424]
**Describe the bug**
I wanted to make the keras model pickable, so i used the solution from this issue: [#34697 (comment)](https://github.com/tensorflow/tensorflow/issues/34697#issuecomment-627193883) 

it solved my problem perfectly in the local environment, but when i build the project on Azure Server and while loading the pickle file it gives, 
> Can't get attribute 'unpack' on <module 'main' from '/opt/python/3.7.9/bin/gunicorn'> 

it's like the gunicorn web server can't interpret or see "unpack" function, i don't know exactly what's going on in the gunicorn server, any help please!

**Environment:**
 - OS: linux - Azure server
 - Python Version 3.7.9
 - Tensorflow Version: 2.4
 - Keras Version: 2.3.4

**Comment by yubozhao** [comment]
@HGamalElDin Can you share what BentoML version you are using? Did you use PickleArtifact or KerasModelArtifact for packing your model artifact?

**Comment by HGamalElDin** [comment]
> @HGamalElDin Can you share what BentoML version you are using? Did you use PickleArtifact or KerasModelArtifact for packing your model artifact?

No, I did the training locally in anaconda using keras models and saved the model as a pickle file by the solution of this issue [#34697 (comment)](https://github.com/tensorflow/tensorflow/issues/34697#issuecomment-627193883), and when loading the pickle file again for predictions locally it's done perfectly, then I create a docker container then push this container to the azure server and when starting the API it throws this error while loading the pickle file.

**Comment by parano** [comment]
@HGamalElDin looks like you should ask this question in Keras/Tensorflow community instead
