### ISSUE TITLE
Cant't pickle module object

### ISSUE THREAD

**Issue by arita37** [bentoml/BentoML#1433]
I have a model stored inside a module (not a class).
Have this message when serializing on disk  :  

```
<class 'lightgbm.sklearn.LGBMClassifier'> LGBMClassifier(early_stopping_rounds=5, learning_rate=0.001, n_estimators=10,
               objective='binary')
(<module 'models.model_sklearn' from 'D:\\_devs\\Python01\\gitdev\\dsa2\\source\\models\\model_sklearn.py'>,)
Traceback (most recent call last):
  File "source/run_bentoml.py", line 139, in <module>
    saved_path = service.save_to_dir(dir_bento + "/"  )
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\bentoml\service\__init__.py", line 710, in save_to_dir
    return save_to_dir(self, path, version)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\bentoml\saved_bundle\bundler.py", line 228, in save_to_dir
    _write_bento_content_to_dir(bento_service, path)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\bentoml\saved_bundle\bundler.py", line 91, in _write_bento_content_to_dir
    bento_service.artifacts.save(module_base_path)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\bentoml\service\artifacts\__init__.py", line 258, in save
    artifact.save(save_path)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\bentoml\service\artifacts\__init__.py", line 181, in wrapped_save
    return original(*args, **kwargs)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\bentoml\frameworks\sklearn.py", line 90, in save
    joblib.dump(self._model, self._model_file_path(dst))
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\joblib\numpy_pickle.py", line 505, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "D:\_devs\Python01\ana3\envs\py36\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "D:\_devs\Python01\ana3\envs\py36\lib\site-packages\joblib\numpy_pickle.py", line 295, in save
    return Pickler.save(self, obj)
  File "D:\_devs\Python01\ana3\envs\py36\lib\pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle module objects
```

Can you try to use dill ?

Goal is to have abitray module to be serializable....

https://stackoverflow.com/questions/2790828/python-cant-pickle-module-objects-error

https://stackoverflow.com/questions/20628623/how-to-overcome-joblibs-typeerror-cant-pickle-instancemethod-objects-on-cla

https://realpython.com/python-pickle-module/

https://github.com/uqfoundation/dill/blob/master/tests/test_module.py

https://www.analyticsvidhya.com/blog/2017/09/machine-learning-models-as-apis-using-flask/

 is advisable to create a separate training.py file that contains all the code for training the model (See here for example).

T```
o install dill
!pip install dill
Requirement already satisfied: dill in /home/pratos/miniconda3/envs/ordermanagement/lib/python3.5/site-packages
import dill as pickle
filename = 'model_v1.pk'
with open('../flask_api/models/'+filename, 'wb') as file:
	pickle.dump(grid, file)
So our model will be saved in the location above. Now that the model is pickled, creating a Flask wrapper around it would be the next step.

Before that, to be sure that our pickled file works fine – let’s load it back and do a prediction:

with open('../flask_api/models/'+filename ,'rb') as f:
    loaded_model = pickle.load(f)
loaded_model.predict(test_df)
array([1, 1, 1, 1, 1])
```

**Comment by arita37** [comment]
Question 2)
  Can we create our own model wrapper ?

  Because serialization requires some dispatch of the model parts

**Comment by yubozhao** [comment]
@arita37 It seems like you are using lightGBM model, did you try to use the [LightGMB artifact](https://docs.bentoml.org/en/latest/frameworks.html#lightgbm) for packing?

> Can we create our own model wrapper ?

Yes, you can.  BentoML is very customizable.  You will create your own model artifact base on the `BentoServiceArtifact` https://github.com/bentoml/BentoML/blob/6aa48e34c4f46aad3ab75cbd2d5fd19a616715a6/bentoml/service/artifacts/__init__.py#L16

We have a lot of artifacts(model wrapper) contributed by the community, such as FastText, CoreML, Gluon.

**Comment by arita37** [comment]
Not related of lightgbm

Check my link,

You are using joblib in your code.
This is very bad serializer.

You should use dill

All others major framework are using dill
(Ie huggingface).

How to plug my own wrapper to bentoml ?

**Comment by arita37** [comment]
Our models are

module_xxxx.py

which includes preprocessors + Model ?

So how to use with bentoml ?

**Comment by parano** [comment]
@arita37 BentoML does not "pickle" your module or preprocessing code, it takes a completely different approach. Simply import your model in your BentoService class definition and all related dependencies will be bundled.


BentoML's PickleArtifact uses cloudpickle as default, not joblib. It is also possible to use your custom pickle module, simply pass in `PickleArtifact(pickle=dill)`.

BentoML's SklearnModelArtifact uses joblib by default.

Users' preprocessing code/module will not be pickled.

**Comment by arita37** [comment]
Thx for clarification.

That’s the issue:

Our model is wrapped in a structured way
inside a module  (singleton class)
   Preprocessor + Model (ie LighGbM or else).

Benefit is we have the preproceesor included,
all within .fit()  , .predict() method.


BentoML is  using “pickle like”
 to serialize on disk (your wrapper),
and can’t serialize it.

Question

1) How to plug custom wrapper into BentoML ?

  It would allow correct serialization/derizaliton



Dill is much better than cloudpickle/pickle.

**Comment by parano** [comment]
@arita37 it's very easy to create a custom wrapper in BentoML, simply create a class that inherits from the BentoArtifact base class and add your own implementation.

If all you need is using dill to serialize your model class, the built-in PickleArtifact is enough:
```python
import dill
import bentoml
from bentoml.service.artifacts.common import PickleArtifact

@artifacts([PickleArtifact("mymodel", pickle=dill)])
class MyPredictionService(bentoml.BentoService)

        ...
```

**Comment by arita37** [comment]
Thank you.

Maybe if you add one minimal example
of custom Artifact, it would help a lot
of people.

Especially, it can become as plugin
with many contributors.

**Comment by parano** [comment]
Thanks, @arita37, that's a great suggestion.  Let me know if the PickleArtifact solution above worked for your use case or not.

**Comment by arita37** [comment]
Its much better,
Having a couple of errors (due to 3rd packages).

because have to split 
the serialization of the module,
manually in specific part.

So, a custom  BentoArtifact will help
to handle each component separately。

Having a plugin structure for Artifact,
will be a big big plus,
many people can contribute on their own ones.

Another part:
   Data preprocessinf is necessary,
   but usually not the base part of models...
    

If you add  some basic example of
artifact with precoessingn+ model,
Thats a good plus.


Thanks for excellent work/feedback.

**Comment by parano** [comment]
Thanks for sharing your thoughts on this @arita37, BentoML by design, asks users to put their pre-processing code in the `@api` callback function and only the model in the Artifact interface. Although it doesn't make a huge difference today, we are working on an optimized architecture where we can run preprocessing and model inference in separate pipelines, in order to better utilize CPU/GPU for better online serving performance.

I will definitely add a guide on adding custom model artifact. Would be great if you could give BentoML's own way of structuring preprocessing code a try and share your thoughts. This will also avoid pickling your module in the process, making it less error-prone.

**Comment by arita37** [comment]
Thanks for comments.

Idea of parallel processing is good,
so data flow is optimized.

One Tricky part is single node, multi processing.
And communication of data.

One of the best design is using
Pytorch way:

Dataset : wrapper of the data

Dataloader : wrapper for the mini-batch, distributed loader.

Model is taking samples from DataLoader.

DataLoader can be extended to include preprocessors.


The very tricky part if 
the preprocessor has parameters (min, max)
setting which needs to “be pickled” !!!!
(Those params are set at training time).

2 ways :
   Hardcoded in the code
   save in pickle/ loaded it

2 types of precessors :
    Need pickle 
    No need of pickle....

Remark :
  Are you planning to add protocal buffer as input ?

**Comment by parano** [comment]
@arita37  - sorry for the late reply, here is our official guide on adding your own model artifact class: https://docs.bentoml.org/en/latest/guides/custom_artifact.html

Were you able to get things working with just PickleArtifact + dill?
