### ISSUE TITLE
CORS headers are not issued for servers

### ISSUE THREAD

**Issue by akainth015** [bentoml/BentoML#1439]
**Is your feature request related to a problem? Please describe.**

I have deployed a Bento to Heroku, and when I try to access it through JS in the browser, it is always blocked by CORS policies.

**Describe the solution you'd like**

`Access-Control-Allow-Origin` header should be issued by `OutputAdapter` for all requests

**Describe alternatives you've considered**

CORS proxies are not a viable long term solution

**Additional context**

Was also unable to deploy to Lambda, while following the documentation verbatim, and adding the `--region` argument.

**Comment by rubensmau** [comment]
I have the same problem when deployed to an EC2 instance. Is there a workaround ?

**Comment by parano** [comment]
@akainth015 @rubensmau thanks for reporting the issue.

A workaround I'd recommend for now is to use the `InferenceResult` class to customize the response headers, e.g.:

```
import bentoml
from bentoml.types import JsonSerializable, InferenceTask, InferenceError  # type annotations are optional

class MyService(bentoml.BentoService):

    @bentoml.api(input=JsonInput(), batch=False)
    def predict(self, parsed_json: JsonSerializable, task: InferenceTask) -> InferenceResult:
        if task.http_headers['Accept'] == "application/json":
            predictions = self.artifact.model.predict([parsed_json])
            return InferenceResult(
                data=predictions[0],
                http_status=200,
                http_headers={"Content-Type": "application/json", .... # any other response header #},
            )
        else:
            return InferenceError(err_msg="application/json output only", http_status=400)
```
More details can be found here: https://docs.bentoml.org/en/latest/concepts.html#defining-a-batch-api


We reserved a `cors` parameter for all output adapters, unfortuntately it's currently only implemented in the AWS Lambda's responses, not in the model server's API endpoint. https://docs.bentoml.org/en/latest/api/adapters.html#jsonoutput
```python
@api(input=DataframeInput(), output=JsonOutput(cors="*"))
```
Should we add the same behavior to the model server's API endpoint? @bojiang
