### ISSUE TITLE
Allow deleting bento bundle from Yatai web UI

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1445]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshitsinghai77** [comment]
I would like to work on this issue.

**Comment by harshitsinghai77** [comment]
In `bentoml/yatai/web/src/server.ts` there is already a route `/api/DeleteBento` 

```
router.post("/api/DeleteBento", async (req: Request, res: Response) => {
    let verifyError = bentoml.DangerouslyDeleteBentoRequest.verify(req.body);
    if (verifyError) {
      logger.error({ request: "DeleteBento", error: verifyError });
      return res.status(400).json({ error: verifyError });
    }
    let requestMessage = bentoml.DangerouslyDeleteBentoRequest.create(req.body);
    try {
      const result = await yataiClient.dangerouslyDeleteBento(requestMessage);
      logger.info({
        request: "DeleteBento",
        data: requestMessage,
        result: result,
      });
      if (result.status.status_code != 0) {
        return res.status(400).json({ error: result.status.error_message });
      }
      return res.status(200).json(result);
    } catch (error) {
      logger.error({ request: "DeleteBento", error: JSON.stringify(error) });
      return res.status(500).json(error);
    }
  });
```

Can you tell me what exactly do we want here?
Should there be a button in the web ui which will make a request to `/api/DeleteBento` ?

**Comment by parano** [comment]
@harshitsinghai77 yes I think you are right, we want to add a button in the UI that allows the user to delete a BentoML bundle from the Bento Details page, and potentially multi-select and batch delete from the BentoList page. This endpoint was based on an older version of the delete gRPC and has not been tested recently, it would be great if you could test it out and see if there's anything we should fix around it, and add unit tests for it

**Comment by yubozhao** [comment]
@syedsameerarshad

**Comment by parano** [comment]
closing this now, will create a new github project for all future Yatai web UI roadmap and track this over there
