### ISSUE TITLE
ModuleNotFound Error

### ISSUE THREAD

**Issue by gvashishtha** [bentoml/BentoML#1450]
**Describe the bug**
I am seeing the following:

```
File "/opt/conda/lib/python3.7/pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'joblib'
```

when attempting to start the BentoML docker container in the Getting Started tutorial.

**To Reproduce**
Steps to reproduce the issue:
1. Go through the BentoML getting started tutorial
2. Attempt the "Containerize Model API server" step
3. Build the image
4. When running the image you will see "ModuleNotFound" error

**Expected behavior**
I expect the image to run successfully

**Screenshots/Logs**

**Environment:**
 - OS: Windows Subsystem for Linux
 - Python Version Python 3.7
 - BentoML Version 0.11.0

**Additional context**

**Comment by yubozhao** [comment]
Thanks for reporting @gvashishtha

I am not very familiar with Windows subsystem for linux.  I will try to replicate that.  

If you have time, could you run the containerize command with the debug flag on `bentoml containerize IrisClassifier:latest -t iris-classifier --debug` and copy the logs to this issue?

**Comment by yubozhao** [comment]
@gvashishtha Do you still encounter the issue?

**Comment by gvashishtha** [comment]
Hi Bozhao, so far I was able to resolve by manually editing the requirements.txt in the saved model to include joblib as a dependency

**Comment by yubozhao** [comment]
You can also include `joblib` in the `pip_packages` list, so you won't need to manually editing it.

```
@bentoml.env(infer_pip_pacakges=True, pip_packages=['joblib'])
class MyService(bentoml.BentoService):
```

**Comment by parano** [comment]
@gvashishtha when you follow through the quickstart example, what is the `scikit-learn` version you are using?

could you try installing the requested versions and run it again?
```
pip install -U -r ./guides/quick-start/requirements.txt
```

**Comment by parano** [comment]
Looks like joblib is a required dependency for scikit-learn, it seem like reinstalling scikit-learn should help with the issue you are seeing - closing for now, let me know if you still run into this issue
