### ISSUE TITLE
Prediction service non responsive while containerizing the model service

### ISSUE THREAD

**Issue by athulprathap** [bentoml/BentoML#1459]
![bentounre](https://user-images.githubusercontent.com/10370721/108194319-7e8bce00-713c-11eb-8672-680e08d4a0d4.jpg)
![bentowork](https://user-images.githubusercontent.com/10370721/108194330-80ee2800-713c-11eb-99da-ada695878936.jpg)

**Describe the bug**
Used BentoML to create a prediction service for the transformer-based Roberta Pytorch model. Model artifact size around 477MB. Input is dataframe. Prediction service working fine while using 'bento serve; locally for data frame of any size
.
Enabled the batch mode and worker timeout value set to 300 while containerizing.
But getting issues after containerizing the service.
Bento ML Docker API service is working for data frame more than 250 rows 
But the request goes unresponsive for smaller data frames sized around 45 rows.

Response time for input dataframe(45 rows)  served using bentoml serve locally - 2.8s
Response time for input dataframe(270 rows)  served using bentoml serve locally - 12.8s
-------------------------------------------------------------------------
Response time for input dataframe(270 rows)  served using containerized bento service - 12.2 s
Response time for input dataframe(45 rows)  served using containerized bento service - NO RESPONSE 
  

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: ubuntu 18
 - Python VersionPython 3.8
 - BentoML Version bentoml==0.11.0

**Additional context**

**Comment by athulprathap** [comment]
@parano Solved the issue for time being for our deployment. Created custom docker images using ubuntu 18 base image and has used bentoML packaged model as a PyPI library inside the custom flask application. Tried initially with gunicorn web server inside docker container.While serving using gunicorn same issue was observed. But replacing gunicorn with Waitress WSGI inside the docker file  solved the issue for us. The issue is during parsing of the result between default bentoML flask server and gunicorn workers.Gunicorn workers are unable to catch the Prediction results given by the flask server that got executed quickly.In our case dataframe containing text data(sentences) of less than 50 rows.Probably for predictions happening below 1 or 2 seconds or so. Request you to check the gunicorn-flask integration settings while containerization the bento service.

**Comment by athulprathap** [comment]
@parano Is there a way to monitor model matrices for models deployed using pyPi packages in custom docker containers?

**Comment by parano** [comment]
@athulprathap yes, the `/metrics` endpoint will expose prometheus metrics
