### ISSUE TITLE
multiprocessing start_method setup runtime exception

### ISSUE THREAD

**Issue by DrizzlingCattus** [bentoml/BentoML#1460]
**Describe the bug**

The problem occurs when I try to build the bentoml service as below. 
```
# do normal bento pack & save
python build_bentoservice.py
```
The problem occurs when using the bentoml master branch, and there is no problem in version 0.11.0.

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

```
Traceback (most recent call last):
  File "/app/BentoML/bentoml/__init__.py", line 40, in <module>
    multiprocessing.set_start_method('fork')
  File "/usr/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Environment:**
 - OS
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
```
 - Python Version : 3.8.3
 - BentoML Version : master branch version (lastest commit aa120e4b8e8aaef8617f51be4a151122a9cd40f4)

**Additional context**

**Comment by yubozhao** [comment]
Thanks for find the bug and create a PR at https://github.com/bentoml/BentoML/pull/1461.

Let me know when the PR is ready and we will go from there.

**Comment by bojiang** [comment]
FYI, in this PR https://github.com/bentoml/BentoML/pull/1466, `set_start_method` was moved back to the API server.
@DrizzlingCattus

**Comment by DrizzlingCattus** [comment]
@bojiang ok thank you!

**Comment by bojiang** [comment]
The final solution #1476
