### ISSUE TITLE
Automatic determining the API server workers

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#1474]
:wave: Hi BentoML community, we have a question for you.

**Background**

In the next BentoML release, the default of API server workers will be changed to `1`. Previously, the number of workers is automatically determined based on the `multiprocessing.cpu_count()`. The original intention of having dynamic workers was to achieve the optimal efficiency in an asynchronous API server. However, there are multiple downsides as well with a dynamically determined workers count.

- The memory footprint of models multiplies as workers increase
- The default workers could be suboptimal when Linux CGroups (e.g. cpu_shares, cfs_quota_us) is used to govern CPU usage
- Tuning is required between micro-batching and API servers

Changing the default workers count to `1` simplifies many assumptions but will require users to update the container resource allocation to achieve the optimal efficiency. Users can also explicitly define the workers through `--workers` parameter.

**Question**

Would you like to continue having the optional to automatic determinate workers for micro-batching and API servers, e.g. `--automatic-workers`? What strategy of workers calculation best work for you?

**Comment by parano** [comment]
In BentoML 1.0, we decided to use # of CPU cores as the default API server worker count. User can change this via config file or the `-w/--worker` CLI option.

**Comment by mathbr10** [comment]
Hoe can we set the number of workers when using bentoctl?
