### ISSUE TITLE
YataiService doesn't allow a BentoService without artifacts

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#1475]
**Describe the bug**

In order to avoid #1037 and #1065, I override the `__init__` function of BentoService to download and initialize the required model files from an external service(MLflow). In this case, I don't need to pack any artifacts, but I found a problem in YataiService that doesn't allow this case. The current YataiService includes the assumption that BentoService must always have artifacts.

**To Reproduce**

1. 
```Python
from sklearn import svm
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf = svm.SVC(gamma='scale')
clf.fit(X, y)
```
2.
```Python
# test_bentoservice.py
import pandas as pd
from bentoml import env, artifacts, api, BentoService
from bentoml.adapters import DataframeInput

@env(infer_pip_packages=True)
class TestBentoService(BentoService):
    def __init__(self):
        # Download model files from MLflow and Initialize them
        pass
    @api(input=DataframeInput(), batch=True)
    def predict(self, df: pd.DataFrame):
        return None # We can predict something with model files here.
```
3.
```Python
from test_bentoservice import TestBentoService
bento_service = TestBentoService()
saved_path = bento_service.save()
```
4. Run a YataiService and select the BentoService.

**Expected behavior**

YataiService should show even BentoService without artifacts.

**Screenshots/Logs**

**Environment:**
 - OS: MacOS 11.2.2
 - Python Version: 3.7.9
 - BentoML Version: 0.11.0

**Additional context**

**Comment by yubozhao** [comment]
> Run a YataiService and select the BentoService.

Is the selection happens in the web UI?

**Comment by withsmilo** [comment]
@yubozhao 
Yes. When I select the BentoService without artifacts in YataiService UI, nothing is visible.

**Comment by yubozhao** [comment]
Got it. I will work on a fix. Thank you for finding it!
