### ISSUE TITLE
Add pydantic model schema

### ISSUE THREAD

**Issue by timothyjlaurent** [bentoml/BentoML#1480]
**Is your feature request related to a problem? Please describe.**

I want to have robust input and output shema validation. Similar to what is achieved with FastAPI https://fastapi.tiangolo.com/.

**Describe the solution you'd like**

Add support to the JsonInput to:
1. Accept lists of json items natively - allows for hitting such endpoints with a list, instead of needing to go through the pandas input. Allow the microbatcher to concat the lists of requests. 
2. accept a `schema` parameter that can be a type definition or a pydantic model https://pydantic-docs.helpmanual.io/usage/models/ . This will be used to generate the response in the openapi schema https://pydantic-docs.helpmanual.io/usage/schema/
3. Allow for _some_ way to turn off validation, as I'm told this is being done for custom FastAPI KFServing apps to be able to handle high load

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
@larme would be great for you to look into this issue

**Comment by aarnphm** [comment]
https://github.com/bentoml/BentoML/blob/9899d58666b62e515c570a1fee87c0905bb1e9d3/bentoml/_internal/io_descriptors/json.py#L133 will provide support for pydantic model schema in the upcoming 1.0 releases. Let me know if we need to reopen this issue. Closing for now
