### ISSUE TITLE
Handle dependency conflict

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1481]
**Is your feature request related to a problem? Please describe.**

There are two aspects that this issue may fail this framework.

1. The pip 2020-resolver is enabled by default after 2020-11. 
For a dependency tree like this,
```
bentoml==0.11.0

 ⌙ package_a==1.0
   ⌙ package_c<2.0

 ⌙ package_b==2.0
   ⌙ package_c<1.5
```
pip may install `package_c==1.6` when it first met ` package_c<2.0`, and fail when it met `package_c<1.5`. This means the image build of an online bentoml service would fail when a sub-dependency like `package_c` published a new release(`1.5` -> `1.6`).
The good news is that the CI of bentoml will fail instantly once it happens. For example https://github.com/bentoml/BentoML/pull/1173.

2. (WIP)

**Describe the solution you'd like**

- [ ] apply [pip-compile](https://github.com/jazzband/pip-tools) to lock dependencies recursively

**Describe alternatives you've considered**

- [ ] check dependency conflict in CI with https://github.com/ambitioninc/pip-conflict-checker

**Additional context**

`pip 2020-resolver`

**Comment by ssheng** [comment]
> The good news is that the CI of bentoml will fail instantly once it happens.

@bojiang how confident are we that our CI will catch problems with overlapping transitive dependency? It becomes dangerous when things appear to work, espcially during CI, but fails in some specific cases.

**Comment by bojiang** [comment]
@ssheng
For the problem during the API server image building:
The integration test will call ` pip install bentoml ` for each build. If there were overlapping issues in the dependencies of bentoml, the integration test would fail instantly.
But it only means we didn't have an actual problem now. I agree that we should take this issue seriously.

**Comment by parano** [comment]
The conclusion from our discussion was basically:

1. For BentoML itself, set up a daily CI job to make sure new public PyPI releases does not break BentoML's core functionality
2. On a related issue, for the `requirements.txt` in the BentoBundle directory, we want to keep the way it is, and recommend users to use the `@env(pip_requirements_txt="...")` API to provide a full list of dependencies with pinned versions for production use cases.
