### ISSUE TITLE
[Bug]docs.json link point to blank page instead of /docs.json

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1486]
**Describe the bug**

<img width="1278" alt="Screen Shot 2021-03-04 at 2 01 30 PM" src="https://user-images.githubusercontent.com/670949/110036870-8463e080-7cf2-11eb-913d-f700c0ea26f8.png">

The docs.json link should be pointing to `/docs.json` instead of open a blank page.

This part of the UI is rendered from `SwaggerUIBundle`
https://github.com/bentoml/BentoML/blob/c607db201036643c2dcf840fd7aca877c6fcbdc9/bentoml/server/api_server.py#L92-L95

**To Reproduce**

**Expected behavior**

Click the `docs.json` link and the browser opens up the right link (`/docs.json`)

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by parano** [comment]
Looks like this has been fixed in the current version, closing now
