### ISSUE TITLE
Add autoscale configuration support for Sagemaker deployments

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1490]
**Background:**

For Sagemaker deployments, Users might not know ahead of time on how much computing resources they might need for the service. It would be great to allow the ability to scale those deployments with different scaling options.

Right now, users have to go to the AWS console and manually set the autoscale configurations for the endpoints. 

**Describe the solution you'd like**

BentoML offers configure Sagemaker deployment autoscale configuration out of the box. Users can customize what scale method they want to use and set the min/max instance counts

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
Moving this to https://github.com/bentoml/aws-sagemaker-deploy
