### ISSUE TITLE
Run as user-defined user in docker

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#1500]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

If a user selects his own model-server image as `docker_base_image`, the user should be able to select a user_id or group_id to actually operate on the image. It can be root, or a specific user_id/group_id.

**Describe alternatives you've considered**

How about adding `docker_base_user` to the env decorator?
```python
@env(infer_pip_packages=True,
          docker_base_image="user_defined_docker_image:latest",
          docker_base_user="bentoml:bentoml",
)
@artifacts([SklearnModelArtifact('model')])
class IrisClassifier(BentoService):
    ...
```

**Additional context**

none

**Comment by bojiang** [comment]
It has been supported in the master branch and would be included in the next release.
`bentoml containerize --build-arg UID=1034 GID=1034`

**Comment by bojiang** [comment]
@parano Shall we add `base_image` option to the command `bentoml containerize`, or add `build_args` to the `@env`?

**Comment by withsmilo** [comment]
@bojiang 
Really nice! I'll wait for next release. 👍

**Comment by parano** [comment]
@bojiang what are the other common use cases for `build_args`?  I think it is ok to leave it at the containerize step, but if there are some common options for the docker build, we can surface those options up for the user

**Comment by bojiang** [comment]
@parano `EXTRA_PIP_INSTALL_ARGS` `BUNDLE_PATH`

**Comment by bojiang** [comment]
I mean surfacing the `--base-image` option to `bentoml containerize` should make sense, since it is high-related with the `build_args`
