### ISSUE TITLE
Add API Server integration tests on Windows Platform

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1506]
**Is your feature request related to a problem? Please describe.**

* Currently there isn't a test covering creating a Bento bundle on the Windows platform, containerize it with docker, and then test the API server docker image. We have seen this workflow break in the past due to the lack of proper testing. 
* may need to rewrite `install_test_deps.sh` and `test_project.sh` in bat

**Describe the solution you'd like**

* Make the API server integration test work on Windows OS: https://github.com/bentoml/BentoML/blob/v0.11.0/.github/workflows/ci.yml#L125

**Describe alternatives you've considered**

**Additional context**

**Comment by bojiang** [comment]
Currently impossible for Github action.

 actions/virtual-environments#1143

**Comment by bojiang** [comment]
Another solution:
https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

**Comment by parano** [comment]
Closing due to low priority. Will revisit if we ran into others issues with API server on windows platform.
