### ISSUE TITLE
Dependency injection to wire BentoML modules only

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#1512]
**Is your feature request related to a problem? Please describe.**

Dependency injection currently `package_walk` and `__import__` all dependent modules when performing `wire`. For large dependencies like `numpy` and `grpcio`, recursive imports can be quite slow.

**Describe the solution you'd like**

Ideally, dependency injection only needs to `wire` BentoML packages without having to import recursively.

**Describe alternatives you've considered**

**Additional context**

**Comment by ssheng** [comment]
https://python-dependency-injector.ets-labs.org/wiring.html#wiring-of-dynamically-imported-modules

**Comment by parano** [comment]
This will be addressed in #1705 when we migrate to simple_di
