### ISSUE TITLE
Changing the name of the API handler

### ISSUE THREAD

**Issue by sayakpaul** [bentoml/BentoML#152]
Hi @parano and @yubozhao. I hope you are doing well. 

I was wondering if you have planned of enabling the users to customize the name of API handlers. As far as I know, the current version allows for `/predict` only. Is there a way I can change this? And the allowed HTTP method as well?

**Comment by parano** [comment]
hi @sayakpaul, in fact, the function name will become the API handler name, not just 'predict'. for example, if you have:
```
@api(DataframeHandler)
def classify(df):
   ...
```
the API endpoint will be `classify`, you can also pass in 'name' parameter to give it an API name different than the python function name, e.g.:
```
@api(DataframeHandler, name='my_custom_api_name')
def any_func(df):
   ...
```

we haven't had a chance to finish BentoML's documentation site, but will definitely include these in it soon!

**Comment by sayakpaul** [comment]
Thanks for letting me know. And what about specifying the allowed HTTP method?

**Comment by parano** [comment]
@sayakpaul BentoML API server currently doesn't support HTTP method other than POST/GET - do you have a use case where you want to customize it? would love to hear about it

**Comment by sayakpaul** [comment]
@pa

**Comment by yubozhao** [comment]
@sayakpaul The API server handle both get and post requests without any specification.  Did you encounter a scenario that you need to specify?

**Comment by sayakpaul** [comment]
So far not.
