### ISSUE TITLE
[CI] ensure bentoml works without test dependencies

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1528]
**Describe the bug**

https://github.com/bentoml/BentoML/issues/1529

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by parano** [comment]
Closing now due to low priority. This must be covered in our manual QA process prior to the release.

Ideally we would need a real end-to-end test that runs things in an isolated environment(e.g. its own docker container that does not contain test dependencies).
