### ISSUE TITLE
Handling image requests

### ISSUE THREAD

**Issue by sayakpaul** [bentoml/BentoML#153]
I am referring to [this tutorial](https://github.com/bentoml/BentoML/blob/master/examples/tf-keras-fashion-mnist/tf-keras-fashion-mnist-classification.ipynb) on FashionMNIST classification with tf-keras. 

I think the prediction API can only handle raw image arrays currently in the way it is coded. I was trying to serve it as REST API endpoint and running with `bentoml serve`. However, I wrote the prediction in a way it could handle images from the API payload directly. Here's the snippet:

```python
%%writefile tf_keras_fashion_mnist.py

import bentoml
from bentoml import api, artifacts, env, BentoService
from bentoml.artifact import TfKerasModelArtifact
from bentoml.handlers import TensorflowTensorHandler
from io import BytesIO
from scipy.misc import imresize, imread

@bentoml.env(conda_dependencies=['tensorflow', 'numpy'])
@bentoml.artifacts([TfKerasModelArtifact('classifier')])
class TfKerasFashionMnistModel(bentoml.BentoService):
    
    @bentoml.api(TensorflowTensorHandler)
    def predict(self, request):
        class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
        
        input_file = request.files.get('file')
        if not input_file:
            return BadRequest("File is not present in the request")
        if input_file.filename == '':
            return BadRequest("Filename is not present in the request")
        if not input_file.filename.lower().endswith(('.jpg', '.jpeg', '.png')):
            return BadRequest("Invalid file type")

        input_buffer = BytesIO()
        input_file.save(input_buffer)
        image_array = imread(input_buffer, mode='L')
        
        image_array_re = imresize(image_array, (28, 28))
        image_array_re = image_array_re.reshape(1, 28, 28, 1)
        preds = model.predict(image_array_re)
        category_int = np.argmax(preds, axis=1)
        return class_names[int(category_int)]
```

However, when I do a hit via Postman I get the following error (with full trace):
```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda3/lib/python3.7/site-packages/bentoml/server/bento_api_server.py", line 116, in wrapper
    response = api.handle_request(request)
  File "/miniconda3/lib/python3.7/site-packages/bentoml/service.py", line 91, in handle_request
    return self.handler.handle_request(request, self.func)
  File "/miniconda3/lib/python3.7/site-packages/bentoml/handlers/tensorflow_tensor_handler.py", line 30, in handle_request
    raise NotImplementedError
NotImplementedError
```

Any help in this regard would be great. Here's [my notebook](https://github.com/sayakpaul/BentoML-Explorations/blob/master/tf-keras-fashion-mnist-classification.ipynb) for your perusal.

**Comment by parano** [comment]
cc @yubozhao

**Comment by yubozhao** [comment]
@sayakpaul That's great you are running the examples.

I think the example you are running is broken and outdated it. We probably should get on that next.  Instead of using TensorflowTensorHandler, you can try use `ImageHandler`.

`ImageHandler` will take in request, and parse files with formats of `'.jpg', '.jpeg', '.png'` and turn that image into a np array.  That np array will pass down to your predict function.

It is unfortunate that we don't have a good example using it at the moment, that misleads you into this.  Keep me updated on your progress with this issue.  If you couldn't get it working, just ping me and I will take a look at the notebook you linked.

**Comment by sayakpaul** [comment]
Sure. Will try and update you.

**Comment by sayakpaul** [comment]
@yubozhao also, when you say:
> ImageHandler will take in request, and parse files with formats of '.jpg', '.jpeg', '.png' and turn that image into a np array. That np array will pass down to your predict function.

Do you mean files parsed from the API payload? How should the payload be defined at the client side in that case? Here's my Postman configuration for you to know how I specifying it:

![image](https://user-images.githubusercontent.com/22957388/58930370-a674ab80-8778-11e9-81b6-2937c53b4024.png)

**Comment by yubozhao** [comment]
@sayakpaul It's my bad I wasn't clear on this handler description.  I will take a look at the notebook and then create an example for this handler. I will probably get to this sometime this week and ping you on this.

Also, here is a quick answer for ImageHandler, in case you want to try again while I am working on the example.

Right now, ImageHandler only handle single image. Using default params, image handler will convert the form data's `image`(key) file with extensions one of the `jpg`, `jpeg`, or `jpg` into np array.

```python
class MyModel(bentoml.BentoService):
	@bentoml.api(ImageHandler, 
				 input_names=['image'],
                 accept_file_extensions=['.jpg'],
	  			 accept_multiple_files=False)
	def predict(self, imageArray):
		return self.artifacts.model.predict(imageArray)
```

**Comment by sayakpaul** [comment]
Yes, I can definitely try this out. But I would need a guide to define the API request.

**Comment by sayakpaul** [comment]
@yubozhao did you by chance have the time to look at this? I understand you must be busy.

**Comment by yubozhao** [comment]
@sayakpaul Yes, I started last night, planning on spend a lot of time on it today, to make sure both fashion mnist examples provide a smooth e2e experience.

**Comment by sayakpaul** [comment]
Thanks @yubozhao. Let me know if I can help :)

**Comment by yubozhao** [comment]
Sure thing! I will definitely ping you when I run into something.

**Comment by yubozhao** [comment]
@sayakpaul Just want you know I am working on this right now.  I am encountering issue with TF kera's threading issue, https://github.com/keras-team/keras/issues/5640, and want to figure out a good design for this.  So, this fix might be taking longer than expected

**Comment by sayakpaul** [comment]
Are you on TF 2.0?

**Comment by sayakpaul** [comment]
@yubozhao a gentle reminder at this.

**Comment by parano** [comment]
hey @sayakpaul , just want to let you know, the issue with keras model serving has been resolved in a recent PR https://github.com/bentoml/BentoML/pull/207

Also you can now use the index page UI to test the API endpoints and post data to it, similar to what you do with postman:
![image](https://user-images.githubusercontent.com/489344/61339302-13f10e80-a7f2-11e9-96e9-b9d793f8d71a.png)

I tried the keras fashion mnist example and it works now, I will update the example in the repo soon, feel free to test out with master branch as well. Note the change has not been released yet, you can play it via `pip install git+https://github.com/bentoml/BentoML.git`
