### ISSUE TITLE
Confusing Docstring in lightgbm.py

### ISSUE THREAD

**Issue by harshit-deepsource** [bentoml/BentoML#1533]
**Describe the bug**

https://github.com/bentoml/BentoML/blob/master/bentoml/frameworks/lightgbm.py#L14

`model_extension (string): Extension name for saved xgboost model`

Why do we need an extension name for saved `xgboost` model?

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by harshit-deepsource** [comment]
Also, why is the default model_extension `.txt`?

https://github.com/bentoml/BentoML/blob/master/bentoml/frameworks/lightgbm.py#L46

I don't think models are saved with `.txt.` extension? :thinking:

**Comment by parano** [comment]
@harshit-deepsource `.txt` is the convention in lightgbm framework, you don't need to specify this extension format if you don't want to customize it, only the name is required for the artifact.

**Comment by harshit-deepsource** [comment]
Got it.
