### ISSUE TITLE
Markdown support in swagger README

### ISSUE THREAD

**Issue by gregd33** [bentoml/BentoML#1536]
**Is your feature request related to a problem? Please describe.**

This is a minor cosmetic request, but: there currently is no CSS on the Markdown in the README page on swagger. It makes it a bit tough to read, especially if things like tables are included. Markdown seems much nicer on the actual swagger page.

The CSS seems to be in `static_content/readme.css` and quite simple.

```
#markdown_readme {
  /* same as swagger*/
  max-width: 1460px;
  margin: 40px auto;
  padding: 0px 20px;
}
```

**Describe the solution you'd like**

Markdown CSS similar to swagger

**Comment by parano** [comment]
This issue will be tracked separately here: https://github.com/bentoml/BentoML/issues/2191
