### ISSUE TITLE
Add schema on output adaptors

### ISSUE THREAD

**Issue by timothyjlaurent** [bentoml/BentoML#1542]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to describe the response schema of my bento apis

**Describe the solution you'd like**
1. make default schema in output adaptor
2. in generate schema use the output adaptors schema

**Describe alternatives you've considered**
1. Switching to FastAPI for this project

**Additional context**
1. maybe bentoml should use fast API instead of flask under the hood

**Comment by parano** [comment]
@timothyjlaurent  - There's no plan to switch to FastAPI - BentoML API server uses lower-level APIs(asynio, aiohttp) under the hood for maximum performance - flask is just a sync layer for users' BentoService code and does not affect the performance that much. However flask is not a hard dependency for BentoML, we are planning to move away from flask in future releases.

**Comment by parano** [comment]
We will investigate schema for JsonOutput as part of https://github.com/bentoml/BentoML/issues/1480
