### ISSUE TITLE
Can't pickle local object for jupyter quick start guide

### ISSUE THREAD

**Issue by jcriddle-nci** [bentoml/BentoML#1547]
**Describe the bug**
When I run through the jupyter quick start guide I get an error any time I run the starting of the dev server. 

**To Reproduce**
I activate my environment using env\Scripts\activate
I made sure all libraries were installed using pip install -r guides\quick-start\requirements.txt
I open the jupyter notebook in vs code
Select the python environment as a the same environment 
Run through all steps one-by-one until the line "iris_classifier_service.start_dev_server()"
This is when I get the error shown below

**Expected behavior**
It is showing the object is being created. If I were to try to continue the next request call fails and says the `"ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it."`

**Screenshots/Logs**
```
[2021-03-30 08:20:09,212] INFO - BentoService bundle 'IrisClassifier:20210330082008_F20D2A' created at: C:\Users\JCriddle\AppData\Local\Temp\tmp3s8xn7yb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\JCriddle\work\examples\BentoML\env\lib\site-packages\bentoml\service\__init__.py in start_dev_server(self, port, enable_microbatch, enable_ngrok, debug)
    836             )
--> 837             self._dev_server_process.start()
    838             logger.info(

~\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py in start(self)
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel

~\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py in _Popen(process_obj)
    223     def _Popen(process_obj):
--> 224         return _default_context.get_context().Process._Popen(process_obj)
    225 

~\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py in _Popen(process_obj)
    326             from .popen_spawn_win32 import Popen
--> 327             return Popen(process_obj)
    328 

~\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     92                 reduction.dump(prep_data, to_child)
---> 93                 reduction.dump(process_obj, to_child)
     94             finally:

~\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 

AttributeError: Can't pickle local object 'BentoService.start_dev_server.<locals>.run'
```

**Environment:**
 - OS: [Windows 10 Enterprise v1909]
 - Python Version [e.g. Python 3.9.2]
 - BentoML Version [e.g. BentoML-0.12.0]

**Comment by parano** [comment]
cc @bojiang  - is this related to  #1546 and #1544?

**Comment by abhi-gm** [comment]
> installed

I am facing the same issue

**Comment by jcriddle-nci** [comment]
I got around this by writing a script for packaging up the model and artifacts, and a separate script for running the api.

**Comment by Dmitry-Void** [comment]
Have the same issue on MacOS during debugging in Pycharm:
![image](https://user-images.githubusercontent.com/61740935/133973179-71504ae2-0996-4c62-b61f-3dbc2f3246a3.png)

**Comment by parano** [comment]
Update: `start_dev_server` was an experimental API and has been replaced by the new APIs provided in BentoML 1.0, namely the new `bentoml serve` command can be used to load a bentoml service definition python file directly and spin up a development server, which also supports auto-reload when code is changed.
