### ISSUE TITLE
ONNX-MLIR  support

### ISSUE THREAD

**Issue by andrewsi-z** [bentoml/BentoML#1565]
**Is your feature request related to a problem? Please describe.**
Add support for ONNX-MLIR (LLVM) compiler generated library objects.

**Describe the solution you'd like**
See draft PR here: https://github.com/bentoml/BentoML/pull/1545

**Describe alternatives you've considered**
N/A

**Additional context**
The challenge I see is how to best structure integration tests.

ONNX-MLIR generates a shared library object (.so file). Building ONNX-MLIR requires LLVM and other dependencies. ( note pre-built containers are available).

I would appreciate any thoughts on how to incorporate ONNX-MLIR install (or pull a docker image) into the integration test process, and then handling the compile.  The compiler is not installable through pip at this stage. 
Options that come to mind:
- Build from source is possible but takes a long time as LLVM must be built. 
- As mentioned above, pre-built containers are available for different platforms and could potentially be used (they are fairly large though).
- Perhaps it is possible to include or pull-in a precompiled model (.SO file)?

**Comment by yubozhao** [comment]
Hey @andrewsi-z Thank you for the PR and my apologies for the delayed responses.

For integration test, I think we can go with the first option for now.  I think we can get it working an merged and then look into how to improve the testing time.  I can see in the follow up PRs, we can make the test only trigger by commands, or we are using the second option, a pre-built container for it.

Let me know what you think we can figure out it together.

Thank you for helping the community and contributing!

**Comment by andrewsi-z** [comment]
Hi @yubozhao . Thank you for your response!
I've started investigating option 1. Github workflows are a bit new to me so I'm exploring how to implement the tests.

Without a prebuilt container for ONNX-MLIR, the steps are: 
1. install onnx-mlir prerequisites (this is a build from source primarily of llvm).
2. install onnx-mlir (build from source) 
3. create simple TF model and save 
4. convert to onnx 
5. compile onnx model
6. test artifact

I know how to complete all these steps, putting them in the workflow is the next part that I'm a bit unsure of.
I'll investigate further and follow-up in the next day or so how it's progressing.

**Comment by andrewsi-z** [comment]
@bojiang @yubozhao 
It looks like the CI for onnx-mlir is now running in the docker image I am pulling from docker hub... So I think I need to work through now the errors in the next step on running the setup script.
see the draft PR here: https://github.com/bentoml/BentoML/pull/1545

What are your thoughts on this approach given the above? This seemed more straightforward that building from source, but I have to work through the rest of the issues.

**Comment by yubozhao** [comment]
@andrewsi-z I think this approach is good. Rest of the issues would the part about build and install onnx-mlir in the install script?

We start to adopting a new pattern for the integration test.  You can find an example here: https://github.com/bentoml/BentoML/tree/master/tests/integration/projects/fastai2

I think your current integration test is good, we can update it to the new pattern in a follow up PR.

**Comment by andrewsi-z** [comment]
> @andrewsi-z I think this approach is good. Rest of the issues would the part about build and install onnx-mlir in the install script?
> 

The rest of the issues are just to get the subsequent steps to run in the container... Hopefully just some minor debugging to get it working.

**Comment by yubozhao** [comment]
Merged at https://github.com/bentoml/BentoML/pull/1545

close this issue, reopen if needed
