### ISSUE TITLE
[JsonOutput] ensure_ascii=False to not escape UTF-8 characters

### ISSUE THREAD

**Issue by soeque1** [bentoml/BentoML#1577]
**Describe the bug**

https://github.com/bentoml/BentoML/blob/master/bentoml/adapters/json_output.py#L59-L60

Non-ASCII code is escaped using`curl` or python requests.

```
if output == "json":
     json_str = json.dumps(json_obj, cls=NumpyJsonEncoder)
```

**To Reproduce**

```
>>> json.dumps('한국어中國語ABC')
"\\ud55c\\uad6d\\uc5b4\\u4e2d\\u570b\\u8a9eABC"
```

**Expected behavior**

Just add `ensure_ascii=False`

>>

```
if output == "json":
     json_str = json.dumps(json_obj, cls=NumpyJsonEncoder, ensure_ascii=False)
```

```
>>> json.dumps('한국어中國語ABC', ensure_ascii=False)
"한국어中國語ABC"
```

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by parano** [comment]
@soeque1 could you explain why you need this change?

**Comment by soeque1** [comment]
Non-ASCII code is escaped using CURL or python requests.
Of course, it is possible to convert from client (Python) to "\\ud55c\\uad6dABC".encode('utf-8').decode('utf-8')

But, it was uncomfortable.
Please let me know if there are other good alternatives on the client side.

**Comment by parano** [comment]
Thanks, @soeque1, I had a discussion with @bojiang and we think your proposal makes sense, we will accept the PR and use `ensure_ascii=False` as the new default going forward.
