### ISSUE TITLE
Refactor labels storage in Yatai

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1579]
**Describe the bug**

Separate it from bento service metadata protobuf  - which makes it possible to add additional features around searching and filtering saved bentos

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by parano** [comment]
This is no longer relevant since we have moved Yatai to a separate project here, rebuilt from scratch https://github.com/bentoml/yatai
