### ISSUE TITLE
[Tracing] Jaeger tracing need dict type header

### ISSUE THREAD

**Issue by hsiehjackson** [bentoml/BentoML#1591]
**Describe the bug**

When using tracing with Jaeger in bentoml, there is an error from Jaeger client because of the type of header.
[Bug](https://github.com/bentoml/BentoML/blob/master/bentoml/tracing/jaeger.py#L104) - header type is 'werkzeug.datastructures.EnvironHeaders'
[Reason](https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/codecs.py#L57) - header type must be 'dict'

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.12.1]

**Additional context**

**Comment by parano** [comment]
Fixed via https://github.com/bentoml/BentoML/pull/1720
