### ISSUE TITLE
Error with micro-batching and Sentence-Transformers : <status: 500> when using internal BenchmarkClient

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/BentoML#1593]
**Describe the bug**
Hi community,

When load testing sentence-transformer with internal bentoML BenchmarkClient  and micro-batching activated, most of my requests failed with the following status: `<status: 500> The return values of Api Function doesn't match tasks`

If I look into prediction.log file and compare one request that succeeded:
`{"service_name": "StsBTGpuTransformerService", "service_version": "20210420162648_D90CD1", "api": "predict", "request_id": "98b0bc9b-e64b-4ab2-8b0e-6875ca7eaae2", "task": {"data": "[\"Navigateur Web : Ce logiciel permet d'acc\\u00e9der \\u00e0 des pages web depuis votre ordinateur. Il en existe plusieurs t\\u00e9l\\u00e9chargeables gratuitement comme Google Chrome ou Mozilla. Certains sont m\\u00eame d\\u00e9j\\u00e0 install\\u00e9s comme Safari sur Mac OS et Edge sur Microsoft.\"]", "task_id": "98b0bc9b-e64b-4ab2-8b0e-6875ca7eaae2", "http_headers": [["Host", "127.0.0.1:5000"], ["content-type", "application/json"], ["Accept", "*/*"], ["Accept-Encoding", "gzip, deflate"], ["User-Agent", "Python/3.8 aiohttp/3.7.4.post0"], ["Content-Length", "295"]]}, "result": {"data": "[[-0.5516163110733032, 0.519773006439209, -0.14720813930034637, 0.04608222469687462, -0.05576413869857788, -0.6953222155570984, 0.7339898943901062, 0.2998219430446625, 0.4053557217121124, -0.17605258524417877, 0.1258787214756012, 0.5670403838157654, -0.40738561749458313, 0.1579401195049286, 0.9467802047729492, 0.029552875086665154, -0.3122499883174896, 0.8667414784431458, -0.7031294703483582, -0.00017417002527508885, -0.15444207191467285, -0.2352159470319748, -0.280192106962204, -0.4440619647502899, -0.640231728553772, 0.6880815029144287, 0.2133478969335556, 0.7267807126045227, 0.009036175906658173, ... -0.061271343380212784, 0.05050498992204666, 0.6614540219306946, -0.367836594581604, 0.31827312707901, -0.5193310976028442, 0.06689674407243729, -0.42599913477897644, 0.8638445734977722, 0.413980633020401, -0.09093481302261353, -0.7597688436508179, -0.24376055598258972, -0.12419113516807556, -1.6632903814315796, -0.502410888671875, -0.1071905866265297, 0.3488980233669281, 0.27710211277008057, -0.30685925483703613, -0.37533727288246155, -0.27567875385284424, -0.3994866907596588, -1.0101531744003296, 0.021396487951278687, -0.19006676971912384, -0.6827069520950317, -0.13121862709522247, 0.12978988885879517, -0.3881247937679291, 0.2341720312833786]]", "http_status": 200, "http_headers": [["Content-Type", "application/json"]]}, "asctime": "2021-04-20 16:28:16,285"}`

from one request that failed:
`{"service_name": "StsBTGpuTransformerService", "service_version": "20210420162648_D90CD1", "api": "predict", "request_id": "b8562aa1-0998-41fe-8750-2f9c65bb1f66", "task": {"data": "[\"Navigateur Web : Ce logiciel permet d'acc\\u00e9der \\u00e0 des pages web depuis votre ordinateur. Il en existe plusieurs t\\u00e9l\\u00e9chargeables gratuitement comme Google Chrome ou Mozilla. Certains sont m\\u00eame d\\u00e9j\\u00e0 install\\u00e9s comme Safari sur Mac OS et Edge sur Microsoft.\"]", "error": {"err_msg": "The return values of Api Function doesn't match tasks"}, "task_id": "b8562aa1-0998-41fe-8750-2f9c65bb1f66", "is_discarded": true, "http_headers": [["Host", "127.0.0.1:5000"], ["content-type", "application/json"], ["Accept", "*/*"], ["Accept-Encoding", "gzip, deflate"], ["User-Agent", "Python/3.8 aiohttp/3.7.4.post0"], ["Content-Length", "295"]]}, "result": {"data": "[[-0.5516163110733032, 0.519773006439209, -0.14720813930034637, 0.04608222469687462, -0.05576413869857788, -0.6953222155570984, 0.7339898943901062, 0.2998219430446625, 0.4053557217121124, -0.17605258524417877, 0.1258787214756012, 0.5670403838157654, -0.40738561749458313, 0.1579401195049286, 0.9467802047729492, 0.029552875086665154, -0.3122499883174896, 0.8667414784431458, -0.7031294703483582, -0.00017417002527508885, -0.15444207191467285, -0.2352159470319748, -0.280192106962204, -0.4440619647502899, -0.640231728553772, 0.6880815029144287, ... -1.6985574960708618, 0.10716142505407333, 0.6118273735046387, -0.061271343380212784, 0.05050498992204666, 0.6614540219306946, -0.367836594581604, 0.31827312707901, -0.5193310976028442, 0.06689674407243729, -0.42599913477897644, 0.8638445734977722, 0.413980633020401, -0.09093481302261353, -0.7597688436508179, -0.24376055598258972, -0.12419113516807556, -1.6632903814315796, -0.502410888671875, -0.1071905866265297, 0.3488980233669281, 0.27710211277008057, -0.30685925483703613, -0.37533727288246155, -0.27567875385284424, -0.3994866907596588, -1.0101531744003296, 0.021396487951278687, -0.19006676971912384, -0.6827069520950317, -0.13121862709522247, 0.12978988885879517, -0.3881247937679291, 0.2341720312833786]]", "http_status": 200, "http_headers": [["Content-Type", "application/json"]]}, "asctime": "2021-04-20 16:28:16,309"}`

I can't figure out what caused that since input and result data are the same in both of those cases.

Please anyone could figure out what's wrong?

Thanks!

**Environment:**
 - OS: [Ubuntu 18.04.5 LTS]
 - Python Version [Python 3.8.8]
 - BentoML Version [BentoML-0.12.0]

**Comment by bojiang** [comment]
@Matthieu-Tinycoaching 
Is this issue still happening?

**Comment by Matthieu-Tinycoaching** [comment]
Hi @bojiang no this issue can be close. The inputs used for microbatching wasn't appropriate, which has been corrected.

**Comment by uniquerussa** [comment]
Could you please let me know how you resolved this issue? I'm using custom input processing and I'm having the same issue.
