### ISSUE TITLE
Cannot delete BentoML model in Yatai service

### ISSUE THREAD

**Issue by mar-muel** [bentoml/BentoML#1606]
My model name is
```
test-model:1.0.20210507102237_9234C9
```

which means I've used `bentoml.ver(major=1, minor=0)` and 
```
@property
def name(self):
     return "test-model"
```
in the service class.

When trying to delete this model with
```
bentoml delete test-model:1.0.20210507102237_9234C9
```
I get the following error:
```
Error: Invalid value for '[DELETE_TARGETS]': Bad formatting. Please present a valid bento bundle name or "name:version" tag. For list of bento bundles, separate delete targets by ",", for example: "my_service:v1,my_service:v2,classifier"
```

**Comment by yubozhao** [comment]
@mar-muel Thank you for filing this issue.  Can you share with me what BentoML version you are using? and other system info such as python version?

**Comment by mar-muel** [comment]
Ok - thanks @parano.

The idea here was to be consistent between Bento service names and docker image names which are usually required to be snake case. 

If this is not a feature you are willing to support in the future, I will close this issue.

**Comment by parano** [comment]
@mar-muel  it sounds like it's just a preference on naming, not a blocker for you?  if that's the case, we probably won't provide this support because it will require lots of changes on BentoML side
