### ISSUE TITLE
Yatai service (deployed on Kubernetes) becomes unusable until restarted following exception or error 

### ISSUE THREAD

**Issue by nicjac** [bentoml/BentoML#1614]
**Describe the bug**

I have Yatai service deployed on Kubernetes. When encountering an issue with an operation (e.g. in this case a missing IAM permission when attempting to deploy a service to Lambda), the service becomes unusable until restarted.

The error message is always of the type:
```
Error: lambda deploy failed: INTERNAL:Instance '<Deployment at 0x7fbf871f6310>' has been deleted, or its row is otherwise not present.
```

**To Reproduce**
1. Setup bentoml to use a remote Yatai service
2. Encounter an error during an operation (e.g. lambda deployment)
3. Attempt another operation
4. See error message above

**Expected behavior**
An error should not impact the functioning of the service and subsequent operations.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/3091276/117692169-a9724500-b1b4-11eb-9059-b425a6bd3fd9.png)

**Environment:**
- OS: Client is MacOS 11.2.3, Kubernetes 1.16
- Current default Yatai image
- BentoML client version: 0.12.1

**Additional context**
Yatai deployed on Kubernetes using S3 storage

**Comment by parano** [comment]
@nicjac we are now moving the deployment functionalities out of Yatai https://github.com/bentoml/BentoML/issues/1677 - this particular issue was related to creating lambda deployment, which will become a standalone tool that's way easier to use and debug for devops.  https://github.com/bentoml/aws-lambda-deploy/
