### ISSUE TITLE
Livereload support for speeding up development

### ISSUE THREAD

**Issue by jeanCarloMachado** [bentoml/BentoML#1617]
Hello Bento Team,

First of all, thanks for the great project. 

**Is your feature request related to a problem? Please describe.**
 I did some investigation and looks like bento does not support live reloading.
Live reloading is especially useful if one wants to do some complex pre and post-computation logic in the web service (which is my case). 

**Describe the solution you'd like**
By passing a flag to ```bentoml serve``` one would get live reload. Meaning, that every change in the source code is available immediately in the local development webservice. 

Not sure if this is possible at all with the current bento architecture, but let me know :)

Thanks in advance!

**Comment by yubozhao** [comment]
@jeanCarloMachado 
Have you able to try out `start_dev_server` method on the bento service instance? You can start an API server without saving.  Here is the link for it.  I will make sure update doc's API section to make it easier to find

https://github.com/bentoml/BentoML/blob/f55685018fa5a2584aa4026b48c2df75a93dffa1/bentoml/service/__init__.py#L782

**Comment by jeanCarloMachado** [comment]
Hello, @yubozhao 

Thanks for pointing out. I'm indeed using that, still I have to cancel the process and start again to see my changes.

Maybe I'm using it wrong?

```py
predictor = RankingService()
predictor.pack("main", model)
predictor.start_dev_server(port=self.PORT, debug=True)
while True:
    time.sleep(1000)
```

**Comment by jeanCarloMachado** [comment]
Another thing that hinders the development is that the breakpoint() function does not work. If I set a breakpoint in the predict function I get this error:

```sh

ERROR - Error caught in API function:
Traceback (most recent call last):
  File "/home/jean/anaconda3/envs/ranking/lib/python3.7/site-packages/bentoml/service/inference_api.py", line 177, in wrapped_func
    return self._user_func(*args, **kwargs)
  File "/tmp/tmpmuc4ecwh/RankingService/ranking/online_inference.py", line 23, in rank
    logging.info("Inference happening")
  File "/tmp/tmpmuc4ecwh/RankingService/ranking/online_inference.py", line 23, in rank
    logging.info("Inference happening")
  File "/home/jean/anaconda3/envs/ranking/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/jean/anaconda3/envs/ranking/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

I think could be related with bentoml using a subprocess in the background to run the webserver thus the breakpoint session cannot be raised to the screen.

Let me know if you prefer I set a new issue regarding this topic, happy to do it!

**Comment by jjmachan** [comment]
livereload is something that would be useful for me too. I use a watchdog scrip to monitor for file changes and then use the library functions to get the same effect. A more elegant approach would be helpful

**Comment by aarnphm** [comment]
Hi @jeanCarloMachado we are currently working on 1.0 release, which will include QOL improvement such as live reload. Stay tuned! 😄

**Comment by totalhack** [comment]
Is this close? I'd like to be able to use `bentoml serve` in development/testing with live reload of the endpoint if I make changes to the service. Not sure if that's something you plan to support. Thanks.

**Comment by aarnphm** [comment]
HI @totalhack , this will be supported in the upcoming release. stay tuned

**Comment by totalhack** [comment]
Thanks @aarnphm . I was hoping to get an idea of timing as I'm in the process of deciding whether to use bento in a new project. Is there a progress tracker for the new release, or just a general ETA? Just trying to understand whether it is a matter of weeks or months at least.

**Comment by aarnphm** [comment]
Hi @totalhack, 1.0 should be very close now. In the meantime, feel free to check out the `bentoml-1.0` branch

**Comment by parano** [comment]
This is supported now in BentoML 1.0, users can use `bentoml serve` command with `--load` option, which will automatically reload the server when the service definition file or related files are changed.

**Comment by jeanCarloMachado** [comment]
Great news! Thanks @parano
