### ISSUE TITLE
Support Azure blob storage in BentoML Model Registry (YataiService)

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1620]
**Is your feature request related to a problem? Please describe.**

BentoML currently support AWS S3, Google Cloud Storage as Yatai service's storage backend. With [Azure Blob Storage ](https://azure.microsoft.com/en-us/services/storage/blobs/) support, BentoML will integrate with all major cloud providers' object storage services.

TODO list:
- [ ] implement Azure blob storage support
- [ ] Add cli options similar to GCS or S3: `$ bentoml yatai-service-start --azure-url AZURE-url`
- [ ] Add tests
- [ ] Add documentation: guide, API reference

**Describe alternatives you've considered**

**Additional context**

**Comment by yubozhao** [comment]
cc @Qiao-Liang

**Comment by jjmachan** [comment]
I'd like to work on this is no one is working on this yet

**Comment by parano** [comment]
@jjmachan I don't think anyone is working on this, you're welcome to take it :D

**Comment by jjmachan** [comment]
Thanks man 😃 @parano

**Comment by jjmachan** [comment]
hey @alxmke, I see your making steady progress on this too

**Comment by aarnphm** [comment]
@jjmachan I think this is done?
