### ISSUE TITLE
Microbatch not enabled by default on 0.12.1

### ISSUE THREAD

**Issue by calclavia** [bentoml/BentoML#1638]
**Describe the bug**

I'm running Bentoml v0.12.1 and it seems that I still need to use --enable-microbatch in order for microbatching to take effect. Otherwise, `bentoml serve-gunicorn` doesn't batch requests.

**To Reproduce**

Run a bentoml service with/without `--enable-microbatch` flag.

**Expected behavior**

I expect microbatching to be enabled by default, as specified in the docs.

**Environment:**
 - OS: Ubuntu 14
 - Python Version Python 3.7
 - BentoML Version 0.12.1

**Comment by parano** [comment]
Thanks for reporting @calclavia - Tracking this issue here now https://github.com/bentoml/BentoML/issues/1647
