### ISSUE TITLE
The artifact metadata are not getting saved when the yatai-url is configured to point to minio repo

### ISSUE THREAD

**Issue by morningcloud** [bentoml/BentoML#1649]
**Describe the bug**
The artifact metadata are not getting saved when the yatai-url is configured to point to minio repo, but it is saved as expected when bentoml is running using local repo.

**To Reproduce**
1.  Run the following script in CLI
`bentoml config set yatai_service.url=https://yatai.service.url:50051`
2. Run following python script
```
metadata_dict = {"classpackage": "simpletransformers.classification", "classname": "ClassificationModel", "use_cuda": False, "num_labels": 2}
bento_service = BentoServiceName()
bento_service.pack(model_name, {'model':model, 'metadata':metadata_dict})  //the content of metadata will be saved to self._metadata as part of BentoServiceArtifact class implementation
bento_service.save(labels=get_valid_bento_labels({'sha': sha, 'runid': run_id}))
```
3. Run the following script in CLI
`bentoml get BentoServiceName:latest`
4. The output will be returned as:
```
{
  "name": "BentoServiceName",
  "version": "20210531024204_CD4228",
  "uri": {
    "type": "S3",
    "uri": "s3://bentoml/BentoServiceName/20210531024204_CD4228.tar.gz",
    "s3PresignedUrl": "xxx"
  },
  "bentoServiceMetadata": {
    "name": "BentoServiceName",
    "version": "20210531024204_CD4228",
    "createdAt": "2021-05-31T02:42:06.551831Z",
    "env": {
      "condaEnv": "name: bentoml-default-conda-env\nchannels:\n- conda-forge\n- defaults\ndependencies:\n- pip\n",
      "pythonVersion": "3.7.6",
      "dockerBaseImage": "xxx",
      "pipPackages": [
        "bentoml==0.10.1",
        "simpleartifact==xxx"
      ]
    },
    "artifacts": [
      {
        "name": "model",
        "artifactType": "SimpleTransformersModelArtifact"
      }
    ],
    "apis": [
      {
        "name": "predict",
        "inputType": "JsonInput",
        "docs": "BentoService inference API 'predict', input: 'JsonInput', output: 'DefaultOutput'",
        "outputConfig": {
          "cors": "*"
        },
        "outputType": "DefaultOutput",
        "mbMaxLatency": 10000,
        "mbMaxBatchSize": 2000,
        "batch": true
      }
    ],
    "labels": {
      "runid": "xxx",
      "sha": "xxx"
    }
  }
}
```
5.  Run the following script in CLI to use a local registry
`bentoml config set yatai_service.url=`
6. Run the same python script in point 2.
7. Run the same CLI command in point 3.
8. The output will return:
```
{
  "name": "BentoServiceName",
  "version": "20210531055055_A41DA6",
  "uri": {
    "type": "LOCAL",
    "uri": "/home/user/bentoml/repository/BentoServiceName/20210531055055_A41DA6"
  },
  "bentoServiceMetadata": {
    "name": "SituationSolutionService",
    "version": "20210531055055_A41DA6",
    "createdAt": "2021-05-31T05:50:58.722927Z",
    "env": {
      "condaEnv": "name: bentoml-default-conda-env\nchannels:\n- conda-forge\n- defaults\ndependencies:\n- pip\n",
      "pythonVersion": "3.7.6",
      "dockerBaseImage": "xxx",
      "pipPackages": [
        "bentoml==0.10.1",
        "simpleartifact==xxx"
      ]
    },
    "artifacts": [
      {
        "name": "model",
        "artifactType": "SimpleTransformersModelArtifact",
        "metadata": {
          "classpackage": "simpletransformers.classification",
          "classname": "MultiLabelClassificationModel"
          "num_labels": 2.0,
          "use_cuda": false
        }
      }
    ],
    "apis": [
      {
        "name": "predict",
        "inputType": "JsonInput",
        "docs": "BentoService inference API 'predict', input: 'JsonInput', output: 'DefaultOutput'",
        "outputConfig": {
          "cors": "*"
        },
        "outputType": "DefaultOutput",
        "mbMaxLatency": 10000,
        "mbMaxBatchSize": 2000,
        "batch": true
      }
    ],
    "labels": {
      "runid": "xxx",
      "sha": "xxx"
    }
  }
}
```

**Expected behavior**
The output in step 4 should contain metadata under the artifacts just like in step 8

**Environment:**
 - Python Version: Python 3.7.6
 - BentoML Version: BentoML 0.10.1

**Additional context**
The yatai service is confirgued to point to minio as s3 bucket

**Comment by yubozhao** [comment]
@morningcloud Thanks for reporting this issue and the very detailed reproducible!  Apologies for the late responses.

I use the latest version `0.12.1` and can't reproduce your issue.  The step 4 contains the metadata under the artifacts section.

Can you test it with this version and let me know?

**Comment by morningcloud** [comment]
@yubozhao Thanks for getting back to me, I have tried with the latest version and still didn't see the metadata under the artifcats section.

[test_metadata.ipynb.zip](https://github.com/bentoml/BentoML/files/6629142/test_metadata.ipynb.zip)

However, I found out later that the saved model files actually contain the metadata and also when serving the model, the metadata are getting loaded correctly as expected. It is just not getting printed with `bentoml get` command. Therefore, this it is not an issue to me and it can be closed.

I am attaching a sample notebook where I tested with version `0.12.1` and the output is shown for reference.

**Comment by parano** [comment]
Update: we have moved Yatai to a separate project here, rebuilt from scratch https://github.com/bentoml/yatai

In the new Yatai and BentoML 1.0, users can push/pull models and bentos to/from Yatai, and we made sure that model metadata are being kept in this process. Here's a model details UI in Yatai:

![Uploading Screen Shot 2022-01-18 at 5.12.14 PM.png…]()
