### ISSUE TITLE
How to use the bemtoml monitor model serving？

### ISSUE THREAD

**Issue by sunnyl95** [bentoml/BentoML#1651]
I did not find any examples of model monitoring in the[ technical documentation](https://docs.bentoml.org/en/latest/quickstart.html). If anyone knows the use of model service monitoring, please teach me, thank you very much！

———Health check endpoint and Prometheus /metrics endpoint for monitoring

**Comment by aarnphm** [comment]
You can run Prometheus on your local machine with docker, refers to their [guide](https://prometheus.io/docs/prometheus/latest/installation/) on this. Then you need a `prometheus.yml` config file to setup server for scraping metrics. BentoML provides `/metrics` for every BentoService so you can start from there.

You can also use Grafana to setup some nice dashboard. Let me know if you have any more questions. I will pick this up and let you know if there are any updates with this.

**Comment by aarnphm** [comment]
@sunnyl95 ping me if you have any other questions. I will close this
