### ISSUE TITLE
`/metrics` doesn't get exposed while running with bentoml `serve-gunicorn`

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#1662]
**Describe the bug**

when running `bentoml serve-gunicorn` metrics doesn't get exposed as expected.

**To Reproduce**

1. Serve any current `BentoService` that you have (if none run `make torch-pipe` from [here](https://github.com/aarnphm/distributed-deployment-ml))
2. `docker run --gpus all -p 5000:5000 bento-torch-gpu:latest`
3. `curl -v localhost:5000/metrics`

**Expected behavior**

Terminal should returns prometheus format metrics, similar to when run `bentoml serve`

**Screenshots/Logs**
when run with `bentoml serve ...` (expected and correct behaviour)
![image](https://user-images.githubusercontent.com/29749331/120963031-144e7600-c78b-11eb-87db-b46cc45ad39b.png)

when running in docker container (which is `bentoml serve-gunicorn`)
![image](https://user-images.githubusercontent.com/29749331/120963202-57104e00-c78b-11eb-8e03-f3f17ce0f6f0.png)
![image](https://user-images.githubusercontent.com/29749331/120963237-65f70080-c78b-11eb-9d6a-40bd870f3a28.png)

**Environment:**
 - OS: archlinux 5.12.8-arch1-1
 - Python Version: 3.8.8
 - BentoML Version: `master` branch 

**Additional context**

**Comment by bojiang** [comment]
Let me take a look.

**Comment by aarnphm** [comment]
@bojiang I will take this.

**Comment by bojiang** [comment]
A probable reason.

https://github.com/bentoml/BentoML/blob/slo/bentoml/server/instruments.py#L95

>  Warning: for this to work, prometheus_client library must be imported after this function is called

I guess the latest configuration refactoring, which just changed the import order might cause this issue.

**Comment by bojiang** [comment]
We may create `<project_root>/bentoml/server/metrics.py` and unified all importing `from prometheus_client import *` to that module.

**Comment by aarnphm** [comment]
Thank you for the help.

**Comment by aarnphm** [comment]
Done
