### ISSUE TITLE
Add custom pages into Yatai UI

### ISSUE THREAD

**Issue by henrywu2019** [bentoml/BentoML#1675]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would integrate Yatai with other systems.

**Describe alternatives you've considered**
Create multiple web servers to serve different pages

**Additional context**
- Now I just want to integrate some static pages
- How about dynamic page like django, flask...

**Comment by parano** [comment]
@henrywu2019  the easiest way is probably to deploy Yatai's API server and run your own web server that talks to Yatai.   You can also fork Yatai's frontend server and modify it to include additional web pages.  may I ask what are the things you want to achieve with dynamic pages with django or flask?

**Comment by parano** [comment]
This is no longer relevant since we have moved Yatai to a separate project here, rebuilt from scratch https://github.com/bentoml/yatai
