### ISSUE TITLE
Edit yatai dockerfile to fetch s3 signature and start service

### ISSUE THREAD

**Issue by alborotogarcia** [bentoml/BentoML#1676]
**Is your feature request related to a problem? Please describe.**

IMHO I think it would be useful to fetch pre-signed s3 URL at runtime when deploying on kubernetes cluster. So anyone could deploy yatai pointing to any s3/minio bucket with a few env variables.

**Describe the solution you'd like**

Let yatai service entrypoint fetch environment variables to fetch the signature eg. as described on https://github.com/bentoml/BentoML/pull/679
` $ AWS_ACCESS_KEY_ID=Q3AM3UQ867SPQQA43P2F AWS_SECRET_ACCESS_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG AWS_REGION=us-east-1 bentoml yatai-service-start --s3-endpoint-url=https://play.min.io:9000 --repo-base-url=s3://chaoyu-bentoml`
**Describe alternatives you've considered**

Edit the Dockerfile adding an initContainer or a precommand before the entrypoint that creates the signature

**Additional context**

**Comment by parano** [comment]
hi @alborotogarcia - do you mind describing your use case in more detail?  I'm not sure I understand what you mean by "fetch pre-signed s3 URL at runtime".  Yatai already fetch pre-signed S3 URL at runtime when the client requests to upload or download a bento bundle from s3

**Comment by alborotogarcia** [comment]
hi @parano !
Basically I've been templating the yatai helm chart and I can't pass env variables to yatai like

```
          args:
            - "--db-url=$BACKEND_STORE_URI"
            - "--repo-base-url=$DEFAULT_ARTIFACT_ROOT --s3-endpoint-url=$MLFLOW_S3_ENDPOINT_URL"
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-secrets
                  key: MINIO_SECRET_KEY
            - name: DEFAULT_ARTIFACT_ROOT
              value: s3://yatai/artifacts
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: storage-secrets
                  key: MINIO_ENDPOINT
            - name: BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: storage-secrets
                  key: backend_store_uri
```
It throws the following error

```
+ ml-system yatai-service-6c994c966f-dbspk › yatai-service
ml-system yatai-service-6c994c966f-dbspk yatai-service Traceback (most recent call last):
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/bin/bentoml", line 8, in <module>
ml-system yatai-service-6c994c966f-dbspk yatai-service     sys.exit(cli())
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
ml-system yatai-service-6c994c966f-dbspk yatai-service     return self.main(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
ml-system yatai-service-6c994c966f-dbspk yatai-service     rv = self.invoke(ctx)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
ml-system yatai-service-6c994c966f-dbspk yatai-service     return _process_result(sub_ctx.command.invoke(sub_ctx))
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
ml-system yatai-service-6c994c966f-dbspk yatai-service     return ctx.invoke(self.callback, **ctx.params)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
ml-system yatai-service-6c994c966f-dbspk yatai-service     return callback(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 139, in wrapper
ml-system yatai-service-6c994c966f-dbspk yatai-service     return func(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
ml-system yatai-service-6c994c966f-dbspk yatai-service     return_value = func(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
ml-system yatai-service-6c994c966f-dbspk yatai-service     return func(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/yatai_service.py", line 91, in yatai_service_start
ml-system yatai-service-6c994c966f-dbspk yatai-service     web_prefix_path,
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/yatai/yatai_service.py", line 104, in start_yatai_service_grpc_server
ml-system yatai-service-6c994c966f-dbspk yatai-service     db_url=db_url, repo_base_url=repo_base_url, s3_endpoint_url=s3_endpoint_url,
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/yatai/yatai_service_impl.py", line 100, in __init__
ml-system yatai-service-6c994c966f-dbspk yatai-service     self.sess_maker = init_db(db_url)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/yatai/db.py", line 57, in init_db
ml-system yatai-service-6c994c966f-dbspk yatai-service     engine = create_engine(db_url, **extra_db_args)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 525, in create_engine
ml-system yatai-service-6c994c966f-dbspk yatai-service     return strategy.create(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
ml-system yatai-service-6c994c966f-dbspk yatai-service     u = url.make_url(name_or_url)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
ml-system yatai-service-6c994c966f-dbspk yatai-service     return _parse_rfc1738_args(name_or_url)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
ml-system yatai-service-6c994c966f-dbspk yatai-service     "Could not parse rfc1738 URL from string '%s'" % name
ml-system yatai-service-6c994c966f-dbspk yatai-service sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '$BACKEND_STORE_URI'

```

- ml-system yatai-service-6c994c966f-dbspk › yatai-service
+ ml-system yatai-service-6c994c966f-dbspk › yatai-service
ml-system yatai-service-6c994c966f-dbspk yatai-service Traceback (most recent call last):
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/bin/bentoml", line 8, in <module>
ml-system yatai-service-6c994c966f-dbspk yatai-service     sys.exit(cli())
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
ml-system yatai-service-6c994c966f-dbspk yatai-service     return self.main(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
ml-system yatai-service-6c994c966f-dbspk yatai-service     rv = self.invoke(ctx)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
ml-system yatai-service-6c994c966f-dbspk yatai-service     return _process_result(sub_ctx.command.invoke(sub_ctx))
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
ml-system yatai-service-6c994c966f-dbspk yatai-service     return ctx.invoke(self.callback, **ctx.params)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
ml-system yatai-service-6c994c966f-dbspk yatai-service     return callback(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 139, in wrapper
ml-system yatai-service-6c994c966f-dbspk yatai-service     return func(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
ml-system yatai-service-6c994c966f-dbspk yatai-service     return_value = func(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
ml-system yatai-service-6c994c966f-dbspk yatai-service     return func(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/cli/yatai_service.py", line 91, in yatai_service_start
ml-system yatai-service-6c994c966f-dbspk yatai-service     web_prefix_path,
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/yatai/yatai_service.py", line 104, in start_yatai_service_grpc_server
ml-system yatai-service-6c994c966f-dbspk yatai-service     db_url=db_url, repo_base_url=repo_base_url, s3_endpoint_url=s3_endpoint_url,
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/yatai/yatai_service_impl.py", line 100, in __init__
ml-system yatai-service-6c994c966f-dbspk yatai-service     self.sess_maker = init_db(db_url)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/bentoml/yatai/db.py", line 57, in init_db
ml-system yatai-service-6c994c966f-dbspk yatai-service     engine = create_engine(db_url, **extra_db_args)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 525, in create_engine
ml-system yatai-service-6c994c966f-dbspk yatai-service     return strategy.create(*args, **kwargs)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
ml-system yatai-service-6c994c966f-dbspk yatai-service     u = url.make_url(name_or_url)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
ml-system yatai-service-6c994c966f-dbspk yatai-service     return _parse_rfc1738_args(name_or_url)
ml-system yatai-service-6c994c966f-dbspk yatai-service   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
ml-system yatai-service-6c994c966f-dbspk yatai-service     "Could not parse rfc1738 URL from string '%s'" % name
ml-system yatai-service-6c994c966f-dbspk yatai-service sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '$BACKEND_STORE_URI'`

It seems like my BACKEND_STORE_URI doesn't get evaluated, though this pattern works for mlflow having no args spec field at the entrypoint.. My env variables are parsed from sealed secrets so I was looking for a way to connect to db and artifact repo that automatically creates the tables and bucket repo

**Comment by parano** [comment]
@alborotogarcia have you tried putting the env var in parentheses? like 

```
          args:
            - "--db-url=$(BACKEND_STORE_URI)"
            - "--repo-base-url=$DEFAULT_ARTIFACT_ROOT --s3-endpoint-url=$(MLFLOW_S3_ENDPOINT_URL)"
```

See related document https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments

```
Note: The environment variable appears in parentheses, "$(VAR)". This is required for the variable to be expanded in the command or args field.
```

**Comment by alborotogarcia** [comment]
Thanks @parano ! It's fully working.. I had some issues with db uri string and sealed secrets.. I may close this !
