### ISSUE TITLE
Async Support in Inference API

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#1684]
**Is your feature request related to a problem? Please describe.**

The current synchronous implementation of the inference API is great for model computation which is mostly C/GPU intensive tasks. The inference logic can also include I/O-bound operations like other calling downstream services, e.g. a feature store, which having async support can best utilize system resources. This issue is to gauge the community's interests in having async support in BentoML.

**Comment by ssheng** [comment]
@theopinard

**Comment by theopinard** [comment]
Hi everyone,
I am interested in this feature. The main use case we have would be to be able to query a feature store before doing the inference. BentoML allowed a lot of flexibility in the way you defined your predict API function. [Flask 2.0](https://flask.palletsprojects.com/en/2.0.x/changes/) introduced async/await which hopefully would make it possible (an hopefully not too complicated) for BentoML to add support also.

**Comment by parano** [comment]
This is supported in BentoML 1.0 now https://docs.bentoml.org/en/latest/concepts/api_io_descriptors.html
