### ISSUE TITLE
The base GPU image has no git installed 

### ISSUE THREAD

**Issue by illy** [bentoml/BentoML#1699]
**Describe the bug**

The GPU base image (bentoml/model-server:0.13.0-py38-gpu) doesn't have git installed, whereas the previous CPU base image has no such issue.

**To Reproduce**

Steps to reproduce the issue:
1. Go to a packed bento folder with GPU serving support
2. run the DockerFile (bentoml/model-server:0.13.0-py38-gpu)
3. See error

Package 'git' has no installation candidate

**Expected behavior**
The git is preinstalled in the GPU base image, which is similar to the CPU base image. 

**Screenshots/Logs**

If applicable, add screenshots, logs or error outputs to help explain your problem.

To give us more information for diagnosing the issue, make sure to enable debug logging:

From the docker build log:

#12 12.29 Reading package lists...
#12 12.30 Building dependency tree...
#12 12.30 Reading state information...
#12 12.30 Package git is not available, but is referred to by another package.
#12 12.30 This may mean that the package is missing, has been obsoleted, or
#12 12.30 is only available from another source
#12 12.30
#12 12.30 E: Package 'git' has no installation candidate
#12 12.30 ./setup.sh: line 9: git: command not found
#12 ERROR: executor failed running [/bin/bash -c ./bentoml-init.sh custom_setup]: exit code: 127

**Environment:**
 - OS: [e.g. MacOS 11.4]
 - Python Version [e.g. Python 3.8.0]
 - BentoML Version [e.g. BentoML-0.13.0]

**Additional context**

**Comment by parano** [comment]
cc @aarnphm
