### ISSUE TITLE
Enable PyLint on tests/integration

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1700]
**Is your feature request related to a problem? Please describe.**

Currently the `make lint` task does not run `pylint` on the `tests/integration` folder. This is configured here in the `pylintrc` file: https://github.com/bentoml/BentoML/blob/master/pylintrc#L10

We would like to enable Pylint on this directory, remove it from the `ignore` list in the `pylintrc` file, and fix all the pylint errors found under that directory.

Note: some of the lint errors might be best to ignore inline with inline comment like this: `# pylint: disable=some-message,another-one`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbrishabh** [comment]
Hey! I can try to help with this!

**Comment by aarnphm** [comment]
This has been addressed and fixed in `bentoml-1.0` branch
