### ISSUE TITLE
Parameter 's3_endpoint_url' cannot get injected into get_yatai_service

### ISSUE THREAD

**Issue by notniknot** [bentoml/BentoML#1707]
**Describe the bug**
When using a self hosted MinIO as S3 storage, the generated presigned url contains the amazonaws domain, such as
'https://yatai-bucket.s3.amazonaws.com/IrisClassifier/26.tar.gz?...'. Thus, storing and loading models from S3 storage result in an error. This bug is new in Version 0.13.0.

The function _get_yatai_service_ lacks the s3_endpoint_url parameter.
Additionally, if no channel_address in _get_yatai_service_ is given, the call to _create_repository_ for the repository parameter of _LocalYataiService_ lacks the s3_endpoint_url.

This can be fixed by first adding the following paramter to the _get_yatai_service_ function (yatai/yatai_services.py):
`s3_endpoint_url: str = Provide[BentoMLContainer.config.yatai.repository.s3.endpoint_url],`

And second, adding the s3_endpoint as paramter to the _create_repository_ call inside of the _get_yatai_service_ function (yatai/yatai_services.py):
```python
repository = create_repository(
        repository_type=repository_type,
        file_system_directory=file_system_directory,
        s3_url=s3_url,
        s3_endpoint_url=s3_endpoint_url,
        gcs_url=gcs_url,
)
```

**To Reproduce**
1. Set up a local MinIO-Storage
2. Reference the storage in the config yaml:
```yaml
yatai:
    repository:
        type: s3
        s3:
            signature_version: s3v4
            url: s3://yatai-bucket/
            endpoint_url: http://...
```
3. Create a simple hello world example: https://docs.bentoml.org/en/latest/quickstart.html#example-hello-world
4. See error when saving the service class

**Expected behavior**
The model gets saved in the MinIO storage.

**Environment:**
 - OS: Linux (Redhat)
 - Python Version 3.8
 - BentoML Version BentoML-0.13.0

**Comment by bojiang** [comment]
Hi @notniknot. Thanks for reporting!
Could you give it a try on my branch https://github.com/bentoml/BentoML/pull/1705 ?

**Comment by bojiang** [comment]
pip install git+https://github.com/bojiang/BentoML.git@di2

**Comment by notniknot** [comment]
Hi @bojiang. Sorry, but I still get a presigned amazonaws url. The _get_yatai_service_ function is missing the proposed changes.

**Comment by bojiang** [comment]
@notniknot Oh, I see. Thanks.
