### ISSUE TITLE
Local config file cannot be found with custom bentoml configuration location

### ISSUE THREAD

**Issue by notniknot** [bentoml/BentoML#1717]
The docs state _"By default, configurations defined in $BENTOML_HOME/bentoml.yml is applied if present."_ (see https://docs.bentoml.org/en/latest/guides/configuration.html). This is true for the bentoml.cfg in Version 0.12.1. However, 
with BentoML 0.13.0, the bentoml.yml does not get read from $BENTOML_HOME/bentoml.yml if `BENTOML_CONFIG` is not defined.

Thus, with a custom BentoML location that is specified in `BENTOML_HOME`, the bentoml.yml is still searched in ~/bentoml (if `BENTOML_CONFIG` is not defined).

Logic to read config file in 0.12.1:
```python
def get_local_config_file():
    if "BENTOML_CONFIG" in os.environ:
        # User local config file for customizing bentoml
        return expand_env_var(os.environ.get("BENTOML_CONFIG"))
    else:
        return os.path.join(BENTOML_HOME, "bentoml.cfg")
```

Logic to read config file in 0.13.0 (missing the else statement):
```python
def get_local_config_file():
    if "BENTOML_CONFIG" in os.environ:
        # User local config file for customizing bentoml
        return expand_env_var(os.environ.get("BENTOML_CONFIG"))
    return None
```

In order to fix this issue, add the else statement from 0.12.1 but with the bentoml.yml.

**To Reproduce**
1. Install BentoML Version 0.13.0
2. Select a custom bentoml config location with `bentoml.yml`
3. Set `BENTOML_HOME` but not `BENTOML_CONFIG`
4. bentoml.yml in custom location gets ignored

**Expected behavior**
The `bentoml.yml` gets loaded from the custom location in `BENTOML_HOME` if `BENTOML_CONFIG` is not present.

**Environment:**
 - OS: Linux
 - Python Version 3.8
 - BentoML Version 0.13.0

**Comment by aarnphm** [comment]
@ssheng

**Comment by notniknot** [comment]
Any updates?

**Comment by ssheng** [comment]
@notniknot thanks for raising the issue. Starting release 0.13.0, BentoML removed default config loading under BentoML home and asks users to explicitly set the configuration location in a environment variable `BENTOML_CONFIG`. The motivation behind this change was to limit it to only one way to set configuration. The documentation is no longer accurate. I will update it soon.

**Comment by notniknot** [comment]
> 
> 
> @notniknot thanks for raising the issue. Starting release 0.13.0, BentoML removed default config loading under BentoML home and asks users to explicitly set the configuration location in a environment variable `BENTOML_CONFIG`. The motivation behind this change was to limit it to only one way to set configuration. The documentation is no longer accurate. I will update it in #1792.

Thanks for clarifying this behavior!
