### ISSUE TITLE
Expose more informative error message and logging during containerize

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#1719]
**Is your feature request related to a problem? Please describe.**

Hello, everyone! I'm facing an issue that I already know the cause, but I don't know how to debug it.
```Error: bentoml-cli containerize failed: Failed to containerize MyBentoService:20210625160440_750150 - INTERNAL:The command '/bin/sh -c ./bentoml-init.sh install_pip_packages' returned a non-zero code: 1```
It's because there are some pip dependencies issues while installing it inside the container, but I don't know which dependency is causing this issue.

**Describe the solution you'd like**

We should probably redirect the bash output to surface the errors.

**Describe alternatives you've considered**

**Additional context**

**Comment by aarnphm** [comment]
one way to do it is to 
```bash
RUN set -ex
```
This will start your shell in debug and trace mode, which it should throw out which part is causing error. I believe that we should discuss more about `save_bundle` as we might want to implement a development feature, which allow users to quickly develop `bento_bundle` without going through the whole pipeline

**Comment by parano** [comment]
We have moved away from the python docker API client, currently in BentoML 1.0, `bentoml containerize` should show build errors the same way a regular `docker build` command would do.
