### ISSUE TITLE
Trace on Jaeger can connect with remote span

### ISSUE THREAD

**Issue by wei840222** [bentoml/BentoML#1721]
After fix this pr https://github.com/bentoml/BentoML/pull/1720
It will be happend.
Here is a trace I expected.
<img width="1670" alt="截圖 2021-06-29 下午4 04 17" src="https://user-images.githubusercontent.com/17737823/123764960-dfe85880-d8f7-11eb-95c0-fcdf5f75a3fc.png">

But the actual trace will spilt in two part.
one is the ingress part
<img width="1669" alt="截圖 2021-06-29 下午4 09 16" src="https://user-images.githubusercontent.com/17737823/123765094-fb536380-d8f7-11eb-9878-e372692e6899.png">

another is Bentoml server part
<img width="1671" alt="截圖 2021-06-29 下午4 06 15" src="https://user-images.githubusercontent.com/17737823/123765146-0ad2ac80-d8f8-11eb-858d-86ddf75af99d.png">
and also the gunicorn server part is disappear.
 
 And I found the code in https://github.com/bentoml/BentoML/blob/master/bentoml/marshal/marshal.py#L379 didn't pass the 'Uber-Trace-Id' to the Bentoml server.
 How can I fix it ?
 
The code change of the screenshot of trace I expected is:
![image](https://user-images.githubusercontent.com/17737823/123765952-cdbaea00-d8f8-11eb-8bea-d26e3b57cbec.png)
But I'm not sure. Is it correct?

**Comment by bojiang** [comment]
https://github.com/bentoml/BentoML/pull/1334/files#diff-beea2b4d7a2b388c93b2054ca771e3dc87671c3618fc7a7d888744c8e935e8d5R298

**Comment by parano** [comment]
Update: this issue should be fixed now the in the new BentoML 1.0 version, as part of the support for Open Telemetry: https://github.com/bentoml/BentoML/issues/2163
