### ISSUE TITLE
precommit: conflict with husky pre-commit

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#1728]
**Describe the bug**

With the recent introduction of `hooks/commit-msg` by @larme , it appears that there is already a `commit-msg` generated by `husky`, which will create error when using commit convention.

**To Reproduce**

1. Go to `master` branch
2. `./dev/install_git_hooks.sh`

**Expected behavior**

Should return nothing

**Environment:**
 - OS: [ArchLinux 5.10]
 - Python Version [N/A]
 - BentoML Version [master]

**Additional context**

Possbile fix is to remove husky behaviour

**Comment by larme** [comment]
or should we change the behavior of install_git_hooks.sh and append its content to the existing hooks?

**Comment by aarnphm** [comment]
actually the current husky `commit-msg` doesn't do anything

**Comment by parano** [comment]
I think we are using husky to manage some commit hooks related to typescript code formatting? it might be limited to the typescript project under yatai @yubozhao

**Comment by yubozhao** [comment]
We can probably move the husky related to the CI check

**Comment by aarnphm** [comment]
actually all the hooks are under `.git/hooks` are generated by husky
