### ISSUE TITLE
Overriding `/health` endpoint

### ISSUE THREAD

**Issue by JulesBelveze** [bentoml/BentoML#1757]
**Is your feature request related to a problem? Please describe.**
Hey everyone,
I am deploying my Bento service on a preemptible GPU and I'm willing to overwrite the default healthchecker to become unhealthy if the GPU got preempted (using something like `torch.cuda.is_available()` to detect if the GPU is still here).

**Describe the solution you'd like**
From what I've seen by going through the code it will require quite some work to override the `ModelApi.healthz_view_func`.
Is there currently any way to add new routes ? Or any way to communicate with the healthchecker from the BentoService?

Cheers,
Jules

**Comment by aarnphm** [comment]
similar to #1161. We will look into this when designing bentoml 1.0

**Comment by parano** [comment]
This is supported in BentoML version 1.0 now, see discussion here: https://github.com/bentoml/BentoML/issues/1161#issuecomment-1015965160
