### ISSUE TITLE
Change Footer in https://www.bentoml.ai/

### ISSUE THREAD

**Issue by harshitsinghai77** [bentoml/BentoML#1761]
**Describe the bug**
Change from 2020 to 2021 in https://www.bentoml.ai/ footer `Copyright 2020 BentoML`

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by parano** [comment]
Thanks for reporting @harshitsinghai77 - we will make that change, the website source is actually not in this github repo so I'm going to close it here to avoid confusion.
