### ISSUE TITLE
Support for TensorRT

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/BentoML#1775]
Regarding high performance of transformer models with TensorRT, would it be envisageable to adapt bentoML to work with?

**Comment by aarnphm** [comment]
I assume this is for docker container?

**Comment by Matthieu-Tinycoaching** [comment]
Yes for sure.

**Comment by aarnphm** [comment]
you can build it on top of the Docker GPU image we provided and work from there 😄

**Comment by Matthieu-Tinycoaching** [comment]
Hi @aarnphm sorry I don't really know what includes tensorRT. Doesn't it correspond to a framework/runtime as ON X?

**Comment by aarnphm** [comment]
[tensorrt docs](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html) [onnxruntime dockerfile
](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt)

**Comment by yaysummeriscoming** [comment]
+1 on tensorrt support. Benchmarks against Triton would also be great!

**Comment by aarnphm** [comment]
we will consider this integration after bentoml 1.0

**Comment by hxu296** [comment]
Hello! Do we have any updates on the TensorRT integration? First-class TensorRT support for model serving seems to be a very useful feature.

**Comment by parano** [comment]
This is supported in [BentoML 1.2](https://github.com/bentoml/BentoML/releases/tag/v1.2.0) now! An example project is coming soon!
