### ISSUE TITLE
Feat: Spring cloud eureka client support for scale out

### ISSUE THREAD

**Issue by joswlv** [bentoml/BentoML#1798]
Eureka is used to easily manage node information in MSA (MicroService Architecture) environment using spring cloud.

A scale-out environment is needed to handle large-volume traffic, and at this time, BentoML applications are used on multiple servers.
Eureka client support is required to efficiently manage multiple servers and use routing using spring cloud.

**Comment by frostming** [comment]
Out cloud infra is based on Kubernetes, this is not in the scope. Closing.
