### ISSUE TITLE
Unable to containarize Bento service using Yatai Service from Docker

### ISSUE THREAD

**Issue by picsag** [bentoml/BentoML#1808]
**Description**
I managed to create a Docker image with Yatai-service and save models to the Yatai service inside Docker. However, I am unable to containerize the models, I believe is a bug.

Unable to containarize the BentoService using Python API or bento CLI
The error is:
    raise BentoMLException(
bentoml.exceptions.BentoMLException: Failed to containerize TensorflowService:Aug-12-2021 - INTERNAL:Docker is required for this deployment. Please visit www.docker.com for instructions

I have Docker installed and I also checked inside the Yatai service image, Docker is installed.
**To Reproduce**

Steps to reproduce the issue:
1. Create a Docker image using Yatai-service: latest
2. Save Tensorflow model using model_service.save(yatai_url="127.0.0.1:8081")
3. Containerize the model using yatai_client.repository.containerize('TensorflowService:Aug-12-2021', tag='latest', push=True)

**Comment by parano** [comment]
hi @picsag - what version of the Yatai docker base image are you using? Docker client should be included by default in the latest Yatai docker image release but it's missing in older versions. And did you mount the docker socket as suggested by the documentation?

**Comment by picsag** [comment]
Hello
I used the latest Yatai docker base image. Indeed Docker client is included, I checked via bash inside the Yatai image.
I am using Docker Compose under Windows and in the BentML documentation I found:
 docker run  -v /var/run/docker.sock:/var/run/docker.sock \
I would be grateful if you could give me an example on how to to mount the Docker socket correctly using the Docker compose .yaml file? 
Regards

**Comment by parano** [comment]
Hi @picsag - you can put a similar setting in the docker compose yaml like below:

```
volumes:
   - /var/run/docker.sock:/var/run/docker.sock 
```

**Comment by parano** [comment]
Update: BentoML 1.0 and the new Yatai project launch is around the corner, in the new Yatai implementation, docker image build process will be automated on a K8s cluster, user won't need to manually mount the docker socket any more.
