### ISSUE TITLE
error when using `FileInput` handler in AWS lambda

### ISSUE THREAD

**Issue by jjmachan** [bentoml/BentoML#1816]
when using the file input handler and deploying to lambda, I'm unable to send any requests due to the following error
```
[ERROR] TypeError: expected bytes-like object, not strTraceback (most recent call last):  File "/home/bentoml/bundle/app.py", line 21, in api_func    
prediction = bento_service_api.handle_aws_lambda_event(event)  File "/opt/conda/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 336, in handle_aws_lambda_event   
 inf_task = self.input_adapter.from_aws_lambda_event(event)  File "/opt/conda/lib/python3.8/site-packages/bentoml/adapters/file_input.py", line 174, in from_aws_lambda_event    
f = FileLike(bytes_=base64.decodebytes(event.get('body', "")))  File "/opt/conda/lib/python3.8/base64.py", line 545, in decodebytes    
_input_type_check(s)  File "/opt/conda/lib/python3.8/base64.py", line 513, in _input_type_check    
raise TypeError(msg) from err | [ERROR] TypeError: expected bytes-like object, not str Traceback (most recent call last):   File "/home/bentoml/bundle/app.py", line 21, in api_func    
 prediction = bento_service_api.handle_aws_lambda_event(event)   File "/opt/conda/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 336, in handle_aws_lambda_event    
 inf_task = self.input_adapter.from_aws_lambda_event(event)   File "/opt/conda/lib/python3.8/site-packages/bentoml/adapters/file_input.py", line 174, in from_aws_lambda_event     
f = FileLike(bytes_=base64.decodebytes(event.get('body', "")))   File "/opt/conda/lib/python3.8/base64.py", line 545, in decodebytes     _input_type_check(s)   File "/opt/conda/lib/python3.8/base64.py", line 513, in _input_type_check     
raise TypeError(msg) from err
```

looking into it I think this line could be the issue

https://github.com/bentoml/BentoML/blob/a9032e2b0249f3e7ffc09ba1b39dcaa842d42d8a/bentoml/adapters/file_input.py#L174

the reason could be that the API Gateway sitting before the lambda service always encodes the binary data coming into base64 and the passes it. the `event` object, that is received by lambda container a base64 str while the `from_aws_lambda_event` expect  b64 encoded bytes.

**Comment by jjmachan** [comment]
also for the upcoming 1.0 design, I was wondering if it would be a good idea to take the logic of `from_aws_lambda_event` and put it into the aws-lambda-deployment since that will make the InputHandler focused on handling the core, if we can figure out a general way to transform the lambda_event into something that can be processed by the `from_http_request()` method

**Comment by aarnphm** [comment]
cc @bojiang @parano

**Comment by parano** [comment]
This is now fixed in the new deployment tool [bentoctl](https://github.com/bentoml/bentoctl) and its [aws-lambda-deploy](https://github.com/bentoml/aws-lambda-deploy) plugin.
