### ISSUE TITLE
Extract JSON serialization to separate method in `JSONOutput` to ease customization

### ISSUE THREAD

**Issue by rsayn** [bentoml/BentoML#1861]
**Is your feature request related to a problem? Please describe.**
Currently, the JSON serialization performed in `JsonOutput.pack_user_func_return_value` is made with a custom `NumpyJsonEncoder` class. Users might want to extend the `JsonOutput` class and add support for different data types (e.g. dataclasses).

**Describe the solution you'd like**
It might be useful to extract the JSON serialization into a separate method in the class `JsonOutput`. This would allow users to extend the class with custom serialization logic or pass a custom serializer class to the `json.dumps` call without having to replicate the whole `pack_user_func_return_value` function, thus maintaining full compatibility with future updates of BentoML.

**Describe alternatives you've considered**
N/A

**Additional context**
[Reference code here](https://github.com/bentoml/BentoML/blob/b19def038fe9ddd04602acf213ea56647deae67f/bentoml/adapters/json_output.py#L50-L83)

**Comment by parano** [comment]
Great suggestion @rsayn! This is actually supported in the upcoming 1.0 release https://github.com/bentoml/BentoML/blob/bentoml-1.0/bentoml/_internal/io_descriptors/json.py#L51, we will be beta testing it soon

**Comment by parano** [comment]
Update: this feature is now supported in BentoML 1.0, where user can provide a custom `json_encoder` for the JSON input or output:  https://docs.bentoml.org/en/latest/api/api_io_descriptors.html#bentoml-io-json
