### ISSUE TITLE
Detectron2 custom model issue

### ISSUE THREAD

**Issue by amarquinar** [bentoml/BentoML#1867]
Hi experts,

I tried to test the example test_detectron2_model_artifact.py, it works fine with the model from COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml.

But when I tried to test with my custom model, it doesn't work, I mean the predictor return a lot of instances with very low accuracies. In the following code part of test_detectron2_artifact_pack function,  the first call response = svc.predict(image) works fine, but the second one after load_from_dir(saved_bundle) doesn't work fine. I think the problem is when I save the bundle and recover it with load_from_dir.

....
    response = svc.predict(image)
    assert response['scores'][0] > 0.9
    comparison = np.array(response['classes']) == np.array(
        [17, 0, 0, 0, 0, 0, 0, 0, 25, 0, 25, 25, 0, 0, 24]
    )
    assert comparison.all()
    saved_bundle = svc.save()
    svc = load_from_dir(saved_bundle)
    response = svc.predict(image)

I only changed the two lines before the line     "clone_cfg = cfg.clone()  # cfg can be modified by model", in the function test_detectron2_artifact_pack, to add my own trained model model_final.pth, with two classes.

def test_detectron2_artifact_pack(detectron2_classifier_class):

    cfg = get_cfg()
    # add project-specific config (e.g., TensorMask)
    # here if you're not running a model in detectron2's core library
    cfg.merge_from_file(
        model_zoo.get_config_file(
            "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
        )
    )
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7  # set threshold for this model
    # Find a model from detectron2's model zoo.
    # You can use the https://dl.fbaipublicfiles... url as well
    #cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(
    #    "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    #)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2 
    cfg.MODEL.WEIGHTS = os.path.join("./model", "model_final.pth")
    clone_cfg = cfg.clone()  # cfg can be modified by model
    clone_cfg.MODEL.DEVICE = "cpu"
    model = build_model(clone_cfg)
    model.eval()

Could you help me, please?

Thank you!

Regards,
Alan

**Comment by alanmarquina** [comment]
Sorry, I forgot tell you I am using bentoml version 0.13.1.

**Comment by alanmarquina** [comment]
![image](https://user-images.githubusercontent.com/74053975/136109651-7483f0f2-90a5-46ec-9614-b8fc229d5f5b.png)

I have checked the files on Artifacts but everithing seems be fine.
