### ISSUE TITLE
Support OpenAPI request header customisation

### ISSUE THREAD

**Issue by hsiehkl** [bentoml/BentoML#1874]
Thank you for your amazing work! BentoML helps us a lot in deploying our ML models smoothly. Recently, we are using BentoML for a more complex project in which we tried to customize the OpenAPI request header but we cannot manage to do it. We had tried to define the header in the request_schema from string_input but we can only update the request body. We are wondering is there any existing way to customize the header as well? If not, it would be very helpful if you can support this feature.

Thanks again for the great project. Looking forward to more features in the following versions!

**Comment by parano** [comment]
Thank you for the feedback @hsiehkl - accessing request header is on our roadmap for BentoML 1.0, will close this issue and track it separately here: https://github.com/bentoml/BentoML/issues/2195

As for customizing the OpenAPI schema, this is possible in BentoML 1.0 now, by overriding the `openapi_request_schema` method of the IO descriptor class. E.g.:

```
import bentoml
from bentoml.io import JSON

class MyJsonInput(Json):
    def openapi_request_schema(self):
         return {  {MIME_TYPE_JSON: {"schema": {"type": "object"}, "headers": ...}}} 
 

svc = bentoml.Service('my_service')

@svc.api(input=MyJsonInput(), output=JSON())
def predict(input_json):
   ...
```
