### ISSUE TITLE
Version and init files not packaged in the service repository

### ISSUE THREAD

**Issue by marcindulak** [bentoml/BentoML#1889]
**Describe the bug**

The `__init__.py` file is empty and `_version.py` file missing in the service repository. The behavior depends on the location of the service export `export_service.py` script.

**To Reproduce**

Steps to reproduce the issue:
1. Clone the example mypackage
```
git clone https://github.com/marcindulak/bentoml-missing-version-import
```
2. Install mypackage
```
deactivate
rm -rf /tmp/venv
python3 -m venv /tmp/venv
. /tmp/venv/bin/activate
pip install ./bentoml-missing-version-import
```
3. Create BentoML service from the location where mypackage cannot be imported from the current working directory
```
cd bentoml-missing-version-import
mv export_service.py
cd ..
python export_service.py
```
4. The `__init__.py` and `_version.py` are missing:
```
ls $(bentoml get Service:latest --print-location --quiet)/Service/mypackage
# __init__.py  service.py
```

**Expected behavior**

The `__init__.py` and `_version.py` are created:
```
ls $(bentoml get Service:latest --print-location --quiet)/Service/mypackage
# __init__.py  service.py  _version.py
```

This is the case when `export_service.py` resides in the `./bentoml-missing-version-import` directory.
```
cd bentoml-missing-version-import
python export_service.py
```

**Screenshots/Logs**

**Environment:**
 - OS: [Ubuntu 21.04]
 - Python Version [Python 3.9.5]
 - BentoML Version [e.g. BentoML-0.13.1]

**Additional context**

The issue looks related to other issues listed in https://github.com/bentoml/BentoML/issues/1621#issuecomment-840513959

**Comment by parano** [comment]
Thank you for the feedback @marcindulak - this issue should be fixed now in BentoML version 1.0, where user can specify arbitrary files to be included in the Bento, via a `bentofile.yaml` file. Here's an example build file:

```yaml
service: "iris_classifier:svc"
description: "file: ./readme.md"
labels:
  foo: bar
  team: abc
include:
- "*.py"
- "*.json"
exclude: 
- "*.pyc"
```

See 1.0 documentation to learn more: https://docs.bentoml.org/en/latest/
