### ISSUE TITLE
Documentation for custom metrics with Prometheus is outdated

### ISSUE THREAD

**Issue by ahallermed** [bentoml/BentoML#1960]
**Describe the bug**
In the file docs/source/guides/monitoring.rst the following passage is outdated, links don't work anymore and the api has changed.

------

**NOTE**  Users can also create custom metrics for *BentoService* making use of |prom_client|_, which can be later scraped by Prometheus.

 ```python
        from bentoml.configuratoin.containers import BentoMLContainer

        metrics_client = BentoMLContainer.metircs_client.get()

        REQUEST_TIME = metrics_clint.Summary('request_processing_time', 'Time spend processing request')

        @artifacts([KerasModelArtifact('model'), PickleArtifact('tokenizer')])
        class TensorflowService(BentoService):

            @REQUEST_TIME.time()
            @api(input=JsonInput())
            def predict(self, parsed_json):
                raw = self.preprocessing(parsed_json['text'])
                input_data = [raw[: n + 1] for n in range(len(raw))]
                input_data = pad_sequences(input_data, maxlen=100, padding="post")
                return self.artifacts.model.predict(input_data)
```
------

**Comment by ahallermed** [comment]
Gets fixed by this pull request and can be closed after #1961 ist merged

**Comment by parano** [comment]
@ahallermed thank you for reporting this, you are right the sample code is outdated and we will look into that. cc @bojiang

**Comment by bojiang** [comment]
There is a typo in the doc:
> from bentoml.configuratoin.containers import BentoMLContainer

> from bentoml.configuration.containers import BentoMLContainer

**Comment by bojiang** [comment]
https://github.com/bentoml/BentoML/pull/1963

**Comment by parano** [comment]
Update: this doc is actually only available for the master branch, not the 0.13.1 release, the document got updated before the release.

For version 0.13.1, the suggested change in #1961 should work.

**Comment by vikramjit-sidhu** [comment]
The docs are outdated again, I have tried the following code:

```python
from bentoml._internal.configuration.containers import DeploymentContainer

metrics_client = DeploymentContainer.metrics_client.get()
REQUEST_TIME = prom_client.Counter(
    name="foo",
    documentation="bar",
    labelnames=["endpoint"],
)
```

However I get an assertion error from the `PrometheusClient` class, "Invalid prometheus multiproc directory"

**Comment by aarnphm** [comment]
Hi there, can you try out our recent documentation on the new metrics API?
https://docs.bentoml.org/en/latest/guides/metrics.html
