### ISSUE TITLE
JSON input validation via python dataclass

### ISSUE THREAD

**Issue by davidberenstein1957** [bentoml/BentoML#2030]
**Is your feature request related to a problem? Please describe.**
I have took keep using custom validation without a uniform coherent way when using JsonInputw/wo batching.

**Describe the solution you'd like**
I would love to be able to initialize the JsonInput with a python-native dataclass object. 

**Describe alternatives you've considered**
Looping through inference tasks myself for every edge case in the book and copying this for every endpoint. 

**Additional context**
I only requires python-native classes and minimal code changes.

**Comment by aarnphm** [comment]
Hi @davidberenstein1957, thank you for bringing this problem forward. I will take a look for our upcoming 1.0 release.

**Comment by parano** [comment]
This feature is supported in BentoML now, user-defined pydantic class can now be used for validating JSON input and output: https://docs.bentoml.org/en/latest/api/api_io_descriptors.html#bentoml-io-json

```python
# sklearn_svc.py
import pandas as pd
import numpy as np
from bentoml.io import JSON
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel

class User(BaseModel):
    id: int
    name = 'John Doe'
    signup_ts: Optional[datetime] = None
    friends: List[int] = []

input_spec = JSON(pydantic_model=User)

svc = bentoml.Service("iris-classifier", runners=[runner])

@svc.api(input=input_spec, output=JSON())
def predict(input_user: User):
    ...
```
