### ISSUE TITLE
Serving model made extremely hard

### ISSUE THREAD

**Issue by ZdsAlpha** [bentoml/BentoML#2072]
**Is your feature request related to a problem? Please describe.**
I need to install mmdetection library and its easy if i just uninstall previous mmcv reinstall mmcv-full and use two terminal commands... JUST LET ME RUN THOSE COMMANDS ON CONDA ENV. ITS NOT A PIP PACKAGE (Tried installing using pip, doesn't work since i cannot uninstall previous mmcv using requirement file) setup_sh runs outside conda env.

**Describe the solution you'd like**
Just add setup_sh_conda.

**Describe alternatives you've considered**
Nothing works.

**Additional context**

**Comment by parano** [comment]
Looks like a duplication with the discussion here: https://github.com/bentoml/BentoML/discussions/2071
