### ISSUE TITLE
API server SLOs

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2147]
- [ ]  `max-latency` & `timeout`
    - [x] api server timeout
    - [x]  provide both max-latency and timeout in BentoServer config
    - [x]  default `max-latency`:  `10s`
    - [ ]  default `timeout = 1.5 * max-latency`
    - [ ]  assert that `max-latency` < `timeout`
    - [ ]  provide `bentoml serve` CLI arg for `--max-latency`
    - [ ]  target: 90% < max-latency
- [ ]  `--max-request-size` ?
    - [ ]  provide BentoServer config
    - [ ]  default to `10MB`

**Comment by ssheng** [comment]
Should we implement max latency similar to the `deadline` feature in gRPC or have a 10 max latency PER runner?

**Comment by chris-aeviator** [comment]
Happy to test the implementation down the road & provide feedback. I have a 100% reproducible situation where I run into timeouts even though the code runs fine (I see my result in the terminal)

**Comment by nadworny** [comment]
hey @parano , is the timeout config already implemented? I don't see it in the `bentoml serve` yet... is it possible to pass this config somehow differently to the container?

**Comment by frostming** [comment]
Yes, but the `timeout` config on `app` doesn't work currently. We will work on improving this. Thank you.
