### ISSUE TITLE
MLflow pyfunc model can't be loaded

### ISSUE THREAD

**Issue by alexdivet** [bentoml/BentoML#2160]
**Describe the bug**
I can't load a *mlflow* model in the beta version of BentoML 1.0

**To Reproduce**
1. Train & log a pyfunc model to mflow
```
from sklearn import svm, datasets

import mlflow


# Load training data
iris = datasets.load_iris()
X, y = iris.data, iris.target

# Model Training
clf = svm.SVC()
clf.fit(X, y)

# Wrap up as a custom pyfunc model
class ModelPyfunc(mlflow.pyfunc.PythonModel):
    
    def load_context(self, context):
        self.model = clf
    
    def predict(self, context, model_input):
        return self.model.predict(model_input)      
      
# Log model
with mlflow.start_run() as run:
    model = ModelPyfunc()
    mlflow.pyfunc.log_model("model", python_model=model)
    print("run_id: {}".format(run.info.run_id))
```

2. Load it into BentoML
```
import bentoml

model_uri = f"runs:/{run.info.run_id}/model"

tag = bentoml.mlflow.import_from_uri("model", model_uri)

model = bentoml.mlflow.load(tag)
```
3. The model gets successfully stored in the local model store (listed in `bentoml models list`), however the loading `model = bentoml.mlflow.load(tag)` is failing to **AttributeError** `module 'mlflow.pyfunc.model' has no attribute 'load_model'`

**Expected behavior**
Pyfunc model should load without issues

**Screenshots/Logs**
```
Traceback (most recent call last):
  File "sandbox.py", line 11, in <module>
    bentoml.mlflow.load(tag)
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/simple_di/__init__.py", line 124, in _
    return func(*_inject_args(bind.args), **_inject_kwargs(bind.kwargs))
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/_internal/frameworks/mlflow.py", line 85, in load
    return loader_module.load_model(mlflow_folder)  # noqa
AttributeError: module 'mlflow.pyfunc.model' has no attribute 'load_model'
```

**Environment:**
 - OS: MacOS 11.6
 - Python Version Python 3.8.5
 - BentoML Version BentoML-1.0.0a1

**Comment by aarnphm** [comment]
what version of mlflow are you using?

**Comment by parano** [comment]
@alexdivet @aarnphm the new 1.0.0a2 was just released, could you help confirm the issue has been resolved?

**Comment by aarnphm** [comment]
![Screenshot 2022-01-20 at 15 39 52](https://user-images.githubusercontent.com/29749331/150418600-d75d6b01-679d-4fa7-9a66-395262c13569.png)
Works just fine for me

**Comment by alexdivet** [comment]
It works on my end too. Thanks for resolving it 🙏🏻
