### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2163]

**Comment by bojiang** [comment]
current status:

* tracing: implemented but not ensured by ci
* meter: to add exporter
* **century?

**Comment by parano** [comment]
Let also add a test to ensure metrics are collected across multiple processes: https://github.com/bentoml/BentoML/issues/2052

**Comment by bojiang** [comment]
The current status of the metrics part of the Opentelemetry Python sdk is still alpha.

Keep using prometheus_client till the upstream gets ready: #2232

**Comment by parano** [comment]
closing this ticket for now as we have a relatively complete metrics/tracing story, will revisit after `opentelemetry-prometheus-exporter` provides better support for multiprocess applications.
