### ISSUE TITLE
bentoml list not working

### ISSUE THREAD

**Issue by alexdivet** [bentoml/BentoML#2165]
**Describe the bug**
BentoML 1.0 fails to list my services using `bentoml list`

**To Reproduce**
1. Just run `bentoml list`

**Expected behavior**
Get a list of all my services

**Screenshots/Logs**
```
Tag  Service  Path  Size  Creation Time 
Traceback (most recent call last):
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/_internal/cli/click_utils.py", line 129, in wrapper
    track(TRACK_CLI_EVENT_NAME, track_properties)
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/_internal/utils/usage_stats.py", line 94, in track
    return _send_amplitude_event(event_type, event_properties)
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/_internal/utils/usage_stats.py", line 62, in _send_amplitude_event
    event_data = {"api_key": _api_key(), "event": json.dumps(event)}
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/_internal/utils/usage_stats.py", line 42, in _api_key
    if is_pypi_installed_bentoml():
  File "/Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/_internal/configuration/__init__.py", line 61, in is_pypi_installed_bentoml
    is_clean = not version_mod.version_tuple[-1].split(".")[-1].startswith("d")
AttributeError: 'int' object has no attribute 'split'
```

**Environment:**
- OS: MacOS 11.6
- Python Version Python 3.8.5
- BentoML Version BentoML-1.0.0a1

**Comment by alexdivet** [comment]
I installed bentoml `pip install bentoml==1.0.0a1`, I guess the configuration should consider it as a clean install

**Comment by aarnphm** [comment]
can you try `pip install bentoml --pre` instead?

**Comment by alexdivet** [comment]
just tried `pip install bentoml --pre` but it collects the same version:

```
Installing collected packages: bentoml
Successfully installed bentoml-1.0.0a1
```
and I've got the exact same error from `bentoml list`

**Comment by aarnphm** [comment]
I can't seem to replicate this issue, everything works on my end. Can you do this and post the content of the following?
```bash
cd /Users/e056232/opt/miniconda3/lib/python3.8/site-packages/bentoml/ && cat _version.py
```

**Comment by alexdivet** [comment]
```
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.0.0a1'
version_tuple = (1, 0, 0)
```

**Comment by aarnphm** [comment]
Thank you

**Comment by aarnphm** [comment]
@alexdivet I wonder which version of `conda` you are using? Because I cannot seem to replicate this issue on my local machine. I have tested this on pyenv and poetry and everything seems to work as expected.

**Comment by aarnphm** [comment]
This should be fixed with a upcoming releases.

**Comment by alexdivet** [comment]
> @alexdivet I wonder which version of conda you are using? Because I cannot seem to replicate this issue on my local machine. I have tested this on pyenv and poetry and everything seems to work as expected.

I'm using conda 4.10.3 / python 3.8.5

Thanks for having fixed it 🙏🏻
