### ISSUE TITLE
Cannot save Pytorch model

### ISSUE THREAD

**Issue by bui-thanh-lam** [bentoml/BentoML#2185]
**Describe the bug**
I follow the tutorial in https://github.com/bentoml/gallery/tree/main/pytorch, but I got an error below:
I've checked the source code, but I don't know why I couldn't import bentoml.pytorch to use save() method.

**Screenshots/Logs**
![Screenshot from 2022-01-18 10-27-47](https://user-images.githubusercontent.com/47263060/149866078-201a2537-2a4a-4df9-9c19-7931c5cb6680.png)

**Environment:**
 - OS: Google Colab, GPU
 - Python 3.7
 - BentoML 0.13.1

**Comment by parano** [comment]
Hi @bui-thanh-lam - sorry about the confusion, looks like you are running the gallery guide for version 1.0, whereas the installed version is 0.13, I've added a note to the README file to point to the older 0.13 branch of the gallery projects. And if you want to try out the new 1.0 preview release, you can install it via `pip install bentoml --pre`

**Comment by mashirali** [comment]
Still not working with .... pip install bentoml --pre
