### ISSUE TITLE
Support for NLTK

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2194]
**Is your feature request related to a problem? Please describe.**

Support for the NLTK library http://nltk.org

* Runner class for NLTK model
* A hook for downloading NLTK model/data during docker build process or server startup

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aarnphm** [comment]
For those who landed here, BentoML provides support for Custom runners, which you can create for supporting [NLTK](https://docs.bentoml.org/en/latest/concepts/runner.html#custom-runner).
