### ISSUE TITLE
Change layers order in Dockerfile.template due permission issues on compile

### ISSUE THREAD

**Issue by pashtet04** [bentoml/BentoML#2199]
**Is your feature request related to a problem? Please describe.**
I am building Container image from BentoML Service bundle with Argo Workflows (Kubeflow) into GKE and always got an error at
`RUN chmod +x ./env/docker/entrypoint.sh`

```bash
...
INFO[0056] USER bentoml                                 
INFO[0056] cmd: USER                                    
INFO[0056] No files changed in this command, skipping snapshotting. 
INFO[0056] RUN chmod +x ./docker-entrypoint.sh          
INFO[0056] cmd: /bin/sh                                 
INFO[0056] args: [-c chmod +x ./docker-entrypoint.sh]   
INFO[0056] util.Lookup returned: &{Uid:1034 Gid:1034 Username:bentoml Name: HomeDir:/home/bentoml} 
INFO[0056] performing slow lookup of group ids for bentoml 
INFO[0056] Running: [/bin/sh -c chmod +x ./docker-entrypoint.sh] 
error building image: error building stage: failed to execute command: starting command: fork/exec /bin/sh: permission denied
F0121 10:26:36.836271      21 main.go:50] Failed to execute component: exit status 1
Error: exit status 1
```

**Describe the solution you'd like**
Switch lines at Dockerfile.template to 
```docker
RUN chmod +x ./env/docker/entrypoint.sh
USER bentoml
```

**Describe alternatives you've considered**
Is at any way to fix order of layers in generated Dockerfile after `save_to_dir`?

**Comment by parano** [comment]
Hi @pashtet04, may I ask what is the base docker image you are using? is it the default one from BentoML?

**Comment by pashtet04** [comment]
For building Container image into Kubernetes I use `gcr.io/kaniko-project/executor:debug`
Base image `FROM bentoml/model-server:0.13.1-py38`
