### ISSUE TITLE
model on cpu/gpu (ver.1.0.0a2)

### ISSUE THREAD

**Issue by jjerry-k** [bentoml/BentoML#2215]
**Is your feature request related to a problem? Please describe.**
I used pytorch 1.10, bentoml 1.0.0a2.
I trained a model using GPU and save using bentoml.pytorch.save.
When I load a model using CPU, runner didn't use CPU. 

If I saved CPU model, runner only uses CPU.
If I saved GPU model, runner only uses GPU.

**Describe the solution you'd like**
Need to modify this line [link](https://github.com/bentoml/BentoML/blob/9d803c30d0576df872d48d72648f6eab2027d345/bentoml/_internal/frameworks/pytorch.py#L95) to set a model to the desired device using device_id.
ex) `return cloudpickle.load(file).to(torch.device(device_id))`

**Describe alternatives you've considered**
Nope

**Additional context**
Original code & Test result
![before_code](https://user-images.githubusercontent.com/25097024/151182606-3be86939-fbf5-4642-ba37-3afeaf120f7e.png)
![before](https://user-images.githubusercontent.com/25097024/151182600-7a0a41f3-5563-4a87-8588-471eecfde314.png)

Modified code & Test result
![after_code](https://user-images.githubusercontent.com/25097024/151182796-3f461195-7c87-4ca3-971e-806b301df0db.png)
![after](https://user-images.githubusercontent.com/25097024/151182788-95b894a4-e21d-4928-9cc3-cc87b7724db4.png)

**Comment by larme** [comment]
Thank you for reporting the issue.

We will push a quick fix for this problem.

**Comment by aarnphm** [comment]
we merged this on our main branch. Can you try installing `1.0.0a3`? Let me know if you still have any other question.

**Comment by jjerry-k** [comment]
@aarnphm 

I tried model loading across device_id.
First of all, I have no problem about model. (bentoml.pytorch.load)
But, I have another problem in loading runner. (bentoml.pytorch.load_runner)
I'll report issue about it.
Thank you!
