### ISSUE TITLE
Standardize packaging of Tokenizer in NLP use cases

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2217]
Problem statement: 

Currently there are a few ways to include a tokenizer in a BentoML service in ver 1.0:
1. Load directly from a file and use it in the API service code
2. Load directly from a file and use it in a custom Runner class
3. Bundle it into the model class(e.g. for Pytorch), in which case the tokenizer will be executed on the same Runner as the model
4. Create a custom Model and custom Runner class, which stores the tokenizer together with the model

Non of these methods are easy for a beginner to adopt, we should either provide official guide on the recommend approach, or build an abstraction layer and give user some of these options.

**Comment by aarnphm** [comment]
I would prefer abstraction layer over documentation, since it seems to be more powerful and versatile. I will look into it more

**Comment by cateto** [comment]
I am a beginner. I need to more easy way. 
But I'm here now.
First, I pack tokenizer into a pickleArtifact. like number 1 you said. 
Second, outside of bentoml env, PyPI packing and load tokenizer.
I wonder. Does it have any problem?

**Comment by parano** [comment]
@cateto that's exactly what we suggest users to do in version 0.13, there's no problem with it. In BentoML 1.0, we introduced both model store and Runner concept, which gives user more flexible in terms of the serving architecture and performance tuning, but currently lacks a standard way of doing it. We want to allow users to version the tokenizer together with the model entry in the model store, and allow user to easily choose where to execute the tokenizer logic, e.g. in the api server worker, the model runner worker, or in its own runner worker.  We have a WIP proposal, will update here soon!

**Comment by ssheng** [comment]
BentoML 1.0 introduced saving `custom_object`s alongside the models, see https://docs.bentoml.org/en/latest/concepts/model.html#save-a-trained-model.
