### ISSUE TITLE
bentoml.pytorch.load_runner using cpu/gpu (ver 1.0.0a3)

### ISSUE THREAD

**Issue by jjerry-k** [bentoml/BentoML#2230]
**Describe the bug**
Hi, I'm Jerry!
Thank you for the quick response to the last report!
After that, I have another problem.

First of all, This is my model code.
```python
class Model(nn.Module):
    """
    Thi is example code.
    Customize your self.
    """
    def __init__(self, base_model_name="alexnet", num_classes=10, freeze=True):
        super(Model, self).__init__()

        assert base_model_name in available_models, f"Please Check available pretrained model list at https://rwightman.github.io/pytorch-image-models/results/"
        
        self.base_model_name = base_model_name
        self.num_classes = num_classes
        self.freeze = freeze
        
        self.model = timm.create_model(self.base_model_name, 
                                        pretrained=True, 
                                        num_classes=num_classes)
        
        if freeze: 
            for layer_name, ops in self.model.named_children():
                if layer_name != 'classifier':
                    ops.requires_grad = False
        
    def forward(self, x):
        x = self.model(x)
        return x

    def predict(self, x):
        self.eval()
        with torch.no_grad():
            raw_output = self(x)
            _, pred = torch.max(raw_output, 1)
            return pred
```

When I use bentoml.pytorch.load, `predict function in model` is working in every case.
![case_cpu](https://user-images.githubusercontent.com/25097024/151649478-4766f852-e525-4aa6-8301-3b5a417cb65c.png)
![case_gpu](https://user-images.githubusercontent.com/25097024/151649482-cd44db02-4378-4677-9dff-61a9580b58c6.png)

When I use bentoml.pytorch.load_runner with cuda, predict function is not working in runner.
Because of DataParallel model..
[code link](https://github.com/bentoml/BentoML/blob/1efd77c609b3fc2e153436c57db9b3707608c894/bentoml/_internal/frameworks/pytorch.py#L259)

This are example images
![runner_case_cpu](https://user-images.githubusercontent.com/25097024/151649822-689fce1f-58a7-4762-be17-307eb6cbe831.png)
![runner_case_gpu](https://user-images.githubusercontent.com/25097024/151649826-996862b2-ff9c-4adb-9ce7-629853703acf.png)

**Comment by jjerry-k** [comment]
As I know, Data parallel model can't use custom method like predict!

**Comment by aarnphm** [comment]
I'm wondering why is your model class need both `forward` and `predict` function? Usually you should only implements `forward` function. the `predict` logics should be done separately?

**Comment by jjerry-k** [comment]
As you said, we usually should only implements `forward function`. 
Of course, I usually don't implement predict function.
The reason I report the issue is because of [this example](https://github.com/bentoml/gallery/tree/main/pytorch).
In this example, predict function is implemented.
and I couldn't think DP model in case of gpu.

**Comment by aarnphm** [comment]
@larme

**Comment by jjerry-k** [comment]
I have a question!

Can I ask about why use data parallel model in case of cuda? (even when gpu is only one)

**Comment by larme** [comment]
@jjerry-k thanks for the detailed bug report!

In our gallery example we implement a `predict` method to demonstrate the flexibility of the framework. However this seems to add more confusions. I will reorganize this example a little bit.

We use data parallel model in case multiple GPUs are available. Like you pointed out this part's logic can be optimized and we will do it in a later fix.
