### ISSUE TITLE
feat: decorator for building custom Runner

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2248]
**Is your feature request related to a problem? Please describe.**

Currently for user to create a new Runner, it requires creating a new class inheriting from the base `Runner` or `Simple` runner class:

```
class MyCustomRunner(Runner):

    def _setup(self):
       ...
  
    def _run_batch(self, *args, **kwargs):
       ...  # process a batch input

class MyCustomSimpleRunner(SimpleRunner):
    def _setup(self):
       ...
  
    def _run(self, *args, **kwargs):
       ...  # process one single input

runner_1 = MyCustomRunner('runner_1')
runner_2 = MyCustomSimpleRunner('runner_2')

svc = bentoml.Service('my_service', runners=[runner_1, runner_2])

@svc.api(input=Text(), output=JSON())
def predict(input_text: str):
      ...
```

This works well for complex runners that requires defining an initialization process, or create custom DataContainer types for custom batching behavior. Although it is fairly verbose for a simple Runner step.

**Describe the solution you'd like**

We'd like to propose a simpler syntax for users to implement custom runner using decorators, similar to the BentoML service definition API, here's a simple example:

```python
import bentoml
from bentoml.io import Text, NumpyNdarray

@bentoml.Runner
async def fetch_features(user_ids: List[str]) -> List[User]:
      async with aiohttp.ClientSession() as session:
          async with session.post('http://my_feature_store') as response:
               return await response.json

@bentoml.SimpleRunner
def feature_transform(raw_data: np.ndarray) -> np.ndarray:
         return my_transform_func(raw_data)

model_runner = bentoml.tensorflow.load_runner('my_model:latest')

svc = bentoml.Service('my_service', runners = [fetch_features, feature_transform, model_runner])

```

Using runner sync API:
```python
@svc.api(input=Text(), output=NumpyNdarray())
def predict(user_id: str):
       user_profile = fetch_features.run(user_id)
       features = feature_transform.run(user_profile)
       return model_runner.run(features)  
```
Equivalent async implementation:

```python
@svc.api(input=Text(), output=NumpyNdarray())
async def predict(user_id: str):
       user_profile = await fetch_features.async_run(user_id)
       features = await feature_transform.async_run(user_profile)
       return await model_runner.async_run(features)  
```

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
Will incorporate this in our ongoing new design for declaring runners

**Comment by chlee1016** [comment]
Hi @parano ! I think it is very useful feature for BentoML users.


In this case, it seems that the reason for using `await fetch_features.async_run(user_id)` is to fetch features for each `user_id` from the batched input `user_ids`.
As I understand, when processing batch input inside `_run_batch`, even if it is implemented using the `for` statement **synchronously**, it can be processed **asynchronously**.

Is my understanding correct?

**Comment by parano** [comment]
@chlee1016 yes that's right, for IO intense Runner used for fetching features - ideally you would want a batch API for fetching a batch of features at once. But if that's not available, you can only fetch one item at once, I'd recommend sending all requests at once via a for loop, but don't use `await` on each `async_run` call, instead use `asyncio.gather`to wait for all of futures to come back.

**Comment by parano** [comment]
@chlee1016 we are working on a new iteration of the Runner internal design, which will bring more options for customization to Runner, it's getting close to being released in the coming week, you can check it out in the runner-1.0 branch here: https://github.com/bentoml/BentoML/tree/runners-1.0
