### ISSUE TITLE
framework: ``import_from_huggingface_hub`` decoupling

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#2249]
**Is your feature request related to a problem? Please describe.**
Current implementation of `import_from_huggingface_hub` uses `AutoModel` API from HuggingFace to detect the correct type of model to save
We include a concept call `lm_head` (which directly ported from huggingface) to determine which type of `AutoModel` to use. For example a Roberta model loaded from `AutoModel` is different than a Roberta model loaded from `AutoModelForSequenceClassification`

There aren't any way for us to explicitly determine which type of model a usecase may use from `import_from_huggingface_hub` could be, hence the `load_autoclass` (described below) implementation. 

The current API users can use:
```python
import bentoml

LM_HEAD = "sequence-classification"

tag = bentoml.transformers.import_from_huggingface_hub("j-hartmann/emotion-english-distilroberta-base", lm_head=LM_HEAD)
```
This makes it difficult for users to know what`lm_head` to use. To determine to LM of the above mentioned model, one have to go to [model-card page](https://huggingface.co/j-hartmann/emotion-english-distilroberta-base) and then see how they would implement a pipeline. Since in this case the pipeline is a `text-classification`, if you work with transformers before you will know that this is a `sequence-classification` tasks alias, hence the `LM_HEAD`. 

I would love to have some more feedback on this API and how we can improve it and make it easier for users to use

PS: our hope for this API is to directly download all the required files to BentoML modelstore instead of loading it from `from_pretrained()` and the save the model via `save_pretrained`. We tried to directly download the required files before but it wouldn't work for a lot of test cases.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Current implementation of a autoclass detection works as follow:
```python
_FRAMEWORK_ALIASES: t.Dict[str, str] = {"pt": "pytorch", "tf": "tensorflow"}

_AUTOMODEL_PREFIX_MAPPING: t.Dict[str, str] = {
    "pytorch": "AutoModel",
    "tensorflow": "TFAutoModel",
    "flax": "FlaxAutoModel",
}

_AUTOMODEL_LM_HEAD_MAPPING: t.Dict[str, str] = {
    "base": "",
    "pre-training": "ForPreTraining",
    "causal": "ForCausalLM",
    "masked": "ForMaskedLM",
    "seq2seq": "ForSeq2SeqLM",
    "sequence-classification": "ForSequenceClassification",
    "question-answering": "ForQuestionAnswering",
    "token-classification": "ForTokenClassification",
    "multiple-choice": "ForMultipleChoice",
    "next-sentence-prediction": "ForNextSentencePrediction",
    "image-classification": "ForImageClassification",
    "audio-classification": "ForAudioClassification",
    "ctc": "ForCTC",
    "speech-seq2seq": "ForSpeechSeq2Seq",
    "object-detection": "ForObjectDetection",
}
def load_autoclass(framework: str, lm_head: str) -> "_BaseAutoModelClass":
    framework_prefix = (
        _FRAMEWORK_ALIASES[framework] if framework in _FRAMEWORK_ALIASES else framework
    )
    class_inst = f"{_AUTOMODEL_PREFIX_MAPPING[framework_prefix]}{_AUTOMODEL_LM_HEAD_MAPPING[lm_head]}"  # noqa
        return getattr(import_module("transformers"), class_inst)
```
`framework` will be determined automatically from huggingface API, and user only have to provide this `lm_head`.

All current work can be tracked here: #2250

**Comment by parano** [comment]
Discussed offline, we will hide the `bentoml.transformers.import_from_huggingface_hub` api for now, revisit after 1.0 release
