### ISSUE TITLE
Convert Bento / Model metadata to basic python objects

### ISSUE THREAD

**Issue by sauyon** [bentoml/BentoML#2258]
All metadata should be relatively easily representable in both the web interface and the CLI. To support this, I think the only supported metadata types should be `dict`, `list`, `str`, `int`, and `Float`.

When a user creates a model or bento with associated metadata, that metadata will be converted as much as possible into those types. e.g. if the user passes an `ndarray`, it will be converted to a standard python list before being stored.

/cc @parano for thoughts

**Comment by parano** [comment]
I think this is done in the runner-1.0 branch now?

**Comment by sauyon** [comment]
This one should be done, closing.
