### ISSUE TITLE
Uploading Model to Yatai

### ISSUE THREAD

**Issue by mlopezfernandez** [bentoml/BentoML#2269]
**Describe the bug**

I have managed to create a model and even dockerize the service with the information specified in the guides.
The next step was to use Yatai to serve different models. Currently I have managed to start the service and create a token with which I make the authentication. The problem comes when I try to upload the model that returns the following error:

![image](https://user-images.githubusercontent.com/17619458/153859685-f5936ec7-8bfd-441a-b4ca-88b2b6d99e46.png)

I may have done something wrong. Any ideas?

**To Reproduce**

After having the model available:
![image](https://user-images.githubusercontent.com/17619458/153860076-5bf789cb-1a2c-480b-8560-4bd1f6c5ebe3.png)

Login against the yatai service:
![image](https://user-images.githubusercontent.com/17619458/153860216-17f16e86-8900-4ac4-b684-03391dd3576f.png)

Upload model:
![image](https://user-images.githubusercontent.com/17619458/153860331-91b37e21-27f9-4535-952d-3b88b0bd583b.png)

**Environment:**
 - OS: Ubuntu 20.04
 - Python Version 3.8
 - BentoML Version 1.0.0a3

**Comment by aarnphm** [comment]
cc @yetone

**Comment by parano** [comment]
Hi @mlopezfernandez - may I ask how/where did you deploy yatai? Is it a local Minikube or a managed K8S service? And did you modify the helm chart for installing Yatai?  It looks like Yatai is expecting the Minio installation in the same cluster but failed to query its credentials.

**Comment by mlopezfernandez** [comment]
Hi @parano I am deploying yatai locally using Minikube. I have not modified the helm chart and as you indicate it is possible that the MinIO installation is missing in the same cluster. If I check the containers in the cluster, the MinIO container is not found as you can see in the image. Would it be necessary to add it manually or would I have to specify something else in the yatai installation. Thanks you for answering.

![image](https://user-images.githubusercontent.com/17619458/154028003-52d4c980-55d8-487f-9074-9f372533d26c.png)

**Comment by yetone** [comment]
@mlopezfernandez Is the cluster without a load balancer? If you are using minikube, you should start a load balancer manually with this command: `sudo minikube tunnel`

**Comment by parano** [comment]
Thanks for the feedback @mlopezfernandez - we will improve the documentation to make this steps more clear. What happened was that the MinIO installation can not proceed until there's a working load-balancer in the cluster. You should be able to check the progress by:

```bash
kubectl -n yatai-operators logs -f deploy/deployment-yatai-deployment-comp-operator
```

In the case of Minikube, running `minikube tunnel` will unblock that process and allow Minio to be installed properly.
