### ISSUE TITLE
Restore a runnable quickstart

### ISSUE THREAD

**Issue by marcindulak** [bentoml/BentoML#2284]
**Is your feature request related to a problem? Please describe.**

When reporting bentoml issues it is useful to have a runnable code template.
In the past there used to be a directory https://github.com/bentoml/BentoML/tree/legacy-master/guides/quick-start, which contained python code that was ready to run. Currently it appears that the code has been moved into the rst files https://github.com/bentoml/BentoML/tree/main/docs/source, and the quickstart is not runnable without copy/pasting.

**Describe the solution you'd like**

Keep all the files necessary to install and execute the quickstart as code, and include them in the rst using https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude

See an example https://gitlab.com/ase/ase/-/blob/master/doc/tutorials/atomization.rst rendered into https://wiki.fysik.dtu.dk/ase/tutorials/atomization.html

**Describe alternatives you've considered**

**Additional context**

Having runnable examples in the documentation allows it to be tested.

**Comment by aarnphm** [comment]
Hi @marcindulak, we have decided that our quick-start guide are now living under [bentoml/gallery/quickstart](https://github.com/bentoml/gallery/tree/main/quickstart). The reason why we are doing this is that we want users to also explore our gallery project (we are currently working hard on that) and shows what bentoml can do. 

Do you think that it is still beneficial for bentoml to have an `example` directory under bentoml main github? We find that by separating it into a gallery repo which makes it a lot easier to maintain and adding new features.

**Comment by marcindulak** [comment]
I think that the gallery examples written as sphinx' rst + literalinclude of the source code would help the quality of the examples going forward, especially if there will be many examples. I imagine that scheduled, functional tests of the examples could be setup against the corresponding bentoml release branches, and the gallery, versioned by releases, could be hosted e.g. at https://gallery.bentoml.org/. I think if gallery maintains working examples, and it's sufficiently promoted and easy to find, then an example directory may be unnecessary under the bentoml repo.
