### ISSUE TITLE
Display Hosting URL In Production

### ISSUE THREAD

**Issue by splch** [bentoml/BentoML#2287]
**Describe the solution you'd like**
When running `bentoml serve tag`, the hosted URL is printed to console `INFO     [dev_api_server] Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)` but when running `bentoml serve tag --production`, that message isn't shown.

The solution I'd like would be showing the hosted URL.

**Additional context**

Standard:

> ![Screen Shot 2022-02-17 at 4 10 30 PM](https://user-images.githubusercontent.com/25377399/154592899-73441598-34df-4baf-b110-7ab1af219f5b.png)

Production:

> ![Screen Shot 2022-02-17 at 4 11 28 PM](https://user-images.githubusercontent.com/25377399/154592982-1d2d8f09-390d-4e92-963d-72635ef49007.png)

**Comment by ssheng** [comment]
Seems like this was caused by how we start the Uvicorn server. We changed from calling `uvicorn.run()` to calling `uvicorn.Server().run()` so the Uvicorn supervisor is not used.

https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/server/cli/api_server.py#L64-L69

**Comment by ssheng** [comment]
Discussed with @bojiang in a quick sync. We will unify the startup logic of Unicorn server the same way as how we startup `--production` and configures Circus to print the address line.

**Comment by ssheng** [comment]
PR https://github.com/bentoml/BentoML/pull/2311 is going to address this.
