### ISSUE TITLE
SDK: service.asgi_app not work without `PROMETHEUS_DIR`

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#2290]
**Describe the bug**

https://github.com/bentoml/aws-lambda-deploy/issues/24

In the current version, `service.asgi_app` only works with the PROMETHEUS_DIR set and exists.

**To Reproduce**

**Expected behavior**

1. decouple asgi_app with that env var
1. running standalone `service.asgi_app` is covered in e2e tests

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by parano** [comment]
@bojiang I believe this is fixed by now?

**Comment by ssheng** [comment]
https://github.com/bentoml/BentoML/pull/2526 should have address this issue.
