### ISSUE TITLE
``--quiet`` actually doesn't quiet logs

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#2316]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: MacOS Monterey
 - Python Version Python 3.9.7
 - BentoML Version git+https://github.com/bentoml/BentoML

**Additional context**

**Comment by cateto** [comment]
it still happens.

```
bentoml==1.0.4
```

**Comment by aarnphm** [comment]
Are you setting `BENTOML_DEBUG` environment variable?
