### ISSUE TITLE
BentoML fastai support

### ISSUE THREAD

**Issue by WarriorMmb** [bentoml/BentoML#2332]
Fastai is a widely used framework in research community. So please add the support and documentation for fastai. Waiting for it from long time.

**Comment by timliubentoml** [comment]
Thanks for the suggestion! We definitely like to add support for frameworks that people like to use. In order to get a little more clarity, could you give me a high (or low if you'd like) level example of how you would like to use the integration with bentoml?

**Comment by WarriorMmb** [comment]
I think it will have a pitty similar solution like pytorch but we have to pack learner in this case. @timliubentoml is there any progress from your end. I can help if you need any.

**Comment by ssheng** [comment]
@WarriorMmb fastai progress can be track in this PR. fastai support will be included in the 1.0 release.

**Comment by aarnphm** [comment]
Hi @WarriorMmb the implementation for fast ai has been finished. The documentation will get merged shortly.

**Comment by dnth** [comment]
Thank you! That's really good news!

**Comment by aarnphm** [comment]
docs will be tracked at https://github.com/bentoml/BentoML/pull/2649
