### ISSUE TITLE
AWS Lambda Deployment: Internal Server Error: No module named BentoML

### ISSUE THREAD

**Issue by Mu7ammad** [bentoml/BentoML#235]
**Describe the bug**
Running through the Scikit-learn demo "IrisClassifier" and deploying to AWS Lambda. The deployment is a success and it shows in the Functions dashboard in AWS. But using Postman to test it returns an internal server error, and using the online test evens in AWS Lambda I can see the error message: "Unable to import module 'handler': No module named 'bentoml'",

**To Reproduce**
Installation of BentoML 0.3.1 /Serverless 1.48.4 is done on macOS Mojave Python 3.7
Running IrisClassifer demo in quick-start-guide

**Expected behavior**
Running the quick-start-guide successfully

**Screenshots/Logs**
![スクリーンショット 2019-07-30 午前6 28 42](https://user-images.githubusercontent.com/309605/62100870-97e7d380-b293-11e9-83cf-098f3b5e6a8f.png)

**Environment:**
 - OS: MacOS 10.14.
 - Python/BentoML Version [Python 3.7.3, BentoML-0.3.1]

Thanks!

**Comment by yubozhao** [comment]
Hi thank you for reporting this. 

I will look into it tmw and get you an update about it soon

**Comment by yubozhao** [comment]
hi @Mu7ammad 
Thank you for reporting.

I looked into this issue.  It is an issue with the way we set our env parameters.
The way to use it is as of now is located at this example notebook [Deploy with Serverless](https://github.com/bentoml/BentoML/blob/master/examples/deploy-with-serverless/deploy-with-serverless.ipynb)

Since you brought up this to our attention, we have improved this and made it more explicit to define environments. In the next release, you can use the `pip_dependencies` parameter along with others.
```python
@env(pip_dependencies=['numpy', 'pandas', '...'])
class MyService(BentoService)
	....
```

**Comment by Mu7ammad** [comment]
Follow up: So I tried version 0.3.4 with same example and environment, and it indeed seems to package the dependencies this time, but then when I run the lambda function I get internal server error, and from the logs it says:

"Error creating bentoml home dir '/home/sbx_user1051/bentoml': No such file or directory"

It's thrown from executing: bentoml/config/__init__.py , line 61 with exception: "Error creating bentoml home dir"

It seems can't find the home directory in the sandbox, so what do you think the reason for that?

Thanks

![スクリーンショット 2019-08-28 午前0 14 03](https://user-images.githubusercontent.com/309605/63811900-04a0cd00-c929-11e9-99c0-079590812cdb.png)

**Comment by parano** [comment]
@Mu7ammad  thanks for reporting this, looks like it's an issue related to our new config implementation and limited disk access in AWS lambda environment https://docs.aws.amazon.com/lambda/latest/dg/limits.html  - I will work on a fix
