### ISSUE TITLE
Running production server with multiple workers does not increase the CPU utilization

### ISSUE THREAD

**Issue by andreea-anghel** [bentoml/BentoML#2355]
I'm running a production server that serves a sklearn (iris_classifier) model first with 1 BentoML worker and then with 2 BentoML workers (the rest of the system configuration stays the same for both scenarios). 
```
Scenario 1:
bentoml_workers = 1
sklearn_predict_n_jobs = 1
cpus = 1 (1 CPU, 2 threads)

Scenario 2:
bentoml_workers = 2
sklearn_predict_n_jobs = 1
cpus = 1 (1 CPU, 2 threads)
```

The 2-worker scenario does not show any change in the system CPU utilization when compared to the single-worker scenario. I can provide more info on how to reproduce this behavior, but just wanted first to ask if this is an expected behavior. 

If Scenario 1 would give an average CPU utilization of 30%, isn't Scenario 2 expected to get about 60% average CPU utilization (assuming both scenarios can fully sustain the incoming client rate)?

Note: The number of workers is set via the `bentoml_configuration.yml` file (setting `workers` to 1 or 2)

BentoML version: 1.0.0a6
OS: Ubuntu 20.04
Hardware: x86

**Comment by andreea-anghel** [comment]
Is the number of workers used at runtime set here?

https://github.com/bentoml/BentoML/blob/d37aa9e49fd6a3273eb73701eba26f5bb1eb0055/bentoml/_internal/server/__init__.py#L138

If so, if I set the number of workers to something >1 via the configuration file, the `app_workers` is still set to 1.

**Comment by timliubentoml** [comment]
@andreea-anghel How are you measuring CPU utilization? Generally I would think that if you're running on 1 CPU, even if you increase the number of workers, you'd still get the same throughput given that it's 1 cpu. Maybe even worse if it's context switching between the 2 workers.

When you run a "ps" do you see more than 1 process running when increasing the number of workers?

**Comment by andreea-anghel** [comment]
@timliubentoml I'm measuring the CPU utilization using psutil cpu_percent. 

I'm running the server as follows: 
`bentoml serve service:latest --production` and I set the workers parameter to 2 in the `bentoml_configuration.yaml` file. 
Is this the correct way of setting the number of workers?

**Comment by timliubentoml** [comment]
@andreea-anghel Right now the way that you specify the number of workers is in design review. Our idea was that you can specify a strategy like "Process per cpu". You could potentially configure the workers explicitly, but that would require more customization where you would create your own custom runner.

With a 6 CPU machine, would you be looking at creating 6 workers?

**Comment by ssheng** [comment]
@andreea-anghel spawning multiple API server workers does not directly imply that the CPU utilization will multiply. Spawning multiple API server workers allow the service to utilize more system resources with inbound traffic.
