### ISSUE TITLE
Pytorch Runner fails to serve models because resource_quota is no longer used

### ISSUE THREAD

**Issue by timliubentoml** [bentoml/BentoML#2366]
**Describe the bug**

This line in the runner does not evaluate properly: https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/common/pytorch.py#L72

We then get a "set_num_threads expects a positive integer":

                             File "/opt/conda/lib/python3.9/site-packages/bentom
                           l/_internal/frameworks/common/pytorch.py", line 84,
                           in _configure
                               torch.set_num_threads(self._num_threads)
                           RuntimeError: set_num_threads expects a positive
                           integer

For the entire stack trace see: https://bentoml.slack.com/archives/CKRANBHPH/p1647887573742579?thread_ts=1647536520.735299&cid=CKRANBHPH

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by aarnphm** [comment]
cc @larme

**Comment by ssheng** [comment]
Fixed in release 1.0.0.
