### ISSUE TITLE
Error while saving the bentoml 

### ISSUE THREAD

**Issue by OriAlpha** [bentoml/BentoML#2382]
Hello, 
i have recently found error while saving bentoml model, specfically in following function. 
```
    def save(self, yatai_url=None, version=None, labels=None):
        '''
        Save and register this BentoService via BentoML's built-in model management
        system. BentoML by default keeps track of all the SavedBundle's files and
        metadata in local file system under the $BENTOML_HOME(~/bentoml) directory.
        Users can also configure BentoML to save their BentoService to a shared Database
        and cloud object storage such as AWS S3.

        :param yatai_url: optional - URL path to Yatai server
        :param version: optional - save with version override
        :param labels: optional - labels dictionary
        :return: saved_path: file path to where the BentoService is saved
        from bentoml.yatai.client import get_yatai_client
        '''

        yc = get_yatai_client(yatai_url)

        return yc.repository.upload(self, version, labels)
```
while the function is trying to return saved model path, i am getting error as 
`AttributeError: 'torch.dtype' object has no attribute '__module__'` 

If i disable this return does it have any impact ?? or any way to fix this issue
i am using pytorch=1.9.0 maybe (its because of this version but not sure)

**Comment by OriAlpha** [comment]
I tried to track the issue and found out 
`cloudpickle.dump(self._model, open(self._file_path(dst), "wb"))` is creating issue

**Comment by timliubentoml** [comment]
Hello! Yes I see what you are saying. I think I was a little confused because you are using 0.13. Have you tried to save with 1.0 yet? In 1.0 we use the torch.save method to save the model: https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/pytorch.py#L166

It still specifies to use cloudpickle, but I'm wondering if their new implementation handles this case. If so you could potentially fix it for the old version... Though making that fix would probably necessitate a change of the load() method as well which would potentially introduce regressions for any model which was saved the previous way

**Comment by timliubentoml** [comment]
Oh yea, sorry about that. 1.0 is definitely not backwards compatible, you'd have to look at upgrading everything which you may not have time for. Maybe just look at seeing if your model saves right? you can do a bentoml.pytorch.save("modelname", model) without all of the artifact imports

**Comment by OriAlpha** [comment]
i checked quickly, yes i can save model by 
`bentoml.pytorch.save("dummy", model)`
result :  dummy:pwl7e3vrh6abxg7k

**Comment by timliubentoml** [comment]
oh, cool. Yea, maybe it's worth thinking about upgrading then.

Can you do:

model = bentoml.pytorch.load("dummy:latest")
model.predict(some_input)

And get a valid result? If so, I think that approach works

**Comment by aarnphm** [comment]
Hi @OriAlpha, BentoML recently put out 1.0.0rc0 for preview, Can you try out the latest version and then report back to us if you still have any issues? Thank you

**Comment by yubozhao** [comment]
@OriAlpha Let us know if your issue is not resolved or need additional helps.
