### ISSUE TITLE
Support custom content types for I/O descriptors

### ISSUE THREAD

**Issue by sauyon** [bentoml/BentoML#2387]
We may want to support content types other than the default for these descriptors.

I think there are two options here:
 - add an additional parameter to the I/O descriptors which allows users to customize what content type they would like to accept, or
 - add a field or method `content_type` to the I/O descriptor API, which users can then override to manually set which content types they would like to accept.

I'm leaning somewhat towards the latter, though I also feel that we may want to ignore the content type for specifically the `File` I/O descriptor, as that should probably be somewhat of a catch-all for I/O descriptors we may want to implement in the future.

See also: https://github.com/bentoml/BentoML/discussions/2381

**Comment by parano** [comment]
Notes:
* Will allow content_type to be anything
* `input.name` should return the file name when sending File with `form-data`
* generate OpenAPI schema for both octet-stream and form-data
* future work: add audio/video IO descriptor

**Comment by parano** [comment]
This will be supported in the upcoming new IO descriptor design!

**Comment by HaithemH** [comment]
> Notes:
> 
> * Will allow content_type to be anything
> * `input.name` should return the file name when sending File with `form-data`
> * generate OpenAPI schema for both octet-stream and form-data
> * future work: add audio/video IO descriptor

Are audio/video supported now?
