### ISSUE TITLE
Support for Using model from Cloud Storage Mounted into the Container for Serving

### ISSUE THREAD

**Issue by sarmientoj24** [bentoml/BentoML#2411]
I would like to know if BentoML supports something similar to:
1. mounting a Cloud Storage (e.g. GCS) into the container upon starting,
2. use the model inside the cloud storage instead of that which comes within the BentoML containerized image

**Comment by timliubentoml** [comment]
Hi @sarmientoj24! We have a couple different ways to do this. 

1. I haven't tested this, but the library that "bentoml import/export" uses, which is the fs library, has support for GCP as I understand it here: https://pypi.org/project/fs-gcsfs/ 

You'll have to add the library and use the gcp prefix that they specify, but I think that should work.

2. You could implement your own custom runner. Right now we don't have the doc for writing your custom runner, working on it now. But you can see how we create runners for each of our frameworks. 

Here's a pretty straightforward example: https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/sklearn.py

You'll need to extend the "BaseModelRunner" and then in __init__, you would download the model from gcp and then in run_batch, you would call the model.predict.

**Comment by ssheng** [comment]
@sarmientoj24 Please look into the suggestion from @timliubentoml, I think it will work for first case listed. We need work on getting this pattern better documented. For second case, we have no out-of-box support yet but it can be done through our custom runners (https://docs.bentoml.org/en/latest/concepts/runner.html#custom-runner). We'd like to learn more about the use case you have in mind to better design a solution.
