### ISSUE TITLE
Error while importing bentoml

### ISSUE THREAD

**Issue by su-park** [bentoml/BentoML#2412]
Hello,
I am recently introduced BentoML and am quick-touring [Getting Started page](https://docs.bentoml.org/en/latest/quickstart.html#getting-started-page) of your official document.

I feel sorry it didn't work out as you described.

**Describe the bug**
I tried to `import bentoml` and get error message like belows.

```
ModuleNotFoundError: No module named 'attrs'
```
and installed the package `attrs` manually using pip/conda successfully but failed to import.

Actually I can manage to import it when I edited package name and function call from `attrs` to `attr` in files under the folder `bentoml/_internal/utils/analytics/`

**Environment:**
 - OS: [continuumio/anaconda3](https://hub.docker.com/r/continuumio/anaconda3)
 - Python Version: Python 3.9.7
 - BentoML Version: bentoml-1.0.0a7

**Comment by timliubentoml** [comment]
Hi @su-park! Thank you for reporting this. I actually saw this myself in the latest release as well. Talking with the team about it right now.

In the meantime, the solution for this issue is to install the attr library like this:

`pip install attrs -U`
