### ISSUE TITLE
Docs: write "advanced guides -> logging"

### ISSUE THREAD

**Issue by sotte** [bentoml/BentoML#2413]
I know that bento is in the transition period to 1.0, but I with there was already documentation for the [logging feature](https://docs.bentoml.org/en/latest/guides/logging.html) (especially prediction logging) like there was for [0.13](https://docs.bentoml.org/en/0.13-lts/guides/logging.html).

So this is just a "reminder ticket" that the docs have to be written, and maybe people up vote it :+1: if they think it's important.

**Comment by timliubentoml** [comment]
Thanks @sotte! I've been working on documentation for the last few days. I'll prioritize this one for this week.

**Comment by timliubentoml** [comment]
Hi @sotte! I have an initial draft here if you'd like more information: https://github.com/bentoml/BentoML/blob/727d54fe115847fd6529c308de10a4b616070387/docs/source/guides/logging.rst

We took a pretty different approach to logging than in 0.13. Would definitely like feedback if you have it. We have a new format and are using RichHandler which is way better for readability. Also have implemented the OpenTelemetry standard which is pretty cool as well.

Based off of 0.13 experience, we're also a lot more opinionated in this new version whereas in the previous version it sort of left everything up to the user to implement

**Comment by sotte** [comment]
I should have time to check it out within the next two weeks. Looking forward to it.
