### ISSUE TITLE
AttributeError: module 'bentoml' has no attribute 'sklearn'

### ISSUE THREAD

**Issue by Chethan-Babu-stack** [bentoml/BentoML#2465]
I have installed bentoml version 0.13.1.

Saving the model as shown in link: https://docs.bentoml.org/en/latest/quickstart.html#save-models-section says "bentoml' has no attribute 'sklearn'

What is the issue here?

**Comment by ssilb4** [comment]
me too.
I think documents is old.

in [https://docs.bentoml.org/en/0.13-lts/quickstart.html](https://docs.bentoml.org/en/0.13-lts/quickstart.html) , there is no ./guides/quick-start/requirements.txt

**Comment by aarnphm** [comment]
hi @Chethan-Babu-stack, the latest docs are updated based on the main branch, which includes the pre-releases of bentoml. If you want to follow bentoml documentation on the main branch, please install bentoml with:
```bash
pip install bentoml --pre
```

**Comment by psc0606** [comment]
+1, I have the same problem,  `pip install bentoml --pre` does not work

**Comment by aarnphm** [comment]
make sure to uninstall bentoml first, then install bentoml with `pip install bentoml --pre`

**Comment by parano** [comment]
Basically there are two different versions out there:

* The 0.13.1 version - it's a stable but older release, the source branch can be found here https://github.com/bentoml/BentoML/tree/0.13-LTS, it can be installed with `pip install bentoml`
* The 1.0.0.a7 preview version - it's the latest version of BentoML that's still under preview/beta. You can find source code at the main branch https://github.com/bentoml/BentoML, and install it with `pip install bentoml --pre`

If you already have BentoML installed, you can verify your version by `bentoml --version`. If you want to install a different version, you may specify the desired version with `-U` option. For example, if you are currently on 0.13 version and wants to upgrade to the 1.0 preview version, use `pip install bentoml -U --pre` or `pip install -U betnoml==1.0.0.a7`

> in https://docs.bentoml.org/en/0.13-lts/quickstart.html , there is no ./guides/quick-start/requirements.txt
@ssilb4 you will need to switch to the 0.13-LTS branch for accessing that file: https://github.com/bentoml/BentoML/tree/0.13-LTS/guides/quick-start

**Comment by aarnphm** [comment]
Please check with the latest docs with our rc releases, and try again. Thank you
