### ISSUE TITLE
TF2 tutorial fails: 'TensorflowRunnable' has no attribute 'SUPPORT_NVIDIA_GPU'

### ISSUE THREAD

**Issue by AndreasLR** [bentoml/BentoML#2524]
**Describe the bug**

This bug occurs when trying to serve a bento based on TensorflowRunnable in production mode, i.e.
`bentoml serve your-model:latest --production`

This calls 'serve_production(...)' which in turn calls 'get_worker_count(...)'. The latter requires the runnable to have the attribute 'SUPPORT_NVIDIA_GPU'. However, TensorflowRunnable instead has an attrribute 'SUPPORT_GPU'. 

https://github.com/bentoml/BentoML/blob/8e3713e8797a1b820b3489d66d2debe44ee5198d/bentoml/_internal/runner/strategy.py#L45

https://github.com/bentoml/BentoML/blob/8e3713e8797a1b820b3489d66d2debe44ee5198d/bentoml/_internal/frameworks/tensorflow_v2.py#L219

**To Reproduce**

Build a bento based on TensorflowRunnable and try to serve it. For example https://github.com/bentoml/gallery/tree/main/tensorflow2

**Expected behavior**

The program crashes with the error 'AttributeError: type object 'TensorflowRunnable' has no attribute 'SUPPORT_NVIDIA_GPU''

**Environment:**
 - OS: ManjaroLinux 21.2.6
 - Python 3.10.4
 - BentoML 1.0.0rc0

**Comment by aarnphm** [comment]
Hi @AndreasLR can you try again?

**Comment by AndreasLR** [comment]
@aarnphm the model can now be served without the previous error. However, prediction request fail with another error that could be due to lack of gpu memory. 

Is the correct way to enforce CPU to use bentofile.yaml and specify something like:
```
runners:
  - name: your_runner
    cpu: 1
    nvidia_gpu: 0  
    max_batch_size: 8

```

**Comment by aarnphm** [comment]
your config is incorrect. `nvidia_gpu` here means that it will use GPU 0. You should remove that field and then try again. If you still run into problem please open another ticket

**Comment by AndreasLR** [comment]
I was unsuccessful in using bentofile.yaml to enforce using the cpu. The settings do not seem to carry over to bento.yaml generated by `bentoml build`. Anyway, here's the error reported by the server using: `bentoml serve tensorflow_mnist_demo:latest --production`

![image](https://user-images.githubusercontent.com/78612439/171298119-b3a86a82-674a-4c35-a805-cf3b55c4e7f4.png)

I had to change service.py a bit to make it work: 
```
import bentoml
import numpy as np
import PIL.Image
from bentoml.io import Image, NumpyNdarray
import tensorflow as tf

mnist_runner = bentoml.tensorflow.get("tensorflow_mnist:latest").to_runner()  # Changed as per deprecation warning

svc = bentoml.Service(
    name="tensorflow_mnist_demo",
    runners=[
        mnist_runner,
    ],
)


@svc.api(
    input=NumpyNdarray(dtype="float32", enforce_dtype=True),
    output=NumpyNdarray(dtype="float32"),
)
async def predict_ndarray(inp: "np.ndarray") -> "np.ndarray":
    assert inp.shape == (28, 28)
    # We are using greyscale image and our PyTorch model expect one
    # extra channel dimension
    inp = np.expand_dims(inp, 2)
    return await mnist_runner.async_run(inp)


@svc.api(input=Image(), output=NumpyNdarray(dtype="float32"))
async def predict_image(f: PIL.Image) -> "np.ndarray":
    assert isinstance(f, PIL.Image.Image)  # Changed from isinstance(f, PIL.Image)
    arr = np.array(f) / 255.0
    assert arr.shape == (28, 28)

    # We are using greyscale image and our PyTorch model expect one
    # extra channel dimension
    arr = np.expand_dims(arr, 2).astype("float32")
    return await mnist_runner.async_run(tf.convert_to_tensor([arr]))  # Changed from mnist_runner.async_run(arr)

```

Note that serving using `bentoml serve service:svc --reload` worls.
