### ISSUE TITLE
model creation time is always utc

### ISSUE THREAD

**Issue by ALee008** [bentoml/BentoML#2540]
**Is your feature request related to a problem? Please describe.**
Upon saving a model a creation time is added as a ModelInfo attribute. However it is not taking respective timezone into consideration.

**Describe the solution you'd like**
In `models.py` the class `ModelInfo` is created with `creation_time=creation_time or datetime.now(timezone.utc)`. Removing the `tz` argument `timezone.utc` is (according to the documentation) equivalent to `datetime.today()` which returns the current local datetime.

**Describe alternatives you've considered**
I don't think a reasonable alternative is possible because `creation_time` is not exposed directly upon model creation. 

**Additional context**
-

**Comment by aarnphm** [comment]
maybe we can add a timezone field with respect to utc? Can you specify more about your usecase for timezone usage?

**Comment by ALee008** [comment]
Hey @aarnphm , thanks for your reply. My use case is straight forward. I would like to create an overview of all saved models displaying some relevant metadata, including the creation time. As you can see in the next screenshot, I created the model `iris_clf` at around 09:03 a.m.:
![image](https://user-images.githubusercontent.com/39236016/172319865-a9779e9e-066d-4717-9600-1ccac9d12cfe.png)
Creation time is 07:03 a.m. though:
```python
>>> iris_clf.creation_time
datetime.datetime(2022, 6, 7, 7, 3, 22, 630569, tzinfo=datetime.timezone.utc)
```
Today I found (kind of) a workaround by creating a `timedelta` object and adding it to `iris_clf.creation_time`:
```python
>>> delta = datetime.datetime.today() - datetime.datetime.utcnow()
>>> iris_clf.creation_time + delta
datetime.datetime(2022, 6, 7, 9, 3, 22, 630570, tzinfo=datetime.timezone.utc)
```
I could live with this solution since I can't think of an elegant way to take the time zone into account, unless you have an idea of course.

**Comment by sauyon** [comment]
The creation time field for the model is stored as UTC to prevent confusion in absolute times when working across timezones.

When loading, the `creation_time` field should include the `tzinfo` for UTC. To convert to local time, it should be sufficient to do `model.info.creation_time.astimezone(tz=None)`.

If that's not the case, that's a bug; I'll take a look at it now.

**Comment by ALee008** [comment]
Hi @sauyon ,

thanks for your advice. Using `.astimezone` method solved the issue. Hence this ticket could be closed (if no further tasks are open).

**Comment by sauyon** [comment]
That's great to hear!

**Comment by parano** [comment]
> The creation time field for the model is stored as UTC to prevent confusion in absolute times when working across timezones.
> 
> When loading, the `creation_time` field should include the `tzinfo` for UTC. To convert to local time, it should be sufficient to do `model.creation_time.astimezone(tz=None)`.
> 
> If that's not the case, that's a bug; I'll take a look at it now.

Should we display local time in `bentoml models list/get` CLI output? or show the

**Comment by sauyon** [comment]
> Should we display local time in `bentoml models list/get` CLI output? or show the timezone info

Yes, we absolutely should. I'll put up a PR for that really quickly.
