### ISSUE TITLE
feat: deploy latest bento

### ISSUE THREAD

**Issue by gaspard-met** [bentoml/BentoML#2551]
Hi bentoml team,

Setup: 
- `bentoml==1.0.0a7`
- Gallery quickstart
- minikube + `yatai-charts==0.3.2`

**Is your feature request related to a problem? Please describe.**
When trying the examples from the documentation, `bentoml build` and `bentoml push iris_classifier:latest` are smooth and have low friction.
However for deployments I have always tempted not to look at the bento hash but to use in `my_deployment.yaml`:
```
spec: 
  bento_tag: iris_classifier:latest
``` 

1. This fails silently -> no feedback from the CLI nor the yatai UI (but then again, it's the only command executed via `kubectl` and not the bento CLI)
2. This doesn't work, but there might be a good reason behind it (like model/bento CI or human validation before updating a deployment)

**Describe the solution you'd like**
Either make it possible to use `latest` bento in deployment, or at least make it easier to use the latest one 
Also if possible have a error being raised or at least a warning that `latest` will not be deployed

Thanks in advance

**Comment by parano** [comment]
Thank you for reporting the issue @gaspard-met, indeed we initially decided not to support the `latest` tag in Yatai deployment, to prevent human errors in the deployment workflow. Currently, I think there is validation happening in the CRD controller backend, so the user can view the error by querying the deployment status, but not immediately upon user running `kubectl apply` command.

As we are currently documenting Yatai user guide, we will make sure to ask users not to use the `latest` tag in the deployment config.  We are also open to supporting the `latest` tag, in which case we will warn users that it's not meant for production use, to avoid deploying an unexpected version of the bento by mistake.

Does it help if we provide a CLI command to quickly retrieve the latest version of a given Bento name? e.g.:

```bash
> bentoml yatai get my_service:latest

service: service:svc
name: iris_classifier
version: bfj2fjw73s7rzuqj
bentoml_version: 1.0.0rc0
creation_time: '2022-05-30T05:47:49.784424+00:00'
labels:
  owner: bentoml-team
  project: gallery
models:
- tag: iris_clf:2cgiyew73o6n7uqj
  module: bentoml.sklearn
  creation_time: '2022-05-30T05:46:13.134998+00:00'
runners:
- name: iris_clf
  runnable_type: SklearnRunnable
  models:
  - iris_clf:2cgiyew73o6n7uqj
  resource_config:
    cpu: 10.0
    nvidia_gpu: 0.0
apis:
- name: classify
  input_type: NumpyNdarray
  output_type: NumpyNdarray
```
And:

```
> bentoml yatai get my_service:latest | jq ".version"

bfj2fjw73s7rzuqj
```

**Comment by gaspard-met** [comment]
Hello @parano, thanks for taking the time to reach out

I totally understand the choice not to allow for the `latest` tag to be used for deployment Yatai.
The documentation / an error message would prevent this from being an issue 

As for the usage, currently I deploy local bentos via the `kubectl apply` command
So after I train/save/build the model, I check the tag with `bentoml list` then copy-paste the latest one to `my_deployment.yaml`
Naively I would suggest a `bentoml update -f my_deployment.yaml` command to apply the latest tag manually without copy-pasting, since `my_deployment.yaml` already contains the name of the bento so all the required information should be available. 

Then again, this is not a feature request but merely something that appears to solve my particular use case but might not fit with the design principles of bentoml.

As for the `bentoml yatai` commands, as far as I can see, there is only `bentoml yatai login` at the moment, right ?

**Comment by timliubentoml** [comment]
Once you do a "yatai login" you should then be able to use the "push" and "pull" commands to upload bentos as well.

**Comment by parano** [comment]
Hi @gaspard-met, thanks for the feedback! This is definitely an important step in the CI/CD story. We do plan to provide CLI commands for `bentoml yatai deploy`, including creating and updating deployments. see https://github.com/bentoml/BentoML/issues/2405

As for now, I'd recommend go with a traditional workflow similar to how people deploy newly built docker images to kubernetes. Here's an example with envsubst, for more advanced cases, I'd recommend using something like Jsonnet or kustomize to parameterize your deployment configuration:

```bash
bentoml build  # create a new Bento
BENTO_VERSION=$(bentoml get iris_classifier:latest -o json | jq ".version") # get the version of the new Bento
bentoml push iris_classifier:$BENTO_VERSION # push Bento to Yatai
```

Let's say you have the following in your `my_deployment.yaml` file:
```yaml
spec: 
  bento_tag: iris_classifier:${BENTO_VERSION}
```

Trigger a re-deployment with the new bento:
```bash
cat my_deployment.yaml | envsubst | kubectl apply ..
```

See reference:
https://stackoverflow.com/questions/48296082/how-to-set-dynamic-values-with-kubernetes-yaml-file
https://stackoverflow.com/questions/56003777/how-to-pass-environment-variable-in-kubectl-deployment

**Comment by gaspard-met** [comment]
Hi @parano ,

Thanks for the suggestion, made it work on my side 👍 

What worked for me: 

- Double curly brackets:
```
spec: 
  bento_tag: iris_classifier:{{BENTO_VERSION}}
  ```
  
- Kubectl apply to unnamed file: 
```
cat my_deployment.yaml | envsubst | kubectl apply -f -
```

Closing this as it's solved 🍱

**Comment by ndziuba** [comment]
Opening this up again as 
bentoml yatai get my_service:latest does not work anymore.

and running
`bentoml deployment get production-deployment `
gets me
```
    | Traceback (most recent call last):
    |   File "<cattrs generated structure bentoml._internal.cloud.schemas.ClusterFullSchema>", line 70, in structure_ClusterFullSchema
    |     res['resource_instances'] = __c_structure_resource_instances(o['resource_instances'], __c_type_resource_instances)
    | KeyError: 'resource_instances'
    | Structuring class ClusterFullSchema @ attribute resource_instances
```

i have a json like for example:
{
    "cluster_name": "default",
    "name": "prod",
    "description": "",
    "targets": [
        {
            "type": "stable",
            "bento_repository": "iris_classifier",
            "bento": "wbv2kla24snskasc",
            "config": {
                "hpa_conf": {
                }
            }
        }
    ],
    "kube_namespace": "yatai"
}

where i want to set the bento as a variable and update it. 
But i cant retrieve the current "latest" version.
