### ISSUE TITLE
Rc0 release broke dockerfile for windows support

### ISSUE THREAD

**Issue by timliubentoml** [bentoml/BentoML#2563]
**Describe the bug**

From support channel in slack
https://bentoml.slack.com/archives/CKRANBHPH/p1654618223220669

User mentions that windows support was working with a7 but not rc0.

> It seems to be a path issue within the generated dockerfile (path with "\" and "/" raise an error), for example line 118 this command raises an error RUN chmod +x /home/bentoml/bento\env\docker\entrypoint.sh

Docker file contains slashes which are not compatible with windows

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by aarnphm** [comment]
#2547 will fix this
