### ISSUE TITLE
Takes abnormally long time to build image

### ISSUE THREAD

**Issue by ebbunnim** [bentoml/BentoML#2582]
**Describe the bug**

Hi, i have been building an API server using Bentoml.
Recently when building an image, it takes too much time to install a package. 
(It's been over 3000s so far, and the image build hasn't ended yet.)
There was no problem with the image build about 3 days ago, but I wonder if there was a problem with the recent code revision.

**To Reproduce**

Below are my requirements.
```
bentoml==0.13.1
SQLAlchemy==1.3.24
SQLAlchemy-Utils==0.36.7
xgboost
easydict==1.9
numpy==1.21.6
transformers==4.18.0
requests==2.23.0
sentence-transformers==2.2.0
pandas==1.4.2
torch==1.6.0
dataclasses==0.6
tqdm==4.64.0
fasttext==0.9.2
pororo==0.4.1
emoji==1.7.0
```

**Expected behavior**

Look forward to the normal image build process.

**Screenshots/Logs**

```
 => [12/18] RUN ./bentoml-init.sh restore_conda_env                                                                                                                                   3.4s
 => [13/18] COPY --chown=bentoml:bentoml requirements.txt ./                                                                                                                          0.0s
 => [14/18] RUN ./bentoml-init.sh install_pip_packages                                                                                                                             3649.1s
 => => # WARNING: Discarding https://files.pythonhosted.org/packages/10/aa/f31c8a858e23fe5b14c59e6a03ae80b4cb76353c184df48a582a55eb2674/ruamel.yaml-0.15.0.tar.gz#sha256=f9f4a50422acf4a6a
 => => # b55b568ae879b3ceb62e8e62a60022cb88816c17e40782e (from https://pypi.org/simple/ruamel-yaml/). Command errored out with exit status 1: python setup.py egg_info Check the logs for 
 => => # full command output.                                                                                                                                                             
 => => # INFO: pip is looking at multiple versions of regex to determine which version is compatible with other requirements. This could take a while.                                    
 => => # Collecting regex!=2019.12.17                                                                                                                                                     
 => => #   Downloading regex-2022.4.24-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (764 kB)                        
```

**Environment:**
 - OS: [MacOS 11.3.1]
 - Python Version [Python 3.8.4]
 - BentoML Version [BentoML-0.13.1]

**Additional context**

**Comment by aarnphm** [comment]
Hi @ebbunnim, This is often due to incompatibilities among your locked dependencies. 

One more note is that bentoml `0.13` is in LTS atm. We have recently released an `rc1` releases that you can try out. https://github.com/bentoml/BentoML/releases/tag/v1.0.0-rc1

You can try install it with `pip install bentoml==1.0.0rc1`

**Comment by aarnphm** [comment]
you can pass in extra pip arguments. This is an older implementation of the init.sh file and we changed the internal generation process for 1.0. We are focussing on 1.0 and thus 0.13 LTS support is not very high on our list right now. I don't know how to add extra pip args in 0.13 (cc @parano). For 1.0 you can follow the tutorial here https://docs.bentoml.org/en/latest/concepts/bento.html

**Comment by ebbunnim** [comment]
Well, i solved the problem by passing pip args in the following way.
```
docker build --no-cache -t {docker repo} {saved bundle path} 
--build-arg EXTRA_PIP_INSTALL_ARGS='--use-deprecated=legacy-resolver'
```

And as you advised, I will try to apply rc1 version to the existing project.
Thanks a lot :)
