### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '$(circus.sockets.{runner_name}) when runner name has a space character in production mode

### ISSUE THREAD

**Issue by ALee008** [bentoml/BentoML#2583]
**Describe the bug**
A Runner object can be instantiated with a `name` argument. It seem as if this name contains a space seperator mentioned ValueError is raised when serving in production mode. As you can see in the screenshot, name of the runner is *Document Klassifikation*. I added some print statements starting with `>>>`:
![image](https://user-images.githubusercontent.com/39236016/173335889-cf02fb9e-b42e-4f31-a8da-9dfc3e4f3899.png)
Removing the space, `name="DocumentKlassifikation"` fixed the problem. 
I tracked the problem down to `/bentoml/_internal/server/cli/runner.py`. Seems the `runner_name` needs to be sanitized before using it for the bind I guess.

**To Reproduce**

Steps to reproduce the issue:
1. Create a Runner object 
2. set argument `name="Document Classification"
3. run `bentoml serve service.py --production`
4. See ValueError

**Expected behavior**
No ValueError is raised.

**Environment:**
 - OS: SLES 12 SP5
 - Python Version 3.10.4
 - BentoML Version bentoml, version 1.0.0rc0

**Comment by sauyon** [comment]
Thanks for reporting this! I've limited runner names to valid python identifiers in #2588, which should resolve this issue.

**Comment by ALee008** [comment]
Thank you @sauyon !
