### ISSUE TITLE
Fail to `bentoml build` when using custom docker image

### ISSUE THREAD

**Issue by chlee1016** [bentoml/BentoML#2591]
**Describe the bug**

When using `bentoml build` with custom base_image in `bentofile.yaml`, an error occurred.

**To Reproduce**

Assume that my bentoml service and runner, api have been implemented, thus ready to `bentoml build`.
```python
# bentofile.yaml
service: "bentoml_service.py:service"  # A convention for locating your service: <YOUR_SERVICE_PY>:<YOUR_SERVICE_ANNOTATION>
description: "file: ./README.md"
labels:
    owner: bentoml-team
    stage: demo
include:
 - ".env"
 - "*.py"  # A pattern for matching which files to include in the bento
python:
  packages:
   - boto3==1.20.31
   - click==8.0.4
   - dill==0.3.2
   - pydantic==1.8.2
   - mlflow==1.23.1
   - tqdm==4.62.3
   - pydantic[dotenv]
   - validators==0.18.2
   - bentoml==1.0.0-rc0
   - rich==12.0.1
   - image==1.5.33
   - tensorflow==2.8.0
   - protobuf==3.20.1
docker:
  base_image: "my_custom_image:latest"
```
**Expected behavior**

**Screenshots/Logs**

```bash
$ bentoml build
Error: [cli] `build` failed: function is called before with_defaults() is invoked.
```
**Environment:**
 - BentoML Version [e.g. BentoML-1.0.0rc0]

**Additional context**

1. If I add any text instead of `my_custom_image:latest`, I got the same error.
2. When I add the docker `distro` config in `bentofile.yaml`, `$ bentoml build` can be successfully done. However, the generated dockerfile seems contain additional info with regard to distro. (Even if [the guide](https://docs.bentoml.org/en/latest/concepts/bento.html?highlight=base_image#custom-base-image-advanced) says **`When a base_image is provided, all other docker options will be ignored, (distro, cuda_version, system_packages, python_version)`**.

**Comment by parano** [comment]
Hi @chlee1016, we fixed a number of issues regarding Docker build options in the 1.0.0rc1 release, could you try it out?

> If I add any text instead of my_custom_image:latest, I got the same error.

Do you mean adding text to the base image tag? The base image is only pulled when user runs `bentoml containerize`, BentoML does not verify access to the image during `bentoml build`

> However, the generated dockerfile seems contain additional info with regard to distro

What do you mean additional info? Did you specify both `base_image` and `distro`?  The `base_image` is an advanced option for special use cases only. When it is provided, BentoML will try do bare minimum on top of the user image. As specified in the linked document:

> When a base_image is provided, all other docker options will be ignored, (distro, cuda_version, system_packages, python_version). bentoml containerize will build a new image on top of the base_image with the following steps:
> 
> * setup env vars
> * run the setup_script if provided
> * install the required Python packages
> * copy over the Bento file
> * setup the entrypoint command for serving.
>

**Comment by chlee1016** [comment]
Hi @parano ! thank you for your quick response!
> we fixed a number of issues regarding Docker build options in the 1.0.0rc1 release, could you try it out?

I found that this issue has been solved in 1.0.0rc1 release, I can successfully use `bentoml build` when using custom docker base image in `bentofile.yaml`. Thanks!

> Do you mean adding text to the base image tag?

It meant that I got the same error even if I replace my_custom_image:latest with `aaa` or `nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu20.04` or anything of text.
I just wanted to say that it was the same when I tested it with my existing docker base image, not an example.

> What do you mean additional info? Did you specify both base_image and distro? The base_image is an advanced option for special use cases only. When it is provided, BentoML will try do bare minimum on top of the user image. As specified in the linked document:

Yes. I specified both base_image and distro to workaround the error when using `bentoml build`.
I expected that the dockerfile created when distro was inserted and not inserted was exactly the same. but found some diffs in dockerfile.
```bash
ENV DEBIAN_FRONTEND=noninteractive
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,from=cached,sharing=shared,target=/var/cache/apt \
    --mount=type=cache,from=cached,sharing=shared,target=/var/lib/apt \
  apt-get update -y \
    && apt-get install -q -y --no-install-recommends --allow-remove-essential \
    ca-certificates gnupg2 bash build-essential \
    && apt-get clean

# Install user-defined system package
RUN --mount=type=cache,from=cached,sharing=shared,target=/var/cache/apt \
    --mount=type=cache,from=cached,sharing=shared,target=/var/lib/apt \
    apt-get install -q -y --no-install-recommends --allow-remove-essential \
     \
    && apt-get clean

RUN rm -rf /var/lib/{apt,cache,log}
```

**Comment by aarnphm** [comment]
this is a bug on our end, `system_packages` should not be there. The issue here is probably due to passing `system_packages` as a empty list or empty dict. We have a fix on the build config PR @parano

**Comment by aarnphm** [comment]
Hi @chlee1016. Can you try again with rc3 releases and see whether you still run into this issue.

**Comment by aarnphm** [comment]
@chlee1016 can you confirm that everything is working now?
