### ISSUE TITLE
Couple of issues with pip_args in dockerfile

### ISSUE THREAD

**Issue by timc** [bentoml/BentoML#2596]
**Describe the bug**
1. If pip_args.txt has multiple options (i.e. there's a space), e.g. --index-url=some_server/some_index --trusted_host=some_server, then the cat of the file into a variable will fail
2. The heredoc that uses the $EXTRA_PIP_INSTALL_ARGS needs to escape it so that it is evaluated correctly, i.e. reference is as \\$EXTRA_PIP_INSTALL_ARGS  (that's with 1 preceeding slash, just in case the markup is not clear)

**To Reproduce**
bentofile.yaml specifies both index-url and trusted-host under python
Build the bento and containerize it

Will receive error "unknown command --trusted-host=xyz"

Resolve by changing Dockerfile replacing
```
EXTRA_PIP_INSTALL_ARGS=$(cat /home/bentoml/bento/env/python/pip_args.txt)
```
with
```
EXTRA_PIP_INSTALL_ARGS="`cat /home/bentoml/bento/env/python/pip_args.txt`"
```

Try containerizing again

The pip args will not be applied to the command (you only verify this if you try and install a package that is only on a local index)

The pip commands should change from:
```
pip install -r /home/bentoml/bento/env/python/requirements.lock.txt -U $EXTRA_PIP_INSTALL_ARGS
```
to
```
pip install -r /home/bentoml/bento/env/python/requirements.lock.txt -U \$EXTRA_PIP_INSTALL_ARGS
```

otherwise the EXTRA_PIP_INSTALL_ARGS is evaluated from outside (ref: accepted answer here: https://stackoverflow.com/questions/1167746/how-to-assign-a-heredoc-value-to-a-variable-in-bash)

**Expected behavior**
The container should build as expected.

**Extra info**
Version 1.0.0rc1

**Comment by aarnphm** [comment]
Thanks for the PR @timc
