### ISSUE TITLE
BentoML fails with 503 error while not utilizing the timeout setting

### ISSUE THREAD

**Issue by beshu** [bentoml/BentoML#2603]
**Describe the bug**

BentoML container fails to process the request with 503 error (Service unavailable). The problem persists on one of the servers at my company's disposal. The hardware on that server is quite weak, and when the container is created on another server with better hardware, no exceptions are raised. 

The service have a long timeout (720 000ms) specified in bentoml.yml because the average time of a prediction is around 10 minutes. However, the gunicorn worker cancel itself due to timeout literally in a minute. 

The main question of this issue besides why this error happens: is there any hardware requirements to serving ml models with bentoml?

**To Reproduce**

1. Create a bentoml container
2. Push container to the registry
3. Start container with Portainer
4. Make a request to the service with curl
5. See a log error

**Expected behavior**

Expected prediction service to work normally, respecting timeout from the config and not failing with 503 error. At least it should display an error that points to the exact reason of why it's failing

**Screenshots/Logs**

```
[2022-06-16 13:15:11 +0000] [14] [INFO] Worker exiting (pid: 14),
[2022-06-16 13:15:11,356] ERROR - Traceback (most recent call last):,
[2022-06-16 13:15:11 +0000] [13] [CRITICAL] WORKER TIMEOUT (pid:14),
  File "/opt/conda/lib/python3.6/site-packages/bentoml/marshal/marshal.py", line 397, in _batch_handler_template,
  File "/opt/conda/lib/python3.6/site-packages/bentoml/marshal/marshal.py", line 392, in _batch_handler_template,
    api_url, data=reqs_s, headers=headers, timeout=timeout,
  File "/opt/conda/lib/python3.6/site-packages/aiohttp/client.py", line 1117, in __aenter__,
  File "/opt/conda/lib/python3.6/site-packages/aiohttp/streams.py", line 604, in read,
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected,
    await resp.start(conn),
    self._resp = await self._coro,
  File "/opt/conda/lib/python3.6/site-packages/aiohttp/client.py", line 544, in _request,
  File "/opt/conda/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 890, in start,
    message, payload = await self._protocol.read()  # type: ignore,
    await self._waiter,
Traceback (most recent call last):,
,
During handling of the above exception, another exception occurred:,
  File "/opt/conda/lib/python3.6/site-packages/bentoml/marshal/marshal.py", line 325, in request_dispatcher,
  File "/opt/conda/lib/python3.6/site-packages/bentoml/marshal/dispatcher.py", line 153, in _func,
    resp = await self.batch_handlers[api_route](req),
    raise r,
  File "/opt/conda/lib/python3.6/site-packages/bentoml/marshal/dispatcher.py", line 213, in outbound_call,
    outputs = await self.callback(tuple(d for _, d, _ in inputs_info)),
  File "/opt/conda/lib/python3.6/site-packages/bentoml/marshal/marshal.py", line 132, in _batch_handler_template,
    return await func(requests, api_route, max_latency),
    e, payload=HTTPResponse.new(status=503, body=b"Service Unavailable"),
bentoml.exceptions.RemoteException: Server disconnected
```

**Environment:**
 - OS: [linux x86_64 Amazon Linux 2]
 - Python Version [3.6.15]
 - BentoML Version [Bentoml 0.13.1]
 - Total CPU [4]
 - Total memory [16.6 GB]

**Additional context**

bentoml.yml

```yaml
version: 0.13.1
kind: BentoService
metadata:
  created_at: 2022-06-15 14:13:29.024625
  service_name: VGG19Blast
  service_version: 20220615171326_6EC2FD
  module_name: bento_service
  module_file: bento_service.py
env:
  pip_packages:
    bentoml==0.13.1
    torch==1.4.0
    scikit-image==0.17.2
    opencv-python-headless==4.5.1.48
    numpy==1.19.4
    pillow==8.0.1
    torchvision==0.5.0
  conda_env:
    name: bentoml-default-conda-env
    dependencies: []
  python_version: 3.6.15
  docker_base_image: bentoml/model-server:0.13.1-py36
apis:
  name: predict
  docs: "BentoService inference API 'predict', input: 'FileInput', output: 'JsonOutput'"
  input_type: FileInput
  output_type: JsonOutput
  mb_max_batch_size: 4000
  mb_max_latency: 720000
  batch: true
  route: predict
  name: predict_aug8
  docs: "BentoService inference API 'predict_aug8', input: 'FileInput', output: 'JsonOutput'"
  input_type: FileInput
  output_type: JsonOutput
  mb_max_batch_size: 4000
  mb_max_latency: 720000
  batch: true
  route: predict_aug8
artifacts:
  name: pytorch_model
  artifact_type: PytorchModelArtifact
  metadata: {}
bento_server:
  microbatch:
    workers: 4
```

**Comment by beshu** [comment]
Problem is still persisting and no idea why...

**Comment by yubozhao** [comment]
@beshu 

Did you set the `--timeout` option in the command: `bentoml serve-gunicorn`?  The default value is 60 seconds, you will want to increase that what appropriate for your prediction.

We didn't do a good job at explaining the batch fields and their values. Our bad.  The `mb_max_latency` means how long the max latency you are willing to tolerance for your prediction requests.

Let me know how it goes after you try out the new timeout option.

**Comment by beshu** [comment]
Hello! Sorry for the long response. Thanks for letting me know about this option, it worked like a charm. Closing the issue
