### ISSUE TITLE
Small breaking change to onnx-mlir PyExecution session requires small tweak to open source code

### ISSUE THREAD

**Issue by messerb5467** [bentoml/BentoML#2622]
**Describe the bug**
A change to the onnx-mlir PyExecutionSession requires BentoML's onnx-mlir PyExecutionSession to be updated with a fix where `run_main_graph` no longer needs specified in the PyExecutionSession invocation as shown below:
![image](https://user-images.githubusercontent.com/7052326/174867827-350ebfb5-1062-4d2a-8439-4f490ab5f017.png)

**To Reproduce**
Any workflow using an old copy of the compiled models will need to refresh their compiled model and repack their serving environment. Any discussions for incompatible changes needed beyond that should be discussed with me immediately.

**Expected behavior**
The model should run as expected and give the expected output.

**Screenshots/Logs**
Sufficient documentation has been provided in the documentation above and I or @andrewsi-z will provide the fix for this since he originally authored this code.

**Additional context**
A fix has been discussed with @andrewsi-z and should be straightforward in implementation. I'll work with the team moving forward to implement the PR.

**Comment by aarnphm** [comment]
@messerb5467 currently for rc1, we don't have support for onnx-mlir yet. If support onnx-mlir is crucial for your 0.13 work, you are more than welcome to open a PR to address this issue.

I believe that the fix would just to remove `run_main_graph`
```python
ExecutionSession(shared_lib_path=self._model_so_path)
```
0.13 are in LTS now, and right now it is not our main focus. We will let you know asap when ONNX-mlir is supported in 1.0. In the meantime, feel free to join our [Slack](https://www.bentoml.com/clkg/https/l.linklyhq.com/l/ktIc) for more updates on 1.0. Thanks a bunch

**Comment by messerb5467** [comment]
Definitely. @andrewsi-z and I will be talking about how to handle 1.0 moving forward too since we're also stewards of the onnx-mlir project.

I've had my attention directed elsewhere for the last few months with the ongoing 1.0 support. You are correct about the solution though. It'll be very straightforward.

I'll get into the slack channel and start poking around

**Comment by andrewsi-z** [comment]
Hi @aarnphm ! for 1.0, is the onnx-mlir support something that would be reenabled as a later RC or do you see this (and perhaps other frameworks) as a post-release item?

**Comment by aarnphm** [comment]
yes ONNX-mlir will be a post-release item. We will get on providing support incrementally for all of the missing framework that we support prior to 1.0. Hopefully we will get 1.0 out soon. Sorry for any inconvenience.

**Comment by aarnphm** [comment]
I have made the PR for 0.13 to try addressing this. @andrewsi-z would be great to have your input on this. I hope it should at least fix the issue for 0.13

**Comment by messerb5467** [comment]
Hi there, I currently have the PR as well, but was hitting issues running the tests locally and was going to talk with Andrew first.

This seems like a good a time as any though to ask. How do you run the integration tests locally? I tried both running them outside a container and installing the dependencies inside a container and couldn't get it working

**Comment by aarnphm** [comment]
Honestly, I forgot how to run most of the CI for 0.13 considering we have been working on the redesign for quite a while now. IIRC it is very hard to set up ONNXmlir tests to run it locally. After compiling the ONNXmlir library, I have to manually go into the test file and add the compiled library to sys.path. Maybe you can try that out.

I believe there is something similar in the test file about injecting the `.so`.

**Comment by messerb5467** [comment]
If everything runs on the creation of the pull request, that should be ok from my point of view and we can use that to do any further debugging on my side or if your PR is working, we can just merge that in. That being said, we can also create a little something on running those tests so we don't have this trouble again.

**Comment by messerb5467** [comment]
I'll let us decide how we want to resolve this. [Based on the test-coverage documentation](https://github.com/bentoml/BentoML/blob/ca56a7ca98e32cfbc9057db73f1a310ad60551c5/CONTRIBUTING.md#testing-and-improving-test-coverage) and the files introduced in https://github.com/bentoml/BentoML/pull/1545, just running these through the CI should be sufficient to doing a full scope of tests. Trying to get these working outside of a CI outside a container just seems overly painful.

**Comment by aarnphm** [comment]
I have finished building onnx-mlir

**Comment by aarnphm** [comment]
Let me test the changes locally.

**Comment by messerb5467** [comment]
ok cool. I'm running everything through the CI/CD pipeline for my own edification, but I've got sphinx failing to build on my side for some reason in PR #2692 even though it is setup against the correct branch.

**Comment by aarnphm** [comment]
I think the docker image is very hard to use, but the installation from git source for onnx-mlir is pretty straightforward. It took me a while to compile on my old i7 desktop but it is relatively quick on a m1 mac :).

I have a few ideas around devex for `bentoml.onnxmlir` and will ping you when I have the PR up.

**Comment by messerb5467** [comment]
cool thanks so much Aaron. Really appreciate the help here.

**Comment by aarnphm** [comment]
Lets close this one and create a different ticket to track ONNXMlir support here. https://github.com/bentoml/BentoML/issues/2693

**Comment by aarnphm** [comment]
@messerb5467 for now to use onnxmlir via docker you can do
```bash
docker run --rm -it -v $(pwd):/workdir onnxmlirczar/onnx-mlir:latest -O3 --EmitLib /workdir/mnist.onnx -o torch_mnist
```
This assumes your current working directory has a `mnist.onnx`

**Comment by messerb5467** [comment]
That's the part I'm very familiar with since I maintain the project. I was having trouble with the sphinx build on the PR merge since I've switched between a few different disciplines and I'm trying my hand at development now.

**Comment by messerb5467** [comment]
and I also don't want to give too much an unexperienced vibe as I put in a lot of work on my own time to close the gap. This is just one of those things I might need a slight pick me up on so I can bootstrap myself.

**Comment by aarnphm** [comment]
ah no worries. Just take your time no need to rush.
