### ISSUE TITLE
`containerize` ignores conda install errors

### ISSUE THREAD

**Issue by hotplot** [bentoml/BentoML#2648]
**Describe the bug**

If `conda env update ...` fails when containerizing a bento that specifies a conda environment, the error is silently ignored during the Docker build and `bentoml containerize` reports a successful build despite generating an invalid docker image.

**To Reproduce**

1. Create a bentoml service with a bentofile.yaml that specifies a conda environment
2. Make sure the conda env can't be installed (use an invalid package name, build the docker image on a device with no space, etc)
3. Run `bentoml containerize ...`

**Expected behavior**

`bentoml containerize` should abort and exit with a non-zero status to indicate failure

**Screenshots/Logs**

Partial log of the `conda env update ...` failure:

```
...

#19 4.913 Preparing transaction: ...working... done
#19 4.929 Verifying transaction: ...working... done
#19 4.975 Executing transaction: ...working... done
#19 5.980 Updating conda base environment with environment.yml
#19 6.803 Collecting package metadata (repodata.json): ...working... done
#19 15.85 Solving environment: ...working... done
#19 18.48 
#19 18.48 Downloading and Extracting Packages

...

#19 592.5 Rolling back transaction: ...working... ERROR conda.core.link:_execute(730): An error occurred while installing package 'nvidia::cudatoolkit-11.1.74-h6bb024c_0'.
#19 593.1 done
#19 593.1 
#19 593.1 [Errno 28] No space left on device
#19 593.1 ()
#19 593.1 
#19 594.2 Will remove 42 (2.80 GB) tarball(s).
#19 594.2 Proceed ([y]/n)? 
#19 594.4 Will remove 1 index cache(s).
#19 594.4 Proceed ([y]/n)? 
#19 594.5 Will remove 42 (6.68 GB) package(s).
#19 594.5 Proceed ([y]/n)? 
#19 595.2 There are no tempfile(s) to remove.
#19 595.2 There are no logfile(s) to remove.
#19 DONE 595.5s

#20 [stage-6 10/14] RUN --mount=type=cache,mode=0777,target=/root/.cache/pip     pip install bentoml==1.0.0rc1 --no-cache-dir
#20 1.515 Collecting bentoml==1.0.0rc1
#20 1.541   Downloading bentoml-1.0.0rc1-py3-none-any.whl (800 kB)
#20 1.617 Collecting aiofiles
#20 1.620   Downloading aiofiles-0.8.0-py3-none-any.whl (13 kB)
#20 1.845 Collecting cattrs
#20 1.853   Downloading cattrs-22.1.0-py3-none-any.whl (33 kB)
#20 2.090 Collecting cloudpickle
#20 2.093   Downloading cloudpickle-2.1.0-py3-none-any.whl (25 kB)

...
```

**Environment:**
 - OS: [e.g. MacOS 10.14.3]: Linux
 - Python Version: Python 3.9.7
 - BentoML Version: 1.0.0rc1

**Additional context**

Looks like the relevant line in the docker templates is [here](https://github.com/bentoml/BentoML/blob/21267df1fc4239d4a9ae3d0c682f4cbd6dbf94da/bentoml/_internal/bento/docker/templates/miniconda_debian.j2#L18)

**Comment by parano** [comment]
Hi @hotplot - looks like it's due to low disk space for conda to install packages, `#19 593.1 [Errno 28] No space left on device`. Maybe try clean up unused docker images/containers or increase disk space mounted for docker?

Also I noticed that you are using BentoML 0.8.6 which is a very old version. We did a lots of things in later versions(especially in 1.0) to improve conda integration and reduce docker image size. I'd recommend to try out the latest 1.0 preview release.

**Comment by aarnphm** [comment]
`bentoml containerize` spawn a process that invoke `docker buildx`, which if it fails, it should just exit completely. Can you try the latest rc2 releases to see if you can replicate this issue?

**Comment by hotplot** [comment]
`docker buildx` doesn't fail or exit, as the non-zero exit code from `conda env update` is ignored by the bentoml dockerfile.

See the log and compare to `miniconda_debian.j2`: 

1. `conda env update -n base -f {{ __environment_yml__ }}` is executed **and fails** (the line I linked in original comment)
2. `conda clean --all` is immediately executed and the failure from above is completely ignored
3. `docker buildx` continues the build, thinking everything is fine, because the non-zero exit code from `conda env update ...` was ignored
4. The build completes, yielding an invalid docker image with no warning that it is broken

**Comment by parano** [comment]
@hotplot thank you for providing the details, I can reproduce the issue on my end with 1.0.0rc2 release. we will prioritize a patch for fixing this issue. cc @aarnphm @ssheng

**Comment by hotplot** [comment]
Thanks for the help and quick fix @aarnphm :)

**Comment by aarnphm** [comment]
my pleasure @hotplot
