### ISSUE TITLE
PyTorch Runner doesn't support dict as input when inference on GPU

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#2694]
**Describe the bug**

Slack conversation: https://bentoml.slack.com/archives/CKRANBHPH/p1656589220060889

> It seems that the PyTorch Runner supports only Tensor or ndarray types. My model consumes dicts with images and some metadata. It fails when it tries to move the dict to GPU:
  ```File ".../lib/python3.7/site-packages/bentoml/_internal/frameworks/common/pytorch.py", line 101, in _mapping
    return item.to(self.device_id)  # type: ignore # the overhead is trivial if it is already on the right device
AttributeError: 'dict' object has no attribute 'to'
```

Current workaround:
Using custom Runner:
```
from mmdet.apis import init_detector, inference_detector
import bentoml
import numpy as np
from bentoml.io import Image, JSON


bento_model = bentoml.pytorch.get("detector:latest")

class mmDetectionRunnable(bentoml.Runnable):
    SUPPORT_NVIDIA_GPU = True
    SUPPORT_CPU_MULTI_THREADING = True

    def __init__(self):
        self.model = bentoml.pytorch.load_model(bento_model)   

    @bentoml.Runnable.method(
        batchable=True,
        batch_dim=0,
    )
    def detect(self, input_tensor):
        return inference_detector(self.model, input_tensor)

mmdet_runner = bentoml.Runner(mmDetectionRunnable, models=[bento_model])

svc = bentoml.Service("detector", runners=[mmdet_runner])

@svc.api(input=Image(), output=JSON())
def detect(input_img):
    return mmdet_runner.detect.run(np.array(input_img))
```

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by ssheng** [comment]
@yubozhao dictionary input can be supplied as multiple named tensors. However, we should document this better.

**Comment by seyong92** [comment]
@ssheng Could you explain how to give "multiple named tensors" to the model in detail?

In my case, the model input is named a variable "x", a dictionary that could have single or multiple key-value pairs.

However, when I give a dictionary x to a model, it returns the error that the tensors in x are located on the CPU.

If I give an input as a keyword parameter like `runner.async_run(key1=value1)` it returns the error that the model got an unexpected keyword argument 'key1'.

**Comment by MarioMarkov** [comment]
Why is this closed? [ssheng](https://github.com/ssheng) didn't give the answer in code I still have the same problem on bentoml v 1.0.19 I want to pass dict which has the feature names as keys and tensors for the values, because that is what tensorflow preprocessing layers require, but it is not possible to use runners in bentoml for that.
