### ISSUE TITLE
AWS Lambda Deployment: error creating bentoml home dir and config file

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#271]
Thanks @Mu7ammad for reporting this bug here: https://github.com/bentoml/BentoML/issues/235, creating a new issue for tracking:

> Follow up: So I tried version 0.3.4 with same example and environment, and it indeed seems to package the dependencies this time, but then when I run the lambda function I get internal server error, and from the logs it says:
> 
> "Error creating bentoml home dir '/home/sbx_user1051/bentoml': No such file or directory"
> 
> It's thrown from executing: bentoml/config/init.py , line 61 with exception: "Error creating bentoml home dir"
> 
> It seems can't find the home directory in the sandbox, so what do you think the reason for that?
> 
> Thanks

![image](https://user-images.githubusercontent.com/489344/63813036-43ee0e80-c967-11e9-9952-ad2b559dc426.png)

This is due to AWS Lambda has limited disk access to '/tmp' directory: https://docs.aws.amazon.com/lambda/latest/dg/limits.html

Proposed solution: set bentoml home dir to '/tmp/bentoml' in AWS lambda deployment

**Comment by Mu7ammad** [comment]
I'm basically trying to run the "getting started" example using scikit-learn with tiny model, and I want it to deploy to AWS-Lambda in any verified way. Even when I use BentoML version 0.3.0 I get either of two errors: if I didn't include BentoML in the requirements.txt it doesn't find module BentoML in runtime and throws no such module error, and if I did include it the package size reaches about 66 MB (even though the scikit dependencies is only about 40MB) and it throws the same error as above (/home/sbx_user no such file or directory).

Is there a version of BentoML where I can verify AWS Lambda deployment for this quick start example to run correctly as-is? I really like your approach guys to this and I think this option specifically could be great running without issues.

**Comment by parano** [comment]
@Mu7ammad The last time I tested serverless deployment was BentoML-0.2.0 Beta which should work, you may verify on that branch.  I'd recommend waiting a little bit for next release - We are currently working on a completely revamped deployment implementation coming in our next release, which brought lots of improvements to serverless deployment workflow as well. Would be ideal for you to try out the new implementation and we'd love to hear your feedback as well. Also, make sure to join the slack channel if you plan to use BentoML for production workload!

**Comment by parano** [comment]
@Mu7ammad  this issue has been fixed in #284, the serverless deployment should work end-to-end in next release
