### ISSUE TITLE
Document how to test a BentoML service

### ISSUE THREAD

**Issue by sauyon** [bentoml/BentoML#2722]
We should have good docs for using BentoML with various testing frameworks.

**Comment by sauyon** [comment]
@Sherlock113 something we might want to add to the todo pile!

**Comment by duksis** [comment]
looking forward to this

**Comment by Sherlock113** [comment]
This is already on my radar. Will add the docs once https://github.com/bentoml/BentoML/pull/3878 is merged.

**Comment by parano** [comment]
Testing a Bento:
https://docs.bentoml.com/en/latest/concepts/bento.html#test-bentos
