### ISSUE TITLE
perf: support multiple bento build stage

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#2733]
Currently the generated Dockerfile is only one stage. We should take advantage
of the [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) or similar OCI-compilant tools to reduce the bundle size.

**Comment by parano** [comment]
@aarnphm could you try to modify the current BentoML generated Dockerfile to multi-stage and observe how much improvement it is?  My feeling is that we already do lots of things to ensure installation cache and temporary files are not part of the final image, I'm not sure how much improvement multi-stage build could bring us.

**Comment by aarnphm** [comment]
Yet the image size a still pretty huge. We are still installing tools like curl, build-essentials to the target images

imo this is not needed.
