### ISSUE TITLE
feat(framework): PaddlePaddle

### ISSUE THREAD

**Issue by cgyeon-muhayu** [bentoml/BentoML#2748]
### Feature request

`NotImplementedError: Support for "bentoml.paddle" is temporarily unavailable as BentoML transition to the new design in version 1.0.0 release. Before this module is officially implemented in BentoML, users may use Custom Runner as a workaround. Learn more at http://docs.bentoml.org/`

Thanks!

**Comment by frostming** [comment]
This is by design, and we decide to leave some frameworks to the community to contribute as an extension.
