### ISSUE TITLE
feature: api for custom model and bento tags

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#2750]
### Feature request

Hello! Is it possible to change the version assigned to a model before saving it? I’d like to be able to assign a semantic version instead of the random generated version in the Tag, This used to be possible with artifacts in 0.13, but I can’t find a way to do it now with 1.0.0. A possible way to do this might be to allow an argument tag in the save_model method that takes a bentoml.Tag and that supersedes the argument name .Thanks :)

**Comment by parano** [comment]
Custom Bento tag is actually supported via the `--version` CLI argument in `bentoml build`:

```bash
bentoml build --version 1.0.2
```

We should allow user to specify a version tag for their models in `save_model` APIs, e.g.:

```bash
version = "1.0.2"
bentoml.tensorflow.save_model("my_model:{version}", model_instance)
```

**Comment by ssheng** [comment]
@dbuades we will implement model versioning similar to what @parano has suggested above. Do you think this will solve the problem you face?

**Comment by dbuades** [comment]
> @dbuades we will implement model versioning similar to what @parano has suggested above. Do you think this will solve the problem you face?

@ssheng Yes, that's perfect. Thank you very much! 🙂
