### ISSUE TITLE
Update BentoML recipe on conda-forge to use version 1.0

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#2751]
#2641 added BentoML 0.13 to conda-forge channel, with the recent release of 1.0 version, we need to update BentoML receipt on conda-forge to point to 1.0 and update the dependencies list.

cc @aarnphm  @sugatoray

**Comment by aarnphm** [comment]
@sugatoray feel free to take a stab at this

**Comment by sugatoray** [comment]
I will look into it. Thanks for the heads up. 🚀

**Comment by sugatoray** [comment]
> https://github.com/conda-forge/staged-recipes/pull/19680

You will not need to create a new recipe for `bentoml`. The update needs to happen in the conda-forge feedstock repository for bentoml. So, please close the PR opened in staged-recipes repository. 

- https://github.com/conda-forge/bentoml-feedstock

**Comment by sugatoray** [comment]
I opened a PR in the feedstock.

- https://github.com/conda-forge/bentoml-feedstock/pull/4

**Comment by sugatoray** [comment]
:bulb: Someone please change the title of this issue; there is a typo:

```diff
- Update BentoML receipt on conda-forge to use version 1.0
+ Update BentoML recipe on conda-forge to use version 1.0
```

**Comment by aarnphm** [comment]
This will be tracked at the corresponding feedstock.

**Comment by sugatoray** [comment]
@aarnphm @parano bentoml was updated to `v1.0.0` on conda-forge just now. Give it 2-3 hours for the updated package to show up on conda-forge.

Please run the following command to check the available versions.

```sh
conda search -c conda-forge bentoml
```

- https://anaconda.org/conda-forge/bentoml 

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/bentoml.svg)](https://anaconda.org/conda-forge/bentoml)
