### ISSUE TITLE
bug: bentoml containerize should support multiple tags

### ISSUE THREAD

**Issue by dbuades** [bentoml/BentoML#2789]
### Describe the bug

The method `buildx.build` support a list of tags [here](https://github.com/bentoml/BentoML/blob/6b80bb533887d219c5bc2d8c01ea1d8dfdb13dc7/bentoml/_internal/utils/buildx.py#L168) but `containerize` only send a single tag [here](https://github.com/bentoml/BentoML/blob/6b80bb533887d219c5bc2d8c01ea1d8dfdb13dc7/bentoml/bentos.py#L423).

This causes that when passing multiple `--docker-image-tag` arguments to `bentoml containerize`, only the last one is kept.

### To reproduce

Pass multiple `--docker-image-tag` to `bentoml containerize` and only the last one will be kept.

### Expected behavior

In my opinion, if multiple `--docker-image-tag` are passed to `bentoml containerize`, all of them should be passed to buildx.

### Environment

`bentoml`: 1.0.0
`python`: 3.9.10
`platform`: macOS-12.5-arm64-arm-64bit

**Comment by parano** [comment]
thank you for reporting the issue @dbuades!

cc @aarnphm for `bentoml containerize`, the `-t` should support multi-options, see  https://click.palletsprojects.com/en/7.x/options/#multiple-options

**Comment by aarnphm** [comment]
The progress will now be tracked and bugs will be fixed at #2797. Thanks for reporting this.
