### ISSUE TITLE
feature: allow user to specify URLs to exclude from tracing

### ISSUE THREAD

**Issue by jiewpeng** [bentoml/BentoML#2829]
### Feature request

Currently, if tracing is enabled, traces are collected / sampled from all routes. There should be a way to disable tracing on certain routes, especially when a deployment on Kubernetes may have liveness and readiness probes pinging the deployment frequently. Since we cannot disable tracing on the liveness/readiness probe routes, many redundant traces get collected.

For example, you can see below that a lot of the traces collected are of the liveness and readiness probe, and only one of them has a useful trace for the predict route.
![image](https://user-images.githubusercontent.com/12453748/181473003-79c7c9e5-9fa9-4b15-8b71-c727d4cbb5c2.png)

For other opentelemetry instrumentations, we can use an environment variable like `OTEL_PYTHON_FASTAPI_EXCLUDED_URLS` to specify routes to exclude from tracing, we should be able to do something similar.

**Comment by aarnphm** [comment]
I think your proposal makes sense. We would love to have you contribute this feature 🚀

**Comment by jiewpeng** [comment]
Alright, will try to work on it

**Comment by aarnphm** [comment]
This issue now will be tracked at #2843.
