### ISSUE TITLE
Composing handlers

### ISSUE THREAD

**Issue by lambdaofgod** [bentoml/BentoML#286]
I'd like to handle multiple content types at once.
For example while uploading image I'd like to also be able to provide some metadata, for example in JSON format.

For now this is impossible as handlers use custom logic inside and it's impossible to combine them.

**Alternatives**
Subclassing specific handlers every time there is need for specific behavior. This is pretty cumbersome and bug-prone.

**Comment by parano** [comment]
Revisited this issue again and I think it is now very hard to re-use the logic from multiple handlers(input adapters) and composing them, especially with the introduction of micro-batching, which makes the API request handling logic a lot more complex. 

I think for your use case where you need handling an image and some extra metadata, the best way to do it is to use JsonInput and use base64 to encode the image file and put it in the JSON message.
