### ISSUE TITLE
feat: Include custom FastAPI endpoint in the Swagger UI

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#2900]

**Comment by aarnphm** [comment]
This can be done by reading https://github.com/tiangolo/fastapi/blob/5c576e42be8f8832f0e225beaa72153a256892d7/fastapi/applications.py#L197 and merge with BentoML [generated OpenAPI spec](https://github.com/bentoml/BentoML/blob/a48d83e07f04a881c4550ca652d1e80309fbbbf4/bentoml/_internal/service/service.py#L196) 

Would love for community to contribute on this feature 🎉

**Comment by aarnphm** [comment]
This has been addressed by #3358 and will be included in the coming release.

**Comment by aarnphm** [comment]
This has now been included in 1.0.13 release
