### ISSUE TITLE
feat(containerize): support custom ports

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#2916]
### Feature request

The ports specified in custom `bentoml_configuration.yaml` should be persistent with the generated dockerfile.
```yaml
api_server:
  port: 5000
```

Since `--config` is a global option:
```bash
bentoml build --config ./custom_config.yaml
```
This port will have no effect on the generated Dockerfile, and hence the exposed ports would not be correct.

The same arguments applies if `BENTOML_PORT` envar is set

### Motivation

Current workaround is 
```bash
cd $(bentoml get <bento>:<tag> -o path) && vim ./env/docker/Dockerfile
```

Change `EXPOSE 3000` to `EXPOSE 5000`

```bash
bentoml containerize <bento>:<tag>
```

```bash
docker run -it --rm -p 5000:5000 <bento>:<tag>
```

**Comment by parano** [comment]
is there a real use case for this feature? Users can already customize the port when running the container:

```
docker run <bento>:<tag> --port 3000
```
or
```
docker run -e BENTO_PORT=3000 <bento>:<tag> 
```

Note that the Dockerfile command `EXPOSE 3000` doesn't do anything at all. It just serves as documentation, indicating the default port.
