### ISSUE TITLE
feature: yatai GUI should recognize bento deployments that weren’t deployed via yatai

### ISSUE THREAD

**Issue by mqk** [bentoml/BentoML#2954]
### Feature request

I would like it if yatai recognized bento deployments that were created outside of the yatai GUI.

### Motivation

In our organization we limit deploys of bentos via yatai GUI to the dev environment. In higher environment we instead enforce a gitops-style of deploys. In this set up, we have a repo (bentoml-config) in which we manage all k8s configuration files (pretty much just a bento.yaml file that defines the resources of the `BentoDeployment` object, and a kustomization.yaml that defines the exact docker image version we want to deploy). So when we want to deploy a new bento into staging or production, we simply issue a pull request that adds these files for the new bento to the repo. Then when this PR is merged to main, our [Argo CD](https://argo-cd.readthedocs.io/en/stable/#:~:text=Argo%20CD%20is%20implemented%20as,target%20state%20is%20considered%20OutOfSync%20) tool picks it up and creates the `BentoDeployment` object in our staging/production kubernetes clusters, where Yatai detects it and completes the deploy. This process is working for us: we are able to deploy our bento services into our staging and production clusters, and they work as expected. However, one piece of functionality is missing. Yatai does not display such deployments in its GUI, i.e. they’re not visible under the Deployments tab. This means that we’re missing one of the functionalities that we were hoping to get out of yatai, namely the ability to track deployments to our production systems in a web service.

**Comment by yetone** [comment]
@mqk Yatai has this feature at the beginning of the birth, it may be where there is an error, you can check out yatai-deployment-operator's log:

```bash
kubectl -n yatai-components logs -f deploy/yatai-yatai-deployment-operator
```

**Comment by benjamintanweihao** [comment]
I just tested this on my end (i.e. deploying a `BentoDeployment` YAML via CI/CD) and I'm able to see the deployment on the UI. @mqk what does `kubectl get bentodeployment -A` show?

**Comment by mqk** [comment]
Looks like this is due to some kind of misconfig on our end.

I'm OOO through Monday. Will update on Tuesday.

Thanks!

Mike

**Comment by mqk** [comment]
We have this working now.
