### ISSUE TITLE
feature: add support for XGBoost models trained using the XGBoost scikit-learn interface

### ISSUE THREAD

**Issue by gustavocidornelas** [bentoml/BentoML#2983]
### Feature request

I would like to use BentoML to save and deploy XGBoost models that were trained using the scikit-learn learn interface of the XGBoost model. 

### Motivation

I'm trying to save an XGBoost model using BentoML. I'm using the [scikit-learn interface](https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn) of the XGBoost module, so my final model is of type `xgboost.sklearn.XGBClassifier`. I noticed [here](https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/xgboost.py#L162) that BentoML expects the model to be of type `xgboost.core.Booster`, which is what you get when you use the native XGBoost module. 

I also can't save the model as an sklearn model (without failing [this validation](https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/sklearn.py#L145)).

**Comment by aarnphm** [comment]
Hi @gustavocidornelas, I believe the support for sklearn interface are straightforward, I will work on this and get back to you asap.
