### ISSUE TITLE
bug: incorrect tracing when batching is enabled

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#2989]
When batching is enabled, runner’s `/receive` span and any subsequent spans created in the service are always attributed towards the first trace id. The the trace of the first request will indefinitely grow as new requests arrive.

**Comment by parano** [comment]
Is this addressed in https://github.com/bentoml/BentoML/pull/2977?

**Comment by ssheng** [comment]
No but https://github.com/bentoml/BentoML/pull/2996 is intended to address it.
