### ISSUE TITLE
ONNX Runner Only return first of the outputs!

### ISSUE THREAD

**Issue by cristozz** [bentoml/BentoML#3007]
https://github.com/bentoml/BentoML/blob/28f0bc320637851a158cafaed90ef15bb87fe82a/bentoml/_internal/frameworks/onnx.py#L415

I have a onnx model that have two outputs ['label', 'probabilities'] but when i use RUN only return 'label' values, and i dont see any configuration to return all outputs.

**Comment by petcai** [comment]
Hi guys, I am wondering whether we have any progress on this issue. Thanks

**Comment by parano** [comment]
Hi @petcai sorry about the delay in getting back to you here, this issue has been fixed in #2912 and released since 1.0.7
