### ISSUE TITLE
bug: ran out of resources with --production flag

### ISSUE THREAD

**Issue by Max-Rubino** [bentoml/BentoML#3037]
### Describe the bug

When i run the bentoML CLI with the --production flag then all the cpus and ram are running out of resourses.
![image](https://user-images.githubusercontent.com/57390521/192227984-339bde98-7149-47ce-a57c-8012f9cdcd55.png)

I did several experiments also with the  [Intro Tutorial](https://docs.bentoml.org/en/latest/tutorial.html)  and I have the same problem, but only for first 10 seconds and then the API works fine.

Is it possible that the size of the service is causing this problem?
Example:
![image](https://user-images.githubusercontent.com/57390521/192232687-13cc1495-1f4c-4e5b-9c2f-02de5642ecd9.png)

### Environment

`bentoml`: 1.0.5
`python`: 3.7.12
`platform`: Linux

**Comment by aarnphm** [comment]
Hi @Max-Rubino, can you send us the output of `bentoml env` as well as the bento?

you can export the bento with `bentoml export my_bento:latest`

**Comment by Max-Rubino** [comment]
[iris_classifier-7mx4mxkivg5nqodi.zip](https://github.com/bentoml/BentoML/files/9746952/iris_classifier-7mx4mxkivg5nqodi.zip)

**Comment by parano** [comment]
Hi @Max-Rubino - this is likely due to too many API workers being launched at the same time, could you try `bentoml serve` with `--api-workers=1`?
