### ISSUE TITLE
bug: pandas IO descriptor

### ISSUE THREAD

**Issue by jiewpeng** [bentoml/BentoML#3086]
### Describe the bug

When a user constructs a `PandasDataFrame` IODescriptor using `from_sample()`, it creates a broken IODescriptor.

```python
inst = cls(
    orient=orient,
    enforce_shape=enforce_shape,
    shape=sample_input.shape,
    apply_column_names=apply_column_names,
    columns=[str(x) for x in list(sample_input.columns)],
    enforce_dtype=enforce_dtype,
    dtype=True,  # set to True to infer from given input
    default_format=default_format,
)
```

Specifically, when calling `from_http_request`, there is a line that asserts that `self._dtype` is not a boolean, but when we create the IODescriptor using `from_sample`, it sets `dtype` to `True`.

```python
obj = await request.body()
if serialization_format is SerializationFormat.JSON:
    assert not isinstance(self._dtype, bool)
```

Currently, I work around this by setting `self._dtype = None` after constructing the IODescriptor using `from_sample()`.

### Environment

bentoml: v1.0.7
python: 3.8.14
platform: Linux-5.4.209-116.367.amzn2.x86_64-x86_64-with-glibc2.2.5

**Comment by frostming** [comment]
Use the new BentoML IO descriptors please
