### ISSUE TITLE
bug: Detectron2 installation error during bentoml containerize

### ISSUE THREAD

**Issue by shinilseop** [bentoml/BentoML#3093]
### Describe the bug

I am going to serve the Detectron2 model using BentoML.
Also, I want to image through bentoml containerize function.

However, an error occurs during containerize when installing Python dependencies.
bentofile.yaml is as follows:
```yaml
service: "main:svc"
labels:
  owner: so1s
  stage: dev
include:
  - "*.py"
  - "*.txt"
docker:
  distro: debian
  python_version: "3.8.12"
  cuda_version: "11.6.2"
  system_packages:
    - git
  env:
    - INPUT_TYPE=image
    - OUTPUT_TYPE=image
    - MODEL_NAME=detectron2basic
    - LIBRARY=detectron2
python:
  packages:
    - "torch==1.12.0+cu116"
    - "torchvision==0.13.0+cu116"
    - "torchaudio==0.12.0"
    - "pyyaml==5.1"
    - "opencv-python==4.6.0.66"
    - "git+https://github.com/facebookresearch/detectron2.git"
  extra_index_url:
    - "https://download.pytorch.org/whl/cu116"
```

```
bentoml build
bentoml containerize modelname:tag --network host --verbose --platform=linux/amd64
```

Containerize ends with an error that there is no 'torch' module while checking the dependency of detectron2 :
```bash
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/2n/bdz7z2vj7179hs0n6zy3pwbc0000gn/T/pip-install-vwe148tw/detectron2_3d76682006014f2f8d7a5e69c14bfad6
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /private/var/folders/2n/bdz7z2vj7179hs0n6zy3pwbc0000gn/T/pip-install-vwe148tw/detectron2_3d76682006014f2f8d7a5e69c14bfad6
  Resolved https://github.com/facebookresearch/detectron2.git to commit 7c2c8fb168a2093ce06a531c1208fba48d2984ec
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2n/bdz7z2vj7179hs0n6zy3pwbc0000gn/T/pip-install-vwe148tw/detectron2_3d76682006014f2f8d7a5e69c14bfad6/setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I can't set the order for pip installation. 
So I couldn't find a way to resolve the error.

The only way I found it is to set up the detector2 module separately after bentoml containerize through Dockerfile.template.
https://docs.bentoml.org/en/latest/guides/containerization.html#dockerfile-template

Is there a better way than this?

### Environment

bentoml: 1.0.5
python: 3.8.12
os: mac os (m1)

**Comment by RGuven** [comment]
did you solve the error? I'm getting the same error too.
I don't want to configure Dockerfile.template, there should be a cleaner way to do it.

BENTOML_VERSION=1.0.20
os: mac os (m1)

**Comment by aarnphm** [comment]
This is not a bug, rather than a usage question

See https://github.com/bentoml/OCR-as-a-Service/blob/main/Dockerfile.template and https://github.com/bentoml/OCR-as-a-Service/blob/main/bentofile.yaml for setting up detectron.

**Comment by aarnphm** [comment]
This has to do with detectron requiring torch first. With the requirements.txt, it will always respect the dependencies from git before everything, hence the error
