### ISSUE TITLE
bug:  failed to decode byte in position 1 for remote runner.

### ISSUE THREAD

**Issue by bharath-krishna** [bentoml/BentoML#3120]
### Describe the bug

Build a bento from quickstart example, build and pushed image via builder pod,
then calling /classify endpoint of quickstart example is throwing error as above,

`curl -X 'POST' \
  'https://<host>/classify' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '[
  [
    4.9,
    3,
    1.4,
    0.2
  ]
]'`

The only changes I have made to builder yaml file and docker file is adding proxy env vars

The output inside the container is as below
<img width="1725" alt="Screen Shot 2022-10-19 at 12 48 35 PM" src="https://user-images.githubusercontent.com/7752784/196754283-d9abe84d-4b26-4e35-a0f9-994a880edfeb.png">

running `bentoml serve service.py:svc --verbose` inside Bento directory does not show this error and returns expected result.

### To reproduce

To reproduce the bug one needs to build any example service from bentoml and deploy that image via yatai-deployment, then call predict/classify endpoint via swagger UI or curl in a private cluster.

May be need to add custom proxy env vars which is required for my infrastructure.

### Expected behavior

return prediction result similar as 
`{
  "prediction": 2
}
`

### Environment

bentoml: v1.0.5
python: 3.9
platform: linux-amd64

**Comment by aarnphm** [comment]
Can you try to update to the latest version and try if you still this bug?

**Comment by bharath-krishna** [comment]
Yes updated to v1.0.7 and getting has this bug

**Comment by aarnphm** [comment]
Can you share your service definition?

**Comment by bharath-krishna** [comment]
`$> k -n yatai get svc test`

```apiVersion: v1
kind: Service
metadata:
  annotations:
    yatai.ai/bento-repository: iris_fastapi_demo
    yatai.ai/bento-version: cht2j7bza2pfvyuh
  creationTimestamp: "2022-10-19T15:57:42Z"
  labels:
    yatai.ai/bento-deployment: test
    yatai.ai/bento-deployment-component-type: api-server
    yatai.ai/bento-repository: iris_fastapi_demo
    yatai.ai/bento-version: cht2j7bza2pfvyuh
    yatai.ai/creator: yatai-deployment
  name: test
  namespace: yatai
  ownerReferences:
  - apiVersion: serving.yatai.ai/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: BentoDeployment
    name: test
    uid: f46fcaad-c624-4f34-8912-dedec0d3ee4e
  resourceVersion: "130005193"
  uid: de01f16e-33bf-4162-9f33-d859a3324a12
spec:
  clusterIP: 10.98.80.157
  clusterIPs:
  - 10.98.80.157
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    yatai.ai/bento-deployment: test
    yatai.ai/bento-deployment-component-type: api-server
    yatai.ai/bento-repository: iris_fastapi_demo
    yatai.ai/bento-version: cht2j7bza2pfvyuh
    yatai.ai/creator: yatai-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
Is this what your were asking?

**Comment by aarnphm** [comment]
I was thinking about your service.py, but this is helpful as well

**Comment by bharath-krishna** [comment]
Oh ok, I used examples from BentoML repo, and have not made any changes in it.
https://github.com/bentoml/BentoML/blob/main/examples

I can run them locally with 
`bentoml serve service:svc --reload`
and it works fine locally, but not when I build image in a builder pod, push and deploy.

**Comment by bharath-krishna** [comment]
I containerize Bento locally and ran as in doc and got same error, Some problem with containerizing Bento.
Let me also mention this error was not occurring **three days back**.

I am not sure what changed in latest version.
Currently I am using bentoml==1.0.7
yatai: v1.0.0-d7-6c68b8e

**Comment by bharath-krishna** [comment]
Please ignore this ticket.
The issue was due to setting proxy env vars in ENV in Dockerfile instead of exporting in RUN stage.
after reverting its working.
