### ISSUE TITLE
Assigning to BentoService field

### ISSUE THREAD

**Issue by lambdaofgod** [bentoml/BentoML#316]
**Is your feature request related to a problem? Please describe.**
I need to create a service that is able to handle new objects/fields added during it's lifetime. One of my methods gets called with data that is then supposed to be added to make querying it possible.

**Describe alternatives you've considered**
I tried assigning to field in method that does the setup. This doesn't work, after that other methods don't see that the field got assigned.
I also tried using artifacts: I packed needed fields with Nones, and then tried changing them. This also doesn't work, the corresponding fields seem unchanged.

**Additional context**
I'm trying to build a service that wraps kNN engine with model that does feature extraction (let's say we want to search text/images and we have appropriate neural network that does feature extraction, then we want to perform kNN on its output representation). The service is supposed to be built with a model. Then it can receive appropriate data and it will build kNN model that enables searching it.

**Comment by parano** [comment]
hi @lambdaofgod, do you mind sharing some of your source code, especially your BentoService class code? 

Also, are you serving the model via a REST API? did you run it via docker or the serve_gunicorn command? In that case, it may load in multiple instances of your BentoService class, so the second predictions request does not get the field you assigned because the prediction request may get sent to a different worker. If that's the case, I think it's super interesting for us to look into.

**Comment by lambdaofgod** [comment]
That's right, I'm getting this while using REST API. 
Is there a way to limit number of workers?
What are other alternatives?

**Comment by parano** [comment]
@lambdaofgod  yes, if you are using the `bentoml serve-gunicorn` cli command, you can use the `-w` parameter to specify number of workers. And if you are using docker, you can configure it via environment variable: `docker run -e "BENTOML__APISERVER__DEFAULT_GUNICORN_WORKERS_COUNT=1" MY_API_SERVER_IMAGE`

**Comment by parano** [comment]
I think other alternatives you could consider are using something like Redis or Plasma(in apache arrow project) to share data between multiple nodes. One thing we considered on our roadmap is using Plasma to allow sharing data between user API callbacks across multiple threads or nodes efficiently, which might help with your use case. 

Let me know if you'd be open to sharing more details about your project, so we could determine if what we are planning to implement can help. Feel free to ping me on the bentoml slack channel.

**Comment by parano** [comment]
@lambdaofgod closing this issue now - let me know if limiting to one worker worked for your use case - and for others looking to solve similar problem but want to use multiple gunicorn workers or multiple nodes, we'd recommend looking into in-memory database such as Redis.  Integrating with Plasma is still on our roadmap for 2020.
