### ISSUE TITLE
bug: from_sample factory for bentoml.io.PandasDataFrame doesnt work

### ISSUE THREAD

**Issue by subramaniam20jan** [bentoml/BentoML#3169]
### Describe the bug

There seems to be an obvious bug [here](https://github.com/bentoml/BentoML/blob/3193102e13bbd228a8466e308db34cde8c974afe/src/bentoml/_internal/io_descriptors/pandas.py#L557), where the dtype is set to a boolean and then checked [here](https://github.com/bentoml/BentoML/blob/3193102e13bbd228a8466e308db34cde8c974afe/src/bentoml/_internal/io_descriptors/pandas.py#L432) to not be boolean. I tried to circumvent this issue by skipping this factory but couldnt get it to work either.

Simply running the example code [here](https://docs.bentoml.org/en/latest/reference/api_io_descriptors.html#bentoml.io.PandasDataFrame.from_sample), should be able to hit the issue

### To reproduce

Contents of service.py

```python
import pandas as pd
import bentoml
from bentoml.io import PandasDataFrame
arr = [[1,2,3]]
input_spec = PandasDataFrame.from_sample(pd.DataFrame(arr))

svc = bentoml.Service("test")

@svc.api(input=input_spec, output=PandasDataFrame())
def predict(inputs: pd.DataFrame) -> pd.DataFrame:
  return pd.DataFrame([[1]])
```

### Expected behavior

Returns a single static prediction.

Instead throws an error:
```prolog
Traceback (most recent call last):
  File "/home/subu/.local/lib/python3.10/site-packages/bentoml/_internal/server/http_app.py", line 298, in api_func
    input_data = await api.input.from_http_request(request)
  File "/home/subu/.local/lib/python3.10/site-packages/bentoml/_internal/io_descriptors/pandas.py", line 378, in from_http_request
    assert not isinstance(self._dtype, bool)
AssertionError
```

### Environment

bentoml: 1.0.7
python: 3.10

**Comment by aarnphm** [comment]
Can you try again with 1.0.10. We recently update the `from_sample` implementation.

**Comment by sobayed** [comment]
I'm encountering the same issue with 1.0.10. See [here](https://github.com/bentoml/BentoML/blob/v1.0.10/src/bentoml/_internal/io_descriptors/pandas.py#L422) for the respective line.

**Comment by aarnphm** [comment]
Hi there again. I have tested this with the latest version and I didn't encounter the error.
