### ISSUE TITLE
bug: Not able to execute listed pytest

### ISSUE THREAD

**Issue by kpg993** [bentoml/BentoML#3174]
### Describe the bug

ERROR integration/projects/general_non_batch/tests/test_adapter.py
ERROR integration/projects/general_non_batch/tests/test_artifact.py
ERROR integration/projects/general_non_batch/tests/test_meta.py
ERROR integration/projects/general_non_batch/tests/test_microbatch.py
ERROR integration/projects/paddle/tests/test_service.py
import file mismatch:
imported module 'test_adapter' has this __file__ attribute:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general/tests/test_adapter.py
which is not the same as the test file we want to collect:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general_non_batch/tests/test_adapter.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
___________________________________________________________ ERROR collecting tests/integration/projects/general_non_batch/tests/test_artifact.py ___________________________________________________________
import file mismatch:
imported module 'test_artifact' has this __file__ attribute:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general/tests/test_artifact.py
which is not the same as the test file we want to collect:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general_non_batch/tests/test_artifact.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____________________________________________________________ ERROR collecting tests/integration/projects/general_non_batch/tests/test_meta.py _____________________________________________________________
import file mismatch:
imported module 'test_meta' has this __file__ attribute:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general/tests/test_meta.py
which is not the same as the test file we want to collect:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general_non_batch/tests/test_meta.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
__________________________________________________________ ERROR collecting tests/integration/projects/general_non_batch/tests/test_microbatch.py __________________________________________________________
import file mismatch:
imported module 'test_microbatch' has this __file__ attribute:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general/tests/test_microbatch.py
which is not the same as the test file we want to collect:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/general_non_batch/tests/test_microbatch.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_________________________________________________________________ ERROR collecting tests/integration/projects/paddle/tests/test_service.py _________________________________________________________________
import file mismatch:
imported module 'test_service' has this __file__ attribute:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/fastai2/tests/test_service.py
which is not the same as the test file we want to collect:
  /Users/kanupriyagoyal/Documents/BentoML/tests/integration/projects/paddle/tests/test_service.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules

I removed the __pycache__ / .pyc, provided the path of build, getting port error
  AssertionError: Timed out waiting 20 seconds for Server 127.0.0.1:44025 to be ready, exception: <urlopen error [Errno 111] Connection refused>

integration/utils.py:80: AssertionError
================================================================== short test summary info ===================================================================
ERROR integration/projects/general_non_batch/tests/test_adapter.py::test_api_server_image - AssertionError: Timed out waiting 20 seconds for Server 127.0.0.1:44025 to be ready, exception: <urlopen error [Errno 111] Connection refused>
ERROR 

### Expected behavior

All the pytest should be passed on installation of bentoml

### Environment

x86 machine
s390x machine
docker image
conda environment python 3.9.12

**Comment by kpg993** [comment]
Using Bentoml-0.13.2-LTS

**Comment by aarnphm** [comment]
Hi there. We aren't actively maintaining 0.13.x. I'm wondering if there are any reason that block your migration to 1.0?

See https://docs.bentoml.org/en/latest/guides/migration.html

**Comment by kpg993** [comment]
Thanks for the input, i will try for the higher version.
