### ISSUE TITLE
chore: 3.11 Support

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3179]
A few things for supporting 3.11:
- BentoML loosely depends on pyarrow (which is currently doesn't have 3.11 yet).
- aiohttp (internally we are intending to switch to httpx, so this might not be a huge deal anymore.)

We should probably create a follow-up to #3074 for 3.11 support.

**Comment by KimSoungRyoul** [comment]
I think that BentoML 3.11 support is available for consideration.
