### ISSUE TITLE
bug: cli not respecting flags

### ISSUE THREAD

**Issue by alizia** [bentoml/BentoML#3184]
### Describe the bug

The CLI tool does not respect the flags passed to it. I've noticed the following odd behaviors with `bentoml serve`:

--api-workers <int>: Ignores the flag and starts workers equal to the number of cores

--quiet: Actually has the opposite effect and starts loging verbosely. It starts printing DEBUG logs as well instead of stopping printing INFO and WARN logs.
 

### To reproduce

run `bentoml serve service.py:svc --quiet --api-workers 4`

### Environment

`bentoml`: 1.0.0
`python`: 3.8.10
`platform`: Linux-5.15.0-1022-aws-x86_64-with-glibc2.29
`uid:gid`: 1000:1000

**Comment by aarnphm** [comment]
can you upgrade to the latest bentoml version? I believe we did fix this in the newer version.

**Comment by alizia** [comment]
sounds good @aarnphm. let me try out the new version.

**Comment by alizia** [comment]
@aarnphm you're right. works fine in the new version. I'll close the ticket. thanks.
