### ISSUE TITLE
feature: Support For Microsoft FLAML

### ISSUE THREAD

**Issue by VikramxD** [bentoml/BentoML#3193]
### Feature request

Feature request
Support the ML framework  Microsoft Flaml [microsoft.github.io/FLAML/](https://microsoft.github.io/FLAML/)

### Motivation

Motivation
Microsoft FLAML is a popular AutoML library currently there is no native support present for it in Bentoml , we have to use the models for inference by fitting it into a sklearn pipeline , if native support for Flaml objects can be added that would be helpful

**Comment by frostming** [comment]
We will not maintain this framework as a build-in support, instead, community can support is as an extension. Thanks
