### ISSUE TITLE
feature: JSON(pydantic=PydanticModel, sequence=True). -> List[PydanticModel]

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/BentoML#3194]
### Feature request

Hi  Is it not intentionally supporting the Pydantic model Type which is wrapped as a Sequence Type?

**Comment by Plozano94** [comment]
Would be nice, I cant find the best way to do this. Did you achieve it?

**Comment by aarnphm** [comment]
Hi @KimSoungRyoul, after a quick discussion internal, we are going to add two new IO descriptor, `bentoml.io.PydanticModel` and `bentoml.io.AttrsClass`, that extends the functionality of JSON and support newer feature.

I think that having support sequence is nice, lets make a new feature request for it.

Will close this in place of the new one
