### ISSUE TITLE
feature: Explainable AI supports for BentoML

### ISSUE THREAD

**Issue by yangwenz** [bentoml/BentoML#3232]
### Feature request

We have developed an open source project OmniXAI for explainable AI: https://github.com/salesforce/OmniXAI, and implemented an interface for deploying OmniXAI explainers using BentoML: https://github.com/salesforce/OmniXAI/blob/main/omnixai/deployment/bentoml/omnixai.py. Is it possible to integrate it directly in BentoML?

We are happy to provide more supports for it to extend BentoML's capabilities.

**Comment by frostming** [comment]
We will not maintain this framework as a build-in support, instead, community can support is as an extension. Thanks
