### ISSUE TITLE
feature: customize readme with jinja

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/BentoML#3233]
### Feature request

https://docs.bentoml.org/en/latest/concepts/bento.html#description

customize readme.md with argument
`REMAEME.md`
~~~
# {{svc.name}}:{{svc_version}}

I am custom description 
...
~~~

after execute `bentoml build --version="new_version"`
`REMAEME.md`
~~~
# iris:new_version

I am custom description 
...
~~~

**Comment by aarnphm** [comment]
close this feature request as it is not necessary for now.
