### ISSUE TITLE
feat: Client support for re-written URLs

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#3258]
User rewrites the URLs at the ingress by adding the bento name as the path, e.g. from /docs.json to /{bento_name}/docs.json. As a result, the [Swagger UI link](https://github.com/bentoml/BentoML/blob/35cd25c043ae5c85c622f99654df6a67dadf6cbb/src/bentoml/_internal/server/static_content/swagger-initializer.js#L4) and the [Bento Client dummy server](https://github.com/bentoml/BentoML/blob/4220b5190dadd76d3ec19c855c6be6eb0b8221ee/src/bentoml/client.py#L72) no longer work.
- The Swagger UI may be an easier fix by changing the link to ./docs.json
- The Bento Client is trickier. Do you think it makes sense to ask for the docs.json URL instead of just the host URL? cc: 
[@sauyon](https://bentoml-team.slack.com/team/U02J31G8H08)

**Comment by mqk** [comment]
I'm a little unclear on how the "Bento Client dummy server" comes into play, and whether it's even necessary to fix that to satisfy our use case. If we have a properly deployed service running in production and simply navigate to the service's url (without any endpoint) is that just calling the Swagger UI link or is it somehow also involving the dummy server? What I'm getting at is that we just want to be able to access the Swagger page from our API gateway (https://api_gateway_hostname/models/{bento_name}/). Perhaps just making the first change (to `./docs.json`) would be sufficient for that purpose?

**Comment by ssheng** [comment]
@mqk with #3381 and #3394, the ability to generate the bento client with rewritten bento URLs should be support. We will release this feature in `v1.0.13` next week.
