### ISSUE TITLE
feature: `client.health`

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3315]
### Feature request

client to have a health function:
```python
client.health()
await client.async_health()
```

### Motivation

For HTTP, would probably just need to invoke `/readyz`, and for gRPC is to invoke the `Health` rpc from `grpc.health.v1.HealthServicer`.

**Comment by sanspareilsmyn** [comment]
@aarnphm Hi! I'm a newbie to BentoML. May I work on this issue?

**Comment by aarnphm** [comment]
Hi there, feel free to pick up this issue after https://github.com/bentoml/BentoML/pull/3280 is merged.

**Comment by denyszhak** [comment]
Has anyone started this one? It's being here for a while

**Comment by aarnphm** [comment]
feel free to pick it up. The client.health is already implemented for gRPC client. You can go a head and implement for HTTP client.
