### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'

### ISSUE THREAD

**Issue by HenryDashwood** [bentoml/BentoML#335]
I don't suppose you've come across the this error which crops up when running the following cells. I've been trying to adapt the Fastai Pets classification notebook to a regression problem where the model outputs a Fastai ImagePoints object.
![Screenshot 2019-10-12 at 00 00 23](https://user-images.githubusercontent.com/17177967/66689943-2d84e380-ec85-11e9-8086-85529186f246.png)

**Comment by parano** [comment]
hi @HenryDashwood, it looks like an issue with BentoML and the [click](https://click.palletsprojects.com/en/7.x/) package. BentoML currently does not specify a version requirement for click and I think you might have an older version installed. Could you try `pip install -U click` and try again?

If you still see the error, would be great if you could share your python version, BentoML version, and `pip freeze` output.

**Comment by HenryDashwood** [comment]
Nice. That did indeed work. Thanks for such a swift reply!

**Comment by parano** [comment]
Great to know! Thanks again for reporting the issue @HenryDashwood, I will follow up with a PR that enforces a minimum click version check.
