### ISSUE TITLE
KerasModelArtifact#pack expects type: keras.engine.training.Model

### ISSUE THREAD

**Issue by ghunkins** [bentoml/BentoML#336]
**Describe the bug**
`KerasModelArtifact` fails on `Service.pack` due to `isinstance` check on the passed model. Root cause seems to be conflicting definitions between `keras.engine.training.Model` and `tensorflow.python.keras.engine.training.Model`.

Expected behavior is the allowance of both `Keras` trained and `tf.keras` trained models. Additionally, `import keras` may fail for those only working with `tensorflow`.

**Root Cause**

```python
import keras
from tensorflow.python import keras as tf_keras

# create dummy Keras model
a = keras.layers.Input(shape=(32,))
b = keras.layers.Dense(32)(a)
model = keras.models.Model(inputs=a, outputs=b)

# this passes
assert isinstance(model, keras.engine.training.Model)
# this fails
assert isinstance(model, tf_keras.engine.training.Model)
```

**To Reproduce**

Using `bentoml==0.4.3`, `keras==2.2.5`, and `tensorflow==1.13.1`.

```python
import keras
import bentoml

@bentoml.artifacts([bentoml.artifacts.KerasModelArtifact('keras_model')])
class TestService(bentoml.BentoService):
    pass

# create model
a = keras.layers.Input(shape=(32,))
b = keras.layers.Dense(32)(a)
keras_model = keras.models.Model(inputs=a, outputs=b)

# attempt service creation
service = TestService.pack(keras_model=keras_model)
```

This produces:
```python
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    service = TestService.pack(keras_model=keras_model)
  File "/Users/ghunk/miniconda3/envs/test/lib/python3.7/site-packages/bentoml/service.py", line 505, in pack
    artifact_instance = artifact_spec.pack(kwargs[artifact_spec.name])
  File "/Users/ghunk/miniconda3/envs/test/lib/python3.7/site-packages/bentoml/artifact/keras_model_artifact.py", line 92, in pack
    "KerasModelArtifact#pack expects type: keras.engine.training.Model"
ValueError: KerasModelArtifact#pack expects type: keras.engine.training.Model
```

**Expected behavior**

The above test to pass.

**Screenshots/Logs**

Logs above.

**Environment:**
 - OS: MacOS 10.13.6
 - Python/BentoML Version: Python 3.7.3, BentoML-0.4.3

**Additional context**

See comments on [this PR](https://github.com/bentoml/BentoML/pull/334/files/7a23943b17a3888ed309490d122e9d4bf59c3c2a#r334210378) for more context.

Similar open tensorflow [issue](https://github.com/tensorflow/tensorflow/issues/23216).

**Comment by parano** [comment]
Thanks for the detailed notes @ghunkins, just created a PR addressing this issue, feel free to check it out here: https://github.com/bentoml/BentoML/pull/341
