### ISSUE TITLE
Failed to create deployment deployment-name. INTERNAL: Docker is required for this deployment. Please visit www.docker.come for instructions

### ISSUE THREAD

**Issue by Mahathi-Bhagavatula** [bentoml/BentoML#338]
Hi,
I am getting this error when I am trying to deploy my code into aws-lambda. Can I know the reason for this error please.

**Comment by Mahathi-Bhagavatula** [comment]
after saving the service to a path and could successfully do pip install path. But when I give the same version and name to deployment, it is throwing the error.

**Comment by parano** [comment]
hi @Mahathi-Bhagavatula, you are seeing this error because the AWS Lambda deployment feature requires you to have Docker installed on your machine, we use docker to pre-download all the pip dependencies in a Linux environment and bundle them for use in AWS Lambda environment.

If you are doing this for local development, the easiest way is to install the Docker Desktop app from here: https://www.docker.com/products/docker-desktop

**Comment by Mahathi-Bhagavatula** [comment]
Hi Parano. Thanks for the reply.
I have installed docker. Then I got this issue. Can I know how to solve this.
Failed to create deployment. INTERNAL: None

**Comment by parano** [comment]
Hey @Mahathi-Bhagavatula, I will need more information to help you debug this issue, could you try the following and share with us the logs?

```bentoml --verbose deployments delete {YOUR_DEPLOYMENT_NAME} --force```

and run ```bentoml --verbose deployments create ....``` again?

**Comment by Mahathi-Bhagavatula** [comment]
Here is my error message 

[2019-10-15 00:47:05,409] DEBUG - Using BentoML with local Yatai server
WARNING: No swap limit support
[2019-10-15 00:47:05,656] DEBUG - Created temporary directory: /tmp/bentoml-temp-9bzum78o
Failed to create deployment lyrics-write1. INTERNAL: None

**Comment by parano** [comment]
@Mahathi-Bhagavatula  could you share more of your environment information?  Python version, BentoML version, NodeJS version, and Operating System?

**Comment by parano** [comment]
@Mahathi-Bhagavatula  feel free to ping me on Slack channel if you need more help on this, it may also be a bug we recently fixed, you can try upgrade BentoML to latest version with `pip install -U bentoml`

**Comment by parano** [comment]
@Mahathi-Bhagavatula we just made a new release 0.4.5 fixing a few issues with serverless deployment and it should resolve the issue you were seeing. You can upgrade BentoML and try it again: ```pip install -U bentoml```

**Comment by parano** [comment]
Closing the issue now, @Mahathi-Bhagavatula feel free to reopen if you see this error again after upgrade BentoML.

**Comment by cianoh** [comment]
I have also encountered this error when running with bentoml 0.13.1 and docker 20.10.8
`bentoml containerize ModelService:latest --yatai-url=127.0.0.1:50051`

**Comment by mcastrogg** [comment]
Same issue. Can build locally but when attempting to containerize from yatai I get the following error: 
Command:
`bentoml containerize xxxx:latest --yatai-url=xxxx`

Output:
`Found Bento: https:/xxxxx.s3.amazonaws.com/....`
`Error: bentoml-cli containerize failed: Failed to containerize xxxx:xxxx - INTERNAL:Docker is required for this deployment. Please visit www.docker.com for instructions`

**Comment by parano** [comment]
@mcastrogg did you confirm that docker is running and configured correctly?

**Comment by mcastrogg** [comment]
@parano Thanks for the reply. Yes Docker was running on both the yatai box and the ec2 instance that was running the `bentoml containerize` command. Checked that both were running via `docker info`

**Comment by parano** [comment]
@mcastrogg could you share a bit more how Yatai was deployed? Is it running in its own container? and did you deploy with the Yatai Kubernetes helm chart that we provide?
