### ISSUE TITLE
bug: Error: [bentoml-cli] `containerize` failed: Failed to use backend docker.

### ISSUE THREAD

**Issue by chrisjune** [bentoml/BentoML#3389]
### Describe the bug

I installed bentoml in the python docker image and used it as a builder image, and in the Jenkins file, bentoml containerize in the form of docker in docker, becase I don't want to install bentoml in Jenkins server.

The bentoml 1.0.7 version worked well, but the latest version (1.0.12) shows the following error message. 

```
Error: [bentoml-cli] `containerize` failed: Failed to use backend docker.
```
For now, the issue has been resolved while fixing the version to 1.0.7.
Has anyone experienced similar symptoms?

### To reproduce

[1] Dockerfile
```Dockerfile
FROM python:3.9-slim-buster

RUN apt-get update
RUN apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt-get update
RUN apt-get install -y docker-ce docker-ce-cli containerd.io

...

RUN pip install -r requirements.txt
```
[2]Jenkinsfile
```jenkinsfile
docker build -t builder .
docker run --rm -i -v `pwd`:/src -v /var/run/docker.sock:/var/run/docker.sock builder bentoml containerize service:latest
```

### Expected behavior

bentoml containerize should work without error

### Environment

python-3.9-slim-buster
bentoml: 1.0.12

**Comment by aarnphm** [comment]
Hi @chrisjune, can you send the content of your reuqirements.txt?

**Comment by chrisjune** [comment]
[1] requirements.txt
```text
numpy==1.23.*
requests==2.28.*
bentoml==1.0.7
torch==1.12.*
torchvision==0.13.*
pydantic==1.10.*
sentry-sdk==1.11.*
```

[2] output error?
No!
Once I have built a docker image with the command `bentoml containerize`, there has never been a problem running it. 
In my case, it always happened when I was in the container.

**Comment by aarnphm** [comment]
Might be related to #3366. But I think that it might be beneficial to also surface errors from backends.

**Comment by aarnphm** [comment]
Please try again with the recent 1.0.13 release to see if you still run into this issue.

**Comment by chrisjune** [comment]
> Hi @chrisjune, Just a quick q. Is service:latest the name of the bento?
Yes!

Unfortunately, I have left the company that wrote the code now, 
so I cannot reproduce the situation. But thank you so much for your help.
