### ISSUE TITLE
refactor: migrate current `bentoml.testing` to use `bentoml.client`

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3411]
### Feature request

With https://github.com/bentoml/BentoML/pull/3028 it introduces `bentoml.client`.

Currently what we are doing under `bentoml.testing` are essentially doing what `bentoml.client` is doing.

This refactor would make `bentoml.testing` more clean and dry ;)

**Comment by DhanshreeA** [comment]
Hey is this good to take up? :grimacing:

**Comment by aarnphm** [comment]
Yes feel free to get started with this. Feel free to DM me on slack for more information.

**Comment by spyrosavl** [comment]
Hi, @DhanshreeA are you working on it? If not I can pick this up?

**Comment by PierreYoon0129** [comment]
@aarnphm @DhanshreeA Hi there! If you are stucked with this issue, may I try instead? Have a great day:)
