### ISSUE TITLE
API Query parameters

### ISSUE THREAD

**Issue by EmilieDel** [bentoml/BentoML#3415]
### Feature request

Using BentoML for several projects, I was wondering if it is possible to specify query parameters as with fastapi: https://fastapi.tiangolo.com/tutorial/query-params/ ? This would then allow the URL to be of the schema
```
http://$HOST:$PORT/$SERVICE/?$PARAM=$VALUE
```

Thank you very much for your answer,

Emilie

**Comment by EmilieDel** [comment]
Hello @ssheng, 
Thank you very much for your quick reply!
I don't think it is a must have for me. I just wanted to ask if it is possible or not :)

**Comment by ssheng** [comment]
@EmilieDel, using query parameters to pass argument is not currently possible. Work is needed on the OpenAPI site.

**Comment by EmilieDel** [comment]
Thank you for the reply! No problem, it is not a must have on my side!
