### ISSUE TITLE
feature(cli): support parsing space for deletion

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3418]
### Feature request

Right now we don't support parsing space

```python
bentoml models delete model1 model2 ...
```
will fail.

Note that we can already do

```python
bentoml models delete model1,model2
```

**Comment by starkensin** [comment]
Could I try this feature?

**Comment by aarnphm** [comment]
yes please go ahead. Feel free to ping me if you run into any issues.

Some place to start with:
- https://github.com/bentoml/BentoML/blob/main/src/bentoml_cli/models.py and https://github.com/bentoml/BentoML/blob/main/src/bentoml_cli/bentos.py

**Comment by starkensin** [comment]
I have some questions to clarify this issue.

1. When I read the document, https://docs.bentoml.org/en/latest/reference/cli.html#bentoml-models-delete
there is already multiple model deletion feature.
`e.g.: benotml models delete iris_clf:v1,iris_clf:v2`
What is the goal of this issue?
I guess bentoml wants another way of deletion adding existing one. (seperate mutiple models with ',' or ' ')
If not, let me know and please clarify more about this issue.

2. Also, `b models delete model1 model2 ...` here, b means bentoml? 

3. You wrote two reference files `models.py` and `bentos.py`. Both has a similar feature of deletion. Do you intend to make feature about not only model deletion but also bentos.py?

**Comment by aarnphm** [comment]
1. I don't think we parse space correctly
	```bash
	b models delete iris_clf:v1 iris_clf:v2
	```
	So ideally we should be able to do this with different model as well
	```bash
	b models delete model1:asdf model2:v2
	```
2. ah yes force of habit I have `b` as an alias to `bentoml`.
3. Yes. they are similar. You can make two PR, one for parsing multiple models, then the second one is for multiple bentos

**Comment by aarnphm** [comment]
I don't think this is possible because `click.argument` doesn't support multiple. 😢

**Comment by sauyon** [comment]
(the above deleted comment was made in error; please disregard)

**Comment by OmkarMozar** [comment]
@sauyon @aarnphm Please review
