### ISSUE TITLE
refactor(grpc): `enable_so_reuseport` for `reserve_free_port` should be handled separately

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3446]
### Describe the bug

Right now, `enable_so_reuseport` is set under `reserve_free_port`, which is not correct. It should be a different function to set the existing port instead of using `reserve_free_port`.

### Environment

n/a

**Comment by frostming** [comment]
I reviewed the function and find `enable_so_reuseport` takes effect on a `socket` object, so it is fine to keep it there.

Close this first, we can revisit it in the future.
