### ISSUE TITLE
feature: default bento configuration file name 

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/BentoML#3452]
### Feature request

It is easy to make a mistake that set ENV `BENTOML_CONFIG=~~~`  must be included when running the docker. (if I made configuration file)

What do you think about set BENTOML_CONFIG at the time of `bentoml build`?
~~~
{% if `configuration.yaml` file exist %}
    ENV BENTOML_CONFIGURATION=./configuration.yaml
{% end if %}
~~~

**Comment by aarnphm** [comment]
This is not necessary. For configuration, you shouldn't include it inside the packaged bento, as bentoml configuration should be used during runtime.

There is already a default_configuration.yaml under `src/bentoml/_internal/configuration/v1/default_configuration.yaml` that applies all default values if user doesn't specify.

If user want to add it they can use a custom dockerfile template to do that.

**Comment by KimSoungRyoul** [comment]
thank you for your kind comment.

close issue

**Comment by aarnphm** [comment]
fwiw feel free to pick up some `good-first-issue` issues and `help-wanted` 😄
