### ISSUE TITLE
chore: passing `--resolver=backtracking` to pip-compile

### ISSUE THREAD

**Issue by aarnphm** [bentoml/BentoML#3457]
### Feature request

When locking requirements.txt for `bentoml build`, BentoML are utilizing `pip-tools`.

For this we need to pass in the `--resolver` args to pip-compile in `PythonOptions.write_to_bento` to address the following warning:

```prolog
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
```

**Comment by CheeksTheGeek** [comment]
took the chore and did it, so could you assign it to me please :))
