### ISSUE TITLE
bug: bentoml CLI containerize --output parameter

### ISSUE THREAD

**Issue by mtichy92** [bentoml/BentoML#3483]
### Describe the bug

Hello, we encounter this strange behaviour which seems like bug in CLI.
When running `bentoml containerize --opt output=type=registry --image-tag registry.gitlab.com/XXX --backend buildctl TAGGED_BENTO:TAG` it seems like the default --output parameter is not overridden and appears twice in actual command.
Either switching to --output type=registry does not help. Using default `--backend docker` does not help. Using `--push` or `--opt push` does not help (throwing `unknown flag: --push` error)

Traceback looks like this:
```
error: currently only single Exports can be specified (or Error response from daemon: exporter "registry" could not be found - when using docker)

Encountered exception while trying to building image: Command '['/opt/homebrew/bin/buildctl', 'build', '--local',
'context=/var/folders/jz/bb9zdtl57n70bp2bw1lg69km0000gn/T/tmpex446mo8fsTempFS/', '--local',
'dockerfile=/var/folders/jz/bb9zdtl57n70bp2bw1lg69km0000gn/T/tmpex446mo8fsTempFS/env/docker', '--frontend',
'dockerfile.v0', '--output', 'type=registry', '--output', 'type=docker,name=docker.io/registry.gitlab.com/XXX']' returned
non-zero exit status 1.
```

Can you please look at this? Since Yatai is far from being production ready we are trying to containerize and deploy bentos ourselves and this is blocker. Seems like not working on either of OCI backends supported.

Thank you!

### To reproduce

Steps to reproduce:

run any `bentoml containerize` command with `--opt output=type=registry`

### Environment

bentoml: 1.0.13 (also tested on 1.0.12)
python: 3.9.16
docker: 20.10.21
buildctl: 0.11.1

**Comment by KimSoungRyoul** [comment]
Apart from the bug fix, wouldn't this issue be solved if you did the following?

~~~
bentoml containerize iris_classifier:betk2ie5koavizx5 --opt output=type=image,name=registry.gitlab.com/XXX,push=true  --backend buildctl

~~~

**Comment by aarnphm** [comment]
I will take a look into this. Thanks for finding it.

**Comment by mtichy92** [comment]
@KimSoungRyoul Hello, thanks for the suggestion - you are right. If I do quick hack in bentoml/_internal/container/base.py line `cmds.extend(self.construct_build_args(**attrs))` to `cmds.extend(self.construct_build_args(**attrs)[:-2])` then your suggested command works fine.

**Comment by aarnphm** [comment]
Hi @mtichy92, https://github.com/bentoml/BentoML/pull/3484 should fix it, by removing the output completion to local docker.

**Comment by mtichy92** [comment]
@aarnphm Thank you, very fast response and solution!
