### ISSUE TITLE
AttributeError: module 'fastai' has no attribute 'basic_train'

### ISSUE THREAD

**Issue by sgaseretto** [bentoml/BentoML#358]
When running ````!bentoml serve {saved_path}``` in the fastai example on google colab ([here](https://colab.research.google.com/github/bentoml/gallery/blob/master/fast-ai/salary-range-prediction/fast-ai-salary-range-prediction.ipynb)) I'm getting the following error:
```
AttributeError: module 'fastai' has no attribute 'basic_train'
```
Any idea of how to solve this?

**Comment by parano** [comment]
@sgaseretto thanks for reporting this issue, this is a regression introduced in the latest version of BentoML, will follow up with a fix soon

**Comment by parano** [comment]
The fix has been merged to master, feel free to install from master and try it out: `pip install git+https://github.com/bentoml/BentoML.git`, will update here again when it's released to PyPI.

Thanks again @sgaseretto for reporting this!

**Comment by sgaseretto** [comment]
Great @parano, also thanks for the very quick response!

**Comment by parano** [comment]
@sgaseretto np! the fix is now in the latest release, just tested again on Google Colab and all the fastai notebooks work now! If you have already installed BentoML, you can upgrade with `pip install -U bentoml`
