### ISSUE TITLE
Google Cloud Run

### ISSUE THREAD

**Issue by impulsecorp** [bentoml/BentoML#360]
Do you plan to support deployment to Google Cloud Run (https://cloud.google.com/run/) like you do with AWS Lambda and Google Cloud Functions?

**Comment by parano** [comment]
hi @impulsecorp, we do have plans to support Google Cloud Run, it is the next deploy platform we are adding, following by Azure ML and Heroku. Before we add the support, one workaround is to use BentoML for building your model server docker image and then manually deploy the container to google cloud run.

Just curious what's the main reason you'd like to deploy to Google Cloud Run?

**Comment by impulsecorp** [comment]
Right now I am hosting some low usage Python ML algorithms on Algorithmia.com. It could get expensive if my usage increases, so at some point I might switch it to AWS or Google. I currently use an AWS Linux server as my primary server and don't use Docker or virtual environment. Over the years that has become a problem because older programs on my server stop working, like for example I upgrade to TensorFlow 2.

So switching to a serverless system would make things much easier for me.  I had seen AWS Lambda before but it seems to complicated for me to use (I am not much of a programmer). Today I saw Google Cloud Run for the first time and it seems easier. But none of the that really matters if I use BentoML because it seems easy to publish to AWS Lambda.

**Comment by parano** [comment]
Thanks for sharing @impulsecorp, that's very helpful. Have you tried deploying to AWS Lambda with BentoML yet? Would love to hear your thoughts and feedbacks on  it, especially in comparsion to your existing workflow with Algorithmia

**Comment by impulsecorp** [comment]
No, I haven't tried it yet.
