### ISSUE TITLE
feature: worker exception message preserved when worker throws exception handled as `RemoteException` by api_server.

### ISSUE THREAD

**Issue by avicennax** [bentoml/BentoML#3623]
### Feature request

ditto title.

Currently when a service runner predict function is executed by a worker any Python exceptions (AFAICT) will handled via api_server as `RemoteException`. This is fine except all information about the exception is lost with this generic exception message: 

```
bentoml.exceptions.RemoteException: An exception occurred in remote runner my_model_tag: [500] Internal Server Error
```

### Motivation

This would enable users you handle worker exceptions more effectively (return non-500s when appropriate) without forcing those functions (in my case service runner predict functions) to have to know about Bento by letting them raise whatever exceptions make sense and letting the api_server handle them accordingly.

**Comment by frostming** [comment]
This is no longer an issue on the new service API
