### ISSUE TITLE
lightgbm and predict_contrib not working when using get - shapley not available with get method

### ISSUE THREAD

**Issue by whatisAI** [bentoml/BentoML#3629]
Hello, 
I trained a lightgbm model which I have on disk. I would like to use the predict_proba parameter, but this does not work. 

These are the steps I followed
1. I trained a lightgbm model, saved it as a pkl file. 
2. In the training step I load it and save it using   bentoml.lightgbm.save_model("lgb_mymod",model_lgb)
3. If I do model  = bentoml.lightgbm.load_model("lgb_rr1") and then model.predict(sample_x, pred_contrib=True) it works
4. But if I load the model like we are supposed to with model_runner = bentoml.lightgbm.get("lgb_mymod:latest").to_runner() and then do model_runner.predict.run(sample_x3, predict_contrib=True) then I get the error TypeError: _run() got an unexpected keyword argument 'predict_contrib'

Please could you help me?

Many thanks

**Comment by whatisAI** [comment]
Do you think to be able to access the predict_contrib parameter I need to define a new runner?

**Comment by parano** [comment]
Hi @whatisAI, you will need to set the Runner signature, the easiest way to do that is add the option when saving the model:

```python
import bentoml
bentoml.xgboost.save_model(
    "ieee-fraud-detection",
    model_sm,
    signatures={
        "predict_proba": {"batchable": True},
    },
    custom_objects={
        "preprocessor": preprocessor
    }
)
```

Here's an example using prdict_proba:
https://github.com/bentoml/BentoML/pull/3590/files#diff-ee781af7db9fc2bee78bff098fc0d3df585d4e7aaf9fad0887b9610837c7454cR261-R271

**Comment by parano** [comment]
Hi @whatisAI, thanks for reporting the issue, yes this is limited by the default lightgbm runner implementation, which doesn't allow users to easily pass through additional parameters to `predict` method.

An easy workaround is to use BentoML's custom runner interface, see this example here: https://docs.bentoml.org/en/latest/concepts/runner.html#custom-model-runner

You could do something like this:

```python
bento_model = bentoml.lightgbm.get("my_model:latest")

class MyLightGBMRunner(bentoml.Runnable):
    SUPPORTED_RESOURCES = ("cpu",)
    SUPPORTS_CPU_MULTI_THREADING = True

    def __init__(self):
        self.model = bentoml.lightbm.load_model(bento_model)

    @bentoml.Runnable.method(batchable=False)
    def predict(self, input_data):
        return self.model.predict(input_data, predict_contrib=True)
```
