### ISSUE TITLE
feature: Custom exception management 

### ISSUE THREAD

**Issue by tkaraouzene** [bentoml/BentoML#3652]
### Feature request

Hi and thanks for this library!

I would like to be able to add some custom exceptions as possible output.

### Motivation

I've developed a library which train and infer a model based on timeseries data. 
During these two steps, some data validation are made (mainly for dataframe index which are datetime).
I've implemented some custom Exceptions i.e.: ``NotSortedTimestamps`` when timestamps are not sorted.

However when I serve my model through ``bentoml`` these error will appears as ``InternalServerError``. 
So it is not really explicit for users.

Is it possible to provide a list of custom exceptions?

Thanks a lot

**Comment by frostming** [comment]
Make the custom exceptions subclass of `bentoml.exceptions.BentoMLException` and it will correctly returned
