### ISSUE TITLE
Do metrics returned from the `/metrics` endpoint include webserver + asyncio timings?

### ISSUE THREAD

**Issue by Ch0ronomato** [bentoml/BentoML#3661]
Hi!

i was looking at the metrics endpoint the bento (0.13-LTS) api and I was wondering if the response times histogram reported includes all of the asyncio / webserver bits or if it's essentially just the model runtime? 

Without burying the lead, the metric name is `BENTOML_XXX_request_duration_seconds_bucket`, where XXX is a service that gets packed, something like `XXX(BentoService)`

**Comment by ssheng** [comment]
Hi @Ch0ronomato, metrics instrumentation is implemented as a middleware on the server. It starts tracking after the server has received the requests and ends tracking before the server sends out the response. So the tracking includes everything in between and does not include the socket IO time.

**Comment by Ch0ronomato** [comment]
Yeah we do want to upgrade, I just wasn't tossing it on this. Trying to do one change at a time, ha.

So if I'm correct, any time the batching layer holds the request would not be reflected in the metrics?
