### ISSUE TITLE
feature: Pass runtime configuration when serving with Python API

### ISSUE THREAD

**Issue by AndriiG13** [bentoml/BentoML#3718]
### Feature request

As I understand, the way to pass runtime config is by exporting an env var `BENTOML_CONFIG`. However this only seems to work when serving with the CLI, that is  `bentoml serve bento_tag`. 

My team would like to serve with the Python API instead, for instance 

```python
# main.py
from bentoml.serve import serve_grpc_development

serve_grpc_development(bento_tag)
```

However, when testing, I found that when using Python API the runtime config is not picked up. 

So we would like to be able to both use the Python API **and** the runtime config.

### Motivation

For our use case, we find it easier/cleaner to use the Python API instead of the CLI. But right now we have to use the CLI because seemingly that's the only way to pass the runtime config.

**Comment by frostming** [comment]
You have to set the env var `BENTOML_CONFIG` when executing `main.py`, not inside it.
