### ISSUE TITLE
bug: runner in production mode does not get input of type dict

### ISSUE THREAD

**Issue by seyong92** [bentoml/BentoML#3728]
### Describe the bug

I am now using a python dict with PyTorch Tensors as an input of the model. When I serve the model in debug mode, it works correctly.

However, when I serve the model in production mode, the runner does not pass the dict to the model. Instead of dict, the runner gives a list to the model, and the list is composed of keys of dict.

Here is the example.

```python
bento_model = bentoml.pytorch.get('my_model')
config = bento_model.info.metadata
decoder = bento_model.custom_objects['decoder']


_BuiltinRunnable = bento_model.to_runnable()


class CustomRunnable(_BuiltinRunnable):
    def __init__(self):
        super().__init__()

    @bentoml.Runnable.method(batchable=True, batch_dim=0)
    def __call__(self, input_data: dict) -> np.ndarray:
        for k, v in input_data.items():
            input_data[k] = v.to(self.device_id)
        output = super().__call__(input_data)

        return output
```

When I use the runner, I use async_run function, and get the following error in production mode.

```shell
  File "MY_PROJECT_DIR/bentoml_serve.py", line 40, in __call__
    for k, v in input_data.items():
AttributeError: 'list' object has no attribute 'items'
```

### Environment

bentoml: 1.0.16
python: 3.10.9

**Comment by aarnphm** [comment]
Hi there, can you send your service definition here?

I suspect you probably need to do something like
```python
@svc.api()
def predict(input):
    runnable.run([input])
```

**Comment by seyong92** [comment]
Okay, I will share the service definition part.

Should I use a list as an input instead of using dict?

```python
runner = bentoml.Runner(CustomRunnable, models=[bento_model])


svc = bentoml.Service(name='my_service_name', runners=[runner])


@svc.api(input=File(), output=custom_pydantic_model)
async def predict(input_audio):
    audio, sr = torchaudio.load(input_audio)

    if audio.ndim > 1:  # change to mono
        audio = audio.mean(0).unsqueeze(0)

    if sr != config['sample_rate']:
        audio = torchaudio.functional.resample(audio, sr, config['sample_rate'])

    with torch.no_grad():
        y = await runner.async_run({'audio': audio})

    ...

```

**Comment by aarnphm** [comment]
try 
```python
y = await runner.async_run([{"audio": audio}])
```

Since this runners has batchable=True, the input should be a list

**Comment by sauyon** [comment]
The custom runnable can't take a dict and be batchable at the same time, you'll have to change one or the other.

**Comment by frostming** [comment]
This issue can be solved by the new service API
