### ISSUE TITLE
Possible bug in pytorch add_method() source code

### ISSUE THREAD

**Issue by AceMcAwesome77** [bentoml/BentoML#3786]
Hi, I'm looking at the code in two files; in this file: 
  https://github.com/bentoml/BentoML/blob/main/src/bentoml/_internal/frameworks/pytorch.py

from line 207 to line 214 we have:
```
runnable_class.add_method(
            make_pytorch_runnable_method(method_name, method_partial_kwargs),
            name=method_name,
            batchable=options.batchable,
            batch_dim=options.batch_dim,
            input_spec=options.input_spec,
            output_spec=options.output_spec,
        )
```

then in this file:  https://github.com/bentoml/BentoML/blob/main/src/bentoml/_internal/runner/runnable.py

from line 56 to 65 we have:
```
   def add_method(
        cls: t.Type[T],
        method: t.Callable[t.Concatenate[T, P], t.Any],
        name: str,
        *,
        batchable: bool = False,
        batch_dim: tuple[int, int] | int = 0,
        input_spec: LazyType[t.Any] | t.Tuple[LazyType[t.Any], ...] | None = None,
        output_spec: LazyType[t.Any] | None = None,
    ):
```
It looks like the number of function inputs don't line up between the definition and the call.  Specifically, the definition starts with a cls input that is not present in the call.  I noticed this discrepancy because I'm getting the following error when trying to make a pytorch model runner with bentoml:
```
   File "/app/bento_service.py", line 115, in <module>
     torch_model_runner = bento_model.to_runner()
   File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/models/model.py", line 346, in to_runner
     self.to_runnable(),
   File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/models/model.py", line 356, in to_runnable
     self._runnable = self.info.imported_module.get_runnable(self)
   File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/frameworks/pytorch.py", line 207, in get_runnable
     runnable_class.add_method(
   File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runnable.py", line 73, in add_method
     setattr(cls, name, meth)
 TypeError: __class__ must be set to a class, not 'RunnableMethod' object.
```
This error would make sense if the function was looking for class first but getting the method parameter first instead.  Is this a bug in the code?  Thanks!

**Comment by parano** [comment]
Hi @AceMcAwesome77 - the `Runnable#add_method` is a `classmethod`, so the when invoking `runnable_class.add_method(..)` call, the `runnable_class` becomes the first parameter
