### ISSUE TITLE
bug: Client requires grpcio dependency even if HTTP only is used

### ISSUE THREAD

**Issue by nadworny** [bentoml/BentoML#3797]
### Describe the bug

This happens when I use bentoml HTTPClient. The following error is thrown:
`bentoml.exceptions.MissingDependencyException: 'grpcio' is required for gRPC support. Install with 'pip install bentoml[grpc]'. (reason: No module named 'grpc')`

### To reproduce

1. Install bentoml `poetry add bentoml@1.0.8`
2. Initialize client `HTTPClient.from_url("")`
3. Run the code (I'm using simple fastapi server which invokes the bentoml server url)

### Expected behavior

I would expect that when I only want to use HTTPClient, I don't need to install the grpc extras.

### Environment

bentoml: 1.0.19
python: 3.9

**Comment by aarnphm** [comment]
Hi there, can you try with the latest release 1.0.19?

**Comment by nadworny** [comment]
Hey, just did it, exactly the same problem
