### ISSUE TITLE
bug: HTTPS doesn't work with client

### ISSUE THREAD

**Issue by nadworny** [bentoml/BentoML#3802]
### Describe the bug

Using HTTPS url for bentoml client doesn't work.

I'm getting the following error (since my service is doing https termination, it's 301):
```
bentoml.exceptions.RemoteException: Failed to get OpenAPI schema from the server: 301 Moved Permanently:
```

### To reproduce

1. Initialize client from https url, i.e. `HTTPClient.from_url("https://your-server")`
2. Start your app

### Expected behavior

HTTPS urls are supported.

### Environment

bentoml: 1.0.19
python: 3.9.16

**Comment by frostming** [comment]
This is solved by using httpx to replace the aiohttp
