### ISSUE TITLE
bug:  Transformer pipeline not working with trust_remote_code=True

### ISSUE THREAD

**Issue by ghpu** [bentoml/BentoML#3816]
### Describe the bug

Some models (ex databricks/dolly-v2-3b) require to download additional python code to work.
This code is stored in ~/.cache/huggingface/modules/
It seems that bentoml.transformers.save_model does not include this additional code.
Thus the bento does not work.

### To reproduce

```
import bentoml

from transformers import pipeline


MyPipeline = pipeline(model="databricks/dolly-v2-3b", trust_remote_code=True)
bentoml.transformers.save_model("databricks-dolly-v2-3b_pipeline",
                                pipeline=MyPipeline)
```

### Expected behavior

get a working pipeline

### Environment

bentoml: 1.10.18
python: 3.11.2

**Comment by aarnphm** [comment]
This is not really a bug, but rather a usability issue.

I will make a PR adding a section to the transformers doc about this.

**Comment by ghpu** [comment]
Thanks you so much, it did solve my issue !

**Comment by ghpu** [comment]
Some side-effects though : see https://github.com/bentoml/BentoML/issues/3819
