### ISSUE TITLE
feat: Observability enhancement in tracing and logging

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#3818]
The community made the following suggestions to BentoML observability.

1. Add a configuration option to return the trace id in the response as a header.

Consider adding a `traceparent` header that includes the trace id in the response. I only found mentioning of such protocol by vendors, such as https://uptrace.dev/opentelemetry/opentelemetry-traceparent.html, but not any official OpenTelemetry documentation.

2. Add `service.name=%(otelServiceName)s` in logs generated.

`otelServiceName` should be configurable through an environment variable. Possibly through the OTEL_SERVICE_NAME environment name, https://github.com/open-telemetry/opentelemetry-specification/pull/1677, and default to the bento name. Evaluate adding `OTEL_RESOURCE_ATTRIBUTES` to include any arbitrary KVPs to be logged. https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/

**Comment by aarnphm** [comment]
number 2 addressed by #3825

**Comment by aarnphm** [comment]
Number 1 addressed by https://github.com/bentoml/BentoML/pull/3827
