### ISSUE TITLE
Bug: cloudpickle and external_modules issue when host and docker have different python versions

### ISSUE THREAD

**Issue by ghpu** [bentoml/BentoML#3819]
### Describe the bug

When using :
```  external_modules=[importlib.import_module(MyPipeline.__module__) ```
in ```bentoml.transformers.save_model```

The resulting bento model is dependent of the python version on the host (ie the caller of ```bentoml.transformers.save_model```) , and a ```bentoml containerize``` will fail during deserialization with cloudpickle.

I encountered the case while working on Ubuntu 23.04 (python3.11 only) and trying to build a python3.10 container.

Issue was kind of expected : according to the documentation, "Cloudpickle can only be used to send objects between the exact same version of Python."
But It makes me wondering how we should serialize existing code to make it compatible with all python versions during containerization.

### Environment

bentoml : 1.0.18
python: 3.11

**Comment by aarnphm** [comment]
Bento build will always respect host python version. To set the target python version on docker, please see https://docs.bentoml.org/en/latest/concepts/bento.html#docker-options-table and put it into your bentofile.yaml

3.11 is supported, and the docs is a bit out of date.

**Comment by ghpu** [comment]
Ok. I was late on my version of BentoML. Once upgraded to 1.0.19, python3.11 is recognized as a docker option.

However, bentoml build now fails when using python-3.11 and cuda 11.7 at the same time : 
 ```
 > [base-container  4/14] RUN --mount=type=cache,target=/var/lib/apt --mount=type=cache,target=/var/cache/apt     set -eux &&     apt-get install -y --no-install-recommends --allow-remove-essential software-properties-common &&     add-apt-repository ppa:deadsnakes/ppa &&     apt-get update -y &&     apt-get install -y --no-install-recommends --allow-remove-essential curl python3.11 python3.11-dev python3.11-distutils:
#0 1.027 + apt-get install -y --no-install-recommends --allow-remove-essential software-properties-common
#0 1.259 Reading package lists...
#0 1.316 Building dependency tree...
#0 1.330 E: Unable to locate package software-properties-common
```

The build works properly if using only python-3.11.
