### ISSUE TITLE
bug: max_batch_size does not take into account input batch size

### ISSUE THREAD

**Issue by mkmenta** [bentoml/BentoML#3859]
### Describe the bug

Hi! I have found that the [max_batch_size](https://docs.bentoml.org/en/latest/guides/batching.html#max-batch-size) parameter of the adaptive batching does not take into account if the input `x` in a `predictions = await runner.async_run(x)` call has already a batch size higher than 1 (risking out-of-memory errors).

### To reproduce

In my case, I was using an ONNX model (I'm not sure if it also affects other types of runners).
1. Create a service that executes:
```python3
x = np.random.rand(32, 3, 224, 224).astype(np.float32)
predictions = await onnx_runner.async_run(x)
```
2. Configure the service with:
```yaml
runners:
  myonnxmodel:
      batching:
          enabled: true
          max_batch_size: 32
          max_latency_ms: 100000
```
3. Set the `bentoml` logger to `DEBUG` in the code
4. Run the service (I ran it with `bentoml serve service:svc --api-workers=4 --production`)  
5. Perform a lot of requests in a short amount of time to force the service to begin batching (in my case running 1000 async requests from a script was enough).
6. Check that:
- The logs output batch size values higher than 1:
```
2023-05-12 12:31:28 server1 bentoml._internal.marshal.dispatcher[4078012] DEBUG Dynamic batching cork released, batch size: 11
```
- The GPU memory usage is higher than what it normally takes to run a batch of 32 images directly with `onnxruntime.InferenceSession().run()`.

As a double check:
Modifying the service code to
```python3
x = np.random.rand(1, 3, 224, 224).astype(np.float32)
predictions = await onnx_runner.async_run(x)
```
forces a GPU memory usage very similar to what it takes to run a batch of 32 images directly with `onnxruntime.InferenceSession().run()`.

### Expected behavior

I would expect that the adaptive batching checks the batch size of each input to compute and would batch the elements trying to not overcome the `max_batch_size` parameter. 

As an alternative, adaptive batching could first split the input batches into single inputs of a batch size of 1 to be able to batch them freely afterward.

If this behavior was expected, I would expect to have it clearly specified in the docs to avoid unwanted memory errors or handle the input batches accordingly.

### Environment

bentoml: 1.0.19, 1.0.20
onnxruntime-gpu: 1.13.1

**Comment by ssheng** [comment]
@mkmenta Thanks for reporting. @sauyon Didn't we address this issue in https://github.com/bentoml/BentoML/pull/3741?

**Comment by sauyon** [comment]
Actually, I was looking at this and I think that it got rebased away somewhere... it's definitely in the target latency pr, not super sure how that happened. Let me fix that and the other batching issue and make a PR.

**Comment by mkmenta** [comment]
Hi @sauyon was this fixed at the end?

**Comment by sauyon** [comment]
Hi @mkmenta, the batching PR in question was delayed quite a bit due to other changes, sorry about that. In the interim I've opened #3973, which should hopefully solve this issue.

**Comment by bojiang** [comment]
close on PR merged
