### ISSUE TITLE
bug: Readme typo in first example

### ISSUE THREAD

**Issue by Jhappy77** [bentoml/BentoML#3869]
### Describe the bug

I found a minor typo in the first example from the README.

The following curl does not work, because the endpoint is wrong:
`curl -F 'image=@samples/1.png' http://127.0.0.1:3000/predict_image`

### Expected behavior

It should be updated to this:
` curl -F 'image=@samples/1.png'  http://127.0.0.1:3000/predict`

### Environment

N/A

**Comment by ssheng** [comment]
Thanks for the suggestion. Would you like to file an issue?

**Comment by OmkarMozar** [comment]
I would like to create PR for this, if [Jhappy77](https://github.com/Jhappy77) is not working on this one. @ssheng

**Comment by sauyon** [comment]
Please go ahead!
