### ISSUE TITLE
requests and endpoints using ImageHandler

### ISSUE THREAD

**Issue by lambdaofgod** [bentoml/BentoML#387]
I have a service that is used for prediction on images. I need to call it from some other place in my Python application, but I cannot figure out how to do it.

My CURL command from swagger looks like this:

> curl -X POST "http://localhost:5000/predict" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "image=@astronaut_ok.png;type=image/png"

Which I translated into requests request:
```
files = {'image': open('astronaut_ok.png', 'rb')} 
headers = { 
       'Content-Type': 'multipart/form-data', 
       'Accept': '*/*' 
} 
requests.post(url, files=files, headers=headers)
```

But this only gives
`
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'`

I also tried
`files = {'image': ('astronaut_ok.png', open('astronaut_ok.png', 'rb'))} `
and
`files = {'image': ('astronaut_ok.png', open('astronaut_ok.png', 'rb'), 'image/png')}`

But these also fail.

**Comment by parano** [comment]
hi @lambdaofgod, I just tested a similar setting with our pytorch fashion mnist example, and sending request from python, everything seems to work as expected:
![image](https://user-images.githubusercontent.com/489344/69136759-46489c00-0a70-11ea-9a7f-c589b2612cf8.png)

It seem this has to do with how request library handles the headers automatically for you, could you try omit the `headers=headers` part in you python client code?
