### ISSUE TITLE
Python packaged model implicitly requires bentoml package

### ISSUE THREAD

**Issue by kevlar1818** [bentoml/BentoML#395]
## Describe the bug
A Python package built by BentoML requires the bentoml Python package implicitly.

## To Reproduce
```
$ pip install my_packaged_model
```
Then:
```
>>> import my_packaged_model
ModuleNotFoundError: No module named 'bentoml'
```
Not only do I need to install BentoML, I need to install the precise version used to create the Python package, else the package fails to import because of apparent BentoML API changes.

## Expected behavior
`import my_packaged_model` should Just Work.

## Environment:
 - OS: Arch Linux
 - Python Version: Both Python 3.8.0 (Arch Linux) and Docker image `python:3.7`
 - BentoML Version: Both 0.4.9 and 0.5.0

**Comment by parano** [comment]
@Kevlar1818 Thanks for reporting this issue! The BentoML package should indeed be added to the install_requires list with fixed version, will follow up with a PR soon.

**Comment by parano** [comment]
The fix has just been merged to master https://github.com/bentoml/BentoML/pull/396 @kevlar1818 thanks again for reporting the issue.

We will do some more testing before making a release, in the meanwhile, feel free to try it out by installing BentoML from master branch: `pip install git+https://github.com/bentoml/BentoML.git`

**Comment by parano** [comment]
Release 0.5.2 is out now including the fix. It should be able to use saved BentoService bundle as PyPI package with all the pip dependencies specified with the setup.py file.

Closing this issue now, feel free to reopen if you are still seeing this/related issues with it.
