### ISSUE TITLE
bug: Not able to run on the CPU when CUDA devices are available

### ISSUE THREAD

**Issue by RomainGehrig** [bentoml/BentoML#3972]
### Describe the bug

I tried OpenLLM and wanted to have the model run on my CPU for testing because the GPU does not have enough RAM.

I tried setting `CUDA_VISIBLE_DEVICES=""` and `--device ""` (for `openllm`) but BentoML changed it back to `0` as shown in the log:

```
$ CUDA_VISIBLE_DEVICES="" openllm start stablelm --quantize int8 --device "" 
2023-06-20T09:09:22+0200 [INFO] [cli] Environ for worker 0: set CUDA_VISIBLE_DEVICES to 0
```

I believe the change at https://github.com/bentoml/BentoML/blob/90eab360016331f365c15e902fb2ba8cfec54992/src/bentoml/_internal/runner/strategy.py#L121-L160 is the source of this behavior. It's the first time I'm testing BentoML and OpenLLM so I don't know if it's a regression or not. I worked around that by commenting the GPU section so it's not really pull-request worthy.

### To reproduce

To reproduce with OpenLLM:
- Run `CUDA_VISIBLE_DEVICES="" openllm start stablelm`
- Look at the log line `Environ for worker[...]`

### Expected behavior

After removing the GPU code, I get the expected:
```
$ CUDA_VISIBLE_DEVICES="" openllm start stablelm --quantize int8
2023-06-20T09:42:57+0200 [INFO] [cli] Environ for worker 0: set CPU thread count to 16
```

(Now I'll have to figure out how to assign less threads, but it's an OpenLLM problem.)

### Environment

Using
`openllm`: 0.1.8
`bentoml`: 1.0.22

**Comment by aarnphm** [comment]
You can just set CUDA_VISIBLE_DEVICES= to enfoce disabling GPU

**Comment by sauyon** [comment]
BentoML should also respect `CUDA_VISIBLE_DEVICES`, do you want to open an issue there?

**Comment by aarnphm** [comment]
@RomainGehrig I have addressed this on the latest change of OpenLLM, please try it out
