### ISSUE TITLE
feature: Add vLLM engine for generation tasks

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [bentoml/BentoML#3981]
### Feature request

As it is done with Triton Inference server, it would be great to integrate vLLM (https://github.com/vllm-project/vllm) as a higly optimized engine for LLM generation based on continuous batching.

**Comment by aarnphm** [comment]
I think this is more suited for OpenLLM, rather than bentoml itself.

**Comment by aarnphm** [comment]
Let's track the decision and progress there. I don't think it is suited for BentoML yet.
