### ISSUE TITLE
bug: trailing special characters in the model name cause an exception

### ISSUE THREAD

**Issue by naphtul** [bentoml/BentoML#4015]
### Describe the bug

Running my code crashes with:
```
Traceback (most recent call last):
  File "****/site-packages/bentoml/_internal/tag.py", line 111, in from_str
    raise BentoMLException(f"Invalid {cls.__name__} {tag_str}")
bentoml.exceptions.BentoMLException: Invalid Tag pt-databricks-dolly-v2-3b:f6c9be08f16fe4d3a719bee0a4a7c7415b5c65df
python-BaseException
```

It happens because there's a trailing `\r` after `tag_str`.

### To reproduce

This is `requirements.txt`:
```
openllm==0.1.19
...
langchain==0.0.220
```

This is my code:
```python
from langchain.llms import OpenLLM

llm = OpenLLM(
    model_name="dolly-v2",
    model_id="databricks/dolly-v2-3b",
    temperature=0.94,
    repetition_penalty=1.2,
)
```

### Expected behavior

I expect the class to handle some whitespace errors.

### Environment

bentoml: 1.0.23
python: 3.11.4

**Comment by naphtul** [comment]
I can submit a PR if I had access to push to a branch.

**Comment by sauyon** [comment]
Hello! I think this is expected behavior, this kind of thing should probably be handled by the frontend (OpenLLM, it seems, in this case).

You don't need push access to make a PR, you should just be able to fork the repo.

/cc @aarnphm ^

**Comment by naphtul** [comment]
OK, let me know your final decision. If you say 'fix', I'll fork, add a `strip()` and create a PR.

**Comment by aarnphm** [comment]
Hey, Feel free to open the PR on OpenLLM. Note that I'm currently doing refactoring on these components. I can factor in this issue. Thanks.

**Comment by naphtul** [comment]
Very well. Thank you.
