### ISSUE TITLE
bug: Can't modify BENTOML_HOME when running build_bentofile from Python

### ISSUE THREAD

**Issue by jhostetler** [bentoml/BentoML#4080]
### Describe the bug

Changes to the BentoML environment configuration made via the Python APIs don't get propagated to the `build` workflow because the build now runs in a subprocess in `v1.1`.

### To reproduce

I have a Python app that's sort of a Bento "build server", so it needs to build Bentos in temporary directories. In BentoML v1.0, I used the following code to accomplish this:

```
with tempfile.TemporaryDirectory() as tmp, \
     bentoml.bentos.BentoMLContainer.bentoml_home.patch(tmp):
    ... create the model
    bentoml.<framework>.save_model(...)
    ... create bentofile.yaml under tmp
    bentoml.bentos.build_bentofile(build_ctx=tmp)
```

In v1.1, the implementation of `build_bentofile` has changed to delegate to the CLI app running in a subprocess. As a result, it has a different copy of the configuration objects, and always uses whatever is set for `BENTOML_HOME` at the system level. This results in an error like:

```
Error: [bentoml-cli] `build` failed: no Models with name <name> exist in BentoML store <osfs '/root/bentoml/models'>
```

because `BENTOML_HOME` was (the value of) `tmp` when `save_model()` was called, but in the build it has reverted to its default value of `~/bentoml`.

### Expected behavior

The build should run as though `BENTOML_HOME` had been set to the temporary directory, i.e., the equivalent of `BENTOML_HOME=<value of tmp> bentoml build ...`

### Environment

bentoml: 1.1
python: 3.8
Linux in a Docker container

**Comment by poudrouxj** [comment]
Can also confirm that this issue is also happening for us where we use the [bentoml.build](https://docs.bentoml.org/en/latest/reference/core.html#bentoml.bentos.build) api in a runtime environment where we've altered the `BENTOML_HOME` variable. Seems it defaults to the `~/$home/bentoml` here as well.
