### ISSUE TITLE
service.save is not backwards-compatible (model Registry breaks old model saving flow?)

### ISSUE THREAD

**Issue by lambdaofgod** [bentoml/BentoML#409]
Before adding model registry I could just run 

`service.save('/tmp/service_name')`
And each time it created appropriate artifacts.

Now when I try doing that I get the following 
```

(ObjectDetector is the name of my service's class)
[2019-11-29 14:00:02,183] INFO - BentoService bundle 'ObjectDetector:20191129135821_FB7689' created at: /tmp/bentoml-temp-0kmic7f6
[2019-11-29 14:00:02,190] WARNING - Overriding default repository path to '/tmp/object_detection'
---------------------------------------------------------------------------
BentoMLException                          Traceback (most recent call last)
<timed eval> in <module>

~/Projects/venvs/ml_server/lib/python3.7/site-packages/bentoml/service.py in save(self, base_path, version)
    484         from bentoml.yatai import python_api
    485 
--> 486         return python_api.upload_bento_service(self, base_path, version)
    487 
    488     def save_to_dir(self, path, version=None):

~/Projects/venvs/ml_server/lib/python3.7/site-packages/bentoml/yatai/python_api.py in upload_bento_service(bento_service, base_path, version)
     74     with TempDirectory() as tmpdir:
     75         save_to_dir(bento_service, tmpdir, version)
---> 76         return _upload_bento_service(tmpdir, base_path)
     77 
     78 

~/Projects/venvs/ml_server/lib/python3.7/site-packages/bentoml/yatai/python_api.py in _upload_bento_service(saved_bento_path, base_path)
     98             "BentoService version with BentoService#set_version or bypass BentoML's "
     99             "model registry feature with BentoService#save_to_dir".format(
--> 100                 bento_service_metadata.name, bento_service_metadata.version
    101             )
    102         )

BentoMLException: BentoService bundle ObjectDetector:20191129135821_FB7689 already registered in repository. Reset BentoService version with BentoService#set_version or bypass BentoML's model registry feature with BentoService#save_to_dir
```
Is there a way of doing that that will work like it did before? Or do I have to set `version` manually each time I use `service.save`?

**Comment by parano** [comment]
hi @lambdaofgod, we did make `save` backward compatible, the only difference is that ```service.save('/tmp/service_name')```  still tries to save the model information to a local SQLite DB(assuming you are not using our remote model registry functionality), and it does verify if the same name/version has been saved before.

One workaround is to simply use `BentoService#save_to_dir`, which is identical to the `save` before BentoML-0.4.0, and bypasses all the model registry related code path. The other way is to do a `service.set_version()` before `service.save()`, which generates a new version id.

**Comment by lambdaofgod** [comment]
This is pretty confusing. `save_to_dir` is not exactly mapping to what happened before, because it actually saves to the direction specified by argument, and does not generate another folder structure, like `save` did before.

> it does verify if the same name/version has been saved before.
It was done by making sure new saved version has a new hash, right?
Could you just show me how to get this autogenerated value, so that I can use it in `save`/`save_to_dir` to make it work like it did before?

**Comment by parano** [comment]
@lambdaofgod  

> It was done by making sure new saved version has a new hash, right?
Yes that's exactly right

> Could you just show me how to get this autogenerated value, so that I can use it in save/save_to_dir to make it work like it did before?

here's an example:

```python
svc = MyBentoService()
svc.pack(...)

svc.save() # saving for the first time, generates an version string
print(svc.version)

svc.save() # saving for the second time, this will fail due to version exists

# To reset the version:
# Option 1, call `set_version` without parameter, this will generate a new version string:
svc.set_version() 
print(svc.version)
svc.save()   # this should succeed now

# Option 2, call `versioneer` function manually to generate a new version string
new_version_str = svc.versioneer()
svc.set_version(new_version_str)
svc.save()   # this should succeed now
```
Note that you can choose to override `versioneer` function in order to generate customized version string pattern if you need to. `self.set_version(serlv.versioneer())` gets called automatically when you do a `save` or `save_to_dir`.

We will add this to our documentation soon, sorry about not clearly documenting it when me made the change!

**Comment by parano** [comment]
@lambdaofgod and thanks for pointing out the difference of `save_to_dir` vs. the old `save`!  You are right, they are not exactly equivalent in terms of using the name and version as the path prefix.

`save_to_dir` was meant for advanced users to build customized workflow, so we made it less restrictive. A workaround to mimic the old behavior is to use `svc.name` and `svc.version` strings to create sub-directory, and pass that path into `save_to_dir` instead:

```
path_to_save_models = '/Users/...../models'
path = os.path.join(path_to_save_models, svc.name, svc.version)
os.mkdirs(path)
svc.save_to_dir(path)
```
