### ISSUE TITLE
bug: Model files created with lightgbm 4.0.0 is not supported by bentoml==1.*

### ISSUE THREAD

**Issue by poudrouxj** [bentoml/BentoML#4123]
### Describe the bug

In a runtime environment with the following relevant pip packages installed
```
lightgbm==4.0.0
bentoml[io-json]==1.0.25
```

An invocation of the ` bentoml.lightgbm.save_model` will fail:

``` bash
 bentoml.lightgbm.save_model(
2023-08-16 09:35:36.816	
  File "/usr/local/lib/python3.10/site-packages/bentoml/_internal/frameworks/lightgbm.py", line 222, in save_model
2023-08-16 09:35:36.816	
    model.save_model(bento_model.path_of(MODEL_FILENAME))
2023-08-16 09:35:36.816	
  File "/usr/local/lib/python3.10/site-packages/lightgbm/basic.py", line 3301, in save_model
2023-08-16 09:35:36.816	
    self.handle,
2023-08-16 09:35:36.816	
AttributeError: 'Booster' object has no attribute 'handle'. Did you mean: '_handle'
```

I'm assuming there's a breaking change in the internals of lightgbm, would be nice to support this.

### Environment

lightgbm==4.0.0
bentoml[io-json]==1.0.25
python 3.10

**Comment by frostming** [comment]
The most recent two frames of the trackback lie in the internals of lightGBM, so it is lightGBM not referencing the correct name. Not a bug with BentoML. Maybe you should report it in lightGBM

* * *

I found it is correctly using `self._handle` in the main branch.
