### ISSUE TITLE
feature: support starlette BackgroundTask

### ISSUE THREAD

**Issue by KimSoungRyoul** [bentoml/BentoML#4148]
### Feature request

starlette support backgroundTask
https://www.starlette.io/background/

~~~python
# starlette example
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.background import BackgroundTasks

async def signup(request):
    data = await request.json()
    username = data['username']
    email = data['email']
    tasks = BackgroundTasks()
    tasks.add_task(send_welcome_email, to_address=email)
    tasks.add_task(send_admin_notification, username=username)
    message = {'status': 'Signup successful'}
    return JSONResponse(message, background=tasks)
~~~

### Motivation

 Fastapi also supports it even if it is just wrapper object,

https://fastapi.tiangolo.com/tutorial/background-tasks/

~~~Python
# fastapi example
from fastapi import BackgroundTasks, FastAPI

app = FastAPI()


def write_notification(email: str, message=""):
    with open("log.txt", mode="w") as email_file:
        content = f"notification for {email}: {message}"
        email_file.write(content)


@app.post("/send-notification/{email}")
async def send_notification(email: str, background_tasks: BackgroundTasks):
    background_tasks.add_task(write_notification, email, message="some notification")
    return {"message": "Notification sent in the background"}

~~~

### to-be (`BentoML backgroundTask `)

~~~Python

import httpx
import numpy as np
from starlette.background import BackgroundTask, BackgroundTasks

import bentoml
from bentoml.io import NumpyNdarray, JSON, TaskResponse

iris_clf_runner = bentoml.sklearn.get("iris_clf:latest").to_runner()

svc = bentoml.Service("iris_classifier", runners=[iris_clf_runner])


async def sub_task(runner, url: str, input_series: np.ndarray):
    result: np.ndarray = await runner.predict.async_run(input_series)
    
    async with httpx.AsyncClient() as client:
        await client.post(
            url,
            json={"result": result.tolist()}
        )


@svc.api(
    input=NumpyNdarray.from_sample(
        np.array([[4.9, 3.0, 1.4, 0.2]], dtype=np.double), enforce_shape=False
    ),
    output=JSON.from_sample({"message": "success or fail"}),
)
async def classify(input_series: np.ndarray) -> TaskResponse[dict[str, str], BackgroundTask]:
    task1 = BackgroundTask(sub_task, iris_clf_runner, url="http://anothre-server:3000/callback", input_series=input_series)
 
    # return {"message":"success"}
    return TaskResponse(res={"message": "success"}, background=task1)
~~~

**Comment by aarnphm** [comment]
I don't think this makes sense to be supported in BentoML. If you just want to send background task, you can already do it with a FastAPI app and then mount it to bentoml service

**Comment by aarnphm** [comment]
Also the example for sending client to another endpoint using background tasks also doesn't make sense to me. It shouldn't be the server responsibility to schedule or run such tasks. It should be left to the client or adjacent services to handle it for different use cases.

**Comment by KimSoungRyoul** [comment]
I agree that the example mentioned in the text is not a good example to show that backgroundTask is a necessary feature.

However, the feature to execute task asynchronously in the background without any module extensions is definitely useful (optional responsibility of the server)

The links below are examples of web frameworks that support asynchronous task without any dependency
* [django-task TaskThreaded](https://github.com/morlandi/django-task#7threaded-vs-rq-based-tasks)
* [spring @EnableAsync](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/scheduling/annotation/EnableAsync.java)

Of course, bentoml is not WebFramework, it's model serving framework. 
model serving framework should remain lightweight, and excessive feature extensions should be danger

However, I don't think bentoml need to limit even the feature supported by starlette.

**Comment by aarnphm** [comment]
FWIW you can always do this as a starlette app and then mount it to the bentoml.Service.

**Comment by sauyon** [comment]
> I don't think this makes sense to be supported in BentoML. If you just want to send background task, you can already do it with a FastAPI app and then mount it to bentoml service

Why not? It seems like a function that would be good to have, if maybe not an immediate priority.

> Also the example for sending client to another endpoint using background tasks also doesn't make sense to me. It shouldn't be the server responsibility to schedule or run such tasks. It should be left to the client or adjacent services to handle it for different use cases.

I disagree. Sometimes the server will have to run some updates or connect to other servers without blocking the client.

I think this is something we should have a good API for.

That said, I believe you should be able to just spawn a thread manually and let it run, though obviously that's a lot more code overhead.

**Comment by aarnphm** [comment]
> I disagree. Sometimes the server will have to run some updates or connect to other servers without blocking the client.

I think we can think about this during our server improvement. Having more thoughts on this, BackgroundTasks would be useful for continuous batching, as we want to schedule incoming requests without blocking the main thread.

**Comment by KimSoungRyoul** [comment]
https://github.com/bentoml/BentoML/issues/4148#issuecomment-1715647792

cool, this example should be nice practice. 

but the topic(I wanted to discuss in this issue) is not implementing a background Task with asyncio.
whether bentoml allow to use starlette's BackgroundTask feature or not. 

The benefit of the starlette background task is its simplicity.

I just want to ask that `does bentoml really need to limit starlette's owned feature(backgroundTask)? `

there is few benefit when the bentoml add backgroundTask feature.
it's minor optional feature.

This is a minor optional feature, so if you(`bentoML teams`) don't see a few benefit to it, I don't think any reason to add it.


I don't think it's a good idea to spend more time on this issue 
you already have so many other important issues to do, 


someday you need this feature in the future, we can reopen it and talk about it then. 

can you close this issue? 

thanks

**Comment by parano** [comment]
thanks @KimSoungRyoul! We will revisit this issue in our Rust-server refactor, happy to chat more about that if you're interested in helping to contribute!
