### ISSUE TITLE
bug: No such option: --print-location

### ISSUE THREAD

**Issue by hugocool** [bentoml/BentoML#4180]
### To reproduce
```
saved_path=$(bentoml get transformers-nlp-service:latest --print-l
ocation --quiet)
```
give the following error:
```
Usage: bentoml get [OPTIONS] BENTO_TAG
Try 'bentoml get -h' for help.
Error: No such option: --print-location
```

### Environment

bentoml 1.1.6
python: 3.9.11
os: debian 24

**Comment by parano** [comment]
Hi @hugocool,

The `--print-location` command is no longer available and replaced by `-o path`. For example, you can use `saved_path=$(bentoml get text-classification-svc:latest -o path --quiet)`.

Did you see the `--print-location` in the documentation somewhere? we should update that to the `-o` option now

**Comment by hugocool** [comment]
I realised I saw it in the old version of the docs, 0.13, so I wanted to remove this bug report but couldn’t.
Thanks for answering how to do this!

___

Hugo Evers

**Comment by aarnphm** [comment]
Since we have stopped providing support for 0.13 a while now, I wonder how do you land on the doc?

**Comment by hugocool** [comment]
By googling for AWS EKS deployment of BentoML.

___

Hugo Evers

**Comment by parano** [comment]
Thank you @hugocool! we will add a deprecation notice to the 0.13 documentation
