### ISSUE TITLE
bug: bentoml containerize Failing

### ISSUE THREAD

**Issue by Mayurji** [bentoml/BentoML#4205]
### Describe the bug

Error description while containerize:

> [base-container  3/11] RUN --mount=type=cache,target=/var/lib/apt --mount=type=cache,target=/var/cache/apt set -eux &&     apt-get update -y &&     apt-get install -q -y --no-install-recommends --allow-remove-essential         ca-certificates gnupg2 bash build-essential:                                                                                  
0.435 + apt-get update -y                                                                                                                                                         
60.99 Ign:1 http://deb.debian.org/debian bookworm InRelease                                                                                                                       
60.99 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease                                                                                                               
60.99 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
61.99 Ign:1 http://deb.debian.org/debian bookworm InRelease
61.99 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
61.99 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
63.99 Ign:1 http://deb.debian.org/debian bookworm InRelease
63.99 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
63.99 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
67.99 Err:1 http://deb.debian.org/debian bookworm InRelease
67.99   Could not connect to debian.map.fastlydns.net:80 (146.75.38.132), connection timed out Could not connect to deb.debian.org:80 (146.75.34.132), connection timed out
67.99 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
67.99   Unable to connect to deb.debian.org:http:
67.99 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
67.99   Unable to connect to deb.debian.org:http:
67.99 Reading package lists...
68.00 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Could not connect to debian.map.fastlydns.net:80 (146.75.38.132), connection timed out Could not connect to deb.debian.org:80 (146.75.34.132), connection timed out
68.00 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Unable to connect to deb.debian.org:http:
68.00 W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Unable to connect to deb.debian.org:http:
68.00 W: Some index files failed to download. They have been ignored, or old ones used instead.
68.00 + apt-get install -q -y --no-install-recommends --allow-remove-essential ca-certificates gnupg2 bash build-essential
68.01 Reading package lists...
68.01 Building dependency tree...
68.01 Package gnupg2 is not available, but is referred to by another package.
68.01 This may mean that the package is missing, has been obsoleted, or
68.01 is only available from another source
68.01 However the following packages replace it:
68.01   gpgv
68.01 
68.01 E: Package 'gnupg2' has no installation candidate
68.01 E: Unable to locate package build-essential

Dockerfile:22
  21 |     RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
  22 | >>> RUN --mount=type=cache,target=/var/lib/apt --mount=type=cache,target=/var/cache/apt set -eux && \
  23 | >>>     apt-get update -y && \
  24 | >>>     apt-get install -q -y --no-install-recommends --allow-remove-essential \
  25 | >>>         ca-certificates gnupg2 bash build-essential 
  26 |     # Block SETUP_BENTO_USER

ERROR: failed to solve: process "/bin/sh -c set -eux &&     apt-get update -y &&     apt-get install -q -y --no-install-recommends --allow-remove-essential         ca-certificates gnupg2 bash build-essential" did not complete successfully: exit code: 100

### Environment

bentoml: 1.1.6
Kubeflow: 1.7
Kubernetes: 1.25

**Comment by timliubentoml** [comment]
Hi @Mayurji! This looks like it's a connection issue to debian. Do you know if there was an connection issue? Are you able to reproduce this? Could you give us a way to reproduce this?

**Comment by Mayurji** [comment]
@timliubentoml, Yes, it was a connection issue while running from AWS instances. It works if the instances have proper access to debian.org.
