### ISSUE TITLE
bug: unable to start BentoML container in RayServe

### ISSUE THREAD

**Issue by tozzi21** [bentoml/BentoML#4252]
### Describe the bug

followed instructions at https://docs.bentoml.org/en/latest/integrations/ray.html

ray serve attempts to instantiate container, but trips up:

2023-10-30 23:45:22,446 INFO scripts.py:471 -- Running import path: 'bento_ray:classifier'.
Traceback (most recent call last):
  File "/home/thor/.local/bin/serve", line 8, in <module>
    sys.exit(cli())
  File "/home/thor/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/thor/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/thor/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thor/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thor/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/thor/.local/lib/python3.8/site-packages/ray/serve/scripts.py", line 473, in run
    import_attr(import_path), args_dict
  File "/home/thor/.local/lib/python3.8/site-packages/ray/_private/utils.py", line 1378, in import_attr
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/d/Data/AIRay/./bento_ray.py", line 5, in <module>
    classifier = bentoml.ray.deployment(
  File "/home/thor/.local/lib/python3.8/site-packages/bentoml/_internal/utils/lazy_loader.py", line 69, in __getattr__
    self._module = self._load()
  File "/home/thor/.local/lib/python3.8/site-packages/bentoml/_internal/utils/lazy_loader.py", line 53, in _load
    raise self._exc(f"{self._exc_msg} (reason: {err})") from None
bentoml.exceptions.MissingDependencyException: None (reason: No module named 'bentoml._internal.ray._internal')

### Expected behavior

Expected RayServe to spin up BentoML container within its cluster

### Environment

Ubuntu 20.04.6

**Comment by jerryharrow** [comment]
Here is a proposed fix https://github.com/bentoml/BentoML/pull/4257

**Comment by tozzi21** [comment]
pulled commit [edfda3b].  progress in attempts to register Bento in Serve on Ray Cluster, but exception when allocating replica 'default#bento-svc-llm-opt-service#SmCOIZ'

Details added to pull request https://github.com/bentoml/BentoML/pull/4257#issuecomment-1793436005

**Comment by tozzi21** [comment]
Details added to pull request https://github.com/bentoml/BentoML/pull/4257#issuecomment-1793436005

**Comment by jerryharrow** [comment]
> pulled commit [[edfda3b](https://github.com/bentoml/BentoML/commit/edfda3b439dfbc1056e644ab18c227d95832efb2)]. progress in attempts to register Bento in Serve on Ray Cluster, but exception when allocating replica 'default#bento-svc-llm-opt-service#SmCOIZ'
> 
> Details added to pull request [#4257 (comment)](https://github.com/bentoml/BentoML/pull/4257#issuecomment-1793436005)

You have made it past the original problem and are now hitting a different problem.   
It looks like it is having a problem loading your bento (specifically something from a yaml file that is apparently empty).
Can you serve the bento locally without Ray?  Good to verify that works.

`benotml serve bento_ray:classifier`

Here is the source of the failure in your log:

```
(ServeReplica:default:bento-runner-llm-opt-runner pid=852) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SERVE_REPLICA::default#bento-runner-llm-opt-runner#JhDlMg:ServeReplica:default:bento-runner-llm-opt-runner.__init__() (pid=852, ip=172.17.85.4, actor_id=e9ed32d116920e8d9f11639e03000000, repr=<ray.serve._private.replica.ServeReplica:default:bento-runner-llm-opt-runner object at 0x7f163f378700>)
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     return self.__get_result()
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     raise self._exception
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/home/thorsten/.local/lib/python3.8/site-packages/ray/serve/_private/replica.py", line 117, in __init__
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     deployment_def = cloudpickle.loads(serialized_deployment_def)
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/home/thorsten/.local/lib/python3.8/site-packages/bentoml/_internal/service/service.py", line 155, in load_exported_bento
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     bento = tmp_bento_store.get(bento_tag)
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/home/thorsten/.local/lib/python3.8/site-packages/bentoml/_internal/store.py", line 153, in get
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     return self._get_item(_tag)
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/home/thorsten/.local/lib/python3.8/site-packages/bentoml/_internal/store.py", line 114, in _get_item
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     return self._item_type.from_fs(self._fs.opendir(tag.path()))
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/home/thorsten/.local/lib/python3.8/site-packages/bentoml/_internal/bento/bento.py", line 308, in from_fs
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     info = BentoInfo.from_yaml_file(bento_yaml)
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)   File "/home/thorsten/.local/lib/python3.8/site-packages/bentoml/_internal/bento/bento.py", line 548, in from_yaml_file
(ServeReplica:default:bento-runner-llm-opt-runner pid=852)     assert yaml_content is not None
```

**Comment by tozzi21** [comment]
good spot.  in the various troubleshooting, it seems like the config got out of sync.  refollowed steps: 
bento save_model > benot service > create yaml > bento build > serve run iris_ray:classifier

thorsten@Liji:/mnt/d/Data/AIRay$ serve run iris_ray:classifier
2023-11-06 23:06:56,526 INFO scripts.py:471 -- Running import path: 'iris_ray:classifier'.
2023-11-06 23:07:01,512 INFO worker.py:1633 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
(HTTPProxyActor pid=2001) INFO 2023-11-06 23:07:07,057 http_proxy 172.19.201.160 http_proxy.py:1433 - Proxy actor f027c0f0a5b55ed8bea23d2801000000 starting on node ad734cd5d9dc7e1838562b1ad7186b295d48c790ef20b1aa6ed389ca.
(HTTPProxyActor pid=2001) INFO 2023-11-06 23:07:07,071 http_proxy 172.19.201.160 http_proxy.py:1617 - Starting HTTP server on node: ad734cd5d9dc7e1838562b1ad7186b295d48c790ef20b1aa6ed389ca listening on port 8000
(ServeController pid=1952) INFO 2023-11-06 23:07:07,200 controller 1952 deployment_state.py:1390 - Deploying new version of deployment bento-runner-iris_clf in application 'default'.
(ServeController pid=1952) INFO 2023-11-06 23:07:07,203 controller 1952 deployment_state.py:1390 - Deploying new version of deployment bento-svc-iris_classifier in application 'default'.
(HTTPProxyActor pid=2001) INFO:     Started server process [2001]
(ServeController pid=1952) INFO 2023-11-06 23:07:07,307 controller 1952 deployment_state.py:1679 - Adding 1 replica to deployment bento-runner-iris_clf in application 'default'.
(ServeController pid=1952) INFO 2023-11-06 23:07:07,314 controller 1952 deployment_state.py:1679 - Adding 1 replica to deployment bento-svc-iris_classifier in application 'default'.
2023-11-06 23:07:14,224 SUCC scripts.py:519 -- Deployed Serve app successfully.

deployed smoothly, served by RayServe
