### ISSUE TITLE
Could one endpoint provides multiple ML services in BentoML? 

### ISSUE THREAD

**Issue by ShelbyHero** [bentoml/BentoML#4278]
### Discussed in https://github.com/orgs/bentoml/discussions/4277

<div type='discussions-op-text'>

<sup>Originally posted by **ShelbyHero** November 11, 2023</sup>
Hello!

I want to deploy multiple machine learning models on BentoML, but I want to deploy them to the same endpoint. 
That is, a endpoint provides multiple independent ML services. 

For example,I want to deploy model1 and model2 on the sever, model1 use the "localhost:5000/model1", and model2 use the "localhost:5000/modelA2" . 
As far as I know, I could make model1 use the "localhost:5000/model1" and make model2 use the"localhost:5001/model2 ", but that's not what I want. 

Can BentoML do this?

Thanks for the answer!</div>

**Comment by aarnphm** [comment]
I will close the issue and will track the discussion there.

**Comment by simonMoisselin** [comment]
Hey any updates on this? 
Thanks!
