### ISSUE TITLE
bug: KeyError: 'name'

### ISSUE THREAD

**Issue by entbappy** [bentoml/BentoML#4499]
### Describe the bug

Everytime i am getting this error when I am running these cmd-

- bentoml build

- bentoml list

![image](https://github.com/bentoml/BentoML/assets/68845761/8ac12da4-7b6a-49ff-8c38-a2e9b8f05b15)

this is my bentofile.yaml

![image](https://github.com/bentoml/BentoML/assets/68845761/2079c046-c315-4d71-a0d7-708c2f7b2930)

I am using the environment:

python=3.8
bentoml==1.0.25

please fix this error.

### To reproduce

none

### Expected behavior

none

### Environment

none

**Comment by bveber-phdata** [comment]
I'm experiencing this too. Everything was working fine last week and now one of my bentos suddenly won't build. I have two different bentos I'm working on and strangely, I can still build the one that only serves a single endpoint, but the other with several models/endpoints is failing with the same error message as shown above.

**Comment by bveber-phdata** [comment]
@entbappy I found [this slack thread](https://bentoml.slack.com/archives/CKRANBHPH/p1702935059793039?thread_ts=1702613227.414019&cid=CKRANBHPH) that recommends pinning the cattrs<23.2. You might have to remove any bento artifacts that were serialized with the bad version of cattrs as well, but this fix worked for me.

**Comment by entbappy** [comment]
> @entbappy I found [this slack thread](https://bentoml.slack.com/archives/CKRANBHPH/p1702935059793039?thread_ts=1702613227.414019&cid=CKRANBHPH) that recommends pinning the cattrs<23.2. You might have to remove any bento artifacts that were serialized with the bad version of cattrs as well, but this fix worked for me.

Thanks, it worked :)
