### ISSUE TITLE
pip dependency version specified in BentoService '@env' should match package in current environment

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#450]
When defining the pip dependencies of a BentoService, e.g.:

```
@env(pip_dependencies=['scikit-learn==0.22'])
class MyPredictionService(BentoService):
     ...
```

BentoML should verify that in the current python session, the scikit-learn package is presented and matches the specified version. A good place to add this verification would be:

https://github.com/bentoml/BentoML/blob/master/bentoml/service_env.py#L147

The ideal behavior is to show a warning to the user, that the specified dependency version is different from the version being used in the current python session.

**Comment by lintingzhen** [comment]
The function `add_pip_dependencies` at https://github.com/bentoml/BentoML/blob/master/bentoml/service_env.py#L147 is not called anywhere.
So?

**Comment by parano** [comment]
@lintingzhen yes we are not using it currently,  `BentoServiceEnv` is initialized in the `@env` decorator and it seems we don't want the user to modify it dynamically anyway, it might be a good idea to just remove those methods such as adding/removing pip dependencies or conda channel.

**Comment by lintingzhen** [comment]
The function `add_pip_dependencies` at https://github.com/bentoml/BentoML/blob/master/bentoml/service_env.py#L147 is not called anywhere.
So?
