### ISSUE TITLE
feature: Cloud Login without CLI

### ISSUE THREAD

**Issue by holzweber** [bentoml/BentoML#4587]
### Feature request

I want to be able to log in with python to my endpoint.
Example:
```
from bentoml.cloud import login
login(endpoint="abc.com", token="1234") # Update current context with the endpoint similar to CLI command
```

### Motivation

So far I have only seend to login via the CLI command: https://docs.bentoml.org/en/latest/bentocloud/reference/bentocloud-cli.html#bentoml-cloud-login

**Comment by frostming** [comment]
Now we respects login credentials from env vars:
```python
import os

os.environ.update(BENTO_CLOUD_API_KEY="...", BENTO_CLOUD_API_ENDPOINT="...")
```

**Comment by holzweber** [comment]
Very nice! Thank you for the quick response! 💯
