### ISSUE TITLE
bug: Docker creating not working with some python versions

### ISSUE THREAD

**Issue by scepeda78** [bentoml/BentoML#4603]
### Describe the bug

**I run "bentoml build --containerize", the error is (it happens for 3.10, 3.11):**
24.56 E: Unable to locate package python3.10-dev
24.56 E: Couldn't find any package by glob 'python3.10-dev'
24.56 E: Couldn't find any package by regex 'python3.10-dev'
24.56 E: Unable to locate package python3.10-distutils
24.56 E: Couldn't find any package by glob 'python3.10-distutils'
24.56 E: Couldn't find any package by regex 'python3.10-distutils'

**BentoML yaml
docker:
  distro: debian
  python_version: "3.9"
  cuda_version: "12"
  system_packages:
    - python3-distutils
    - ffmpeg
    - git

### Environment

python 3.10 and 3.11, it works with python 3.9

**Comment by aarnphm** [comment]
why do you need python3-disutils?

**Comment by scepeda78** [comment]
Its by default in the docker file created when you run the code. I didnt put those requirements.

El 21-03-2024 3:37 a. m., Aaron Pham ***@***.***> escribió:

why do you need python3-disutils? disutils is considered deprecated in 3.10 onwards iirc

**Comment by frostming** [comment]
What's the content of `~/bentoml/bentos/<bento_name>/<bento_version>/env/docker/Dockerfile`?

**Comment by aarnphm** [comment]
It seems like you put distutils there in the `bentofile.yaml`?

**Comment by scepeda78** [comment]
Yes, because my thought was to see if I include it, the error would go. I ll close it, since I ve tried again with python 3.10 and 3.11 and its working.


El 21-03-2024 10:54 p. m., Aaron Pham ***@***.***> escribió:

It seems like you put distutils there in the bentofile.yaml?

**Comment by scepeda78** [comment]
It worked later, don't know why it didn't work before.
