### ISSUE TITLE
bug: Unable to request PILImage with Content-Type image/jpeg with new Service decorator

### ISSUE THREAD

**Issue by adrian-arapiles** [bentoml/BentoML#4651]
### Describe the bug

Unable to get an endpoint with `PILImage` without `Content-Type:multipart/form-data` with new Service decorator

### To reproduce

I already have working code with bentoml 1.1.11, runners, yolo/pytorch model.
I'm trying to migrate to new decorators `@bentoml.service` and `@bentoml.api` to use concurrency feature introduced.

Bentoml version tested: [1.2.9, 1.2.10].

All examples running with `bentoml serve -p 8000 service.py:Service`.

My working code with 1.1.11 and 1.2.10 with Runner/Runnable looks like
```python
from bentoml.io import Image, JSON


my_runnable = bentoml.Runner(
    MyRunnable,
    name="runnable"
)
svc = bentoml.Service("runnable", runners=[my_runnable])


@svc.api(input=Image(), output=JSON(), route="/v1/inference")
async def inference(image: Image):
        #ofuscated code for prepare image, inference, build response and return
        return output_json
```

An example curl to before code is
```sh
curl -X 'POST' \
        'http://localhost:8000/v1/inference' \
        -H 'accept: application/json' \
           -H 'Content-Type: image/jpeg' \
              --data-binary '@/path/to/my/image.jpg'
```
Now, I'm trying to migrate to new decorators and my code looks like
```python

from src.Service import Service
from PIL.Image import Image as PILImage


@bentoml.service()
class Service:
    # this class is a sustitute of MyRunnable class. 
    my_new_service = bentoml.depends(Service)

    @bentoml.api(
        route="/v1/debug"
    )
    async def debug(
            self,
            image: PILImage = Field(description="Image to be processed")
    ):
        return {"width": image.width, "height": image.height}
```
Now my curl for this code (extracted from swagger) is
```
curl -X 'POST' \
  'http://localhost:8000/v1/inference' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'image=@/path/to/my/image.jpg'
```
The code is working, but I don't want to change the endpoint call from `Content-Type: image/jpeg` to `Content-Type: multipart/form-data`.

I tried this:
```
# This is the using the same Image() that `@svc.api(input=Image()` old decorator uses

from bentoml.io import Image
from PIL.Image import Image as PILImage
from src.Service import Service

@bentoml.service()
class Service:
    # this class is a sustitute of MyRunnable class. 
    my_new_service = bentoml.depends(Service)

    @bentoml.api(
        input_spec=Image(),
        route="/v1/debug"
    )
    async def debug(
            self,
            image: PILImage = Field(description="Image to be processed")
    ):
        return {"width": image.width, "height": image.height}

```
With the following errors:
```
  File "/.../service.py", line 34, in <module>
    class Service:
  File "/.../service.py", line 37, in Service
    @bentoml.api(
     ^^^^^^^^^^^^
  File "/.../_bentoml_sdk/decorators.py", line 101, in wrapper
    return APIMethod(func, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init _bentoml_sdk.method.APIMethod>", line 13, in __init__
  File "/.../_bentoml_sdk/method.py", line 36, in _io_descriptor_converter
    raise ValueError(f"{it} must be a class type")
ValueError: Image must be a class type
```

I already tried this:
```
# This is the using the Annotated example in documentation

from typing import Annotated
from bentoml.validators import ContentType
from PIL.Image import Image as PILImage
from src.Service import Service

@bentoml.service()
class Service:
    # this class is a sustitute of MyRunnable class. 
    my_new_service = bentoml.depends(Service)

    @bentoml.api(
        route="/v1/debug"
    )
    async def debug(
            self,
            image: Annotated[PILImage, ContentType('image/jpeg')]
    ):
        return {"width": image.width, "height": image.height}

```
This code is working too but the same mentioned problem, changed Content-Type to multipart.

I'm not sure if it is a bug or not. It's possible just I was missing something.

The motivation to upgrade to new decorators is the use of concurrency feature introduced.
Is there any way to use with old Runners way?

I really appreciated some help there. 

Thanks in advance,
Adrián.

### Expected behavior

Using PILImage or bentoml.io.Image in the same way and with the same endpoint result.

### Environment

bentoml: 1.2.9 and 1.2.10
python: 3.11.8
platform: Macos Sonoma 14.4.1. M1 PRO cpu.

**Comment by frostming** [comment]
@adrian-arapiles It's related to how we translate the API annotations to wire format and the current design is the input must be a dictionary with inputs as field values.

We are not going to change the wire format shortly because of the efforts it needs. Anyway you can make it work by posting with a multipart body, it's easy in any of our supported clients. For example:

cURL:
```
curl -XPOST http://localhost:3000/v1/debug -H content-type:multipart/form -F image=@/path/to/image.jpeg
```
And `requests`:
```python
import requests
requests.post('http://localhost:3000/v1/debug', files=('image', open('/path/to/image.jpeg')))
```

**Comment by bojiang** [comment]
@adrian-arapiles  Here is the full list about how type mapped to http requests:
https://docs.bentoml.org/en/latest/guides/iotypes.html#appendix
