### ISSUE TITLE
bug: i find paddle.py ，but i can't use it

### ISSUE THREAD

**Issue by zzwtop1** [bentoml/BentoML#4681]
### Describe the bug

python3.8/site-packages/bentoml/paddle.py", line 1, in <module>
    raise NotImplementedError(
NotImplementedError: Support for "bentoml.paddle" is temporarily unavailable as BentoML transition to the new design in version 1.0.0 release. Before this module is officially implemented in BentoML, users may use Custom Runner as a workaround. Learn more at http://docs.bentoml.com

### Environment

bentoml 1.1.3
python 3.8.12
system centos7.9

**Comment by frostming** [comment]
Not implemented, as the error message states.
