### ISSUE TITLE
YML file not found

### ISSUE THREAD

**Issue by Awais9** [bentoml/BentoML#471]
I'm trying to run the code but here I have the error "BentoML can't locate config file 'bentoml.yml' in saved bundle." and can not load the project. Please let me know what is missing

**Comment by justin-ki** [comment]
Hi - What was the solution to this? I checked in the saved bundle directory and the bentoml.yml file is definitely there.

**Comment by parano** [comment]
@justin-ki  did you run into this error message? this means the BUNDLE_PATH provided is not the directory that contains the bentoml.yml file.
