### ISSUE TITLE
bug: Cannot install Development environment using pdm

### ISSUE THREAD

**Issue by sanspareilsmyn** [bentoml/BentoML#4742]
### Describe the bug

Hello there:)
I was about to set up dev env in my local mac by following [the guide](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md) described in here.
After cloning the repo and setting upstream, I installed pdm with `brew install pdm` command and executed `pdm install -G all` as described. I encountered installation failure like below.

<img width="718" alt="image" src="https://github.com/bentoml/BentoML/assets/52681837/b99de7b5-220f-4e81-9044-071af8464642">

Due to the large size of log, I add last few hundreds of log instead.
[error.log](https://github.com/bentoml/BentoML/files/15349321/error.log)

### To reproduce

1. Fork BentoML main repo and clone it to local.
2. Execute `pdm install -G all`

### Environment

pdm: 2.15.2
Python: 3.12.3

<img width="518" alt="image" src="https://github.com/bentoml/BentoML/assets/52681837/b8241147-1332-4903-acd7-a3eb0603dc08">

<img width="1101" alt="image" src="https://github.com/bentoml/BentoML/assets/52681837/7ccb4ed2-5d70-4b0b-9813-030290ac4dd1">

**Comment by PierreYoon0129** [comment]
I guess this is related to compatibility issue. I guess It would be solved
1) if we elevate versions of dependencies set in pdm.lock.
2) if I downgrade python version to lower level.

[Python 3.12.3](https://www.python.org/downloads/release/python-3123/): April 9, 2024

[ray 2.9.1](https://github.com/ray-project/ray/releases/tag/ray-2.9.1) : Jan 19, 2024
[multidict 6.0.4](https://pypi.org/project/multidict/6.0.4/): 22 Decenber, 2022
[pyArrow 13.0.0](https://pypi.org/project/pyarrow/13.0.0/): 23 August, 2023
[scipy 1.9.3](https://pypi.org/project/scipy/#history): 20 October, 2022
[numpy 1.24.4](https://pypi.org/project/numpy/1.24.4/): 26 June 2023

**Comment by PierreYoon0129** [comment]
I solved this bug by limiting python version to <=3.11. I will create PR on this issue.
