### ISSUE TITLE
gpu support question

### ISSUE THREAD

**Issue by JeongChanwoo** [bentoml/BentoML#476]
Hi
I have an interesting look at your Bento, and I have questions.

Doesn't Bento yet support the gpu environment in Keras model servings?
If you have a gpu serving plan, can you tell me when the feature is added?
Is there a way to load an existing nvidia docker and merge it with the bento deployment docker?

**Comment by yubozhao** [comment]
hi @JeongChanwoo As right now, we don't have support for GPU env for Keras model serving. @parano will have a better answer for you for the timeline of GPU support.

**Comment by parano** [comment]
We have plan to add custom docker base image support, which will make it easy to customize your API server container with your existing Nvidia Docker image.

I should have some bandwidth to implement it in February, contributions are welcomed too!

**Comment by JeongChanwoo** [comment]
Based on the base docker originally used by bento, we installed cuda10.1 cudnn7 ubuntu.18.04 setting the conda environment on the base docker.

The predictions were loaded without problems in the Docker environment.

However, some issues have arisen.

1. PID problem: I run docker and strangely I get 3 gpu PIDs.

2. gpu utility problem: It takes up 135mb of gpu memory.
When predicting, we couldn't confirm that the memory increased or the utility increased.

**Comment by parano** [comment]
1. BentoML by default uses gunicorn to run API server in Docker, and it launches multiple workers which is why you have 3 instances of the model loaded in GPU. The number of gunicorn workers is configurable via bentoml's config file or environment variable.

If you want to limit it to one worker, try adding env var `export BENTOML__APISERVER__DEFAULT_GUNICORN_WORKERS_COUNT = 1` in your docker image, or change the CMD line in Dockerfile to:
```
CMD ["bentoml serve-gunicorn /bento --workers=1"]
```

2. I'm not quite sure I understand your question. BentoML currently does not collect GPU metrics but does provide support for exporting prometheus metrics via '/metrics' endpoint. It is possible to integrate the API server docker image with something like https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm

**Comment by parano** [comment]
For 1, we are actually working on a new API server implementation that supports adaptive batching and allows users to configure the number of model backends being loaded, which should also help with this issue you are encountering. We plan to release a beta version of that in February.

**Comment by JeongChanwoo** [comment]
It is helpful to refer to your reply @parano, @yubozhao .
I adjust the PID to 1 and served it based on the docker image I used as a learning environment.
As a result, check the GPU utility and found that only one PID was caught.

However, unfortunately I confirmed the problem in speed.
still checking whether the problem is a decrease in PID or a network problem.
Compared to predicting the local port through bentoml serving, the speed was twice as high as the remote transmission to the docker with PID = 1 and gpu fraction = 0.4. 
(4.1 seconds bentoml serving based on 100 images, 10.9 seconds docker remote predict)

Can I edit and contribute to the docker image? The base image is about 8 giga and needs further modification. The docker image is currently on the docker hub.



And I'm looking forward to your release in beta.

**Comment by yubozhao** [comment]
Yes. We would love to have you help and contribute. 

Thank you for doing the investigation for this!

**Comment by parano** [comment]
We plan to work on custom docker image and revisit better GPU support soon!

**Comment by parano** [comment]
The `@env` decorator now supports custom docker base image: https://docs.bentoml.org/en/latest/api/bentoml.html#env

Users can now use this feature to create API server docker images that support GPU, related documentation and tutorials are coming soon!
