### ISSUE TITLE
fastai text classification handler

### ISSUE THREAD

**Issue by pradeepthiyyagura** [bentoml/BentoML#478]
I did not find a text handler for fastai text based classification model. Any pointers on how to do this will be greatly appreciated.

**Comment by parano** [comment]
Hi @pradeepthiyyagura, you can try using JsonHandler to pass the text input, for example:
```
@artifacts(FastaiModelArtifact('learn'))
class MyFastaiTextService(BentoService):

     @api(JsonHandler)
     def predict(json):
            return self.artifacts.learn.predict(json['text'])
```

And you can then send JSON containing the text input via HTTP request, e.g.:
```
curl -d '{"text":"This was a great movie!"}' -H "Content-Type: application/json" -X POST http://localhost:5000/predict
```

**Comment by pradeepthiyyagura** [comment]
Thank you so much!! It works
