### ISSUE TITLE
bug: What's the reason why this concurrency configuration hasn't taken effect

### ISSUE THREAD

**Issue by woshitieren** [bentoml/BentoML#4908]
### Describe the bug

![image](https://github.com/user-attachments/assets/2e08c79c-2c78-4da2-b8c6-8631247441a2)
What is the reason why concurrency configuration thread testing is not effective

### Expected behavior

Concurrent configuration enables concurrent processing of data

### Environment

bentoml

**Comment by frostming** [comment]
It's a config item to control the auto-scaling behavior, not to denote it can process 4 requests concurrently.

Depending on the workload of a single request, raise the number of `workers` to achieve that.
