### ISSUE TITLE
feature: Add Support for Saving Quantized PyTorch Models (INT8) Using Picklable Model in BentoML

### ISSUE THREAD

**Issue by sebasmos** [bentoml/BentoML#5015]
### Feature request

BentoML's `bentoml.pytorch.save_model` function is currently **not compatible with saving quantized PyTorch models (INT8) or less**. When attempting to save a quantized model, it raises errors related to the non-picklable nature of quantized tensors in PyTorch.

### Motivation

I temporal solution is introducing **picklable version** of the quantized model saving function for the Pytorch model. Now, developers can save and reload quantized PyTorch models in BentoML using the `bentoml.picklable_model.save_model` function.

### **What was added:**
- Introduced a picklable model-saving approach using:
   ```python
   bento_model = bentoml.picklable_model.save_model('model', model)
   ```
- This ensures that **quantized models (such as INT8 models)** can be saved without errors, preserving the quantization process and model architecture.
  
### **Why this improvement is important:**
- Enables BentoML users to **save and deploy quantized PyTorch models** (such as INT8), which were previously not supported.
- Simplifies the workflow for developers needing to deploy quantized models without modifying their existing pipelines.

### **Testing:**
- Verified the new functionality by saving and loading quantized INT8 models, ensuring that the model states and inference remain intact.
- Conducted tests on various PyTorch quantized models (both statically and dynamically quantized) to validate the picklable saving and loading process.

 Looking forward to feedback and further suggestions for improvement!

**Comment by jianshen92** [comment]
Hello @sebasmos , thanks for raising the feature request.

As of BentoML 1.2, the idiomatic way to save PyTorch models is to use the `bentoml.models` API.
Here's the [official documentation](https://docs.bentoml.org/en/latest/guides/model-store.html)
To be specific, you should use `bentoml.models.create` to save your quantised PyTorch model.

For example
```python
import bentoml
import cloudpickle

model = ...

with bentoml.models.create(name="new-pytorch-model") as model_ref:
    # Copy the PyTorch model to the model directory
    model_path = model_ref.path_of("model.pth")
    torch.save(model, model_path, pickle_module=cloudpickle)
```

Moving forward, we will raise deprecation warnings for general frameworks support such as PyTorch and TensorFlow.

**Comment by sebasmos** [comment]
> Hello @sebasmos , thanks for raising the feature request.
> 
> As of BentoML 1.2, the idiomatic way to save PyTorch models is to use the `bentoml.models` API. Here's the [official documentation](https://docs.bentoml.org/en/latest/guides/model-store.html) To be specific, you should use `bentoml.models.create` to save your quantised PyTorch model.
> 
> For example
> 
> ```python
> import bentoml
> import cloudpickle
> 
> model = ...
> 
> with bentoml.models.create(name="new-pytorch-model") as model_ref:
>     # Copy the PyTorch model to the model directory
>     model_path = model_ref.path_of("model.pth")
>     torch.save(model, model_path, pickle_module=cloudpickle)
> ```
> 
> Moving forward, we will raise deprecation warnings for general frameworks support such as PyTorch and TensorFlow.

Thanks @aarnphm ! I noticed `custom_objects` is [deprecated](https://docs.bentoml.org/en/latest/reference/stores.html#bentoml.models.create:~:text=bentoml.models.create) with `bentoml.models.create`. I’ve managed to manually define everything using custom pickle files, but am I overlooking something? With `bentoml.picklable_model.save_model`, adding custom objects as a dict was straightforward.

**Comment by aarnphm** [comment]
you can just use cloudpickle directly in conjunction with `bentoml.models.create`.
