### ISSUE TITLE
Using curl to test lambda deployment fails with dataframe handler

### ISSUE THREAD

**Issue by omrihar** [bentoml/BentoML#505]
**Describe the bug**
I deployed a model that uses the DataFrameHandler to aws lambda. When I test it with curl, using, e.g. 
```sh
curl -i --request POST --data '{"key": "value"}' https://<url>/Prod/predict
```
I get as response an Internal server error. The cloudwatch logs indicate a problem with the Content-Type header:
```
[ERROR] KeyError: 'Content-Type'
Traceback (most recent call last):
  File "/var/task/app.py", line 66, in api_func
    return bento_service_api.handle_aws_lambda_event(event)
  File "/var/task/bentoml/service.py", line 98, in handle_aws_lambda_event
    return self.handler.handle_aws_lambda_event(event, self.func)
  File "/var/task/bentoml/handlers/dataframe_handler.py", line 203, in handle_aws_lambda_event
    if event["headers"]["Content-Type"] == "application/json":
```
When using `requests` in an ipython shell, however, the request goes as expected. e.g.
```python
import requests
resp = requests.post(url, json={"key": "value"})
```
works exactly as expected.

**To Reproduce**
1. Deploy a lambda function that uses the DataFrameHandler
2. Use `curl` as described above.
3. See error

**Expected behavior**
A response should be sent back instead of an error.

**Environment:**
 - OS: Manjaro linux  5.4.14-2
 - Python/BentoML Version Python 3.7.6, BentoML-0.6.1

**Comment by parano** [comment]
@omrihar I couldn't reproduce this issue on my end this time(I was able to get the error when using curl from a ubuntu docker container testing your deployment endpoint last time we discussed it in slack).

I suspect in some edge case `curl`  will set the content-type header improperly in a way that AWS Lambda can not handle. #507 should resolve this issue you're encountering.

**Comment by parano** [comment]
Just merged the pull request, if you install BentoML from master now and use that version of BentoML to save a new BentoService bundle, you should be able to deploy it to lambda including this fix. Let me know if this helped with the issue you ran into.

**Comment by omrihar** [comment]
OK, I manually applied these changes to an already-deployed lambda function by downloading it, modifying, and uploading again and it works. So I guess we can close this now.
