### ISSUE TITLE
feature: Stop and resume tasks

### ISSUE THREAD

**Issue by Leon-Sander** [bentoml/BentoML#5058]
### Feature request

I would like to be able to manage stopping and resuming of tasks.

### Motivation

If I have a long running task like large batch processing and the server needs a reboot for example, then I would want to save the intermediate results and resume later on.

**Comment by frostming** [comment]
A task can be interrupted only if it can respond to interrupt signals and save the state of the scene for resumption.

This requires considerable efforts to implement and hard to make it generic. You can implement for specific frameworks but not for all.

**Comment by Leon-Sander** [comment]
Yes absolutely, I agree. 

I thought about it and here is the idea I had. Making a generic pause and resuming, which can be activated by choice if one wants to implement the logic for his framework.

So @betoml.task(is_pausable=True).

It would just be necessary to make the status of the task_id accessible. 
is_pausable=True would make the api endpoints of pause and resume available. If the user does not want to implement it, is_pausable default is False and everything else stays the same.

**Comment by frostming** [comment]
Hi @Leon-Sander  After our discussion, we decided not to do this because `bentoml.task` is not positioned as a mechanism with complete task management.

**Comment by Leon-Sander** [comment]
@frostming Thanks for discussing it with the team! I’m planning to implement this on my end as a way to extend BentoML's functionality for my use case. If I complete it, would a pull request for this feature still be open for consideration, or would it likely be declined?
