### ISSUE TITLE
Add click-completion support to bentoml

### ISSUE THREAD

**Issue by omrihar** [bentoml/BentoML#506]
**Is your feature request related to a problem? Please describe.**
BentoML has a very large CLI implemented in click. To find out what commands are available, I need to use `--help` repeatedly for many subcommands.

**Describe the solution you'd like**
Add hooks for shell completion. One such option is click-completion, which is this project: https://github.com/click-contrib/click-completion. Adding it requires simply initializing it in the bentoml project.

**Comment by parano** [comment]
Contributed by @lintingzhen here: https://github.com/bentoml/BentoML/pull/534 🎉

Will be shipped in the coming release! I will add some related documentation shortly.
