### ISSUE TITLE
bug: bentoml containerize failed by uv installation location change

### ISSUE THREAD

**Issue by lingw777** [bentoml/BentoML#5069]
### Describe the bug

My CICD build is failing at `bentoml containerize`
```
RUN curl -LO https://astral.sh/uv/install.sh &&     sh install.sh && rm install.sh && mv $HOME/.cargo/bin/uv /usr/local/bin/
#12 0.858 downloading uv 0.5.0 x86_64-unknown-linux-gnu
#12 1.514 installing to /root/.local/bin
#12 1.553 mv: cannot stat '/root/.cargo/bin/uv': No such file or directory
```

It's probably related to recent uv release. See https://github.com/astral-sh/uv/issues/8913

### Environment

bentoml: 1.3.10
python: 3.10
platform: --opt platform=linux/amd64,linux/arm64

**Comment by frostming** [comment]
The fix is on the way to the next release.

**Comment by mobecks** [comment]
Workaround until next release (worked for me): 
change above-mentioned "line 17" to
`sh install.sh && rm install.sh && mv $HOME/.local/bin/uv /usr/local/bin/`

**Comment by aarnphm** [comment]
This has now been fixed with 1.3.11

**Comment by mexicat** [comment]
Thanks for the quick fix, but wouldn't it be good to pin a uv installer version in Dockerfiles (i.e. `https://astral.sh/uv/0.5.1/install.sh` instead of `https://astral.sh/uv/install.sh`) to avoid future breakage due to internal changes in uv?

**Comment by JustineAssoulant** [comment]
Hello, I replaced "sh install.sh && rm install.sh && mv $HOME/.cargo/bin/uv /usr/local/bin/" by "sh install.sh && rm install.sh && mv $HOME/.local/bin/uv /usr/local/bin/" in the dockerfile generated by bentoml when we build the bento, but when i try to containerize my bento i still have the same mistake and I can easily see that it tries to containerize the bento base not on my modified dockerfile :(

**Comment by frostming** [comment]
@JustineAssoulant yeah, the containerize command regenerates the dockerfile on the fly.

The best way is to upgrade the version of bentoml
