### ISSUE TITLE
Allow enabling CORS for lambda function deployment

### ISSUE THREAD

**Issue by omrihar** [bentoml/BentoML#509]
**Is your feature request related to a problem? Please describe.**
We use the lambda function deployments with a web app that requires CORS headers to work. Since the deployment uses LAMBDA_PROXY, it's impossible to add the headers in the API Gateway console, but must rather be done directly in code from the Lambda function.

**Describe the solution you'd like**
I'd like to be able to set the CORS policy to be enabled from the DataFrameHandler. The solution is rather simple - in [this line](https://github.com/bentoml/BentoML/blob/efb0204f032085a859f14ade951ee98fbef7dcc5/bentoml/handlers/dataframe_handler.py#L226) one has to add `"headers": {"Access-Control-Allow-Origin": "*"}` (to allow all origins, or a subset thereof if so defined).
I guess the most elegant solution would be to allow to specify that in the constructor of the `DataFrameHandler`.

**Comment by yubozhao** [comment]
@omrihar For lambda deployment, we do specifically set cors to '*' for API gateway with our cloud formation setting.
```
            'Api': {
                'BinaryMediaTypes': ['image~1*'],
                'Cors': {'AllowOrigin': "'*'"},
                'Auth': {
                    'ApiKeyRequired': False,
                    'DefaultAuthorizer': 'NONE',
                    'AddDefaultAuthorizerToCorsPreflight': False,
                },
            },
 
```
Right now the Lambda deployment is based on AWS's official deployment tool, SAM.  We construct a sam template base on bento services and cli parameters

**Comment by omrihar** [comment]
The problem is the following - when you use LAMBDA_PROXY, the lambda function itself has to return a header with `Access-Control-Allow-Origin`. This is achieved most easily as I indicated above, by modifying the dataframe handler to return this setting explicitly. Otherwise AWS API Gateway is unable to make sure this header is returned from the POST call (you can set up the OPTIONS call to return the header - which is something I'm not sure if it happens by default or not).

I don't know why this is the case, but this is the only way I managed to get the CORS configuration to work with this deployment option. You can test this by simply writing a very simple web page that tries to make a post request using `XMLHttpRequest` or using the javascript Fetch API to an endpoint deployed on AWS, and you will also run into problems with CORS. 

While I'm on this topic, the local server also doesn't support CORS (I tried running a local copy with `bentoml serve` and a local javascript application that calls it). Here the problem is that, even though my customized dataframe handler does return `Access-Control-Allow-Origin: '*'`, the `OPTIONS` call only returns 200 without this header, and I couldn't find yet where I can configure that.

**Comment by omrihar** [comment]
To get CORS to work on the local bento api server, I followed the code in https://gist.github.com/blixt/54d0a8bf9f64ce2ec6b8 just after defining the Flask app. Locally for me this works perfectly.
I can provide a PR for both issues, if you'd like, but I'm not sure how to add proper tests for them.

**Comment by yubozhao** [comment]
@omrihar I tested the case with simple fetch request and you are right

We would love to have PRs!  That would be great. We can figure out the proper testing along with the PRs.

**Comment by omrihar** [comment]
Would you like to have an interface to limit the CORS domains to a specific subset? Or just simply set it to `'*'`?

**Comment by yubozhao** [comment]
I think it could be an option that defaults to `*`.  We can also start with a simple `*` and evolve from there
