### ISSUE TITLE
bug: conda-forge version of BentoML outdated

### ISSUE THREAD

**Issue by stream129** [bentoml/BentoML#5099]
### Describe the bug

Current version of BentoML provided by conda-forge channel is significantly outdated (1.2.20 updated 4 month ago). Looks like something broke in the release pipeline. This is extremely inconvenient because you have to mix Conda and pip environments with all the associated problems.

### To reproduce

1. conda create --name bentoml_version_test pydantic=2.8.2 bentoml --channel conda-forge --yes
2. conda activate bentoml_version_test
3. bentoml --version

BentoML reports version 1.2.20 released 4 month ago
pydantic=2.8.2 used due to [#4974](https://github.com/bentoml/BentoML/issues/4974), without this BentoML not working at all

### Expected behavior

BentoML reports version >= 1.3.14

### Environment

not necessary for this kind of problem

**Comment by aarnphm** [comment]
Hi there, the BentoML team is currently not maintaining the conda-forge version of BentoML, and we don't have any plans for maintaining the forge going forward.

We would kindly ask users to use PyPI going forward. You can still install PyPI packages in your conda environment.
