### ISSUE TITLE
bug: bentoml not taking into account latest version of Dockerfile.template

### ISSUE THREAD

**Issue by rlleshi** [bentoml/BentoML#5120]
### Describe the bug

If I run `cat "$(bentoml get <bento>:<tag> -o path)/env/docker/Dockerfile"` I can see its still based the old version of my `Dockerfile.template`. 

What I tried:
- `docker system prune -a` to clear everything in my docker cache
- `bentoml list --quiet | awk '{print $1}' | xargs -I {} bentoml delete {} --yes` to delete all of my bentos
- `bentoml containerize my_bento:latest --no-cache` to build bento without cache

After doing the above the container builds from scratch as expected but it's nevertheless still on the old version of the `Dockerfile.template`. Seems like bentoml must be having another caching mechanism though I haven't found anything from perusing the docs. Also it appears like there's almost no documentation whatsoever on `dockerfile_template` anymore. I remember there being some couple of months ago.

Actually I somehow got it working with the new version of `Dockerfile.template` once but wasn't able to reproduce it later.

### Environment

bentoml: 1.3.15
python: 3.9.0
platform: ubuntu 22.04, 6.5.0-45-generic

**Comment by frostming** [comment]
Did you rebuild your bento? You didn't mention that in the steps.

**Comment by rlleshi** [comment]
Yeah ofc, I'm usually doing that with `bentoml build . --containerize` but I also tried `bentoml build .` & `bentoml containerize my_bento:latest --no-cache` separately.

**Comment by frostming** [comment]
Can you provide a reproducible example?

**Comment by rlleshi** [comment]
Basically, this is how the docker section of my bentofile looks like: 

```
docker:
  distro: debian
  python_version: "3.9"
  system_packages:
    - ffmpeg
    - libsm6
    - libxext6
    - git
    - nano
    - libmagic1
  dockerfile_template: ./Dockerfile.template
```

As I need an older version of ffmpeg I removed it from system packages and updated the `Dockerfile.template` to compile & install the version of ffmpeg that I need. Now my template looks like so:

```
{% extends bento_base_template %}
{% block CUSTOM_BENTO_SETUP %}

# added for libfdk-aac-dev
RUN echo "deb http://deb.debian.org/debian stable non-free" >> /etc/apt/sources.list

# compile & install ffmpeg
# https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
RUN apt-get update -qq && apt-get -y install \
      autoconf \
      automake \
      build-essential \
      cmake \
      git-core \
      libass-dev \
      libfreetype6-dev \
      libsdl2-dev \
      libtool \
      libva-dev \
      libvdpau-dev \
      libvorbis-dev \
      libxcb1-dev \
      libxcb-shm0-dev \
      libxcb-xfixes0-dev \
      pkg-config \
      texinfo \
      wget \
      zlib1g-dev \
      nasm \
      yasm \
      libx265-dev \
      libnuma-dev \
      libvpx-dev \
      libmp3lame-dev \
      libopus-dev \
      libx264-dev \
      libfdk-aac-dev
RUN mkdir -p ~/ffmpeg_sources ~/bin && cd ~/ffmpeg_sources && \
    wget -O ffmpeg-4.4.2.tar.bz2 https://ffmpeg.org/releases/ffmpeg-4.4.2.tar.bz2 && \
    tar xjvf ffmpeg-4.4.2.tar.bz2 && \
    cd ffmpeg-4.4.2 && \
    PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
      --prefix="$HOME/ffmpeg_build" \
      --pkg-config-flags="--static" \
      --extra-cflags="-I$HOME/ffmpeg_build/include" \
      --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
      --extra-libs="-lpthread -lm" \
      --bindir="$HOME/bin" \
      --enable-libfdk-aac \
      --enable-gpl \
      --enable-libass \
      --enable-libfreetype \
      --enable-libmp3lame \
      --enable-libopus \
      --enable-libvorbis \
      --enable-libvpx \
      --enable-libx264 \
      --enable-libx265 \
      --enable-nonfree && \
    PATH="$HOME/bin:$PATH" make -j8 && \
    make install -j8 && \
    hash -r
RUN mv ~/bin/ffmpeg /usr/local/bin && mv ~/bin/ffprobe /usr/local/bin

# runs the bento internal stuff
{{ super() }}

ENTRYPOINT [ "/bin/bash", "-c", "nohup python3 -m src.subscriber & exec {{ bento__entrypoint }}" ]

{% endblock %}
```

The problem is that the ffmpeg installation is not running most of the times that I have tried to build the image. I actually got it running once or twice and the container was healthy but right now it still uses the older version of the template that didn't contain the ffmpeg installation.

**Comment by rlleshi** [comment]
@frostming it appears that the issue is that I had mistakenly renamed the block from the original `{% block SETUP_BENTO_ENTRYPOINT %}` to `{% block CUSTOM_BENTO_SETUP %}`.

Now that I think about it, I recall reading in your docks couple of months ago about this block name. I am no longer able to find those docs now. It appears that you've done some restructuring?

Regardless, please consider bringing back the docs and/or making them more thorough! I spend considerable amount of debugging time given how trivial this issue turned out to be.

If I search for `dockerfile_template` in your documentation I literally get one match, namely [this](https://docs.bentoml.com/en/latest/get-started/packaging-for-deployment.html) page, and, moreover that page literally has a single reference to the template.
