### ISSUE TITLE
bug: the @bentoml.task decorator's cancel functionality does not respond properly.

### ISSUE THREAD

**Issue by oogou11** [bentoml/BentoML#5141]
### Reproduction Code  

```python
import bentoml
import typing as t
import time

@bentoml.service(workers=1)
class ChunkTask:

    @bentoml.task
    def chunk_task(self) -> t.Dict:
        time.sleep(10)
        return {"code": "Ok"}
```
---

### Observed Symptoms  
When attempting to cancel a task, regardless of the task's current state:  
- The application hangs for an extended period.  
- Eventually, it returns a `500 Internal Server Error`.

---

### Initial Diagnosis  
The issue seems to be related to SQLite database operations in the task status management functionality. Specifically, the following method appears to hang when executing `self._conn.execute`:

```python
async def set_status(self, task_id: str, status: ResultStatus) -> None:
    await self._conn.execute(
        "UPDATE result SET status = ?, updated_at = ? WHERE task_id = ? AND status = ?",
        (
            status.value,
            datetime.datetime.now(tz=datetime.timezone.utc),
            task_id,
            ResultStatus.IN_PROGRESS.value,
        ),
    )
    await self._conn.commit()
```
### Additional Notes  
The issue might stem from SQLite's locking behavior, particularly during concurrent updates or uncommitted transactions.

### Environment

- **Python Version**: `3.11.x`  
- **BentoML Version**: `>=1.3.15`  
- **Operating System**:  
  - Windows  
  - Ubuntu 22.04.5 LTS

**Comment by frostming** [comment]
We do not support interrupting a running task. The cancel endpoint only has effect on **pending** tasks(scheduled but not started yet).
