### ISSUE TITLE
Support custom API server Docker base image

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#532]
**Is your feature request related to a problem? Please describe.**

BentoML should allow custom docker base image to be used when generating Dockerfile in saved bundle. It can be useful:
* when deploying API server to GPU node(#476) - we may want to add a default GPU base image as well
* when using libraries such as H2O or in-house libraries, users often want to control how those libraries are installed
* when certain security requirements demand the type of docker container image can be used

**Describe the solution you'd like**
* When creating BentoService, allow the user to specify a custom Docker base image. e.g.:

```python
@env(
   auto_pip_dependencies=True,
   docker_base_image="myorg/mydockerimage:dockertag"
)
@artifacts(..)
class MyService(BentoService):

    @api(DataframeHandler):
    def predict(df):
        ...

```

* This approach will require the user to make sure that `conda` is installed on the base image properly. 

 * we should investigate making `conda` optional, most of the time only PyPI packages are required

**Comment by Sharathmk99** [comment]
Do we need to have conda installed on custom docker image also? We just need pypi packages.

**Comment by parano** [comment]
@Sharathmk99 conda is optional in users' own custom docker base image if the user does not need to use conda for installing dependencies. From BentoML perspective we do want to provide conda in our default docker base images tho which also helps with ensuring the python version of the docker image.
