### ISSUE TITLE
Guides to Deploy on zeit.co and netlify

### ISSUE THREAD

**Issue by sgaseretto** [bentoml/BentoML#537]
Are there any plans on adding guides to deploy on platforms like zeit.co and netlify? The offer free tiers and could help others to develop some MVPs without having to spend or use a credit card, like with AWS Lambda

**Comment by parano** [comment]
Hi @sgaseretto, we currently don't have any plans to support deployment on zeit.co and netlify yet. I definitely will keep my eye open and see if more people in the community want this. In the meanwhile, anyone is welcomed to contribute this feature and I'd love to offer help or guidance if needed.

**Comment by parano** [comment]
hi @sgaseretto, we did look into both options but unfortunately, none of them really works for ML model serving workloads at the moment.  @yubozhao spent some time looking into this and he found out that:

1) Netlify does not have a python runtime, there's no way we can deploy with it until it supports Python
2) Zeit.co has a 50MB size limit on its function's bundle size, which is way too small for ML workloads. It is not enough for BentoML to include some basic ML packages.

In the meantime, we are working on expanding deployment options for BentoML users, you can find a list of currently supported platforms here: https://docs.bentoml.org/en/latest/deployment/index.html
