### ISSUE TITLE
Not able to load PyTorch saved model: AttributeError: Can't get attribute 'Encoder' on <module '__main__' from '/home/ubuntu/anaconda3/envs/pytorch/bin/bentoml'

### ISSUE THREAD

**Issue by codeslord** [bentoml/BentoML#612]
**Describe the bug**
When trying to serve model saved using torch.save, bentoml is throwing Attribute Error because the main function does not have the definition of the neural network.

  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/bentoml/bundler/loader.py", line 123, in load_bento_service_class
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bentoml/repository/Predictor/20200427120901_5AF631/Predictor/predict.py", line 12, in <module>
    model = torch.load('models/pytorch_model.pt')
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
AttributeError: Can't get attribute 'Encoder' on <module '__main__' from '/home/ubuntu/anaconda3/envs/pytorch/bin/bentoml'>

**To Reproduce**
In the predict.py file
from model import Encoder, Decoder
model = torch.load('models/pytorch_model.pt')
then create a PytorchModelArtifact with bentoml
From terminal:
bentoml run Predictor:20200427120901_5AF631 predict --input "Hello, how are you"

**Expected behavior**
The model should be able to make predictions without any issues

**Screenshots/Logs**
If applicable, add screenshots, logs or error outputs to help explain your problem.

**Environment:**
 - OS: Ubuntu 18.04
 - Python/BentoML Version: Python 3.7.6, BentoML-0.7.3

**Additional context**
Encoder Decoder model to translate from English to French.

**Comment by parano** [comment]
hi @codeslord, it looks like you have the Encoder/Decoder python classes defined in the main module(meaning the code of the class definition is written in a Jupiter notebook or in an interactive python shell)? Unfortunately, BentoML can't yet bundle functions/classes defined in the main module, the workaround is to define the class in a separate python file, e.g. `encoder.py` and then import it in your Jupyter notebook or python shell/script.

We are investigating ways to make classes defined in the `main` module to work when bundling with BentoML, but for now, you will need to put them in a separate python file. Cloud you try it out and let me know if it worked for you?

Another approach is to migrate your code in the jupyter notebook into a python script, e.g. `run.py`. That way if you invoke the script via `python run.py`, everything should just work.

**Comment by jjmachan** [comment]
faced the same issue today. 
just a small suggestion, would a better error msg help the user understand the bug more easily? Would be a really easy fix for now until a better way to pack the model is worked out.

**Comment by parano** [comment]
Hey @jjmachan @codeslord sorry I was wrong in the previous comment, BentoML is actually able to package those classes in main module for PyTorch models. You can have your Encoder/Decoder class defined in the main module when using BentoML. See our PyTorch example notebook:
https://github.com/bentoml/gallery/blob/master/pytorch/fashion-mnist/pytorch-fashion-mnist.ipynb

Could you try to verify this for me - in the example code you provided, add an extra step after loading your saved PyTorch model file, and verify the loaded model works?

```python
# In the predict.py file
from model import Encoder, Decoder
model = torch.load('models/pytorch_model.pt')

# Add this step: Verify `model` is properly loaded and can call `classifier` or `predict` method

# then create a PytorchModelArtifact with bentoml
```

**Comment by parano** [comment]
It seems to me that you are not loading the model properly before packaging it with BentoML. See the PyTorch documentation for saving/loading:
https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model

If you are only saving the `state_dict`, then you should be using something like:
```
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
```
If you are saving/loading the entire model, then according to the documentation:

> The disadvantage of this approach is that the serialized data is bound to the specific classes and the exact directory structure used when the model is saved. The reason for this is because pickle does not save the model class itself. Rather, it saves a path to the file containing the class, which is used during load time. Because of this, your code can break in various ways when used in other projects or after refactors.

This means you can't define Encoder/Decoder classes in the main module.

BentoML's Pytorch model artifact actually avoids this problem and package the model class for you no matter where they are defined.  That's the reason we recommend packaging trained models with BentoML right after the model training pipeline, and avoid saving and loading the model yourself.

**Comment by parano** [comment]
@codeslord feel free to ping me on slack if you have any other questions about this, closing the issue now.
