### ISSUE TITLE
BentoML Kubernetes deployment operator

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#620]
* Add API and CLIs for managing model serving workloads on an existing Kubernetes cluster and deep integration with KFserving
* Helm chart for installing YataiService(BentoML's model repository service)
* Out-of-the-box auto-scaling via KFServing
* Option for enabling prediction log collection side-car
* Option for using GPU resource
* Guide for setting up Prometheus with BentoML deployment

**Comment by yubozhao** [comment]
`bentoml install kubernetes` would be a cool command

**Comment by iancoffey** [comment]
Id love to contribute toward this in some way, particularly kfserving and/or prometheus bits :)

**Comment by parano** [comment]
hi @iancoffey, I will make sure to keep you in the loop as we design and roll out this feature, could you ping me in the BentoML slack?

**Comment by parano** [comment]
Closing this older ticket now, I will create individual tickets for each of the issues mentioned above, along with a detailed roadmap for K8s integration.
