### ISSUE TITLE
botocore.exceptions.ClientError

### ISSUE THREAD

**Issue by jjneojiajun** [bentoml/BentoML#631]
Hey BentoML Maintainers,

I am currently facing an issue deploying my model to AWS Lambda, although i followed the docs completely. I have received the botocore.exceptions.ClientError indicating there's (NoSuchBucket) when calling the GetBuckAcl Operations and InvalidLocationConstraint when calling the CreateBucket Operations. Any tips in regards to this? Is there like a parameter that i can use to create this bucket?

![image](https://user-images.githubusercontent.com/22229998/81140501-1f3d4280-8f9c-11ea-9b0e-ce2306701b50.png)

Thanks!

**Comment by yubozhao** [comment]
hi @jjneojiajun what is the region you are trying to deploy to?  

There is an ongoing issue on boto3 that create an S3 bucket will fail for region `us-east-1` that I am not aware,  https://github.com/boto/boto3/issues/125.  I tested deploy lambda with the `us-east-1` region and received the same error as you did.  

I am working on a fix for creating S3 bucket for the `us-east-1` region.

If you are not deploying to that region, could you provide more info on which region you are deploying to?

**Comment by jjneojiajun** [comment]
> hi @jjneojiajun what is the region you are trying to deploy to?
> 
> There is an ongoing issue on boto3 that create an S3 bucket will fail for region `us-east-1` that I am not aware, [boto/boto3#125](https://github.com/boto/boto3/issues/125). I tested deploy lambda with the `us-east-1` region and received the same error as you did.
> 
> I am working on a fix for creating S3 bucket for the `us-east-1` region.
> 
> If you are not deploying to that region, could you provide more info on which region you are deploying to?

Hi @yubozhao, yes I was trying to deploy to us-east-1 region. So I guess this is part of the bug mix that's required. I will close this thread then. Thank you! :)

**Comment by spencersmith** [comment]
I'm still getting this issue after the first deployment to lambda. 

Running version 0.8.1 or bentoml. 

The first deployment worked for the most part, however subsequent deployments do not.

**Comment by parano** [comment]
cc @yubozhao could you help take a look?

**Comment by yubozhao** [comment]
Hi, @spencersmith, I tested deploying and updating with the quick start example BentoService with `us-east-1` region. Unfortunately, I wasn't able to reproduce the boto3 ClientError about InvalidLocationConstraint error for creating Bucket.

Can you share your boto3 version and what region you are deploying into?

**Comment by parano** [comment]
hey @spencersmith, are you still experiencing this issue?

I think this exact issue(`InvalidLocationConstraint` with us-east-1 region) should have been fixed in 0.8.1, you might be experiencing a different issue (or our fix did not work). Could you provide the exact error logs if you still have it or if you can still reproduce this issue?
