### ISSUE TITLE
Spacy model artifact

### ISSUE THREAD

**Issue by spotter** [bentoml/BentoML#639]
Loading of Spacy models is not supported OOB, or at least, isn't obvious.

Adopting a dedicated artifact class for Spacy models would facilitate this mechanism and make the support for Spacy models more evident.  Alternatively, it is possible to use the pickling mechanisms but again, it isn't easy to grasp for people who are new to BentoML (as I am).

**Comment by yubozhao** [comment]
PR https://github.com/bentoml/BentoML/pull/641 created by @spotter merged. Thank you @spotter !
