### ISSUE TITLE
The Handlers are overwriting pip_dependencies specified through @env

### ISSUE THREAD

**Issue by fernandocamargoti** [bentoml/BentoML#642]
**Describe the bug**
In my use-case, I have a Tensorflow model and I'm using TensorflowSavedModelArtifact. If I'm not wrong, it automatically adds "tensorflow" to the requirements.txt. But I want to specify the tensorflow version, so I have:

`@env(pip_dependencies=["tensorflow=1.15.0", "numpy=1.17.2", "pillow=6.1.0", "scikit-image=0.16.2"])`

I was expecting my definition to take precedence, but instead, only "tensorflow" is put in requirements.txt.

**To Reproduce**
Create any BentoService with TensorflowSavedModelArtifact and use `@env` as above. Pack, save and open the folder to check requirements.txt.

**Expected behavior**
My pip_dependency to take precedence.

**Environment:**
 - OS: Manjaro 20.0
 - Python/BentoML Version: Python 3.6.10, BentoML 0.7.4

**Comment by parano** [comment]
Thanks for reporting the issue @fernandocamargoti  

It's indeed an issue on our side, BentoHandler's optional dependency have the exact same issue, I will work on a fix.

**Comment by spotter** [comment]
I have the same issue. I also tried to set the dependencies using `@env(requirements_txt_file='./requirements.txt')` in which I have set the Tensorflow version explicitely but to no avail. For some reason a new "requirements.txt" file is produced without the version of the tensorflow library (and only for tensorflow, other libraries are left untouched).

**Comment by parano** [comment]
Thanks @spotter, yes exactly we were planning to do this explicit check within `_init_env` function but haven't got to it yet.

I think we can add a new method `add_pip_dependencies_if_missing` to the `BentoServiceEnv`, which will only append the package if it's not already listed in `self.pip_dependencies`.  The BentoServiceEnv class does not currently parse the pip requirements which might be tricky to implement. If you want to give it a try that'd be great!

**Comment by parano** [comment]
@spotter I submitted a quick fix here since this was blocking too many users - sorry if you have spent time on this. BentoML's pip module management code still has lots of room for improvements tho, happy to chat more if you are interested in contributing, feel free to ping me in the community slack.

**Comment by parano** [comment]
The fix has been merged with PR #657,  it will be available in BentoML version 0.7.6 (scheduled for release later today)
