### ISSUE TITLE
Error saving BentoService bundle to S3 backed model registry

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#654]
**Describe the bug**
When `save` a new BentoService bundle to s3, the follow error occurs
```
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```
**To Reproduce**

Run a s3 backed YataiService gRPC server:
```
docker run -p 3000:3000 -p 50051:50051 \
    -e AWS_SECRET_ACCESS_KEY=... -e AWS_ACCESS_KEY_ID=...  \
    bentoml/yatai-service:0.7.2 \
    --db-url postgresql://scott:tiger@localhost:5432/bentomldb \
    --repo-base-url s3://my-bentoml-repo/
```

Save to the YataiService:

```python
bento_service.save(yatai_url="localhost:50051")
```

**Comment by parano** [comment]
The BentoML team is currently working on a fix for this issue, we will be releasing a fix soon

**Comment by parano** [comment]
The issue is due to the latency for s3 to setup global DNS for S3 bucket. This happens when using a newly created S3 Bucket.

The reason behind it is that BentoML uses a pre-signed S3 URL for upload so that each data scientist does not need to configure AWS credentials, only the YataiService has the credentials. But on the AWS side, until a newly created bucket's global DNS gets set up, the pre-signed URLs generated with return a redirect and fail CORS. 

If you are seeing this issue, we recommend waiting until the global DNS is set up for the s3 bucket on the AWS side(it may take a few hours).

**Comment by nicjac** [comment]
I just experienced this - is there any way around this? I am unclear why a global DNS update is required to access the bucket (e.g. I am able to access it with `boto3` right after creation).

There should at least be some kind of warning in place to inform the user that a broken pipe might resolve itself?

**Comment by LeoVS09** [comment]
Have the same error. I am not sure about DNS credentials and newly created bucket, but I didn't have the same issue with a newly created bucket and [DVC](https://dvc.org/). 
Agree with @nicjac, if it is a temporal problem and a need just waits for some time, any warning or descriptive error will be very helpful.

**Comment by parano** [comment]
Thanks for the suggestion, @LeoVS09 @nicjac, in the upcoming BentoML 1.0, uploading to S3 via Yatai will handle this case more gracefully by raising an error and reporting the upload failure, and the user can simply retry `push` later on.
