### ISSUE TITLE
Error in execution of "bentoml get" cli command

### ISSUE THREAD

**Issue by jesudasvf** [bentoml/BentoML#663]
**Describe the bug**
just started to use bentoml 0.7.6 / bentoml 0.7.5 on Windows 10, with Python 3.6.8, TensorFlow-GPU 1.14.0 and Keras 2.2.4. Facing issue in using bentoml cli commands.

**To Reproduce**
1. Created a bentoml service with a working model which was trained with Keras and TensorFlow-GPU 1.14.0
2. The created service was saved to the default location
3. Wanted to get the details of the saved service using cli command "bentoml get servicename"
4. On execution of the command the error occurs which indicates that a particular python package "fnctl" is not found

**Expected behavior**
The bentoml cli command get should have displayed the details of the saved service 

**Screenshots/Logs**
(spemoenv) C:\SL_Projects\SpeechEmotionRecognition\SpeechEmoReco_HireAi>bentoml get SpeechEmoClassificationService
Traceback (most recent call last):
  File "C:\Python368\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python368\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\SL_Projects\SpeechEmotionRecognition\spemoenv\Scripts\bentoml.exe\__main__.py", line 4, in <module>
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\bentoml\cli\__init__.py", line 42, in <module>
    from bentoml.server.marshal_server import MarshalService, GunicornMarshalServer
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\bentoml\server\marshal_server.py", line 20, in <module>
    from gunicorn.app.base import Application
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "c:\sl_projects\speechemotionrecognition\spemoenv\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

(spemoenv) C:\SL_Projects\SpeechEmotionRecognition\SpeechEmoReco_HireAi>

The same error occurs for bentoml version 0.7.6/ 0.7.5/ 0.7.4

Is there any dependent package which needs to be version specific? 
[bentoml_cli_issue_packages.txt](https://github.com/bentoml/BentoML/files/4638014/bentoml_cli_issue_packages.txt)

**Environment:**
 - OS: Windows 10 Pro ver 1909 
 - Python 3.6.8. /BentoML Version 0.7.6 / 0.7.5 / 0.7.4

**Additional context**
The problem occurs with bentoml version 07.6 , 0.7.5 and 0.7.4

The list of the python packages installed in the python project environment is attached for reference. 

Thanks !
[bentoml_cli_issue_packages.txt](https://github.com/bentoml/BentoML/files/4638022/bentoml_cli_issue_packages.txt)

**Comment by parano** [comment]
@jesudasvf the fix has just been merged, it will be available in the coming releases soon.

If you have the same issue with using `bentoml get` command on windows platform to get the saved path, here's a temporary workaround for version 0.7.3-0.7.5: 

1) The file path is actually the returned value of BentoService#save and the path will also be printed to the stdout, when creating the BentoML saved bundle.  
2) The saved bundle files can be found under ~/bentoml/repository which is the default location

**Comment by jesudasvf** [comment]
The new release of the bentoml 0.7.7 contains the resolution to this issue. The bentoml cli commands work well on windows. 

(spemoenv) C:\SL_Projects\bentoml_keras_textclassifier\src>bentoml get KerasTextClassificationService
BENTO_SERVICE                                         AGE                     APIS                  ARTIFACTS
KerasTextClassificationService:20200528134039_19A4FF  2 hours and 43 minutes  predict<JsonHandler>  model<KerasModelArtifact>, word_index<PickleArtifact>
KerasTextClassificationService:20200528133101_9EAC78  2 hours and 52 minutes  predict<JsonHandler>  model<KerasModelArtifact>, word_index<PickleArtifact>

(spemoenv) C:\SL_Projects\bentoml_keras_textclassifier\src>bentoml get SpeechEmpClassificationService
BENTO_SERVICE    AGE    APIS    ARTIFACTS

(spemoenv) C:\SL_Projects\bentoml_keras_textclassifier\src>bentoml get SpeechEmoClassificationService
BENTO_SERVICE                                             AGE                     APIS                  ARTIFACTS
SpeechEmoClassificationService:1.4.20200528114740_628E70  4 hours and 37 minutes  predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200528114617_085CD8  4 hours and 38 minutes  predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200528104254_F946C0  5 hours and 37 minutes  predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200525201501_458BEB  2 days and 20 hours     predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200520190222_C124DE  1 week and 21 hours     predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200520185908_90DA1E  1 week and 21 hours     predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200520120635_354E8F  1 week and 1 day        predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200520115038_D770A2  1 week and 1 day        predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200520112932_BE93D9  1 week and 1 day        predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200519230110_46E79D  1 week and 1 day        predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200519225052_D07EAD  1 week and 1 day        predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200519223630_A5E4FF  1 week and 1 day        predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200518204038_1AEAEB  1 week and 2 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200518203932_7A3293  1 week and 2 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517223217_7FE7D6  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517223041_9DCBAF  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517222706_A98E6F  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517222515_B20E82  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221747_E16D49  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221648_78B654  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221620_03F2EC  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221533_8D705C  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221444_CEDD4D  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221412_949CF1  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221340_D372B1  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221309_F666EA  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221239_3AC055  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221211_40C8BA  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221140_0BC267  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517221057_70C7BE  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200517220953_D03183  1 week and 3 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200516224433_08D93B  1 week and 4 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200516203752_2223E2  1 week and 4 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200516125813_997B0B  1 week and 5 days       predict<JsonHandler>  model<KerasModelArtifact>
SpeechEmoClassificationService:1.4.20200516125522_132FCB  1 week and 5 days       predict<JsonHandler>  model<KerasModelArtifact>
