### ISSUE TITLE
[DOCS] how to configure BentoML (via config file, CLI arg and env var)

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#671]
**Is your feature request related to a problem? Please describe.**
Document how BentoML is configured and some of the most useful configurations.

All configs and their default values can be found in this file: https://github.com/bentoml/BentoML/blob/master/bentoml/configuration/default_bentoml.cfg

Configs have multiple sections, e.g. "core", "logging", "instrument", "yatai_service" etc. BentoML is using a [hierarchical configuration](https://github.com/bentoml/BentoML/blob/master/bentoml/configuration/configparser.py#L46) module built based on the [Python configparser module](https://docs.python.org/3.6/library/configparser.html).

Configs can be set in a few different ways.

1) change config for "this machine", this can be used for your development machine, and it will remember your settings on a local file, `~/bentoml/bentoml.cfg` by default. e.g.:
```bash
# for "core" section:
bentoml config set usage_tracking=false

# for "yatai_service" section:
bentoml config set yatai_service.url=127.0.0.1:50051
```

2. If you only need to set the config one time for a single python session, without persisting the config to local file, set the config via `bentoml.config` in python:
```python
import bentoml
bentoml.config().set('core', 'usage_tracking', 'False')
bentoml.config().set('yatai_service', 'url', '127.0.0.1:50051')
```

3. Or set it via environment variable if you are using BentoML cli commands or don't want to change the python code, e.g.:
```bash
 $ BENTOML__YATAI_SERVICE__URL=127.0.0.1:50051 python guides/quick-start/main.py

 $ BENTOML__YATAI_SERVICE__URL=127.0.0.1:50051 bentoml get IrisClassifier:latest
```

**Describe the solution you'd like**
Document the above in more details and add to `docs` page

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by pncnmnp** [comment]
@parano - I along with @kishore-ganesh  and https://github.com/CallmeMehdi are almost done with this. We can draft a PR in a day or two.

**Comment by parano** [comment]
Sounds good, thanks @pncnmnp @kishore-ganesh

**Comment by pncnmnp** [comment]
@parano 
In this issue, you have mentioned - 
> Document ..... some of the most useful configurations.

Can you specify the configurations you want us to cover from [`default_bentoml.cfg`](https://github.com/bentoml/BentoML/blob/master/bentoml/configuration/default_bentoml.cfg)?

**Comment by parano** [comment]
The new config system has changed what was originally proposed here in this issue, closing now.

Documentation for configuring BentoML: https://docs.bentoml.org/en/latest/guides/configuration.html

**Comment by skkadium** [comment]
Hello,

I have worked last on bentoml version 0.10.0 and all I had to do to directly save the BENTO to s3 is to simply run the command

`bentoml config set yatai_service.repository_base_url=s3://testingbentoml/`

and run the docker 
`docker run -d -p 3000:3000 -p 50051:50051 \
    bentoml/yatai-service`

now with the latest bentoml version, I'm unable to understand how to configure this (even with a config file), so that the bento_service.save directly pushes the tar file to configured s3 location.

Please through some light as I'm struck
