### ISSUE TITLE
[DOCS] How to create custom Input/Output Adapter class

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#674]
Add documentation that covers:

* How BentoML adapter API is designed
* How to customize BentoML built-in handlers by overriding certain methods + example code
* How to create and use a custom input adapter + example code

**Comment by parano** [comment]
This should take into consideration the on-going adapter refactoring
https://github.com/bentoml/BentoML/issues/1002

**Comment by jjmachan** [comment]
I'd like to take this up if no one is working on it.
