### ISSUE TITLE
Make the base Docker image configurable

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#682]
**Is your feature request related to a problem? Please describe.**
Because of our in-house security policy, only images that pass security checks can be deployed to our in-house cluster. To support this case, users should be able to change BentoML's base image (default is continuumio/miniconda3:4.8.2) to own base image using the apt-get package manager and Anaconda pre-installed.

**Describe the solution you'd like**
a new environment variable or BentoML configuration

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by parano** [comment]
Related issue: https://github.com/bentoml/BentoML/issues/532

**Comment by withsmilo** [comment]
@parano 
May I close this issue?
