### ISSUE TITLE
[Dev] fix Python linter errors

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#684]
The linter test can be started with the following command (also see [development.md](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)):
```bash
./dev/lint.sh
```

We've been ignoring the errors from this script for a while because it has not been added to Travis CI. This ticket is for fixing existing linter errors in the project codebase.

**Comment by kautukkundan** [comment]
I am working on this issue 

Is it suggested to add a disable warning flag to the errors or remove code pieces altogether? like removing unused variables and imports

**Comment by parano** [comment]
Awesome, thanks @kautukkundan 

If it's an easy fix in the code, we'd prefer to fix the code style to make the linter happy. If it is really hard to fix in the code, we suggest adding an inline comment to disable the linter rule for just that piece of code, here are some existing examples you can find in the project:  https://github.com/bentoml/BentoML/search?q=pylint%3A+disable%3D&unscoped_q=pylint%3A+disable%3D

It's also recommended to submit your changes in smaller PRs. You can for instance have one PR with all fixes in the `/bentoml` directory, one with changes `/test` and another for `e2e_tests`.

Let me know if you have other questions, feel free to ping me in the slack channel @parano

**Comment by parano** [comment]
Sorry closed this by accident, reopening since @kautukkundan is still working on it

**Comment by kautukkundan** [comment]
hey @parano all the linting errors are now fixed for the current state of the code. I am sorry I forgot to mention. I feel it's okay to close this issue for now. 

```
Running flake8 on bentoml module..
Running flake8 on test module..
Running pylint on bentoml module..

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Running pylint on test module..

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Done
```

only https://github.com/bentoml/BentoML/pull/710#discussion_r429571583 this needs review

**Comment by parano** [comment]
@kautukkundan got it, I thought there will be more in 'test' but looks like it's all done! Thanks again for the contribution! Let me know if you are interested in helping with other things, I'd be happy to help provide any guidance or help if needed. 

Closing this ticket now! 🎉

**Comment by kautukkundan** [comment]
Yes definitely interested in contributing more! :D
