### ISSUE TITLE
Support specifying arbitrary local files to bundle with

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#685]
BentoML supports searching local Python file modules automatically when saving a BentoML saved bundle, and adding saved model files via the Artifact API. This makes it very convenient to bundle python code and saved model for inferencing.

In some cases, however, the user may want to include additional files(json/yaml files, or python code files) with the saved bundle and access them when starting the API server.

## Extra Python code dependencies

The first scenario is, in some edge cases, when there are local python dependencies that can't be inferred by BentoML automatically. For example, the user has a `preprocessing` function, defined in `my_lib.py` file, and the BentoService class definition file imports this module:

```python
from my_lib import preprocessing
from bentoml import env, artifacts, api, BentoService
from bentoml.handlers import DataframeHandler
from bentoml.artifact import SklearnModelArtifact

@env(auto_pip_dependencies=True)
@artifacts([SklearnModelArtifact('model')])
class IrisClassifier(BentoService):

    @api(DataframeHandler)
    def predict(self, df):
        df = preprocessing(df)
        return self.artifacts.model.predict(df)
```

The function is used in the service definition, thus it will be required on serving time and must be included when saving a BentoML bundle.  BentoML does this by default, [this function](https://github.com/bentoml/BentoML/blob/v0.7.6/bentoml/bundler/py_module_utils.py#L70) does the module searching, and it is invoked [here when saving BentoML bundle](https://github.com/bentoml/BentoML/blob/v0.7.6/bentoml/bundler/bundler.py#L114).

There are some unit tests covering this behavior, via this example project that uses local python dependencies:
https://github.com/bentoml/BentoML/tree/v0.7.6/tests/bento_service_examples/local_dependencies

There are a few edge cases where this implementation can not work: 
* [zipimport module](https://docs.python.org/3.6/library/zipimport.html) is not yet supported
* Python modules that are c/c++ bindings are not yet supported
* User's own PyPI package installed that can not be found in the public PyPI.org - although the user can specify it via `@env(pip_dependencies=[...])`

We would like to add an API for the user to specify the python module dependency files manually and control this process and workaround the scenarios listed above:

```python
from bentoml import env, artifacts, api, BentoService
from bentoml.handlers import DataframeHandler
from bentoml.artifact import SklearnModelArtifact

import abc
import foo
import my_lib.bar

@env(
   auto_pip_dependencies=True,
   additional_files=["abc.py", "./my_lib/**/*.py", "./my_other_lib/foo.py"]
   local_dependency_imports=["my_other_lib"] 
)
@artifacts([SklearnModelArtifact('model')])
class IrisClassifier(BentoService):

    @api(DataframeHandler)
    def predict(self, df):
        return self.artifacts.model.predict(df)
```

* `additional_files` - List of files to include in the BentoML saved bundle. (must be relative path? similar to [Bazel python library rule](https://docs.bazel.build/versions/master/be/python.html#py_binary.srcs)?)
* `local_dependency_imports` -  Optional, List of import directories to be added to the PYTHONPATH.

## Extra data and config files (JSON, Yaml, CSV)

We found the existing approach to include TEXT file with the Artifact API to be very cumbersome - it does not allow bundling multiple files easily, and limited how the file was read and processed.

```python
from bentoml import env, artifacts, api, BentoService
from bentoml.handlers import DataframeHandler
from bentoml.artifact import SklearnModelArtifact

@env(
   auto_pip_dependencies=True,
   additional_files=["./my_data_files/a.json", "./foo/*.yaml"]
   local_dependency_imports=["my_other_lib"] 
)
@artifacts([SklearnModelArtifact('model')])
class IrisClassifier(BentoService):

    @property
    def data_a(self):
       if not self._provider:
          self._data_a = read_json_file(os.path.join(self.saved_bundle_path, "my_data_files"," a.json"))
       return self._data_a

    @api(DataframeHandler)
    def predict(self, df):
        result = self.data_a[df['name']]
        return self.artifacts.model.predict(result)
```

**Comment by withsmilo** [comment]
@parano 
Could BentoML support a relative import beyond top-level if I add these codes to the top of codes?
```python
import sys
sys.path.append("..") # Adds higher directory to python modules path.
```

**Comment by parano** [comment]
@withsmilo yes it does support that!

Here is the test case that covers this behavior:
https://github.com/bentoml/BentoML/blob/v0.7.6/tests/bento_service_examples/bento_service_with_modified_sys_path.py

**Comment by withsmilo** [comment]
Really great! Thanks!

**Comment by danield137** [comment]
Any updates on this? or is it still up for grabs?

**Comment by parano** [comment]
@danield137 this issue still requires additional design, would you be interested to discuss over a call? Feel free to ping me in slack

**Comment by jsemric** [comment]
@danield137 are you planning to work on this?

I've already created a [PR](https://github.com/bentoml/BentoML/pull/1261) for handling zip imports. If you wish to take this issue, I can keep only the part of the PR which auto-infers the zipimports as the second part (specifying the zipimport files in `env` decorator) would be covered by  `additional_files` and `local_dependency_imports` parameters.

**Comment by parano** [comment]
another potential use case is for users to include a default kubernetes deployment YAML file to be included in the bundle, see discussions here in #bentoml-users https://bentoml.slack.com/archives/CKRANBHPH/p1606748614122000

**Comment by MasterScrat** [comment]
Is there any alternative way to bundle json/yaml files for now?

I need load a large number of pre-computed values to perform inference with my PyTorch model. I guess I could save them in a `nn.Module` but that feels a bit too hacky 😅

**Comment by parano** [comment]
@MasterScrat  for now, you can use either a PickleArtifact, JSONArtifact, or TextFileArtifact https://docs.bentoml.org/en/latest/api/artifacts.html

**Comment by hzlmn** [comment]
Hi, is there any progress on it? It would be nice to have such feature. 
Also, for now is there any proper ways how i can include additional files and folder with my service bundle. For example we need folder with credentials file used to query external service inside API function. Thanks!

**Comment by parano** [comment]
Hey @hzlmn  - we have a design doc out for this and it will come out in the 0.14 release(0.13 will be out later this week). Although for credential files, we'd recommend mounting those files when deploying or use environment variables instead.

**Comment by parano** [comment]
This is now supported in BentoML 1.0, where user can specify arbitrary files to be included in the Bento, via a `bentofile.yaml` file. Here's an example build file:

```yaml
service: "iris_classifier:svc"
description: "file: ./readme.md"
labels:
  foo: bar
  team: abc
include:
- "*.py"
- "*.json"
exclude: 
- "*.pyc"
```

See 1.0 documentation to learn more: https://docs.bentoml.org/en/latest/

**Comment by hzlmn** [comment]
Thanks for your work. It is really valuable feature!
