### ISSUE TITLE
[DOCS] Guide on using custom docker base image

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#693]
* How to set the docker base image
   * Per BentoService setting via the `@env` parameter
   * Change the system-wide default docker base image used via bentoml config file or environment variable

* How to create a docker base image for use with bentoml, and what are the requirements
   * `conda` is required, what others?

Edit:
* The custom Docker base image should use the apt-get package manager, e.g. ubuntu. (suggested by @withsmilo)

**Comment by withsmilo** [comment]
need to add : The custom Docker base image should use the `apt-get` package manager, e.g. ubuntu.

**Comment by mattiantonini** [comment]
hi!
It would be nice if it is possible to use also other images, e.g., alpine. Alpine-based images are usually much lighter than ubuntu-based images. However, apt is not available in alpine.

**Comment by parano** [comment]
@mattiantonini we implemented a Debian-slim based docker image(very light just like alpine but a lot easier to work with) and it is now available in 0.8.1
