### ISSUE TITLE
Add a command to containerize the model API server

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#696]
**Is your feature request related to a problem? Please describe.**
BentoML supports various serving clusters now e.g. K8s, KNative, Kubeflow and KFServing. However we should execute some Docker commands to containerize our model API server. ([Docs](https://docs.bentoml.org/en/latest/deployment/kubernetes.html#deploy-bentoservice-to-kubernetes)) How about adding a command to containerize our model API server to the BentoML instead of it?

**Describe the solution you'd like**
```bash
$ bentoml containerize [--docker-username ID] [--push] IrisClassifier:latest
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by parano** [comment]
That's a great idea @withsmilo! Really love it!

I guess you are also suggesting using the BentoService tag (e.g. `IrisClassifier:20200518151822_B40DEC`)  as the docker image tag by default? That's really nice, I'm not sure if this "name:version" string is always a valid docker image tag. But I think we can always add a parameter for user to set a docker image tag manually. This really helps users to keep the docker image tags (and especially the version) the same as the BentoService saved bundle's version.

**Comment by withsmilo** [comment]
@parano 
It's really nice idea, too!

**Comment by jackyzha0** [comment]
@parano would love to take this on too 👀
