### ISSUE TITLE
[TEST] Move yatai_service end-to-end test to run on Github actions

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#702]
The tests under `e2e_tests` directory are not automated in CI right now. This ticket is for supporting the `e2e_tests/yatai_service` tests on Github Action.

* Some tests in `e2e_tests/yatai_service` requires AWS S3. We should modify our tests to use a MinIO docker container instead.

Here is an example of yatai_service deployment with MinIO's sample deployment:
```
AWS_ACCESS_KEY_ID=Q3AM3UQ867SPQQA43P2F AWS_SECRET_ACCESS_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG AWS_REGION=us-east-1 bentoml yatai-service-start --s3-endpoint-url=https://play.min.io:9000 --repo-base-url=s3://chaoyu-bentoml
```
```
export BENTOML__YATAI_SERVICE__URL=127.0.0.1:50051
```

* The `e2e_tests/yatai_service` tests should be skipped when running in the Window platform

**Comment by jackyzha0** [comment]
Should this be moved to Github Actions instead?

**Comment by yubozhao** [comment]
@jackyzha0 Yes. This issue should be updated.

**Comment by parano** [comment]
@yubozhao do you want to revisit this issue?

**Comment by parano** [comment]
Will revisit e2e tests structures as part of the deployment revamp https://github.com/bentoml/BentoML/issues/1677
