### ISSUE TITLE
[DOCS] how to build API client library with swagger(openapi)

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#704]
Add a document showcasing how a user can utilize BentoML API model server's Swagger definition endpoint "/docs.json", to build API client for any programming language.

This can be a guide under `advanced guides` section.

BentoML already provides swagger definitions for user to build API clients. User can find the API spec from the "/docs.json" endpoint of BentoML API server, or the `bentoml open-api-spec IrisClassifier:latest` cli command.

The guide should also demonstrate how to use the API spec to build a simple API client as an example. More about it here: https://swagger.io/tools/swagger-codegen/

**Comment by rscnt** [comment]
is someone already working on this? if not I can start working on this

**Comment by parano** [comment]
@rscnt I don't think anyone is working on it, feel free to take it!
