### ISSUE TITLE
Add a GUI for running inferencing job

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#715]
**Is your feature request related to a problem? Please describe.**

A tool to turn a BentoML saved bundle to a standalone "app" with GUI, that ml scientists can send to other non-technical users to run prediction job on their on computer.

Currently, BentoML provides CLI command to run a bundled model, take the quickstart guide for example(https://docs.bentoml.org/en/latest/quickstart.html), the user can load and run the saved BentoService from CLI directly with the saved bundle files:

```bash
bentoml run IrisClassifier:latest predict --input='[[5.1, 3.5, 1.4, 0.2]]'

bentoml run IrisClassifier:latest predict --input='./iris_test_data.csv'
```

Or the equivalent after `pip install` the saved bundle:
```
IrisClassifier run predict --input='./iris_test_data.csv'
```

Considered using https://github.com/chriskiehl/Gooey - BentoML handler's CLI handling code is written with the default python ArgParser and Gooey has great support for that

**Describe alternatives you've considered**

**Additional context**
n/a

**Comment by kautukkundan** [comment]
Hey @parano  
I wish to look after this feature

**Comment by parano** [comment]
@kautukkundan sure thing! this feature is super open-ended tho, would be great if you can post your plans/design here for feedback before committing to implementing it. Happy to discuss more if you have any questions

**Comment by kautukkundan** [comment]
@parano actually I got engaged with some other work. I'm sorry I should've informed earlier 😅 I'll be able to start contributing to this project again only after some time.

**Comment by parano** [comment]
Closing this for now since we've recently added custom Web UI that's probably gonna be a better solution than this proposal in most use cases https://github.com/bentoml/BentoML/pull/839
