### ISSUE TITLE
Improve `import bentoml` load time

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#720]
Running `import bentoml` has become very slow compared to a few releases before.  This is most likely coming from importing large dependencies while loading bentoml module.

We should be able to improve this by lazily loading the large dependencies.

**Comment by highvight** [comment]
Import times of individual modules (on my machine) with [tuna](https://github.com/nschloe/tuna). The big ones:

1. numpy (22.8%)
2. google.protobuf (12.9%)
3. aiohttp (11.1%)
4. flask (10.8%)
5. requests (8.1%)
6. py_zipkin (6.7%)
7. boto3 (6.4%)

![import_times](https://user-images.githubusercontent.com/25797927/86983224-9f924680-c18b-11ea-905a-5257fb477abd.png)
