### ISSUE TITLE
[TEST/CI] Add tests covering TensorflowSavedModelArtifact

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#721]
Currently, there isn't any integration test covering the `TensorflowSavedModelArtifact`:

* Similar to PR #726, add a unit test assuming tensorflow pypi package installed, and create a BentoService with TensorflowSavedModelArtifact, test the major functionalities including save, load, run inference
* Build a docker container with the saved bundle and test the API server endpoint, see related PR #855 and #871 which have some utility function code that can be re-used for this
* Add a script `./travis/run-tensorflow-v2.2-tests.sh` that runs `pip install tensorflow==2.2` and `pytest tests/test_tensorflow_v2.2_model_artifact.py ...`
* Add another script `./travis/run-tensorflow-v1.14-tests.sh` that runs `pip install tensorflow==1.14` and `pytest tests/test_tensorflow_v1.14_model_artifact.py ...`

* Add two separate task in travis.yml that launches the two test scripts above https://github.com/bentoml/BentoML/blob/master/.travis.yml

**Comment by joshuacwnewton** [comment]
Hi @parano. I'm a student in the MLH Fellowship program. I'd like to begin working on this issue. Thanks! :)

**Comment by joshuacwnewton** [comment]
It looks like the requirements have updated, and #876 no longer fixes this. I will make the new changes to address the updated issue. :)

**Comment by joshuacwnewton** [comment]
> Add another script ./travis/run-tensorflow-v1.14-tests.sh that runs pip install tensorflow==1.14 and pytest tests/test_tensorflow_v1.14_model_artifact.py ...

Two small notes:
* 1.15 is the last TF1 revision, I think
* Python 3.8 breaks tests using `pip install tensorflow==1.15`, see: https://github.com/tensorflow/tensorflow/issues/39768#issuecomment-632799481. I can stick to developing with 3.7 for now, but it might be worth keeping in mind for the future.

**Comment by joshuacwnewton** [comment]
I am having some difficulty developing a simple TF 1.14 example. I have only used TF2, so it is a bit challenging to search through old TF1 documentation! :stuck_out_tongue: 

Because the test I am writing involves saving and loading a TF1 model artifact, I have run into this warning from Bento:

```bash
                WARNING - Importing SavedModels from TensorFlow 1.x.
                `outputs = imported(inputs)` is not supported in bento service due to
                tensorflow API.

                Recommended usage:

                ```python
                from tensorflow.python.saved_model import signature_constants

                imported = tf.saved_model.load(path_to_v1_saved_model)
                wrapped_function = imported.signatures[
                    signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
                wrapped_function(tf.ones([]))
                ```

                See https://www.tensorflow.org/api_docs/python/tf/saved_model/load for
                details.
```

But I am having trouble figuring out how to give a test model the `.signatures` attribute for the above fix.

@bojiang: I think you wrote the warning in #421. Do you think this will cause some problems writing a TF1 test? Or, do you know of a good workaround? Thanks much! :)

**Comment by joshuacwnewton** [comment]
I am a bit curious about the motivation behind supporting TF1 in BentoML, considering the strong push away from TF1 from Google. For clarity, what were your thoughts when the `tf==1.14` test was initially proposed? :)

Part of me is wondering if it is more trouble that it's worth to have to take on the maintenance costs of accommodating for legacy TF1 API features _(e.g. models which use `tf.Session`, input placeholders, `feed_dict`, etc.)_. It is a bit challenging to write/debug TF1 code given how scattered TF1 documentation can be these days -- some materials are outdated and some are not. But, there could be benefits that I'm not aware of, so I'm happy to hear other opinions.

**Comment by bojiang** [comment]
@joshuacwnewton 

It took me a while to retrieve an example of using non-keras TensorFlow v1 API:
https://github.com/bentoml/gallery/blob/3ce0644d04ccce7b262947b85d3b3bcd1bc57dd8/tensorflow/fashion-mnist/tensorflow_1_fashion_mnist.ipynb

In fact, we did not do extra work to make bentoml support tensorflow v1. `tensorflow.saved_model` did most of the dirty work. And I think there are still a certain number of projects using this API. There is insufficient reason for dropping it.

**Comment by joshuacwnewton** [comment]
Great work finding this example @bojiang! It looks like it has all the necessary steps, so thank you. I will see what I can do to adapt the steps to a simpler model for testing purposes. :smile: 

Interestingly, I notice that the example you linked uses [`tf.saved_model.simple_save`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/simple_save), while I was trying to use the `save` method used by BentoML, see below.

https://github.com/bentoml/BentoML/blob/2b6d6778bdc8fd9195d4f76475e8bc7264487105/bentoml/artifact/tf_savedmodel_artifact.py#L294-L298

I think this might be a key difference, as `tf.saved_model.save` requires signatures to be indicated explicitly, while `tf.saved_model.simple_save` handles that automatically for you (using [`tf.saved_model.signature_def_utils`](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/saved_model/simple_save.py#L79-L82).)

**Comment by parano** [comment]
@bojiang has already implemented tests for V2, and planning to add TF V1 tests
