### ISSUE TITLE
[TEST/CI] Add tests covering PyTorchModelArtifact

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#723]
Currently, there isn't any integration test covering the `PyTorchModelArtifact` with the Tensorflow library. One reason for that is we did not want to include all ML framework libraries in our CI tests.

* Use this PR as a reference:  https://github.com/bentoml/BentoML/pull/726
* Add a unit test assuming `torch` pypi package installed, and create a BentoService with PyTorchModelArtifact, test the major functionalities including save, load, run inference, and API server
* Add a script `./travis/run-keras-tests.sh` that runs `pip install tensorflow==...` and `pytest tests/test_pytorch_model_artifact.py`
* Add a separate task in `travis.yml` that launches the test script https://github.com/bentoml/BentoML/blob/master/.travis.yml
* Make sure this `tests/test_pytorch_model_artifact.py` is ignored in regular CI build

**Comment by jjmachan** [comment]
can I work on this?

**Comment by parano** [comment]
@jjmachan sure thing!

**Comment by parano** [comment]
@jjmachan make sure to rebase after https://github.com/bentoml/BentoML/pull/757 was merged tho

**Comment by jjmachan** [comment]
got it!

**Comment by jjmachan** [comment]
The unit test for PytorchArtifact should also be in /tests/integration_tests/ rt?

**Comment by parano** [comment]
@jjmachan yes exactly! 

Since it's actually importing PyTorch module, testing the interaction with PyTorch instead of using a mock, we categorize it as an integration test here. You may use the definition in this post as a reference for the terminology https://www.browserstack.com/guide/testing-pyramid-for-test-automation

**Comment by jjmachan** [comment]
Also when we are creating the Pytorch model should we train it ? Right now what I'm planning to do is simply  do a forward propagation and check the result. That way the results are deterministic. 

If we want to train the model also it might take more time.

**Comment by parano** [comment]
@jjmachan I think there's no need to train the model unless it's on a small toy dataset designed for this kind of testing. Your approach sounds great!
