### ISSUE TITLE
[TEST/CI] Add tests covering XgboostModelArtifact

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#724]
Currently, there isn't any integration test covering the `XgboostModelArtifact`:

* Similar to PR #726, add a unit test assuming xgboost pypi package installed, and create a BentoService with XgboostModelArtifact, test the major functionalities including save, load, run inference
* Build a docker container with the saved bundle and test the API server endpoint, see related PR #855 and #871 which have some utility function code that can be re-used for this
* Add a script `./travis/run-xgboost-tests.sh` that runs `pip install xgboost==...` and `pytest tests/test_xgboost_model_artifact.py ...`
* Add a separate task in travis.yml that launches the test script https://github.com/bentoml/BentoML/blob/master/.travis.yml

**Comment by xiwang129** [comment]
Hi @parano, I would like to work on this one. Thanks!

**Comment by yubozhao** [comment]
Complete with https://github.com/bentoml/BentoML/pull/1079
