### ISSUE TITLE
Support passing a conda environment.yml file to `@env`

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#725]
Currently, the user will need to pass in conda environment parameters individually, e.g.:

```python
@bentoml.artifacts([H2oModelArtifact('model')])
@bentoml.env(
  pip_dependencies=['pandas', 'h2o==3.24.0.2'],
  conda_channels=['h2oai'],
  conda_dependencies=['h2o==3.24.0.2']
)
class ExamplePredictionService(bentoml.BentoService):

   ...
```

This can be tedious If the user already has a conda enviornment.yml file as the source of truth. BentoML should support taking a conda environment.yaml file directly, e.g.:
```python
@env(conda_env_yaml="./environment.yml")
```

Feature suggested by Cameron T in the community slack channel.

**Comment by yashika51** [comment]
Hi @parano, are we looking to make changes in [this class](https://github.com/bentoml/BentoML/blob/7af5a8f4ebe4e053bb65638ad8b9ab59555a411b/bentoml/service_env.py#L54-L83)?

**Comment by parano** [comment]
@yashika51 yes that's correct, you can add a class method for initializing a CondaEnv with a yaml file, and you will also need to modify the `env` decorator implementation

**Comment by yashika51** [comment]
Okay, I have made a draft PR just to show you the method before moving forward. I've only added the method for your approval first.

**Comment by parano** [comment]
This is now closed in https://github.com/bentoml/BentoML/pull/1084
