### ISSUE TITLE
API Handler(Input Adapter) for Numpy array

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#737]
Similar to the DataframeHandler for handling input data in pandas.Dataframe format, add support for using NumPy array as API input.

User should also be able to provide type information about the NumPy array. And ideally user can provide a sample input data for BentoML to infer the input type, similar to https://github.com/microsoft/MLOps/blob/master/model-deployment/score.py#L20 (related implementation: https://github.com/Azure/InferenceSchema/blob/master/inference_schema/parameter_types/numpy_parameter_type.py#L10)

This should be using the newly proposed InputAdapter API https://github.com/bentoml/BentoML/issues/736

**Comment by mkosecki** [comment]
Hey @parano, I'm interested in this task,  i'll be much more helpful here.

**Comment by parano** [comment]
This is now supported in BentoML version 1.0: https://docs.bentoml.org/en/latest/api/api_io_descriptors.html#bentoml-io-numpyndarray
