### ISSUE TITLE
Custom service web UI to replace default swagger UI

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#739]
* Currently when starting a BentoML API model server, it starts a simple web UI in addition to the API endpoints. This Web UI is generated with swagger API schema, it can be used for data scientists to test the API endpoint from a browser. But not ideal for a non-technical user to use.

* This proposal is to allow BentoML user to provide a tarfile when building a BentoService saved bundle, which contains static content being hosted web page code, including a `index.html` and optionally other JS code.

* User javascript code should be able to send prediction request to the API model server for prediction

* This makes it possible for users to customize the web UI of their ML application for end-user to consume directly. It can be very powerful for building internal tools.

API design draft:
```python
@env(..)
@artifacts([...])
@web_static_files("./web_ui/*")
class MyPredictionService(BentoService)
     
         @api(...)
         def predict(...)
              pass
```

BentoML should provide a few template frontend projects for a user to get started with building a web UI easily. e.g. a basic HTML form submitting input data, a file upload window that can be used to drag-n-drop a image or audio file, a d3 visualization that visualized the prediction result, etc

An advanced version of this should allow user to declared UI elements right from their Python code. similar to how R Shinny works.

**Comment by Korusuke** [comment]
Hey @parano, I would like to work on this if no one else is already working on it

**Comment by parano** [comment]
Thanks, @Korusuke, let me know if you have any questions about it
