### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [bentoml/BentoML#750]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by mkosecki** [comment]
@parano  Can I take this one for start?

**Comment by parano** [comment]
@mkosecki sure thing!

**Comment by mkosecki** [comment]
@parano , I did small research and has not enough access to codecov account and repo to install app. So here are the things to make it work:
1. https://github.com/apps/codecov install app in bentoml repos (by somebody who has right access)
2. To prevent double messaging from codecov reset the team bot to null as it is mentioned [here](https://docs.codecov.io/docs/team-bot#github-users-why-am-i-getting-two-codecov-comments-on-my-prs)
