### ISSUE TITLE
Automatic Update of BentoML Server Endpoint with new Model

### ISSUE THREAD

**Issue by ssakhavi** [bentoml/BentoML#754]
**Is your feature request related to a problem? Please describe.**
I have a model that has been deployed via docker. I have a new model and would like to add a new endpoint with a new version number to access the new endpoint. I don't want to rebuild the docker image and I want it to be done automatically.

**Describe the solution you'd like**
Assuming that we've deployed the model using a container and the repository is mounted on storage (e.g. S3), is it possible to update the server without the need to do it manually? Something similar to what TensorFlow serving is doing. 

**Describe alternatives you've considered**
Tensorflow serving can automatically detect the presence of a new SavedModel as long it's in the watched folder. 

**Additional context**

**Comment by parano** [comment]
Thanks for the suggestion @ssakhavi  we are looking to support this as part of https://github.com/bentoml/BentoML/issues/754

Note that there are in fact lots of drawbacks to the Tensorflow-serving workflow. It almost works exactly like the old days where web developers will upload their PHP files directly to a server over FTP and expect Apache to load those scripts and website got updated. It is extremely error-prone especially for something like BentoML where dependencies and service logic can also get updated.  It is very convenient for testing out a model in the development phase and that's the reason we plan to support it, we'd never suggest users use that for serious production workloads. Building a comprehensive CI/CD pipeline that rebuilds the docker image, tests the new image, and then uses something like canary deployment to update the production deployment is probably the right way to go.
