### ISSUE TITLE
[Deployment]Azure function deployment operator

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#755]
**Is your feature request related to a problem? Please describe.**

Add Azure function support for the automated deployment management system.

Similar to AWS Sagemaker and AWS Lambda, users are able to deploy and manage BentoService to Azure function service with CLI tools, view deployment with YataiService UI.

Update documentation with Azure function deployment guide and example notebooks.

**Describe the solution you'd like**

* Azure function deployment CLI support: `deploy`, `update`, `delete`, `get`, `list`
    * Add and include sub command in `bentoml/cli`
        ```
        # Specific options for Azure function:  --premium-plan-sku, --min-instance, --max-burst --function-auth-level
        $bentoml azure-function deploy -b ...
        $bentoml azure-function update ...
        $bentoml azure-function delete ...
        ...
        ```

* Add `AzureFunctionDeploymentOperator`
    * method: `add`, `update`, `describe` and `delete`
    * Deployment steps for Azure function:
         1. initialize Azure project
              * Generate Azure files `host.json` and `local.settings.json` 
              * Generate Dockerfile for Azure function
              * Copy BentoService
              * Generate functions
                   1. create sub directory with api name as the directory name
                   2. generate `__init__.py` with the BentoService API
                   3. generate `function.json` for Azure                    
         1. Create Azure resource group
         2. Create Azure storage account
         3. Create Azure container registry
         4. Create premium plan (it is required for docker container deployment)
         5. Build and push docker image to the Azure container registry created previously
         6. Create Azure function app
         7. Update Storage connection string to the function app
         8. Enable CICD for the app, and update the webhook URL to the container registry.  (**This is required**, for updating the function with new docker image in the future)
         * make sure set correct CORS
    * Update steps for Azure function:
        1. Initialize Azure project (similar to deploy)
        2. build and push the docker image to the Azure container registry
    * Make sure delete the resource group 
   

* Update/generate `deployment.proto` definition with new `AzureFunctionOperatorConfig`

* Add `create_azure_function_deployment`, `update_azure_function_deployment`, `list_azure_function_deployment` to `DeploymentAPIClient` in `bentoml/yatai/client/deployment_api.py`

~~* Create API input and output adapter base on the API handler refactor #736 for BentoML 0.8.0 or later.
      * Create ApiInputAdapter `from_azure_function(request: azure.functions.HttpRequest)`
      * Create APiOutputAdapter `to_azure_function(response: azure.functions.HttpResponse)`~~

* Add e2e deployment tests for Azure function, similar to AWS Lambda and AWS Sagemaker
   * deploy/update/invoke endpoint/delete

* Add Azure deployment guide in the documentation

* Use Azure function deployment with example notebooks in the `bentoml/gallery`

**Additional context**

- Choose custom docker container for Azure function, instead of using `remote build` provide by Azure, because: it enables build dependencies with conda and the ability to run user-defined `setup.py`

- Make sure to follow Azure function python import behavio when generating `__init__.py`: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#import-behavior

**Comment by parano** [comment]
Implemented in #801, will be available in beta state in release 0.8.2
