### ISSUE TITLE
BentoML Artifacts Refactor: Support unload/load/pack dynamically

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#758]
**Is your feature request related to a problem? Please describe.**

There have been a number of user requests related to loading and unloading models artifacts dynamically lately and this is to add this support.

Use cases:
* Speed up BentoService development workflow - currently user always needs to figure out how to save the model and load it back, then test it with the BentoService class. Ideally, the user should be able to do that with BentoML's model artifact class and build their BentoService class iteratively.
* Online learning - a new model is being training on the fly
* Composing model pipeline dynamically and loading models lazily 
* Automatically load new versions of artifact trained from a local directory, similar to the TensorFlow serving design https://github.com/bentoml/BentoML/issues/754 

**Describe the solution you'd like**

WIP

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by parano** [comment]
This is available now in the latest release(0.8.4 and above)

**Comment by LeoVS09** [comment]
@parano 
Very good to see this feature, but can you add a link for an explanation in the documentation of how to use it? Or at least some example? Better to see how it looks with KFServing :) 
I cannot find any mention in docs :(

**Comment by LeoVS09** [comment]
Ah, I found it in docs, sorry, it relates to multiple parts, was need to read it carefully. But I still cannot find an example of usage KFServing and Yatai Service for dynamic model loading. It can be too complex for simple examples, but I guess probably more Kubeflow way of serving model. 
If you accept such a way of usage, I can try to make PR into https://github.com/bentoml/gallery.
