### ISSUE TITLE
[TEST/CI] Add integration test on generated API server docker image

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#759]
**Is your feature request related to a problem? Please describe.**

* Currently we don't have tests covering the behavior of generated Dockerfile and the docker image built from it (as described here https://docs.bentoml.org/en/latest/concepts.html#api-server-dockerization)

* Travis CI support docker and we can create an integration test that produces a BentoML saved bundle, build the docker API server image, and launch a docker container with the image to verify the API model server is running properly

* Related features we should cover in this test:
  - [x] conda dependencies are properly installed
  - [x] pip dependencies are properly installed
  - [ ] setup_sh shell script provided by the user was executed properly (https://docs.bentoml.org/en/latest/api/bentoml.html#env)

**Describe the solution you'd like**
Add a new Travis CI task that launches this integration test

**Describe alternatives you've considered**
Add it to end-to-end tests and only run manually before each release

**Additional context**
n/a

**Comment by jjmachan** [comment]
is anyone working on this?
else I'll like to work on this

**Comment by parano** [comment]
@jjmachan  I don't think anyone is working on it, feel free to take it

**Comment by jjmachan** [comment]
great!

**Comment by jjmachan** [comment]
Will be work on this this week

**Comment by bojiang** [comment]
@parano @jjmachan I believe this issue should have been solved by https://github.com/bentoml/BentoML/tree/master/tests/integration/api_server

**Comment by parano** [comment]
This is mostly implemented, besides testing the `setup_sh` feature:

> setup_sh shell script provided by the user was executed properly (https://docs.bentoml.org/en/latest/api/bentoml.html#env)
