### ISSUE TITLE
Error when creating custom handler class

### ISSUE THREAD

**Issue by palver7** [bentoml/BentoML#763]
I created a custom tensorflow_tensor_handler class in order to help with debugging issue #742. 
I put this class inside tensorflow_fashion_mnist.py and attempt to build the bentoservice bundle according to https://github.com/bentoml/gallery/blob/master/tensorflow/fashion-mnist/tensorflow_2_fashion_mnist.ipynb
Here are the content of tensorflow_fashion_mnist.py and the relevant code to create the bento service bundle :

[bentoserviceandbuildcommand.txt](https://github.com/bentoml/BentoML/files/4739426/bentoserviceandbuildcommand.txt)

However when I run the code to create the service bundle I got these error messages: 

[bentomlservicebuilderror.txt](https://github.com/bentoml/BentoML/files/4739430/bentomlservicebuilderror.txt)

I have tried to find solutions based on the error message but I did not succceed. Any help is much appreciated.

**Comment by parano** [comment]
cc @bojiang could you help take a look when you have a chance?

**Comment by parano** [comment]
hi @palver7  looks like #767 has the fix you need. I think you can also override the `config` method in your inherited method as the following as a temporally workaround:
```
from bentoml.handlers import BentoHandler, TensorflowTensorHandler

def MyTensorHandler(TensorflowTensorHandler):
    @property
    def config(self):
        base_config = super(BentoHandler, self).config
        base_config = super(TensorflowTensorHandler, self).config
        return dict(base_config, method=self.method,)

    def handle_request(...):
       ...
```
