### ISSUE TITLE
Add --print-location option to `bentoml get`  command

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#819]
**Is your feature request related to a problem? Please describe.**
See related discussions here: https://github.com/bentoml/BentoML/pull/810#pullrequestreview-432731488

Currently, we've been using `jq` to do this in our documentation:
```bash
$ bentoml get IrisClassifier:latest -q | jq -r ".uri.uri"

/Users/chaoyu/bentoml/repository/IrisClassifier/20200616144911_7CE204
```
But this approach requires installing `jq`

**Describe the solution you'd like**

Would be great to allow the user to get just the saved location, without jq installed, from the CLI:
```bash
$ bentoml get IrisClassifier:latest --print-location

/Users/chaoyu/bentoml/repository/IrisClassifier/20200616144911_7CE204
```

**Describe alternatives you've considered**

A general json selector syntax that works for all JSON CLI output and allow the user to select other fields in the JSON output?

e.g.
```
$ bentoml get IrisClassifier:latest --json-output ".uri.uri"

/Users/chaoyu/bentoml/repository/IrisClassifier/20200616144911_7CE204
```

It can use the same jq syntax, with something like https://github.com/doloopwhile/pyjq

**Additional context**

**Comment by jackyzha0** [comment]
@parano would love to take this on!
