### ISSUE TITLE
Type checking & PEP 563

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#827]
We may introduce type checking to BentoML in the future. But when trying to add more type annotations, I met many problems about lazy import and optional dependencies.

PEP 563 will solve this by making all type hints be strings and skip evaluating them if typing.TYPE_CHECKING is False(When checking type with mypy it would be True).

PEP563 requires Python 3.7+

**Comment by akainth015** [comment]
I will start taking this on, and I've had a look through PEP 563](https://www.python.org/dev/peps/pep-0563/).

**Comment by bojiang** [comment]
The problem is, shall we discard the Python 3.6 support?

**Comment by akainth015** [comment]
I think we will have to do so, but I don't think it would be a big issue since 3.6 > 3.7 should not require any code changes.

If only there were `.d.ts` files for Python :disappointed:

**Comment by parano** [comment]
Does adding the type annotations will break BentoML's py3.6 support? or it just means type annotations will be ignored in py36?

**Comment by akainth015** [comment]
It breaks it because running `from __future__ import annotations` causes a syntax error. You can see this in [this build](https://travis-ci.org/github/bentoml/BentoML/jobs/704397142)

**Comment by parano** [comment]
@akainth015  I see.  I think currently we can not drop Python 3.6 support yet, a lot of users are still on Python 3.6 at the moment.  We should probably get started with adding type annotations without PEP563, and we can migrate to PEP563 later when we were ready to drop 3.6 support(probably in 2021 when the official Python 3.6 support is ended)

**Comment by bojiang** [comment]
Okay

**Comment by parano** [comment]
@bojiang @akainth015 closing this ticket since we prefer to keep Python 3.6 support for now.  I think we should still go back and add type annotations whenever possible in the project, especially for the user-facing APIs. Those will help the end-user to better understand BentoML API's expectation on data types and makes the development process easider.
