### ISSUE TITLE
DataFrame Input - pass NaN values in JSON Request

### ISSUE THREAD

**Issue by Rasen-wq** [bentoml/BentoML#862]
**Describe the bug**

Hi, I am trying BentoML with DataFrameInput and the Titanic Dataset following this [notebook](https://github.com/bentoml/gallery/blob/master/lightbgm/titanic-survival-prediction/lightbgm-titanic-survival-prediction.ipynb). In this dataset there are None values. 

I am sending the following data content, in this case the null value is casted to None and not to `NaN`:
`'{"Pclass":{"0":3},"Age":{"0":null},"Fare":{"0":7.8958},"SibSp":{"0":0},"Parch":{"0":0}}'`

If I change the null value to any number the request is successful. 

I believe the problem is in this [line](https://github.com/bentoml/BentoML/blob/master/bentoml/adapters/dataframe_input.py#L158), when the dtype inference is set to false. This makes impossibile to cast the `NaN` value. 

I am suggesting, in order to solve the problem to change the `dtype` inference to be `True`. 
Doing that, Pandas will automatically infer the NaN value.

Something I found interesting: if I send 1 only row with a null  value this is casted to string. If I send 2 rows, one with null value and one without the casting works well. I don't believe this type of behaviour should be expected.

**To Reproduce**
`pd.read_json('[{"key": NaN }]',dtype=False)`
Is casted to None

`pd.read_json('[{"key": NaN }]',dtype=True)`
Is casted regularly to NaN.

**Comment by Rasen-wq** [comment]
The problem can be easily workaround using the JSON Input, I still think it makes sense to raise the issue when using the DataFrame Input: 
<img width="477" alt="Screenshot 2020-07-02 at 16 24 22" src="https://user-images.githubusercontent.com/17594750/86377940-ea3e2b00-bc80-11ea-8e78-bcff5d0e7689.png">

**Comment by parano** [comment]
Thanks for reporting this @Rasen-wq,  I think your suggestion makes sense, I'm not sure why the `dtype` was set to false.

@bojiang thoughts?
