### ISSUE TITLE
PytorchModelArtifact support JIT traced models

### ISSUE THREAD

**Issue by calclavia** [bentoml/BentoML#873]
**Is your feature request related to a problem? Please describe.**
It would be great if PytorchModelArtifact could support Pytorch JIT traced models.
JIT produces more compact model artifacts and is more suitable for prod applications.
https://pytorch.org/docs/stable/jit.htm

**Describe the solution you'd like**
Change PytorchModelArtifact to accept Pytorch JIT models.

**Comment by yubozhao** [comment]
@calclavia The PR #1293 merged into master, should be release in the next version. Feel free to reopen this issue, if you run into any problems
