### ISSUE TITLE
[Question] Serving without Docker?

### ISSUE THREAD

**Issue by guy4261** [bentoml/BentoML#880]
Hello,

Did you ever try to run the model directly on the environment - without the Docker wrapping it and bringing its overheads and hurting the performance?

Namely, if I go through the quick-start and then do this:
```
$ cd ~/bentoml/repository/IrisClassifier/20200708171658_C26C3B
$ bentoml serve-gunicorn .  # picked up from the `Dockerfile` in the current directory
```

Do you see any problems in doing that - aka any warning you can give me in advance?

Thanks!

**Comment by parano** [comment]
@guy4261 I think as long as you make sure that all dependencies specified in the `requirements.txt` and `environment.txt` under saved bundle are installed properly(that `bentoml serve-gunicorn .` does not install the dependencies for you),  this should just work. 

Although for serving production workloads, we do recommend using Docker for deployment. Besides the benefits docker provides, there should be [pretty much no performance overheads](https://ieeexplore.ieee.org/document/7095802) of running the API server in docker, assuming you are deploying to a Linux server.

**Comment by parano** [comment]
@guy4261 I think as long as you make sure that all dependencies specified in the requirements.txt and environment.txt under saved bundle are installed properly(that bentoml serve-gunicorn . does not install the dependencies for you), this should just work.

Although for serving production workloads, we do recommend using Docker for deployment. There should be very little performance overheads of running the API server in docker, assuming you are deploying to a Linux server.

**Comment by guy4261** [comment]
Thanks @parano ! That's great news for me. I'm deploying to a Mac right now (for production - yes, an odd setting...) so that's wonderful to hear.

**Comment by guy4261** [comment]
Sorry I nagged! I see now that this is written here:

https://docs.bentoml.org/en/latest/concepts.html#online-api-serving

> For running production API server, make sure to run bentoml serve-gunicorn command instead [...]
> `bentoml serve-gunicorn $saved_path --enable-microbatch --workers=2 --port=3000`

Just wanted to make sure. Thanks again.
