### ISSUE TITLE
Add labels and label selection API to YataiService model registry

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#888]
Add `labels` concept to BentoML bundle and YataiService. Labels are key/value pairs that are attached to a BentoML saved bundle, similar to the `labels` concept in Kubernetes: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

> Labels are key/value pairs that are attached to objects, such as pods. Labels are intended to be used to specify identifying attributes of objects that are meaningful and relevant to users, but do not directly imply semantics to the core system. Labels can be used to organize and to select subsets of objects. Labels can be attached to objects at creation time and subsequently added and modified at any time. Each object can have a set of key/value labels defined. Each Key must be unique for a given object.

Example labels:

* "app": "fraud-detection", "product-recommendation", ...
* "team": "fraud-detection-team", "product-recommendation-team", ...
* "user": "jeff", "bo", ...
* "tier" : "experimentation", "golden", "prod", ...
* "customer": "customer_a", "customer_b", ...
* "status": "untested", "passed-ci", "approved" ...

Use should be able to specify the default labels when creating a saved bundle, use the quick start guide as an example:

```python
from bentoml import env, artifacts, api, BentoService
from bentoml.adapters import DataframeInput
from bentoml.artifact import SklearnModelArtifact

@env(auto_pip_dependencies=True)
@artifacts([SklearnModelArtifact('model')])
class IrisClassifier(BentoService):

    @api(input=DataframeInput())
    def predict(self, df):
        # Optional pre-processing, post-processing code goes here
        return self.artifacts.model.predict(df)

-----

from sklearn import svm
from sklearn import datasets

from iris_classifier import IrisClassifier

if __name__ == "__main__":
    # Load training data
    iris = datasets.load_iris()
    X, y = iris.data, iris.target

    # Model Training
    clf = svm.SVC(gamma='scale')
    clf.fit(X, y)

    # Create a iris classifier service instance
    iris_classifier_service = IrisClassifier()

    # Pack the newly trained model artifact
    iris_classifier_service.pack('model', calf, metadata=model_metadata)

    # Add labels
    import getpass
    import subprocess
    git_label = subprocess.check_output(["git", "describe"]).strip()
    labels = {
      'app': 'iris_classifier',
      'job_id': 'xxxxxxx',
      'user': getpass.getuser(),
      'git_hash': git_label,
      'status': 'untested'
    }
    iris_classifier_service.set_labels(labels)

    # Save the prediction service to disk for model serving
    saved_path = iris_classifier_service.save()
```

Now, the YataiService will store all the Labels information in its database, and users can view labels via the `bentoml get` command or in the YataiService Web UI:

```bash
> bentoml get IrisClassifier:latest

name: IrisClassifier
version: 20200701222443_EC5EAB
uri:
  type: LOCAL
  uri: /Users/chaoyu/bentoml/repository/IrisClassifier/20200701222443_EC5EAB
labels:
  app: iris_classifier
  job_id': xxxxxxx
  user: chaoyu
  git_hash: v0.8.3-17-gb6672b56
  status: untested
bentoServiceMetadata:
  name: IrisClassifier
  version: 20200701222443_EC5EAB
  createdAt: '2020-07-02T05:25:06.238433Z'
  env:
    condaEnv: "name: bentoml-IrisClassifier\nchannels:\n- defaults\ndependencies:\n\
      - python=3.7.5\n- pip\n"
    pipDependencies: "scikit-learn\npandas\nbentoml==0.8.2"
    pythonVersion: 3.7.5
    dockerBaseImage: bentoml/model-server:0.8.2
  artifacts:
  - name: model
    artifactType: SklearnModelArtifact
  apis:
  - name: predict
    inputType: DataframeInput
    docs: BentoService API
    inputConfig:
      is_batch_input: true
      input_dtypes:
      orient:
      typ: frame
    outputConfig:
      cors: '*'
    outputType: DefaultOutput
    mbMaxLatency: 300
    mbMaxBatchSize: 2000
```

YataiService's ListBento RPC now should support listing BentoML bundle by labels, and CLI should support querying using this API.  A user should be able to list saved bundle by specifying labels, e.g.:

```bash
> bentoml list -l app=iris_classifier,user=chaoyu
```
In terms of CLI syntax, let's keep it consistent with the Kubectl. This query API should also support `IN` and `NOT IN` operator:

```bash
> bentoml list -l 'app in (iris_classifier, inception),user in (chaoyu)'

> bentoml list -l 'status,status notion (untested)'
```

Lastly, BentoML should allow its user to update labels of saved bundles. We will need to add a new RPC `SetLabels` to YataiService gRPC server and a new CLI command `bentoml label`, similar to the `kubectl label` command https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#label

```bash
# print current labels
> bentoml label IrisClassifier:20200701222443_EC5EAB
labels:
    app: iris_classifier
    job_id: xxxxxxx
    user: chaoyu
    git_hash: v0.8.3-17-gb6672b56
    status: untested

# override `status` label's value from 'untested' to 'approved'
> bentoml label IrisClassifier:20200701222443_EC5EAB status=approved

# update all saved bundle named IrisClassifier with status=unhealthy label 
> bentoml label IrisClassifier --all status=unhealthy
```

Bonus point:

Add a "search by labels" UI element to the model management web UI in YataiService, allowing the user to quickly find the model they need.

**Comment by yubozhao** [comment]
closed with https://github.com/bentoml/BentoML/pull/1064
