### ISSUE TITLE
Test dockerized API Server in artifact integration test

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#891]
There are currently 3 model artifact integration tests under the `test/integration/` directory: https://github.com/bentoml/BentoML/tree/e656c2d79965535eaa8228f925b0578520038528/tests/integration

We currently only test saving and then loading a BentoService with the artifact type being tested within the same python session.  We would like to extend the coverage to fully testing the generated API server docker image, and make sure the artifact can be loaded in the docker environment, and the API server is functioning as expected.

See related discussions here: https://github.com/bentoml/BentoML/pull/876

Related tickets for more artifact integration tests:
* https://github.com/bentoml/BentoML/issues/724
* https://github.com/bentoml/BentoML/issues/722
* https://github.com/bentoml/BentoML/issues/721

cc @joshuacwnewton

**Comment by joshuacwnewton** [comment]
Hi @parano! Thanks for the tag. Just commenting to say I've started to work on this. My plan is to start with the updated #721, and once that looks good, continue on to other artifact types. :)
