### ISSUE TITLE
The CIFAR-10 image classifier prediction fails on Ubuntu 18.04 with bentoml 0.8.3 

### ISSUE THREAD

**Issue by jesudasvf** [bentoml/BentoML#895]
**Describe the bug**
The prediction for the CIFAR-10 image classifier example fails with an error.

**To Reproduce**
1. Get the CIFAR -10 image classifier from the bentoml gallery examples web page https://github.com/bentoml/gallery/tree/master/pytorch/cifar10-image-classification
2. Build the bentoml service PytorchImageClassifier
3. Try to run the PytorchImageClassifier service with the bentoml run command

**Expected behavior**
The prediction function should have a returned a predicted class value 

**Screenshots/Logs**
To give us more information for diagnosing the issue, make sure to enable debug logging:

>>>> Please refer the attached next file for the outputs observed when running the bentoml commands
[prj_notes.txt](https://github.com/bentoml/BentoML/files/4919592/prj_notes.txt)

**Environment:**
 - OS: Ubuntu : 18.04.4 LTS (Bionic)
 - Python/BentoML Version [e.g. Python 3.6.9, BentoML-0.8.3]
 - Pillow : 7.2.0
 - pytorch : 1.5.1
 - torchvision : 0.6.1

**Additional context**

**Comment by jesudasvf** [comment]
The handlers import line was changed to 
>>>> from bentoml.adapters import LegacyImageInput

The bentoml.api line was changed to 
@bentoml.api(input=LegacyImageInput)

With the above changes the prediction still gave the same error

**Comment by jesudasvf** [comment]
The bentoml service file for CIFAR-10 classifier had to be modified as follows: 

@bentoml.api(ImageHandler)     changed to 
>>>> @bentoml.api(ImageInput)

and if in case the pytorch model is trained for GPU the line  
outputs = self.artifacts.net(Variable(torch.stack(input_datas)))   changed to 
>>>> outputs = self.artifacts.net(Variable(torch.stack(input_datas).to('cuda:0'))
  the device name should be given properly to select the required GPU device

With the above changes the model predicts with bentoml run cli command
After serving the model predicts using the swagger tool and curl commands
. 
The final bentoml service file for cifar-10 image classifier is attached. 
[cifar_image_classifier.txt](https://github.com/bentoml/BentoML/files/4925280/cifar_image_classifier.txt)

**Comment by parano** [comment]
Thanks, @jesudasvf! I will update the gallery notebook accordingly.

**Comment by jesudasvf** [comment]
You are welcome @parano ! I will close this bug.
