### ISSUE TITLE
' npm run build' command failed while running BentoML Web UI

### ISSUE THREAD

**Issue by athulprathap** [bentoml/BentoML#896]
**Describe the bug**
Trying to run BentoML Web UI.Followed the section 'How to run and develop BentoML Web UI from 'https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md to load the UI.
After running the yarn and npm run build commands as directed its throwing errors and UI is not getting loaded.

**To Reproduce**
1. Go to 'https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md'

2. Scroll down to 'How to run and develop BentoML Web UI'
3. See error while running it in my local environment.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yatai_web_server@0.0.1 build: `rm -rf dist && concurrently "npm run build:client" "npm run build:server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yatai_web_server@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aicoe/.npm/_logs/2020-07-09T07_27_46_729Z-debug.log

**Expected behavior**
WebUI served on Localhost

**Screenshots/Logs**
![bentoerrorlog](https://user-images.githubusercontent.com/10370721/87456004-f41e4180-c623-11ea-85ec-b9367b89ded8.png)

**Environment:**
 - OS: Ubuntu 18.04

 - Python/BentoML Version [ Python 3.7.1, BentoML-0.8.2]
 - Node version -v12.8.0 
 -Yarn Version - 1.22.4

**Comment by yubozhao** [comment]
@athulprathap Thank you for catching this bug!

This bug was caused by Mac ignore case difference (`./App` and `./app`) when importing other files.
