### ISSUE TITLE
Support KFServing API V2 predict protocol

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#899]
About KFServing API V2 predict protocol: https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2
>The Predict Protocol, version 2 is a set of HTTP/REST and GRPC APIs for inference / prediction servers. By implementing this protocol both inference clients and servers will increase their utility and portability by being able to operate seamlessly on platforms that have standardized around this protocol.

> The protocol is composed of a required set of APIs that must be implemented by a compliant server. This required set of APIs is described in required_api.md. The GRPC proto specification for the required APIs is available.

This is to add an option to BentoML API server, that enables a set of special endpoints that are compatible with KFServing API V2 protocol.  It will make BentoML API server work much nicer with other tools in the kubeflow eco-system.

* Predict protocol V2 spec: https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#tensor-data-types
* KFServing roadmap on V2 protocol support is targeting Q3 2020 https://github.com/kubeflow/kfserving/blob/master/ROADMAP.md#v05-api-stabilization-and-tco-reduction-eta-end-of-q3

**Comment by pncnmnp** [comment]
@yubozhao 
[Kishore](https://github.com/kishore-ganesh) and I are interested in contributing to this issue.

**Comment by parano** [comment]
Hi @pncnmnp @Kishore - it probably makes more sense to first implement gRPC support in bentoML https://github.com/bentoml/BentoML/issues/703 before supporting KFServing V2's predict protocol

**Comment by wolvever** [comment]
KServe predict protocol is supported in KServe, Seldon Core and Triton Inference Server.  I think it make sense to support this protocol to allow users switch different frameworks.  We are currently using Triton Inference Server to serve our own models for historical reason.  And we also want to provide BentoML to our collaborators to simplify serving and deployment.  But our product relied on this predict protocol, and we can't provide BentoML now.
