### ISSUE TITLE
'yarn start ' and 'npm start'  failing while loading web UI

### ISSUE THREAD

**Issue by athulprathap** [bentoml/BentoML#903]
**Describe the bug**
'yarn start' is giving errors while trying to run the web UI  in localhost.Trying to run BentoML Web UI.Followed the section 'How to run and develop BentoML Web UI from 'https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md to load the UI.
After running the yarn and npm run build commands as directed its throwing errors and UI is not getting loaded after 'npm start' and 'yarn start'

**To Reproduce**
1. Go to Go to 'https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md'
2. Scroll down to 'How to run and develop BentoML Web UI'.'
3. See error after 'yarn install' and 'yarn start' command.
   yarn run v1.22.4
$ node dist/index.js
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module '/home/techmadmin/Documents/BentoML/bentoml/yatai/web/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Expected behavior**
WebUI served on Localhost

**Screenshots/Logs**
![bentouiyarnstart](https://user-images.githubusercontent.com/10370721/87624209-c846ad00-c744-11ea-8971-099c94e603e7.png)

Environment:

OS: Ubuntu 18.04

Python/BentoML Version [ Python 3.7.1, BentoML-0.8.2]

Node version -v12.8.0
-Yarn Version - 1.22.

**Comment by yubozhao** [comment]
@athulprathap I encounter a similar error when I didn't run `yarn build` after I ran the command `yarn start`. Did you have a successful build?

**Comment by athulprathap** [comment]
@yubozhao Yes 'npm run build' is successful and 'yarn build' was executed before 'yarn start'.
![bentouiyarnbuild](https://user-images.githubusercontent.com/10370721/87647485-035cd680-c76d-11ea-8b05-4f38f7900de4.png)

**Comment by yubozhao** [comment]
Hi @athulprathap The start script is incorrectly pointing at the wrong file.  I updated it at #906.

**Comment by athulprathap** [comment]
@yubozhao @parano Thank you for the support!!
