### ISSUE TITLE
Update examples?

### ISSUE THREAD

**Issue by nabinkhadka** [bentoml/BentoML#912]
From here https://docs.bentoml.org/en/latest/examples.html

I see there are outdated examples (at least https://colab.research.google.com/github/bentoml/gallery/blob/master/keras/text-classification/keras-text-classification.ipynb#scrollTo=XS3uJ_74NLTT). Any plan to update it? This doesn't help for non-ML dev who learns to just integrate BentoML to webapp.

**Comment by yubozhao** [comment]
@nabinkhadka Thank you for point this out! I have updated the example notebook you mentioned and few others.

Really appreciate that you thought about new devs while you are looking into BentoML!

**Comment by parano** [comment]
Thanks, @yubozhao @nabinkhadka!
