### ISSUE TITLE
Add FileOutputAdapter for returning binary file as API output

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#919]
Many BentoML users have requested the capability to return a file(e.g. an image) as the response of an API endpoint. There isn't direct support for this in BentoML today and we've been asking users to use base64 to encode the file and return it in a JSON response.

This approach works as a workaround but requires the client to decode the response into a file, which in very inconvenient.

This is to propose a new FileOutputAdapter which allows users to return a file as the output of their API callback function and lets BentoML return the file as an HTTP response to the API client.

Additional context:
* We are already working on file input adapter here: https://github.com/bentoml/BentoML/pull/734
* Although not currently documented, users can specify the output of their inference API via output adapters: https://github.com/bentoml/BentoML/tree/v0.8.3/bentoml/adapters
* There is currently a default output adapter which accepts a wide range of different return value data types

**Comment by akainth015** [comment]
I can begin to work on this, hopefully it'll go faster than the `MultiImageInput` :sweat_smile:

**Comment by bojiang** [comment]
## Definetion
FileOutput accepts Python types that represent the content of files.
* str, StringIO -> string file
* bytes, BinaryIO (including BytesIO, opened file object) -> binary file

FileOutput converts python object above and passes to CLI, AWS lambda, and HTTP.

## Behaviour

### HTTP
* the default `Content-Type` header should be `application/octet-stream`, which means _arbitrary binary data_ (RFC 2046)
* (optional) user may customize the `Content-Type` by `FileOutput(content_type="image/jpeg")`
* (optional) file size may exceed [max size limit](https://github.com/bentoml/BentoML/blob/master/bentoml/configuration/default_bentoml.cfg#L69) of HTTP response, support `Transfer-Encoding: chunked` to

**Comment by parano** [comment]
This is now supported in BentoML version 1.0: https://docs.bentoml.org/en/latest/api/api_io_descriptors.html#bentoml-io-file
