### ISSUE TITLE
[Internal] Remove slices from batch responses

### ISSUE THREAD

**Issue by akainth015** [bentoml/BentoML#924]
While writing the `MultiImageInput` adapter, the `slices` parameter that I had to produce was fairly confusing for me to generate. Now, writing the `FileOutput` adapter, it comes up again as more of a hurdle than something helpful in producing responses. I am proposing that we remove the `slices` parameter, and instead place a `None` in the results array, and using the appropriate fallback when a result is `None`.

The principle advantages this change would have are as follows:
1. Eliminate a parameter, and thus complexity from `OutputAdapter`s
2. Align `results` and `fallbacks`, so an index in `results` corresponds to the same index in `fallbacks`.

I believe the only downside to this change would be that models can no longer return `None`, but this is both unlikely and easily remedied by putting `None` in the same position in the `fallbacks` list.

**Comment by akainth015** [comment]
I am also contemplating converting `fallback` into a function that is called with the request body as its only parameter, and that produces a default value. In this way, we can avoid creating a fallback for every request in the batch and instead only producing fallbacks when necessary.

I am assuming that we have an array for individual requests because each fallback is meant to be customizable to each request instead of a generic body that applies to all requests, but if a generic body is possible in the use cases we can simplify this API even further by replacing `fallbacks` with a `fallback` object instead of a `fallback` producer.

**Comment by akainth015** [comment]
After thinking about this a bit more, there are a lot more changes I think we should make. I will open a new issue for them since the scope for that is much wider than for this.

**Comment by parano** [comment]
Thanks for looking into this @akainth015 

I agree that some of the code structure around handling batch inputs in input adapters can be improved, to make implementing new input/output adapters easier, since it is quite common that users may need to implement their own custom input adapter. To redesign this, you may need to look at the patterns across different handlers as well as the marshal server's internal implementation.
