### ISSUE TITLE
CoreML Support / can I extend `BentoServiceArtifact` and serve it?

### ISSUE THREAD

**Issue by guy4261** [bentoml/BentoML#926]
**Is your feature request related to a problem? Please describe.**
I'm running BentoML directly on a Mac. To gain speedups, I would like to convert my PyTorch model (which you support) to CoreML (which you do not support). To do that, I would like to extend `BentoServiceArtifact`. Is that even allowed? Any caveats I should expect?

**Describe the solution you'd like**
Seems like `BentoServiceArtifact` is just a class saying how to save and load an object. So I'd like to write one for a CoreML model (probably one I converted via https://coremltools.readme.io/docs/pytorch-conversion).

**Describe alternatives you've considered**
Convert my model on the first time I load it. Just seems cheesy.

**Additional context**
Supporting CoreML = supporting faster inference for people running the server directly (`$ bentoml serve Foo:latest`) on a Mac.

**Comment by yubozhao** [comment]
Hi, @guy4261. Good suggestion! You can definitely write a new `BentoServiceArtifact` for CoreML.  I don't think there are any caveats, from looking at the `coremltools` package.

I think other people can benefit from this, feel free to submit a PR.

**Comment by guy4261** [comment]
Thanks @yubozhao ! How do I test it? `pip install -e` the BentoML repo, edit the code and do it? This is why I asked - to verify there are no apparent caveats before I begin.

Thanks!

**Comment by yubozhao** [comment]
Yes, for developing you install from the source, install the local version with `pip install -e` and go from there. 

For testing, you can use the ONNX artifact as an example.  We create an [integration test](https://github.com/bentoml/BentoML/blob/master/tests/integration/test_onnx_model_artifact.py) and add additional test suit for Travis by adding [test script](https://github.com/bentoml/BentoML/blob/master/travis/onnx_integration_tests.sh) and updating the [Travis configuration](https://github.com/bentoml/BentoML/blob/master/.travis.yml)

I am pretty excited about this and looking forward to seeing it

**Comment by parano** [comment]
@guy4261 be sure to build base off the latest master branch, there were some recent refactoring on that code path that drastically changed how new artifact can be implemented. See also #758 #925.

**Comment by guy4261** [comment]
Thanks!

Questions begin:

Seems like I can't use `cloudpickle` for the CoreML model. Can I use the library's standard tools, i.e.
```
self._model.save(self._file_path(dst))
```

or does it have to be `cloudpickle`-able?

Log below:

```python
>>> cloudpickle.dump(model, open("model.cloudpickle", "wb"))
Traceback (most recent call last):
  File "/Users/grapaport/ms/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-2b48d5f5d6ec>", line 1, in <module>
    cloudpickle.dump(model, open("model.cloudpickle", "wb"))
  File "/Users/grapaport/Documents/BentoML/bentoml/utils/cloudpickle.py", line 1091, in dump
    CloudPickler(file, protocol=protocol).dump(obj)
  File "/Users/grapaport/Documents/BentoML/bentoml/utils/cloudpickle.py", line 367, in dump
    return Pickler.dump(self, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle coremltools.libcoremlpython._MLModelProxy objects
```

**Comment by parano** [comment]
Hi @guy4261 - it is recommended to use the library's standard tool for serialization.

We use cloudpickle for PyTorch model artifact because PyTorch's standard save/load also uses Pickle, and cloudpickle offers more functionality than the default pickle module.

**Comment by guy4261** [comment]
OK. `cloudpickle` doesn't work with CoreML models though, as you can see 👆 

Is it OK if I extend `cloudpickle` to use CoreML's native save/load?

Right now my `CoreMLModelArtifact` looks like this -

* Load: `model = coremltools.models.MLModel(self._file_path(path))`
* Save: `self._model.save(self._file_path(dst))`

I see that other artifacts (for instance `keras_model_artifact`) also use their respective frameworks' save/load:

```
                if self._store_as_json_and_weights:
                    with open(self._model_json_path(path), 'r') as json_file:
                        model_json = json_file.read()
                    model = keras_module.models.model_from_json(
                        model_json, custom_objects=self._default_custom_objects
                    )
                    model.load_weights(self._model_weights_path(path))
                # otherwise, load keras model via standard load_model
                else:
                    model = keras_module.models.load_model(
                        self._model_file_path(path),
                        custom_objects=self._default_custom_objects,
                    )
        return self.pack(model)
```

**Comment by parano** [comment]
@guy4261, yea that approach looks good.  As I suggested above, we recommend using the frameworks' own serialization standard.

**Comment by guy4261** [comment]
Thank you @parano @yubozhao for your support and encouragement. The PR is waiting for you at https://github.com/bentoml/BentoML/pull/939 🙏 🙏 🙏  !

**Comment by parano** [comment]
@guy4261 thanks again for your contribution! The PR is now merged and this will be available in the next BentoML release!
