### ISSUE TITLE
--enable-microbatch turns empty text into NaN

### ISSUE THREAD

**Issue by dcferreira** [bentoml/BentoML#929]
**Describe the bug**
When the input is a dataframe with a string field, and it contains empty text, microbatching replaces the empty text by NaN.
Wtihout microbatching, this works as expected.

**To Reproduce**
Code to reproduce it:
- Server:
```python
import bentoml
from bentoml.adapters import DataframeInput, DataframeOutput

@bentoml.env(auto_pip_dependencies=True)
class TestSizer(bentoml.BentoService):
    @bentoml.api(input=DataframeInput(input_dtypes={"text": "str"}),
                 output=DataframeOutput())
    def size(self, df):
        if 'text' not in df:
            raise ValueError('The Dataframe needs a column named "text".')
        return df.text.apply(len).to_frame()

if __name__ == '__main__':
    sizer = TestSizer()
    sizer.save()
```
- Client:
```python
import pandas as pd
import requests

class TextClient:
    def __init__(self, server_url: str):
        self.server_url = server_url

    def size(self, df: pd.DataFrame) -> pd.DataFrame:
        if 'text' not in df:
            raise ValueError('The given Dataframe requires a column named "html".')
        resp = requests.post(self.server_url, headers={'Content-Type': 'application/json'},
                             data=df.to_json())
        if resp.status_code != 200:
            raise ValueError('Bad reply!')
        return pd.DataFrame(data=resp.json(), index=df.index)

if __name__ == '__main__':
    client = TextClient('http://127.0.0.1:5000/size')
    ex1 = pd.DataFrame({"text": ["this is a text", "and another one", ""]}, index=["one", "two", "three"])
    print(client.size(ex1))
```

**Expected behavior**
The client should run without problems.
This works fine without using microbatching, but when it's turned on, the server function receives a pandas DataFrame with a NaN value in it.

**Screenshots/Logs**
In this example, the client will crash, and the server logs will have:
```
TypeError: object of type 'float' has no len()
```

**Environment:**
 - BentoML Version: 0.8.3

**Comment by parano** [comment]
@dcferreira thanks for the detailed bug report and sample code to reproduce.

@bojiang could you please take a look?

**Comment by bojiang** [comment]
Yeah. It's a known issue from pandas.read_csv.
https://github.com/pandas-dev/pandas/issues/10205
> I know it may seem a little strange, but pandas actually uses NaN intentionally in string arrays, as a marker for missing values. The pandas string methods will skip NaN, and likewise we use it for methods like isnull, fillna and dropna. If you'd like to replace them with another value, try df.fillna(''). by shoyer

We are aware of this, https://github.com/bentoml/BentoML/blob/master/tests/adapters/test_dataframe_handler.py#L156
