### ISSUE TITLE
Allow setting micro-batching parameters via environment variable and CLI arg

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#930]
**Is your feature request related to a problem? Please describe.**

See related discussions here: https://github.com/bentoml/BentoML/discussions/927

**Describe the solution you'd like**

Add a CLI argument and environment variable for the user to set the micro batching parameter `mb_max_batch_size` and `mb_max_latency`.

**Describe alternatives you've considered**

When defining a service API, allow users to add a few sets of parameters for different hardware profile and a default profile to use.

**Comment by jsemric** [comment]
I would take this one
