### ISSUE TITLE
Fastai2 Vision/Medical Support 

### ISSUE THREAD

**Issue by MadisLemsalu** [bentoml/BentoML#956]
Fastai2 is being released in the upcoming weeks and would be nice if BentoML would support it as well with an example notebook. Especially support for vision submodule. 

Currently the error when trying to serve a fastai2 vision model is: `MissingDepenendencyException: fastai.vision package is required to use FastaiImageInput`

**Comment by parano** [comment]
Have you tried adding the `torchvision` module to your BentoService definition? e.g. `@env(pip_dependencies=['torchvision'])`. I believe fastai2 is already supported via the `bentoml.artifact.Fastai2ModelArtifact`.  There isn't an example notebook for it tho.

cc @yubozhao

**Comment by yubozhao** [comment]
@MadisLemsalu Thanks for the heads up!  I will work on an example notebook for the Fastai2 Vision model.  I am thinking of using the [medical imaging tutoral](https://github.com/fastai/fastai2/blob/master/nbs/61_tutorial.medical_imaging.ipynb) as the example notebook.  Do you have any suggestions?

**Comment by MadisLemsalu** [comment]
@yubozhao I like it that the example is from the medical field. The one bad thing about that notebook is that it is using lambda functions in the Dataloader, which prevents from calling learner.export() in order to pickle the model (pickling doesn't support lambda functions) to be used for BentoML. 

Another example could be from Fastbook: https://github.com/fastai/fastbook/blob/master/02_production.ipynb
but it's quite convoluted. If the dataloader in the medical notebook could be done differently then it's good.

**Comment by yubozhao** [comment]
@MadisLemsalu I was able to solve the lambda and Dataloader issue and create an example notebook at https://github.com/bentoml/gallery/pull/48. You should be able to get started with that. Feel free to ask any questions.

I will add a deployment example for that notebook and then merge it in.

**Comment by MadisLemsalu** [comment]
Okay great thanks!

Sincerely,
Madis Lemsalu

**Comment by yubozhao** [comment]
@MadisLemsalu Have you have the chance to check out that notebook? Feel free to ping us on slack or write issues/discussions on Github if you run into any issues or have questions.

I am going to close this issue for now. Feel free to open this back up again, if something went wrong
