### ISSUE TITLE
Add artifacts for Yaml and JsonPickle

### ISSUE THREAD

**Issue by mkosecki** [bentoml/BentoML#965]
**Is your feature request related to a problem? Please describe.**
Support of yaml objects and [JsonPickle](https://github.com/jsonpickle/jsonpickle) objects.

**Describe the solution you'd like**
Inherit from base class  BentoServiceArtifact and create YAMLArtifact and JsonPickleArtifact, store within artifact directory.

**Describe alternatives you've considered**
The alternative is that each user of BentoML will implement artifact handler for this file formats themselves :)

**Comment by Sharathmk99** [comment]
You can use textfil artifact for YAML files right?

**Comment by mkosecki** [comment]
Yes. Json also could be used with TextFile but then you need to parse it yourself that's why I assume there is JsonArtifact. I think it's better to go with approach of JsonArtifact and extend TextFile artifact with pyyaml handlers.

**Comment by parano** [comment]
We are planning to add a more flexible API for users to include arbitrary files that are not "Models" in the BentoML saved bundle. Most files(JSON, Text, YAML) don't really utilize the Artifact APIs that are designed to be used for ML models.  Alternatively we could introduce a more general `FileArtifact` for including arbitrary files.

See https://github.com/bentoml/BentoML/issues/685 for additional context
