### ISSUE TITLE
Add deployment guide on Heroku

### ISSUE THREAD

**Issue by sayakpaul** [bentoml/BentoML#99]
Hi @parano, @yubozhao. I tried to set up a deployment pipeline of a simple API endpoint (created using `BentoML`) on **Heroku**. I am assuming that the **bento-archive** that gets generated by Bento is the main directory which would be required to in order to proceed with the deployment. Here's how that directory looks like - 

![image](https://user-images.githubusercontent.com/22957388/56466272-2515c380-642d-11e9-920b-093fc93a9400.png)

Also, for your convenience, here's the [GitHub repo](https://github.com/sayakpaul/Heroku-Demo-Deploy) with the files of the archive uploaded to it. I modified the `requirements.txt` accordingly as Heroku needs that in order to manage the dependencies. I thought it might be a good idea to suggest to include a guide for Heroku deployments as well since Heroku is very popular among API developers. Unfortunately, the build keeps getting failed on Heroku(**note** that the module class has been uploaded to PyPI as well, here's the [link](https://pypi.org/project/PassengerClassifier/)). Here's build log - 

```
-----> Python app detected
-----> Installing python-3.6.8
-----> Installing pip
-----> Installing SQLite3
-----> Installing requirements with pip
       Obtaining file:///tmp/build_0cb7bbf6d47f1bcdd63e482cc791f0f9 (from -r /tmp/build_0cb7bbf6d47f1bcdd63e482cc791f0f9/requirements.txt (line 1))
       Collecting None (from PassengerClassifier==0.0.1->-r /tmp/build_0cb7bbf6d47f1bcdd63e482cc791f0f9/requirements.txt (line 1))
         Could not find a version that satisfies the requirement None (from PassengerClassifier==0.0.1->-r /tmp/build_0cb7bbf6d47f1bcdd63e482cc791f0f9/requirements.txt (line 1)) (from versions: )
       No matching distribution found for None (from PassengerClassifier==0.0.1->-r /tmp/build_0cb7bbf6d47f1bcdd63e482cc791f0f9/requirements.txt (line 1))
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

It might help you guys further if you consider to include a guide on Heroku deployments. Might serve you a direction. Looking forward to hearing from you.

**Comment by yubozhao** [comment]
Hi @sayakpaul Thanks for the suggestion!

I think Heroku is on our roadmap for sure.  Have you have the chance to do a [docker image deployment with Heroku](https://devcenter.heroku.com/articles/container-registry-and-runtime)?  I think this might be the easiest way to do so with Heroku.  I am not very familiar with Heroku, so I might be incorrect.

Anyway, we will research on what's the best way to deploy to Heroku and write an example of it to give others an easier start.

Thank you for suggestion!

**Comment by sayakpaul** [comment]
Sure @yubozhao. I shall do the **docker** variant and get back to you.

**Comment by sayakpaul** [comment]
Cc: @yubozhao

**Comment by yubozhao** [comment]
@sayakpaul I am writing documentation site atm.  Will have more time after that to figure out issues to work on.  This is definitely on our list of things.

**Comment by sayakpaul** [comment]
Sure thing. I am going to close the issue then.
