### ISSUE TITLE
DataframeInput does not handle indices

### ISSUE THREAD

**Issue by dcferreira** [bentoml/BentoML#993]
**Describe the bug**
I expected ``DataframeInput``/``DataframeOutput`` to keep dataframe indices, but this does not happen.

**To Reproduce**
I'll take the example code I've been using for other bug reports:
* Server:
```python
import bentoml
from bentoml.adapters import DataframeInput, DataframeOutput

@bentoml.env(auto_pip_dependencies=True)
class TestSizer(bentoml.BentoService):
    @bentoml.api(input=DataframeInput(input_dtypes={"text": "str"}),
                 output=DataframeOutput())
    def size(self, df):
        if 'text' not in df:
            raise ValueError('The Dataframe needs a column named "text".')
        return df.text.apply(len).to_frame()

if __name__ == '__main__':
    sizer = TestSizer()
    sizer.save()
```
* Client:
```python
import pandas as pd
import requests

class TextClient:
    def __init__(self, server_url: str):
        self.server_url = server_url

    def size(self, df: pd.DataFrame) -> pd.DataFrame:
        if 'text' not in df:
            raise ValueError('The given Dataframe requires a column named "html".')
        resp = requests.post(self.server_url, headers={'Content-Type': 'application/json'},
                             data=df.to_json())
        if resp.status_code != 200:
            raise ValueError('Bad reply!')
        return pd.DataFrame(data=resp.json(), index=df.index)

if __name__ == '__main__':
    client = TextClient('http://127.0.0.1:5000/size')
    ex1 = pd.DataFrame({"text": ["this is a text", "and another one", ""]}, index=["14", "15", "0"])
    print(client.size(ex1))
```

Notice the indices in the dataframe of the example correspond to the length of the strings, for easier comparison to the correct result.

**Expected behavior**
The expected output here would be:
```
    text
14   14
15   15
0     0
```
However, in my machine I get:
```
    text
14     0
15    14
0     15
```

If I replace `return pd.DataFrame(data=resp.json(), index=df.index)` in the client by `return pd.DataFrame(data=resp.json())`, I get:
```
   text
0     0
1    14
2    15
```
which gives some insight as to why this happens.

The issue here is that `read_dataframes_from_json_n_csv` (in `bentoml/utils/dataframe_util.py`) gets rid of indices.

**Workaround**
There is a way to work around this, by moving the index to a column before sending it to the server, and making sure the server also gives the index in a column.
For this example, these classes work around this issue:
* Server:
```python
class TestSizer(bentoml.BentoService):
    @bentoml.api(input=DataframeInput(input_dtypes={"text": "str"}, orient='columns'),
                 output=DataframeOutput())
    def size(self, df):
        if 'text' not in df:
            raise ValueError('The Dataframe needs a column named "text".')
        return df.set_index('index').fillna('').text.apply(len).to_frame().reset_index()
```
* Client:
```python
class TextClient:
    def __init__(self, server_url: str):
        self.server_url = server_url

    def size(self, df: pd.DataFrame) -> pd.DataFrame:
        if 'text' not in df:
            raise ValueError('The given Dataframe requires a column named "html".')
        resp = requests.post(self.server_url, headers={'Content-Type': 'application/json'},
                             data=df.reset_index().to_json(orient='columns'))
        if resp.status_code != 200:
            raise ValueError('Bad reply!')
        return pd.DataFrame(data=resp.json()).set_index('index')
```

**Comment by bojiang** [comment]
```python
requests.post(self.server_url, headers={'Content-Type': 'application/json'},
                         data=df.to_json(orient="records"))
```
would do the trick.

**Comment by parano** [comment]
@dcferreira

**Comment by parano** [comment]
@bojiang 's suggestion should resolve this problem.  With the new DataframeInput release, we recommend always specify the orient in the code, e.g. `@api(input=DataframeInput(orient="records"))`

**Comment by dcferreira** [comment]
This issue seems to be back, unless I'm misunderstanding something.

Updated server to bentoml 0.9.2:
```python
import pathlib
import shutil

import bentoml
from bentoml.adapters import DataframeInput, DataframeOutput


@bentoml.env(auto_pip_dependencies=True)
class TestSizer(bentoml.BentoService):
    @bentoml.api(input=DataframeInput(columns=['text'], dtype={"text": "str"}, orient='columns'),
                 batch=True,
                 output=DataframeOutput())
    def predict(self, df):
        if 'text' not in df:
            raise ValueError('The Dataframe needs a column named "text".')
        print(df.index)
        return df.fillna('').text.apply(len)


if __name__ == '__main__':
    sizer = TestSizer()
    sizer.save()
```
and client:
```python
import pandas as pd
import requests


class TextClient:
    def __init__(self, server_url: str):
        self.server_url = server_url

    def size(self, df: pd.DataFrame) -> pd.DataFrame:
        if 'text' not in df:
            raise ValueError('The given Dataframe requires a column named "text".')
        resp = requests.post(self.server_url, headers={'Content-Type': 'application/json'},
                             data=df.to_json(orient='columns'))
        if resp.status_code != 200:
            raise ValueError('Bad reply!')
        return pd.DataFrame(resp.json())


if __name__ == '__main__':
    client = TextClient('http://127.0.0.1:5000/predict')
    ex1 = pd.DataFrame({"text": ["this is a text", "and another one", ""]}, index=["14", "15", "0"])
    print(client.size(ex1))
```

Notice that `orient='columns'` is specified both in the server, and in the client request.

Expected output:
```
   text
14    14
15    15
0      0
```

Actual output:
```
   text
0    14
1    15
2     0
```

The raw JSON response is also a bit weird looking, ignoring the index completely:
```
[{'text': 14}, {'text': 15}, {'text': 0}]
```


Am I misunderstanding something, or is this just not expected behavior?

**Comment by bojiang** [comment]
Hi.
Using `DataframeInput`, we assume that each row of a frame is a piece of input data. A full data frame represents a batch of input data. Under this assumption, the values of indices should not be considered in inference.

> The raw JSON response is also a bit weird looking, ignoring the index completely
It is not that weird, it is how `records` oriented frame looks like. (`pandas.Dataframe.to_json(orient="records")`)
`DataframeInput` is designed to ignore the index, so we recommend users to use the orient `records` as input.

Can you describe why you need the indices?

**Comment by dcferreira** [comment]
Ah ok, so this is expected behavior.

As for what I need it, generally speaking I want the ability to treat rows differently, depending on their content.
For example, say I have an NLP classifier, and a column with text.
Some tensorflow text models break if you give it an empty string.
So I'd want to remove the empty strings before sending them to the tf model.
In my response I wouldn't want to include the rows that weren't classified, so the output shape would be different than the input shape.

In my usecase I'm also chaining different models together, depending on the content of the row, until one model has a satisfying result.
This means that each row can go through a different set of models.
I'm doing this with multiple bentoml services linked together.
For this, while it would be feasible to use ranged indices in each service, it would be more convenient (for me as the programmer) to have the same row having the same index in all models.


Anyway, I can use the workaround of having the index as a column.
It's just that in my head, I expected indices to work automagically with the pandas adapters.
Thanks @bojiang! :)
